### ISSUE TITLE
a filter for remote changes only

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#1235]
Apps usually handle their own uI updates, then when you add sync you refresh onChange, however that will refresh twice once from the original code, next from the onchange

**Comment by davidbanham** [comment]
I think this would be a valuable feature.

My use case is that I always want to redraw the UI when there is a new message, so the changes feed is fine for that. I don't, however, want to throw a desktop notification at a user when they write a message, only when a remote counterparty writes a message.

This would normally be trivial, interrogate the document emitted with the change event for the username property or similar. In this case, however, that's not trivial because the document is encrypted.

There are ways out of this, eg decrypting the document, skipping exactly one notification for every message entered, etc. These are okay workarounds, but it feels like it should be simple for Pouch to know whether a change originated locally or remotely, and that's what I really want to know.

I suspect my particular use-case is indicative of a broader pattern, where it's possible to do this in application/framework code, but it would be dramatically simpler if Pouch had a way of just telling you.

**Comment by marten-de-vries** [comment]
@davidbanham You say the changes you want to show are coming from a remote source. If you mean replicating with that, you could listen to ``db.replicate.from(...).on('change', ...)`` instead of the normal changes feed, and leave ``db.replicate.to(...)`` without a change event handler.

For the general point of this bug, I agree with @daleharvey though, that it's too specialistic to put in PouchDB, even more because some workarounds are available. You already name decrypting & skipping if a message has just been entered yourself.

**Comment by daleharvey** [comment]
We cant add it to the changes feed, but a lot of people have been asking for it and I think @marten-de-vries's example works really well, I think we could improve `.sync` to also include the direction of the replication so you can do 

```js
db.sync(remote).on('change', function(change) { 
  if (change.source === 'remote') { 
     // my code
  }
});
```

as well, tell us how you get on with the workaround though, I think that is a good 90% solution

**Comment by davidbanham** [comment]
@marten-de-vries that's an excellent solution and it does the job. I am having to check the change.docs_written property to ensure > 0. If you write a local doc which gets synced to the remote, the 'from' stream fires a change event that we don't care about, because it didn't actually contain any new documents. That is fine, because it's a notification that the state encapsulated in the remote has changed, but it surprised me at first.

@daleharvey I do like the idea of augmenting the sync feed. In order to use this I've had to decompose my previous sync call into separate to and from's. It's fine, but would be nicer to be able to retain the use of the convenient wrapper.
