### ISSUE TITLE
Conflict on CouchDB -> PouchDB replication 

### ISSUE THREAD

**Issue by gpurgal** [pouchdb/pouchdb#1825]
I get 'Document update conflict' when I try to replicate a document from CouchDB which has some deleted conflicts.

```
{
"_deleted_conflicts": [
    "29-443e5b1a705d0e776946b106a682cb24",
    "18-171fbb426def740c2843268158be829f",
    "17-9a4427d5fe4a75d5f71f04744b133553",
    "16-8850b23a886815c92d21d271568bf548",
    "15-ffbb329935078c29c6daf05e39c6358f",
    "14-6c6df29bd0c1b1489b51860273c1f95d",
    "8-68f95a64f171f7577f4dcc343eeea1c5",
    "7-c4aabe805ce8d17060d7c90414a89d59",
    "6-8ed756ed8cd35ae7c4f300443db9a69e",
    "5-2ef0563f462ef218aec5c0a72c4eadf6",
    "4-58cc634489b7bd86e0a9f53de345d51d"
  ],
  "_id": "docId",
  "_rev": "29-e7855ed57c8e84e2335743abd1ed41f3"
}
```

The problem seems to be that `docInfos` array in `processDocs()` function is sorted like this 

```
["4-58cc634489b7bd86e0a9f53de345d51d",
"5-2ef0563f462ef218aec5c0a72c4eadf6",
"17-9a4427d5fe4a75d5f71f04744b133553",
"18-171fbb426def740c2843268158be829f",
"16-8850b23a886815c92d21d271568bf548",
"15-ffbb329935078c29c6daf05e39c6358f",
"29-443e5b1a705d0e776946b106a682cb24",
"29-e7855ed57c8e84e2335743abd1ed41f3",
"8-68f95a64f171f7577f4dcc343eeea1c5",
"7-c4aabe805ce8d17060d7c90414a89d59",
"6-8ed756ed8cd35ae7c4f300443db9a69e",
"14-6c6df29bd0c1b1489b51860273c1f95d"]
```

and in `updateDoc`, `oldDoc`s revision is `4-58cc634489b7bd86e0a9f53de345d51d` and `currentDoc`s is `5-2ef0563f462ef218aec5c0a72c4eadf6`. Both revisions are deleted so `inConflict` is set to `true`. What's the point of checking if the previous and the current documents were deleted?
Tested on Chrome and Firefox.

I've tried to create a test for this but have a problem with `putAfter` function. See the following test that fails: https://gist.github.com/gpurgal/9973154

**Comment by daleharvey** [comment]
Ran the test and this very surprisingly still fails

**Comment by daleharvey** [comment]
Has a failing tests, so putting help-wanted label on this

**Comment by nolanlawson** [comment]
Your test is failing because of some subtle differences in how CouchDB interprets `new_edits=false` documents when you don't specify the `_revisions`. When I add `_revisions` to each of your documents, then the test fails in the exact same way for all 4 cases (local-local, local-http, http-local, and http-http). See 90199e2b67d4b88dd4e3ddf2cc3710e2e763b9ba for the tests.

Closing as this is probably due to some differences between CouchDB and PouchDB that should not matter in the real world where people are not manually using `new_edits=false` with `bulkDocs`. Please reopen if you can demo that this is a bug without using `new_edits=false`.
