### ISSUE TITLE
Replications shouldnt stack

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#1852]
db.replicate.to(remote);
    db.replicate.to(remote);

Should only trigger one replication process

**Comment by janraasch** [comment]
Hi there. This is still a pretty desirable feature IMHO. Could anybody give a short status update here? 

Two questions would be interesting to answer:

1. What is up with the changes/comments in https://github.com/pouchdb/pouchdb/pull/2219. Is that still a valid approach? Maybe even a starting point for an implementation?

2. If https://github.com/pouchdb/pouchdb/pull/2219 was not good enough, what would the ideal solution look like?

I suppose really what I am asking is: What is the battle plan here? 

Maybe we can pin down a feature-set or maybe even an implementation guide so somebody can come along and fix us up with a pr.

(I said there were two questions, but I count at least 5 question marks on this comment. Go figure!... :))

**Comment by nolanlawson** [comment]
@janraasch I'm not aware of any contributors who are looking into this, so you would be more than welcome to tackle it if you're so inclined. :)

The trickiest part would probably be coordinating between two tabs in the same browser, which you can do via `localStorage` signaling (there is [some code](https://github.com/pouchdb/pouchdb/blob/8f3f888fca388ba97d002388072df764d565dad2/lib/changesHandler.js#L96) where we flip a key from `a` to `b` and back again in order to accomplish this, so you can see how it works there).

To answer your questions: #2219 looks abandoned to me. For clues on where to start implementing this feature, I would first look at [replicate](https://github.com/pouchdb/pouchdb/tree/f05e41206e61824a85461f24a654998f79d99342/lib/replicate) and [sync](https://github.com/pouchdb/pouchdb/blob/f05e41206e61824a85461f24a654998f79d99342/lib/sync.js), which correspond to `db.replicate()` and `db.sync()`. If you need help implementing this, feel free to hop in Slack/IRC and we'll try to guide you. :)

**Comment by daleharvey** [comment]
Yeh so this hasnt seen a lot of activity and in hindsight I do not think writing code to automatically 'correct` errors in users code is a good idea, it add complexity, brings in confusing api questions (ie how does cancel work), it was mostly made for when we didnt have retry, which we do now, closing out

**Comment by bean5** [comment]
I am running into a similar case. My PouchDB version is pretty updated, but I see that when I have 2+ tabs open and all are live-syncing, it only takes 1 insert and they all attempt to sync at the same time. Then it hangs on a call to `_revs_diff`. My network tab shows it as `pending`. Once a tab is closed, the rest complete.

Note: Perhaps this is a deliterious result of the fact that my CouchDB version is pretty out of date. If upgrading my CouchDB helps, I'll try to update here so others can avoid the same problem.

Hopefully this is simply a configuration issue rather than a bug. I like PouchDB thus far. It seems well managed. I'm leaning towards my code being the cause.
