### ISSUE TITLE
npm shrinkwrap

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2235]
Otherwise it's kinda dangerous, because we don't know what dependencies might have changed between builds.

**Comment by daleharvey** [comment]
So the second time this week dependency updates have broken our build, we cant even npm install pouchdb any more, assuming it will get fixed shortly but I really dont want this to keep occurring. 

I think we should just plain shrinkwrap the default build (or commit node_modules), either way I would like npm install to install the same code and not give any possibility of dep updates breaking our build

**Comment by daleharvey** [comment]
@calvinmetcalf any reasons to not just shrinkwrap by default?

**Comment by nolanlawson** [comment]
Cost of not  shrinkwrapping: broken installs in npm when a dep author makes a mistake.
Cost of shrinkwrapping: bugs don't get reported early to dep authors, basically a cost to the community.
I see it as a tragedy of the commons kind of thing. I think it's unfortunate, but I'm pro-shrinkwrapping.

**Comment by daleharvey** [comment]
Another thing that was mentioned is shrinkwrapping may reduce the benefits of deduplication, I am still pro, however with main node.js people against it (https://twitter.com/izs/status/551069839465271296), I would like to see a 'blessed' solution to this, I think its worth a blog post

**Comment by calvinmetcalf** [comment]
just got back, so the problem with shirnkwrap is both deduplication and bug
fixes, the idea behind semver is that you want bug fixes to just
automatically get in, while this doesn't work if a breaking change is
marked as a bug fix dems be the tradeoffs

**Comment by daleharvey** [comment]
Hope you had a good honeymoon :)

I tried writing a blog post, but having a hard time coming up with something coherent. I dont think we get any value at all in 'automatic' bug fixes, semver helps but it means depending on everyone to strictly adhere to fuzzy semantics, this is broken enough times that we really should fix it, but I dont want to screw with downstream authors, will try to experiment with how shrinkwrapping effects the build

@mikeal @isaacs it would be nice if there was some systemetic effort to fix this, all the arguments in http://www.futurealoof.com/posts/nodemodules-in-git.html apply to libraries as well as applications, libraries being vunerable to breakages due to upstream changes isnt a good thing imo, and it is a common problem at least in my / pouch's experience

**Comment by calvinmetcalf** [comment]
So I'd point out that shrink wrap wouldn't have prevented the browserify
problem as it stemmed from a dev dependency not an actual not a production
dependency

**Comment by daleharvey** [comment]
you can `npm shrinkwrap --dev` which would have caught this right? the other option being bundling deps

**Comment by nolanlawson** [comment]
@daleharvey I wrote a blog post the last time an upstream breakage broke the build: http://nolanlawson.com/2014/09/01/the-limitations-of-semantic-versioning/

I see auto-updating as a big problem for the future of Node. What happens when the current boom is over? When modules fall into disrepair? Will they slowly break because their deps broke? Will we need to `npm install foo@1.2.3@shrinkwrapped` to get all of `foo`'s deps and sub-deps exactly as they were when `foo` was last published? Lots of nightmare scenarios arise when you imagine a future where people aren't jumping to fix their bugs anymore.

As for PouchDB, we are in a delicate position because we are often better-tested than our own deps. So we often act as the canary in the coalmine when they break something (express, memdown, leveldown, browserify, etc.). That's great for the larger Node community, but not so great for us in particular.

In any case, if shrinkwrapping wouldn't have fixed the last issue, then let's not add the additional build complexity. Maybe we should just accept occasional breakages as the cost of citizenship in the Node community, at least until npm offers us a way out.

**Comment by nolanlawson** [comment]
I'm actually anti-shrinkwrapping. :)  "Cost of citizenship" thing.

Also worth pointing out is that browser users aren't affected, and I'd wager that ~95% of our users are browser users.

**Comment by yaronyg** [comment]
@nolanlawson: I'm working hard on fixing that browser user majority thing. :)

**Comment by daleharvey** [comment]
Shinkwrapping would have fixed the previous issue (you can shrinkwrap dev dependencies)

Yet again our build broke because of a broken upstream dep update (selenium-standalone - https://github.com/vvo/selenium-standalone/issues/60)

Shrinkwrapping enforces some assumptions to downstream dep authors which I would prefer to avoid, but if we commit node_modules then we dont enforce anything on downstream, and we dont have builds that break from one build to another

I am not particularly happy with our build breaking from one build to the next as a cost of being in the node ecosystem as it makes contributions harder (the amount of failed PR's due to dep breakages is increasing) and I cant see much impetus on this being fixed upstream yet. 

What are the downsides to committing node_modules?

**Comment by nolanlawson** [comment]
Downsides:

* it's another thing to npm ignore, delete from the bower release
* might break the platform-specific postinstall scripts
* we are no longer the canary

As much as I have whined about semver/autoupdating, I'm still -1 on shrinkwrapping or committing node_modules. It's pretty easy to go into Travis and see which build last passed and which version of the deps were downloaded, so at that moment we can find the offending package, remove the caret, and inform the author that they broke something.

I really do see this as a citizenship issue, and that we are doing something valuable for the larger npm community by finding bugs for them. If we ever reach a point where pouchdb is "done," though, and we aren't really actively committing to it anymore, then at that point I'd be happy to shrinkwrap.

That being said, I still wish npm could figure out a way to make it a little less painful for those of us who act as canaries; maybe some kind of git-bisect feature where we could selectively lock dependencies and then figure out which one broke us? That would cut down the time to figuring out which dep broke.

**Comment by nolanlawson** [comment]
Issue filed on npm ^

**Comment by daleharvey** [comment]
We often cant just remove the caret if its sub dependencies, and how hard it is to debug has varied quite a lot in the past

As I mentioned on twitter, everyone used to be happy doing `<script src="http://www.json.org/json2.js"></script>` until one day Douglas Crockford put an `alert()` in the code which broke half the internet. I think its a fundamentally bad approach building software, I dont think it does a great service to upstream authors, instead of getting a friendly bug report they get people being fairly obnoxious when they are on their honeymoon because their innocuous update actually broke half of npm.

For downstream authors the only real fix is to put the responsibility on them to shrinkwrap or build proper release packages, but for our own build I think we should expect for our own sanity and for our contributors sake that if nothing has changed on master then the next time you run it it should run the same.

At the moment I think this is a hugely annoying but just manageable, if we want to do further modularisation then I think it will quickly become completely unmangeable. We had to commit node_modules in fxos for the same reason.

**Comment by nolanlawson** [comment]
Agree with you on the Crockford story, but I think for npm deps it's a bit different. Nobody is purposefully introducing bugs in minor/patch releases; it's just humans making mistakes. Closest approximation to the Crockford thing is Express adding ~3 million warnings to try to convince us to upgrade to the next major version, but that doesn't break anything.

I'm still -0, because I just think we are swimming against the tide of npm, and it's not our job to try to find workarounds for fundamental problems in the npm ecosystem/culture. Furthermore, we could put ourselves in a scenario where everything seems peachy until we try to build for a release, and then there are a dozen bugs that have accumulated. Or there's a critical bugfix in a module that we don't get (much more common than the other case). 

But yeah, if we modularize any further, then it's going to get pretty tough. Which is maybe why we shouldn't. :stuck_out_tongue:

@calvinmetcalf @marten-de-vries thoughts?

**Comment by marten-de-vries** [comment]
In general I prefer the 'normal' approach (no shrinkwrapping in libs). I do believe it's a service to upstream. (Better a somewhat heated bug report than none, + we don't open heated bug reports, right? :innocent:) But, I'm not the one who tracks down most dependency issues when they pop up in PouchDB, and I can see that it's a more frequent issue for PouchDB because of the large amount of dependencies. So in short, I'm neutral.

**Comment by daleharvey** [comment]
Ok so I think for now we are sticking to node conventions until this burns us again :)

**Comment by daleharvey** [comment]
lol, awesome timing, npm registry is down and causing total travis failures
