### ISSUE TITLE
Socket Pouch

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2374]
As a *PouchDB developer*

I want *a server-side and client-side socket.io replication plugin*

So that *we can post it on Hacker News and people will go apeshit because zomg websockets.*

**Comment by yaronyg** [comment]
I will be sending an official post about this to the mailing list once we have the final code clean up but I thought you might find this mildly amusing now. We just got PouchDB synching over Bluetooth on Android. You can see a video demo [here](https://t.co/sNYY9Gawk0). 

The way we did this is with a muxing layer we wrote. It's super trivial, you can see it [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/6c74882f3e0f213686e0376099c09bb1f99e83a2/thali/thalireplicationmanager.js#L212). The reason it is so trivial is because the [Multiplex](https://www.npmjs.com/package/multiplex) project did all the hard work.

Note that we do plan to eventually break out this code into a stand alone NPM. E.g. a TCP/IP muxer/de-muxer.

We just took the NPM multiplex library and we slathered some TCP/IP on both sides of it. So the data flow is:

```
Phone A:
[PouchDB HTTP Client] ---> [muxClientBridge running Node.js TCP/IP Listener who then opens a TCP/IP Client] ---> [Native TCP/IP Listener who copies data to] ---> [Native Bluetooth Library]
 |
\_/
Phone B
[Native Bluetooth Library]-->[receives Bluetooth bytes and copies them to Native TCP/IP Client]-->[muxServerBridge running TCP/IP Server who copies bytes to node.js TCP/IP Client]-->[Express-PouchDB Server]
```

So the trick is that from the native code's perspective it is getting a single TCP/IP connection that it then byte copies onto the Bluetooth stream (we are doing the same thing on iOS). One TCP/IP connection === 1 native stream.

But above that single TCP/IP connection we have a muxing layer that can accept N TCP/IP connections from the PouchDB client and then mux them down to a single TCP/IP connection which is then sent across the native layer. 

On the other side the native receiver sees a single stream that it turns into a single TCP/IP client connection. Again, 1 TCP/IP connection === 1 native stream. But that client then calls into out mux server who de-muxes the streams and makes N outgoing TCP/IP connects to Express-PouchDB.

So PouchDB's client can open as many connections as it wants and Express-PouchDB will receive all of them. But from the native layer's perspective there is just a single stream it has to move bytes across. This is nice for maximizing our use of the underlying Bluetooth (or in iOS's case, a hybrid of Bluetooth and Wi-Fi) connection.

**Comment by gr2m** [comment]
> But above that single TCP/IP connection we have a muxing layer that can accept N TCP/IP connections from the PouchDB client and then mux them down to a single TCP/IP connection which is then sent across the native layer. 

Wow, my mind just blew a little <3

**Comment by daleharvey** [comment]
And socket pouch exists :) https://github.com/nolanlawson/socket-pouch

**Comment by genglefr** [comment]
I looked into socket pouch, but it is unfortunately not compatible with Sync Gateway WebSocket.
Thus, I wrote my own "adapter", which creates a WebSocket to Sync Gateway, then use it to feed the local PouchDB, with `bulkDocs({new_edits: false})`.

You can check this code out on my personal GitHub here:
[https://github.com/genglefr/my-gallery](https://github.com/genglefr/my-gallery)

If someone is interested, I might create a formal PouchDB plugin out of it.
