### ISSUE TITLE
Support `revpos` in attachment stubs

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2709]
I don't really understand why it's there or what it's good for, but I don't see any reason not to implement it.

**Comment by yaronyg** [comment]
I thought this was necessary for #2674 but I was just confused.

**Comment by jo** [comment]
`revpos` support is relevant for replication with CouchBase Lite, at least on iOS, see https://github.com/couchbase/couchbase-lite-ios/issues/1200. The issue is that CBL does not replicate documents which have attachments with `revpos: 0`, which are generated by current (5.3.1) PouchDB.

The CouchDB replicator **does** handle such docs, at least in `1.6.1`.

Although I think replicators should be tolerant about this I also see a benefit that PouchDB supports `revpos`. This will improve replication performance for documents generated by PouchDB, but replicated by other replicators, which take advance of the `revpos` optimisation.

**Comment by jo** [comment]
For reference, here is an example document generated by PouchDB:

```json
{
   "_id": "section_image-7d5198c2-5ddf-5405-9835-e980b634535c",
   "_rev": "2-8145a6217ced16862b43577c204d2ac8",
   "_attachments": {
       "image.png": {
           "content_type": "image/png",
           "revpos": 0,
           "digest": "md5-Hke94Wxx368Us7xYprTmIw==",
           "length": 101033,
           "stub": true
       }
   }
}
```

And now a similar doc generated by CouchDB (via Futon):
```json
{
   "_id": "ca7de16f526d6fb755aacdcd5c000542",
   "_rev": "2-9763c729a3ae246f8cf26dde7d40ad99",
   "_attachments": {
       "tf-gelb-quad-huge.png": {
           "content_type": "image/png",
           "revpos": 2,
           "digest": "md5-n7YwXKN1YtMI4H/yw7EbWA==",
           "length": 64712,
           "stub": true
       }
   }
}
```

**Comment by jo** [comment]
Pull is here: https://github.com/pouchdb/pouchdb/pull/5037
