### ISSUE TITLE
Bring back fast replication as opt-in

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2792]
In light of https://github.com/nolanlawson/local-npm/pull/34 and also npm-browser, it seems like there are some valid cases where we want the pre-3.0.3 "fast" replication, because we don't care if we introduce conflicts in the target database. E.g. for read-only situations where we just want to clone from the remote database.

I think replication could have an option like `{allow_conflicts: true}` which would then allow us to switch to "fast" mode. What do y'all think?

**Comment by Rob-pw** [comment]
Has the issue of speed been resolved since? At present replicating (read-only) from a local CouchDB server is the slowest part of my app initialising, there seem to be many sequential requests to the server, just to verify that none of the documents have been modified since last replicate. 

![](http://i.imgur.com/rClGfzc.png)

This occurs noticeably over a WiFi connection, and is even more apparent over GPRS (50Kb/s). I have increased my batch_size, which I believe resulted in a slight reduction in the number of requests.

**Comment by nolanlawson** [comment]
The current best solution is [pouchdb-load](https://github.com/nolanlawson/pouchdb-load). We are also [working with CouchDB](https://issues.apache.org/jira/browse/COUCHDB-2310) to get a faster replication algorithm implemented.

**Comment by Rob-pw** [comment]
That feels a tad awkward, wouldn't allow_conflicts, or just some dumb_clone property serve the same purpose with less work for the time being? Ultimately smarter replication would be the most ideal solution.

**Comment by nolanlawson** [comment]
pouchdb-load is even faster than the old system, and it doesn't introduce conflicts. But yeah, ultimately we want replication itself to be faster. Stay tuned. ;)
