### ISSUE TITLE
db.changes({since: 'now', live: true}).on('change', Always fires a change

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#2800]
Every time my app starts up a change gets fired, pretty sure it shouldnt

**Comment by oliverdm** [comment]
I was about to ask why `db.changes({since: 'now'})` also returns the last change when up-to-date before I saw this issue. From the docs I assumed otherwise.

In 9a33d72ba921320bda42157ab563b8834c408d29 `lib/changes.js` lines 143-166 `now` is mapped to `info.update_seq  - 1;`:

    if (opts.since === 'now') {
        ...
        opts.since = info.update_seq  - 1;
        ....
    }

Would that explain it? And is it intended to behave that way?

**Comment by daleharvey** [comment]
This should be fixed by https://github.com/pouchdb/pouchdb/issues/3450
