### ISSUE TITLE
Indexeddb adapter not working in WKWebView

### ISSUE THREAD

**Issue by timeout2x** [pouchdb/pouchdb#2875]
After switching standard safari (UIWebView) to webkit (WKWebView) in hybrid app - the database stops working.

window.indexedDB is fine (not undefined).
No errors thrown.
PouchDB object is ok.

Switching adapter to websql doesn't help.
Switching to leveldb helps.

I tried test on http://pouchtest.com/tests/test.html
This is an error which i got:
![img_0002](https://cloud.githubusercontent.com/assets/3945286/4655084/659e58c8-54be-11e4-9e4b-c3ad3d1d81cb.PNG)

**Comment by anagromataf** [comment]
I ran into the same problem using a WKWebView with pouchdb. Has there been any progress on this?

**Comment by nolanlawson** [comment]
I pinged a Webkit dev about [these bugs](https://gist.github.com/nolanlawson/08eb857c6b17a30c1b26), but haven't gotten a response yet.

**Comment by daleharvey** [comment]
So right now fruitdown is our main workaround for this, we need to take into consideration that when we do support indexeddb on webkit it is going to mean a migration from anyone who was using websql, idb-next is being built with webkit indexeddb support and planning migration tools for that, so that looks like the  best approach for this, closing as a dupe https://github.com/pouchdb/pouchdb/issues/5207
