### ISSUE TITLE
Replicate {live: true} stops after a network problem

### ISSUE THREAD

**Issue by mikkokam** [pouchdb/pouchdb#2979]
Ran into this while developing a realtime Ionic web app for mobiles.
The app is syncing the clients to CouchDB using {live: true}, and the tests showed it is possible to create the same realtime functionality as Firebase has.

But if a client drops network connection during the sync, the live sync will stop completely with:
`r {message: undefined, status: 405, statusText: "Method Not Allowed", result: Object, name: "unknown_error"…}`

Using mobile networks, this is often the case, and optimally, the sync should recover automatically?
**Maybe retry after a timeout?**

**Comment by t-knapp** [comment]
I face a simular problem even when using this:

`  PouchDB.sync('localDbName', 'http://couchdb.host.address:5984/remoteDbName', {live: true, retry: true});`

The Replication object for "pull" direction is in state "stopped" after the remote CouchDB was not reachable due to network problems (no Wifi connection).

Does this retry option stop at some condition?
