### ISSUE TITLE
`uptodate` event is missing `last_seq` property

### ISSUE THREAD

**Issue by ssured** [pouchdb/pouchdb#2991]
`last_seq` is not available as a property on the `uptodate` event

Should it be?

It seems for the `complete` event the `last_seq` is injected, see https://github.com/pouchdb/pouchdb/blob/08f170d7cadfb450f58ca210f393dbcd5e66d45f/lib/replicate.js#L404-L406. My guess is `last_seq` should be injected somewhere here https://github.com/pouchdb/pouchdb/blob/08f170d7cadfb450f58ca210f393dbcd5e66d45f/lib/replicate.js#L353.

**Comment by willholley** [comment]
Just noting that the above assumption (when `replication.last_seq == db.update_seq` you know the replication is done) doesn't hold in CouchDB 2.0 / Cloudant. The only way to know that replication is complete is to call `_changes?since=<last_known_seq>` and check that no results are returned - you can't even reliably compare last_seq and update_seq. The replication code in PouchDB now does this correctly and I don't think it changes the intent of this ticket (add direction to the uptodate event) but thought I'd mention it.

**Comment by daleharvey** [comment]
`uptodate` is deleted - https://github.com/pouchdb/pouchdb/commit/937ef1f68c84e938ce470c8d03966aa917420587
