### ISSUE TITLE
Replication as a stream

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#3038]

**Comment by nolanlawson** [comment]
There are now pouchdb-stream and pouchdb-replication-stream plugins.

**Comment by snej** [comment]
Is there any documentation of the protocol?

**Comment by nolanlawson** [comment]
https://github.com/nolanlawson/pouchdb-replication-stream#readme

**Comment by nolanlawson** [comment]
or more precisely https://github.com/nolanlawson/pouchdb-replication-stream#design

**Comment by snej** [comment]
Ah, so this is just for the initial replication, not incrementally keeping two already-synced dbs in sync?
(I'm working on a different new replication protocol, but its aim is to completely replace the old REST replicator, so it's more full-featured. It's based on WebSockets.)

**Comment by nolanlawson** [comment]
The replication protocol indeed can be used for incremental replication. It just hasn't been written yet. :)

Right now you could pretty easily use something like [express-pouchdb-replication-stream](https://github.com/conor-mac-aoidh/express-pouchdb-replication-stream), which accepts a `since` parameter. Then it's just the client's responsibility to keep track of checkpoints (which get sent back with the stream).

I've also started working on a WebSocket adapter for PouchDB, but it's based on a different principle (subbing out the existing LevelDB/IndexedDB/WebSQL adapter for a WebSocket-based proxy): [socket-pouch](https://github.com/nolanlawson/socket-pouch). The pouchdb-replication-stream is probably a better bet for the kind of thing that could eventually be included in CouchDB itself; @janl has expressed some interest in that.

**Comment by prust** [comment]
Would it make sense to be compatible with the Websocket changes feed in Couchbase & Couchbase Lite? https://github.com/couchbase/couchbase-lite-ios/wiki/WebSocket-Based-Changes-Feed

**Comment by yaronyg** [comment]
Also, I'm not hallucinating, there is no binary support for attachments? In other words, if we want to use this infrastructure to move attachments efficiently then we would have to create our own variant using something like BSON?

**Comment by snej** [comment]
FWIW, I've decided that the best way to transfer attachments is as separate requests. Base64 is too inefficient, and MIME multipart is too complicated. Also, it's more efficient for the receiver of a revision to look at the `_attachments` property and then decide which attachments it should download — that eliminates the whole `atts_since` thing.

It's also a step towards allowing lazy loading of attachments, which is a feature a number of Couchbase Lite users have asked for. If the logic already downloads the revision first and then decides which attachments to download, it's easy to splice in a user-configurable predicate that can force an attachment not to be downloaded (yet).

**Comment by yaronyg** [comment]
@snej That all makes a ton of sense to me. And as someone actually working on atts_since I wouldn't mind not working on it! :) Also we are running straight out of Node.js so we can use multiple connections and thus get 'mux' like performance for downloading attachments. The bigger problem is that this potentially complicates the replication logic since it means we can't actually get an entire record as a single unit. Instead we are going to have to break it into a JSON request and one or more attachment requests. So I'm not sure yet which will hurt more - atts_since or the replicator? I haven't looked at the code closely enough to know yet. But I do intend to find out.

I have to admit that mime/multi-part doesn't particularly scare me. There are existing libraries that can handle that for us.

I do get the late bound attachment issue. For Thali we are dealing with occasionally connected systems (local P2P or even downloading phone to phone) so when you do have a connection you download everything you can because you have no idea when you might get another opportunity. I recognize this is a rather unique scenario though.

We also have a 'store and forward' scenario where we can leave messages for people that they can pick up later. To make that work we need to be able to serialize everything in a single stream. Hence why BSON is interesting. But I recognize there are other solutions such as creating a ZIP file that contains the JSON replication stream along with the changed files. Given PouchDB's ability to hash the files to avoid duplications there is even an argument that the ZIP approach might be easier to implement and would be more efficient.

We are not really attached to any particular solution. In fact our current plan is to try and nail down our perf requirements more tightly and then work backwards from there to figure out what changes would let us meet them.

**Comment by nolanlawson** [comment]
> Would it make sense to be compatible with the Websocket changes feed in Couchbase & Couchbase Lite? https://github.com/couchbase/couchbase-lite-ios/wiki/WebSocket-Based-Changes-Feed

Yup, didn't know that existed. That's neat. :)

> FWIW, I've decided that the best way to transfer attachments is as separate requests. Base64 is too inefficient, and MIME multipart is too complicated. Also, it's more efficient for the receiver of a revision to look at the _attachments property and then decide which attachments it should download — that eliminates the whole atts_since thing.

Good to know. In general, multipart is only really on my roadmap in order to fix Sync Gateway support. Although the perf improvement when dealing with CouchDB would be nice too.

If y'all are interested in lazy-loading, draw up a spec, and maybe we can convince CouchDB and eventually PouchDB to incorporate it. :) We're already implementing the `_bulk_get` from CSG (https://github.com/apache/couchdb-chttpd/pull/33), so it's not out of the realm of possibility.

**Comment by tejl** [comment]
Does SocketPouch support the Couchbase gateway sync changes feed?

**Comment by nickcolley** [comment]
@tejl currently socket pouch has two parts, the client side plugin and a server to communicate with, so now I don't think it'll support Couchbases' gateway without a server in between for sockets.

For PouchDB to have an adapter compatible with https://github.com/couchbase/couchbase-lite-ios/wiki/WebSocket-Based-Changes-Feed it'd have to be a new adapter.

**Comment by genglefr** [comment]
@tejl @nickcolley 
See [this comment](https://github.com/pouchdb/pouchdb/issues/2374#issuecomment-367253369) on another issue, for Couchbase Sync Gateway compatibility over WebSocket.
