### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3112]
I've seen a lot of articles in other languages about PouchDB ([Spanish](http://www.kabytes.com/programacion/pouchdb-base-de-datos-de-bolsillo-para-crear-aplicaciones-offline/), [French](http://rougetube.fr/2014/12/4/pouchdb-une-base-donnee-pour-les-navigateurs-web-amp-nbsp_87), [Japanese](http://www.moongift.jp/2014/12/pouchdb-%E3%82%B5%E3%83%BC%E3%83%90%E3%82%B5%E3%82%A4%E3%83%89%E3%81%A8%E3%81%AE%E5%90%8C%E6%9C%9F%E3%81%AB%E3%82%82%E5%AF%BE%E5%BF%9C%E3%81%97%E3%81%9F%E3%82%AF%E3%83%A9%E3%82%A4%E3%82%A2%E3%83%B3)). What they all have in common is that they just provide a very basic "hello world" without delving too deeply.

This shows that non-native English speakers have a real need for documentation in their own language. And I think the API/guides are getting stable enough that we could reasonably start thinking about doing it ourselves on the website.

My French is decent enough that I could translate the guide and would just need a native speaker to grammar-check. Anybody else interested in this project? Which parts do you think should be translated? Or is it a crazy idea?

**Comment by 7ictor** [comment]
Is someone working on this? I can help with Spanish (my native language), I run my personal blog in Jekyll and enjoying using Pouch in production for a whole year :blue_heart:

**Comment by nickcolley** [comment]
@7ictor the pull request is ready to have a translation as far as I can remember. I couldn't really go any further because I'm only a native English speaker, so if you want to pair up and get some Spanish going that'd be ace.

**Comment by mnewmedia** [comment]
I could do german, but most germans can or should be able to read english. And since almost all good IT-resources are english, every IT-guy should be able to understand english. And if not they will have to learn it, and when they are forced to learn english it's maybe a bit bad in the beginning but better at the end.
Also translated docs would getting outdated and produce unnecessary issues. I know PouchDB guys are just too lovely and want to help everyone =) but still they really should learn english even I should improve my english skills.
Also my English is only beginner Level and it was sometimes hard to understand the CouchDB Docs, but the PouchDB Docs are mostly written in easy to understand english.

**Comment by nickcolley** [comment]
Hey @mnewmedia thanks for comment.

This issue is mainly an endeavour to be more inclusive within the community, this means if we don't want to just support the typical people that are represented in Open Source currently.

This mirrors the intent written down in our Code of Conduct (https://github.com/pouchdb/pouchdb/blob/master/CODE_OF_CONDUCT.md#diversity-statement)

I'd like to think that even with little English PouchDB would be somewhere people could learn from.

I'd argue if we saw more projects not presuming English as standard we'd see more communities that are not native English speakers represented within our projects.

Also just so you know we're not all guys. :+1:

**Comment by daleharvey** [comment]
So @nickcolley did a bunch of work on this and unfortunately it would have still required a fairly large amount of work to get landed. I think @nolanlawson has a point that while translation provides an opportunity for low barrier contributions it requires a large amount of infrastructure to support them that we dont currently have. I would love someone to come along, reopen this discussion and be able to put resources into getting the infrastructure in shape, but in the mean time this isnt currently actionable / active so closing out. thanks.
