### ISSUE TITLE
DB Corruption? LevelDB Error?

### ISSUE THREAD

**Issue by yaronyg** [pouchdb/pouchdb#3216]
I did a full replication of skimdb on Node.js using level db and was trying to run a map/reduce when I ran into an error at https://github.com/pouchdb/pouchdb/blob/master/lib/adapters/leveldb.js#L948 

The error was that doc.doc._rev threw an exception because doc.doc was undefined. The reason that doc was undefined is because the data argument to allDocsInner was undefined.

The proximate cause of the error was https://github.com/pouchdb/pouchdb/blob/master/lib/adapters/leveldb.js#L975. The err argument to the callback was set to NotFoundError but the callback ignores errors and calls allDocsInner regardless.

However one suspects that the real bug is that the query produced a map/reduce that produced a Leveldb query that produced a NotFoundError. For what it's worth the ID of the document that caused the NotFoundError was 54coffeenode-tides(undefined unicode character)coffeenode-tides(two undefined unicode characters). Also when I walked up the stack to the original levelDB get the key being looked for was ÿby-sequenceÿ0000000000043011

The actual bug however is not in the core db (called localNPM) but rather in localNPM-mrview-temp. I looked at CURRENT and it's value is MANIFEST-000421 but there is no 000421.ldb file. Just a 000422.ldb and a 000423.log. I don't know ldb, Is CURRENT supposed to point to a file that doesn't exist?

I zipped up the entire GIT repository in which I was running my experiments and that's about 3/4 of a Gig. LocalNPM on its own is 458 MB and localNPM-mrview-temp is around 75 MB.

Now that I have a backup I'm going to go and nuke the localNPM-mrview-temp directory to see if that gets things going again.

**Comment by daleharvey** [comment]
So yup, while we dont use batch operations this will always be possible and there has been no indication that there is any other bug at play here. If we migrate leveldb to the same format as `idb-next` it will be super simple to implement batches so if anyone wants to start work on it then I would very much recommend that approach (its possible we may want to do it at the same time as releasing `idb-next`), but otherwise no need to have 2 issues open for the same bug.
