### ISSUE TITLE
PouchDB on node.js using leveldb needs to be Crash Only

### ISSUE THREAD

**Issue by yaronyg** [pouchdb/pouchdb#3224]
One of the key design features of CouchDB is it's 'Crash Only' design. There is no shutdown. If you want to turn it off, you just kill it. The system is always in a safe state so data will never be lost.

It turns out that we use a soft lock in leveldb that will fail if the system is turned off unexpectedly and leave the system in an inconsistent state. (See [here](https://github.com/pouchdb/pouchdb/issues/3216#issuecomment-67639840))

This is bad in general, systems should be robust. But this is particularly deadly for mobile scenarios ranging from phones (Node.js already runs on Android) to tablets to laptops to IoT embedded systems that can be yanked out of the wall at any time. We can't rely on PouchDB in those scenarios if it's going to end up in a horked state if the process is killed unexpectedly.

So we need to re-work the leveldb code so it is crash only.

**Comment by nolanlawson** [comment]
So we currently do a locking transaction queue and every bulkDocs is a single LevelDB batch operation, but you may be right that the update_seq and doc_count and attachment data are not in that same atomic operation, and they ought to be.

The code is complex because it contains a heck of a lot of perf optimizations. It could certainly be cleaned up though.

**Comment by masaeedu** [comment]
I see this is marked as wontfix. So, just to be clear, for situations where the process is prone to brutal death at any time, is it only the leveldb driver one should avoid or is this an unavoidable tradeoff of pouchdb's design?

**Comment by daleharvey** [comment]
It is only marked as WONTFIX because we only keep active bugs open around here, not that it will never be fixed. Its only an issue with the current leveldb implementation, both webSQL and IndexedDB have transactions to maintain data integrity. At some point as part of https://github.com/pouchdb/pouchdb/issues/5207 we will probably have to rewrite the level adapter and as part of that it will become crash safe

**Comment by masaeedu** [comment]
@daleharvey Thanks. Is there some Node JS driver that isn't susceptible to the issue in the meantime? My use-case is a command line tool, so being able to keep things in a consistent state when the process (or entire system) is killed unceremoniously is critical.

**Comment by daleharvey** [comment]
An possibility may be using sqlite with the websql driver, that uses transactions so should be crash resistent, otherwise best case is probably to write the leveldb-next, it shouldnt actually take that much effort

**Comment by rasgo-cc** [comment]
@daleharvey any progress on this? Any pointers to things I could look at so maybe I could help?
I have a user that started having a "not an sstable (bad magic number)" error while trying to create an index. I believe this might be related https://github.com/google/leveldb/issues/408. Still didn't have the chance to reproduce it myself tho.
