### ISSUE TITLE
Keep the updateSeq in memory

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3450]
Similar to how we keep the docCount in memory for better perf, we can do the same thing for the updateSeq in case of `changes` with `since: now`.

**Comment by daleharvey** [comment]
Ugh apologies, I added the failing test to master by accident, I need to stop testing peoples patches on master then accidently pushing them when I review code

**Comment by daleharvey** [comment]
So the issue here is when you do a `db.changes()` or `db.on('change'`, under the hood we do a `db.info` to find the `update_seq`, which means if you do a `db.put` > `db.changes` > `db.put`, we cant have any guarantee about what events you recieve, mostly the worry is if you do a `db.changes` followed by a `db.put`, theres a chance it may not fire an event

**Comment by daleharvey** [comment]
Closing, its an optimisation we would probably like but I dont think its big enough we need to track it
