### ISSUE TITLE
Update PhantomJS?

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3536]
Apparently 2.0 is out now. Supports IndexedDB: http://phantomjs.org/release-2.0.html. Here's an HTML5 test: http://html5test.com/s/3472f4256af8d0a9.html

Downsides to upgrading:

* Phantom 1.0 is super old, so it has WebSQL bugs that none of our other automated browsers catch
* Phantom 1.0 is still in use out there (ugh)
* Phantom 1.0 is a good proxy for Safari 5 or Android 4.0 (ish)

Upsides:

* Probably faster
* More modern
* Can actually test IndexedDB 

I'm on the fence about this. Thoughts?

**Comment by marten-de-vries** [comment]
The current PhantomJS is also quite similar to older versions of QtWebKit, which is good for Python-PouchDB. Looking at your upsides, I'm not convinced upgrading is worth it. (Unless maybe their new indexeddb implementation is unlike any others currently tested?)

**Comment by bedney** [comment]
Note that the Phantom guys are not issuing Linux binaries right now, due to having build issues. This is due to be fixed in 2.0.1 Also, it seems some folks are having rendering issues. Otherwise, everyone seems to be very happy with the new release. If these things aren't impactful to PouchDB (highly doubt the rendering issues are), I'd vote to go for it.

**Comment by nickcolley** [comment]
I'd vote against replacing the older version, I think your points on Phantom 1 looking after older browsers somewhat are important.

**Comment by nolanlawson** [comment]
Yep, I tend to lean towards not upgrading as well. If we're going to test a "fake" browser, we might as well test one that gives us some valuable information about legacy Webkit.

**Comment by daleharvey** [comment]
Yeh I would like to get the real browsers we support tested then remove phantom, or at least only test it for the sake of supporting people who are running phantom tests in their app which happens to use pouchdb, upgrading doesnt seem worth it for now

**Comment by nolanlawson** [comment]
@daleharvey I tend to like Phantom just because it's so fast, and it doesn't depend on Saucelabs.  I've rarely if ever seen it fail due to an intermittent ("failed to connect to selenium" or whatever). But testing Chromium would definitely be better.

**Comment by bedney** [comment]
@nolanlawson - one word of caution on that approach is that it's been almost 2 years since Google forked Webkit to form Blink. I'm not sure they treat core Webkit as a source of upstream bug fixes (I really don't know the answer to this question - if someone does, they could enlighten me). So be aware that testing on Chromium might be the same as testing in Phantom.

In any case, one strategy we use is to use Phantom as a 'first cut' (as opposed to burning Saucelabs cycles right out of the gate) and then if it passes there to then go ahead and run it on Saucelabs.

My 2 cents.

**Comment by nolanlawson** [comment]
@bedney Yep, that's a wise approach (and our current one :smiley:). I think @daleharvey's worry is that we will continue expending effort to fix PhantomJS 1.0 bugs after the world has largely moved on from Safari 5-ish browsers.

**Comment by daleharvey** [comment]
So yeh, think we are keeping old phantom as a websql smoke test, we have local firefox on travis for indexeddb
