### ISSUE TITLE
Test improving CORS performance by avoiding content-type on GETs

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3573]
Per https://lists.w3.org/Archives/Public/public-webappsec/2015Feb/0347.html

**Comment by nolanlawson** [comment]
This should be a pretty easy fix to get us a good performance boost. (If it works! :))

**Comment by nickcolley** [comment]
Does this mean less requests? :octopus:

**Comment by nolanlawson** [comment]
Yes, supposedly we can eliminate most of the OPTIONS requests during replication.

**Comment by remy** [comment]
Is there any reason that [theses headers](https://github.com/pouchdb/pouchdb/blob/master/lib/deps/request-browser.js#L30) should be added if the request type is a `GET`? If I understand correctly, the `content-type` is only needed if there's a body being posted, and since pouch is talking JSON, and a default `GET` request accepts `*` (i.e. all) then you don't need the headers.

I've not tested this at all (and am happy to give it a try if I'm on the right lines), but the change might be as simple as:

```js
if (options.json && options.method !== 'GET') {
```

**Comment by nolanlawson** [comment]
I tried @remy's suggestion, and although it passes the tests (I was worried CouchDB would send us `multipart/mixed` types we weren't prepared to accept), it also doesn't seem to solve the problem of extra OPTIONS requests (see 8a42b10e5241f47446335cf8a542c4bc5baac130). In Chrome at least, every GET still seems to be preceded by an OPTIONS. :confused:

**Comment by nolanlawson** [comment]
OK, the good news is that I've tried another approach - avoiding the `'Content-Type'` header for GETs - and actually, this works great. (Removing the `Accept` does indeed cause an error because CouchDB starts sending us data we can't parse.)

With this approach, the tests pass and I can confirm that GETs no longer require so many OPTIONS. I'll open a PR. Thanks @remy!

**Comment by nolanlawson** [comment]
PR: https://github.com/pouchdb/pouchdb/pull/3777

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/c14d52a3e5b8f4b8e6ae72455696e9e7b41d63ac

**Comment by jo** [comment]
Fuck yeah, it works!
