### ISSUE TITLE
adapter performance

### ISSUE THREAD

**Issue by chino23** [pouchdb/pouchdb#3590]
Hey guys,

thanks again for this incredible library. Been using it for over 6 months now and loving it.

So here's the thing: I've been using websql first, but then switched to indexeddb. Now that I'm deploying an app using nw.js (formerly node-webkit), I have the option of running leveldb as well as node (io.js) is shipped within the package.

As far as I understand, leveldb creates an actual database file, which would be great for backups and such. However, I'm wondering about performance issues and stability. I couldn't really find any leveldb vs indexeddb performance comparisons regarding pouchdb. But the generic tests I find seem to heavily favor leveldb.

What's the best approach here in terms of stability and performance?

**Comment by nolanlawson** [comment]
In NW.js, IndexedDB is actually using LevelDB under the hood. That's how Google implemented it.

My gut feeling is that LevelDB would be faster, because it's the same thing, but without the IndexedDB overhead (transactions, object stores, etc.). This definitely could use some numbers, though. :) E.g. a WebKit dev has informed me that SQLite runs faster than LevelDB on Mac OS X due to HFS+.

If you want some more precise numbers, you could build our [performance tests](https://github.com/pouchdb/pouchdb/blob/0a523ed98c545232b761ba1203c57b6ddd393fb8/TESTING.md#performance-tests-in-the-browser) as a NW app and see what it says.

**Comment by chino23** [comment]
Thanks for the clarification. I'll run some tests and post the results here.

**Comment by daleharvey** [comment]
Answered, cheers
