### ISSUE TITLE
High RAM usage while storing large PDF as blob, results in a tab crash in Google Chrome

### ISSUE THREAD

**Issue by KSchreyer** [pouchdb/pouchdb#3640]
When storing large pdf documents as blob, the RAM usage rises up to 1.6GB and more. This issue report is the result of the chromium bug report https://code.google.com/p/chromium/issues/detail?id=412409 and an email conversation with Nolan Lawson.
Also in this chromium ticket, I've added a test script to reproduce the problem. This can be found here:
https://code.google.com/p/chromium/issues/detail?id=412409#c18

As Chris Mumford describes (https://code.google.com/p/chromium/issues/detail?id=412409#c20), the RAM usage rises up to 1,7GB in Firefox until the process finishes. In Google Chrome this currently results in a tab crash, because of a heap exhaustion.

**Comment by nolanlawson** [comment]
[Test script](https://code.google.com/p/chromium/issues/detail?id=412409#hc18)

**Comment by nolanlawson** [comment]
Interestingly, this does not crash Firefox either.

**Comment by nolanlawson** [comment]
OK, the line that causes the crash is [this one](https://github.com/pouchdb/pouchdb/blob/b0b0200ee9a417233c83033538176e13fce3f4f4/lib/utils.js#L740).

Because we don't support blobs in Chrome < latest Canary, we throw an error when the input is too large, because we create gigantic base64 strings.

I suppose one fix is that we could probably get away with storing binary strings in IDB instead of base64 strings. It's never been tested, though.

**Comment by nolanlawson** [comment]
Hm, binary string seems to crash it as well.

**Comment by nolanlawson** [comment]
Developers who are using PouchDB can work around this issue by just breaking up their attachments into smaller chunks. This is probably a good idea anyway when it comes to replication, because we currently don't support multipart/mixed, and so attachments will be converted to base64 strings anyway in order to be replicated to CouchDB.

**Comment by nolanlawson** [comment]
After profiling and actually spending a lot of time on this, I'm pretty sure this is not something we can fix.

The fundamental problem is that Chrome <43 has Blob bugs, so we cannot use Blobs. Hence we have to fall back to base64, which is fundamentally inefficient since we have to keep it as a string in memory.

This is a Chrome bug that will be fixed with 43. If your code needs to run on Chrome <43 I would recommend splitting up your attachment into many smaller attachments. Sorry about that.
