### ISSUE TITLE
question about aborting sync and issues

### ISSUE THREAD

**Issue by chino23** [pouchdb/pouchdb#3651]
What happens if I start a sync, and once the changes get pulled to my PouchDB I just quit the application. Does that mean that only part of the changes have arrived? 

This might easily break some document dependencies. Or does it work that once all the data is pulled, it gets written in one go to avoid that problem?

**Comment by nolanlawson** [comment]
In the PouchDB replicator, the checkpoint is written after documents themselves are written. Replication operations in CouchDB/PouchDB are idempotent, so you can replicate the same documents over and over again and it won't make a difference.

So if e.g. the browser crashes after the docs are written but before the checkpoint is written, then those docs will be re-written. The `batch_size` can be configured in the options; it defaults to 50.

You have another issue (#3652) where you ask about keeping parents and children in sync in a relational-esque database. Replication is another case where trying to maintain this pseudo-schema can cause you headaches. You have zero control over which documents get replicated and when, so your database can easily end up in an illogical state during syncing.

The only way you could possibly resolve this issue is if you write your CRUD logic with the understanding that your database may be in an illogical state, and then act accordingly (e.g. ignoring missing children).

**Comment by chino23** [comment]
Thanks @nolanlawson for that. I'll talk about the sync issue in the other thread then.
