### ISSUE TITLE
Secondary Indexes Take Up Alot of space

### ISSUE THREAD

**Issue by corps** [pouchdb/pouchdb#3665]
Hi guys,

This isn't an immediate bug, but it's been a nagging design issue I've been running up against.  I've built a study based flash card offline website against pouchdb and everything works pretty well --- except on mobile (specifically IOS).  Many of my heavy users have massive libraries of flash cards: 8-10K.  The raw json payloads for these libraries are around 5-7mb, and stored within PouchDB without any views written around 13mb (this is kind of a minor issue itself -- after compaction, it seems to still double the raw payload size for storage).

However, after even a couple trivial secondary indexes, the size requirement can explode to around 60mb, which then can't be loaded in IOS.  To be clear, these indexes all emit entries like this:

emit(cloze.dueAt, undefined)
emit(effectiveInterval(cloze.interval), undefined)

So the keys are relatively simple (just integers), and the values should be empty (though I merely need to query later with include_docs in order to join against the original data).

Most of my indexes are necessary, as the user's libraries are often big (8K items) and the index is on a moving target (say, the due date for when the card should be shown), and needs to be loaded quickly and in bulk in order to have a responsive feel.

My work around right now is use a secondary, in memory pouchdb, that I sync my stored pouchdb to just for the convenience of the indexes.  However, this can still end up causing slowness when the app is first loaded, and for many users snappily loading straight into the "which flash card is due next" is a high priority.

Is there anything I can do to help reduce the size of these indexes?  Is there a design issue within pouchdb that could explain why otherwise very simple indexes would double, triple the size of the original storage?  Thanks!

**Comment by nolanlawson** [comment]
Secondary indexes are currently designed as a completely separate PouchDB database. So every key basically ends up being the `_id` in another database.

This is not the most efficient design, but it allowed us to iterate quickly and get something passing the tests in LevelDB, WebSQL, and IndexedDB. "Native" secondary indexes are an open issue (https://github.com/pouchdb/pouchdb/issues/2280).

I understand your frustration, but generally there are a few possible workarounds:

1) Consolidate your indexes. Many times, you can create a single index from multiple (e.g. if you index on `name` and also `[name, occupation]`, then just use the second one and then use `group_level`).

2) Abuse the main doc `_id` if you can.

3) Don't put anything in your values; looks like you're already doing that.

4) If your data is large and "binary"-ish (i.e. you don't need to introspect it), then using attachments can help, because PouchDB will deduplicate duplicate attachments. This only really helps reduce the size of your primary index, though.

5) Compact, or use auto-compaction. Again, only reduces the size of the primary index.

6) Use something else for your secondary indexes - LocalForage might be a good fit here, because it works in all the same browsers as PouchDB and is very lightweight (<10MB iirc). Recently I demonstrated that, for very large indexes, I could use straight-up IndexedDB and WebSQL and get orders of magnitude improvements in performance over PouchDB for a full-text search task: https://github.com/nolanlawson/pouchdb-quick-search/issues/22#issuecomment-72150063. Your keys could be keys and your values could be PouchDB `_id`s; it doesn't have to be fancy.

Let me know if that helps! :smiley:

**Comment by corps** [comment]
Actually, I think I have figured out the problem -- and it's totally unrelated to the secondary index sizes themselves!

The clue was when you explained to me that indexes are modeled using entirely separate PouchDB's.  Is it possible that those index PouchDBs are constructed borrowing the opts params from the main PouchDB?  

Recently, I had to increase the requested size limit of the PouchDB constructor to accommodate my largest user's database to around 20mb.  That's around the same time when I started noticing the issue on iOS of the storage not fitting within 50mb.  While the main content would load and fit, the secondary indexes would not.  I assumed this was due to their size, but after I analyzed the issue locally on my Mac OSX safari, I realized the size of these user's data total was still well within 50mb -- but rather, each one seems to be requesting 20mb sized databases, resulting in what safari thinks is a 100mb capacity requirement.

You can demonstrate this fairly simply by creating a PouchDB with size param of, say, 20mb, and then creating 2 or more indexes.  Run the code and safari, and you'll get a prompt after the final indexes are built to increase the size to 100mb.

Would there be any trick I could apply to change the size of primary PouchDB but configure the PouchDB constructors of my indexes separately altogether?

**Comment by corps** [comment]
Ok, I think I may have found a solution without any code changes.  It does seem to make a difference to request different sized databases that fit in total under less than 50mb, even if the actual contents would still fit.  So in order to configure my views into having separate requested sizes than the main PouchDB, I roughly did this:

new PouchDB('mydb', {size: 20}, function(mainDb) {
  new PouchDB('mydb', {size: 5}, function(viewsDb) {
    viewsDb.put({ _id: '_design/myview', views: { ... my view configuration here... });
  }
})

The result is as I expected, the views were created with databases configured with the 5mb size limit, while the main database was configured with the correct size, and the two are still "related" together as expected.  The only thing that sucks is that I end up getting two pop ups, one first to increase the size limits to 25mb, then another to 50mb after the other views are created.  Otherwise, this works.  Would be interesting if it would be possible to share the same database between views in websql, so that you could just request one "big" database for 50mb, and not care how to distribute your size limits amongst your views before hand.

**Comment by nolanlawson** [comment]
Ugh, that is a nasty hack. Unfortunately I don't think there's a good workaround right now; the safari popup is brutal. We can't put both pouches in the same websql database. Sqlite Plugin is a solution if you're using Cordova/phonegap.

**Comment by corps** [comment]
I understand.  Oh well, this hack works well enough when I let the users know before hand, thanks for the help.  Should I close the issue?
