### ISSUE TITLE
put and changes in the same tick with memdown?

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#3686]
What would it take to be able to get a "put" and the corresponding "changes" call to be performed in the same tick using leveldb + memdown?

Would it be possible to achieve by building a plugin?

**Comment by nolanlawson** [comment]
It's not really doable, because MemDOWN is asynchronous and correctly doesn't release Zalgo:    http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony

**Comment by nolanlawson** [comment]
Also memdown is an implementation of levelup, which has a requirement to be async and non-Zalgo-releasing.

**Comment by ronag** [comment]
I see. That kind of makes sense. I guess I'll have to build some form of a cache layer on top of pouchdb then.

**Comment by ronag** [comment]
Would it be possible to schedule at the end of the current tick instead of the next tick. That would both avoid Zalgo and provide the behaviour necessary for e.g. <input> tags in React.

**Comment by ronag** [comment]
See also https://github.com/medikoo/next-tick

**Comment by calvinmetcalf** [comment]
Also https://github.com/calvinmetcalf/immediate

**Comment by nolanlawson** [comment]
So yeah since we're never going to be able to make guarantees about the event loop (due to PouchDB being a unified abstraction over so many different async APIs), I'm gonna go ahead and close this.

Ultimately I think your real issue @ronag is that the memory adapter is just too damn slow. The proper solution to that is to write a custom memory adapter to replace the current, somewhat bloated MemDOWN one. I commented on some ideas for that [here](https://github.com/pouchdb/pouchdb/issues/3644#issue-62377668); it's something I would do myself if I had a spare weekend. :)

**Comment by ronag** [comment]
@nolanlawson: Actually, my problem isn't that it is slow, it's that it is asynchronous which totally breaks things like input fields directly backed by pouchdb.

This is the only issue that is still keeping us from leaving firebase and going all out pouchdb...

**Comment by nolanlawson** [comment]
Firebase synchronously commits changes by using LocalStorage, which is capped at 5MB in some browsers and can block the DOM.
