### ISSUE TITLE
PouchDB not working in IE8

### ISSUE THREAD

**Issue by sannitesh** [pouchdb/pouchdb#3688]
I am testing PouchDB app in IE8, but I am getting following errors. I have included pouchdb.localstorage.js and es5.shim.js file in index.html.

You can find below the errors:

Expected Identifier, string or number for following line (pouchdb.localstorge.js):
Line no. 11019: , try: [
Expected Identifier for following line (main.js - local js file):
}).catch(function (err) { console.log('Unable to insert into DB. Error: ' + err.name + ' - ' + err.message); });

**Comment by nolanlawson** [comment]
Seems we need to es3ify the plugins

**Comment by nolanlawson** [comment]
If you use the `pouchdb.localstorage.min.js` instead, that should fix the problem because it automatically es3ifies.

Unfortunately I don't seem able to use browserify's `es3ify` transform here, because this `try` is in a dependency, so the transform doesn't apply. Making me thing that `es3ify` is really not a good solution to this problem if it only applies to our own code.

**Comment by nolanlawson** [comment]
browserify's `-g` global transform not working either, due to `Error: Parse Error: Line 2: Unexpected token`.

**Comment by nolanlawson** [comment]
this will be fixed in the next release thanks to 5d4265a8fd5738551d368cb2d69be4cb6bce5e88, or if you can't wait, here's a build: https://nolanlawson.s3.amazonaws.com/pouchdb/www/20150412/pouchdb.localstorage.js
