### ISSUE TITLE
QT QML compatibility

### ISSUE THREAD

**Issue by remi-parain** [pouchdb/pouchdb#3709]
I'm trying to adapt the pouchDB js library to be used in  QML JS context and use the qt provided sql storage ( http://doc.qt.io/qt-5/qtquick-localstorage-qmlmodule.html )

I'm facing some issues while i'm trying to import the CDN browserified version of pouchDB (3.3.1).
As the QML implements the ECMA-262 5th edition I think it will be possible to make it work ( with some modification).

Here is the link for QML JS support and limitations :
http://doc.qt.io/qt-5/qtqml-javascript-hostenvironment.html

The issue maybe related to these QML limitations :
   * no DOM (no 'window' var)
   * JavaScript code cannot modify the global object.

I still have hope as someone managed to import Moment.js in QML ( https://plus.google.com/+MikkoAhlroth/posts/JW67rSDkMeH )  with little modification but it seems ineffective (or not enough) for PouchDB.

Does anyone has an idea on how to process? ( I really wants to make it works so i can get rid off couchbaselite binaries ).

**Comment by nolanlawson** [comment]
Never tried to get PouchDB to run in Qt, but you may be interested in this project: https://pypi.python.org/pypi/Python-PouchDB/0.4.1

**Comment by marten-de-vries** [comment]
I've tried this before (as a way of moving away from QtWebKit in Python-PouchDB). There's a few problems:
- Qt's websql implementation is synchronous, not asynchronous. As far as I know, they're the only ones implementing the synchronous version of the spec. (Browsers never did that IIRC). PouchDB only supports the async version. I've somewhat succesfully tried wrapping the synchronous version with the equivalent async API, but it never got to the point where it worked flawlessly. Probably because my websql experience is quite limited.
- Qt's ecmascript implementation has a few extra reserved keywords which prevents it from parsing vanilla PouchDB. IIRC correctly it was some type, maybe 'int'. A simple search/replace fixed that, though.

**Comment by marten-de-vries** [comment]
I digged up the code I once wrote and pushed it to Github. As I said, it doesn't fully work and it's a bit old by now, but it might still contain something useful. https://github.com/marten-de-vries/pouchdb-qml

**Comment by remi-parain** [comment]
thanks you very much to both of you. I'll see what I can do with all this additional informations !

**Comment by daleharvey** [comment]
Very happy to receive any patches that help qt compatibility but unless its something being actively worked on I dont think we need to keep this bug open, cheers (please reopen / open a new bug if someone does start working on this)

**Comment by marten-de-vries** [comment]
FWIW, the files I posted previously are probably not the way to go in that case. A synchronous websql adapter has a far better chance of achieving correctness than trying to add an async interface, which gives fundamental problems.
