### ISSUE TITLE
Replication event handlers must not throw exceptions

### ISSUE THREAD

**Issue by dholth** [pouchdb/pouchdb#3715]
If replication event handlers throw exceptions, replication tends to fail with EventEmitter overflow errors etc.

**Comment by nolanlawson** [comment]
I think the standard Node solution to the "too many listeners" problem is to just increase the max number of listeners.

If we try to solve the problem in PouchDB, i.e. try tokeep the number of listeners always <10 *regardless of what the client code is doing*, then we will have a sad time, because that is an impossible task. Users are free to add an infinite number of listeners if they want to, especially if they have some very complex replication logic.

I think this should be documented in "common errors."

**Comment by nolanlawson** [comment]
@calvinmetcalf Can you back me up here? I consider you the Node guru. :)

**Comment by daleharvey** [comment]
Regardless of the client code, if it sets up a whole bunch of changes listeners then yeh we dont particularly want to worry about working around bad code, but we are definitely leaking listeners in replication (very likely in sync) so there is still a valid bug here

**Comment by dholth** [comment]
It seems that if you throw an exception in an event handler, it somehow leaks event handlers.

**Comment by daleharvey** [comment]
Closing as a dupe - https://github.com/pouchdb/pouchdb/issues/4093
