### ISSUE TITLE
[question] pouchdb, so for each user in my application, we have a database created?

### ISSUE THREAD

**Issue by ptgamr** [pouchdb/pouchdb#3732]
Not really an issue, better mark it as a question/discussion

**Comment by nickcolley** [comment]
Hey @ptgamr!

This information might help you with this: https://github.com/nolanlawson/pouchdb-authentication#couchdb-authentication-recipes

**Comment by ptgamr** [comment]
@nickcolley  thanks for your hint! However, after reading this, I still haven't found any solution that suits my case. I am developing [SoundCloudify](https://chrome.google.com/webstore/detail/soundcloudify/boblphpidkohagaoinepjgecndchlnbk), in the next version, I'm going to save some user data like: playlist, playback history, and their activities.

The only thing I have to identify a user is his **GooglePlusId** retrieved via `chrome.identity` API when user has logged in in Chrome.

I would not go for the approach **database per user**, since this looks not fine for me, after reading [this thread in stackoverflow](http://stackoverflow.com/questions/28538537/couchdb-separate-database-for-each-user).

After that, I start to think what happen if I only have one database for all user. Let imagine I have this database: **http://localhost:5984/soundcloudify**.  With **PouchDB.sync**, I believe it will sync the entire database. Is there anyway that a client can only sync the documents that they own?

**Comment by daleharvey** [comment]
@ptgamr what parts in particular are you worried about for per user databases? It looks like the ideal approach for the application you mentioned.

**Comment by ptgamr** [comment]
@daleharvey I'm worried about some points:
1. I want to do some analysis as well as activities logging in my application. This is quite impossible with per user database
2. There is a feature that I want to implement: ** sharing playlist **. Let image if that playlist existed in one user's db. How can I share that to the public?

**Comment by ermouth** [comment]
@ptgamr I think I was an author of stackoverflow answer, that induced your doubts, so I must comment on your question. 

You can have two Pouch buckets – first, with private profile info, is synced with user remote DB, second – with shared DB. You can partially mirror first to second using Pouch filtered replication that will continuously replicate only those playlist docs, that are marked as public. Also you can replicate from public Couch using filter (that would be list of playlists you follow).

To reduce traffic you can replicate from first to second DB (of from second DB to remote Couch) eventually – say, once an hour or immidiately after public playlist just created/shared.

Please note, that architecture of this kind is ineffective, if you have more then several thousands (or sometimes hunreds) of users.

**Comment by nolanlawson** [comment]
Another strategy is to use one-db-per-user, but add a server-side process to occasionally dump user databases into some global database. E.g. here is a simple Node app:

```js
var Promise = require('bluebird');
var request = Promise.promisifyAll(require('request'));
function syncEverythingToGlobalDB() {
  return request.getAsync('http://localhost:5984/_all_dbs').then(function (dbNames) {
    // find your user databases, however you named them
    var userDBs = dbNames.filter(function (x) { return x.indexOf('userdb') === 0; });
    return Promise.all(userDBs.map(function (userDB) {
        return request.postAsync({
          url: 'http://localhost:5984/_replicate',
          json: {source: 'http://localhost:5984/' + userDB, target: 'http://localhost:5984/globaldb'}
       });
  });
}
// do it every hour
setInterval(syncEverythingToGlobalDB, 3600000);
```

Notice I recommend using pure CouchDB for this because then you're using CouchDB's replicator. If you used PouchDB's replicator, then you'd have a lot of Node EventEmitters in one process and it would probably be inefficient; CouchDB is much better at handling many simultaneous replications.

**Comment by ptgamr** [comment]
@ermouth @nolanlawson

I would prefer to have global database that sync every hour. This solved the first problem regarding analysis the data.  But still my number 2., if I wait for 1 hour for the data to be sync, *user shared playlist* is not accessible at the moment it has not been sync yet?

**Comment by ermouth** [comment]
@nolanlawson it‘s at lest cost ineffective since you employ server for a task that can be performed by user. 

@ptgamr you can enforce immidiate replication on sharing just happened – I‘ve mention it. It solves your problem.

**Comment by nolanlawson** [comment]
@ermouth Yes, you could allow users to replicate from their local PouchDB to the global CouchDB. The problem there is that then they have write-access to a global database. :) So you have to get very fancy with your CouchDB security settings (`validate_doc_update` etc.). Whereas in my solution it's all server-side, so the security situation is easy.

@ptgamr Yes, in that case you will want to set up continuous replication. Read [the CouchDB guide](http://guide.couchdb.org/draft/replication.html), but basically you just add `"continuous":true` to what I wrote above, and CouchDB will manage replication for you. It's probably still prudent to start it up every day in case the replication task ever stops. You can see current running replication tasks at `http://localhost:5984/_utils/replicator.html`.

**Comment by ermouth** [comment]
@nolanlawson validate_doc_update, that allows user to write/update a doc only when user is listed in doc‘s ACL is very simple. Rejecting docs were user listed in ACL is not the user authorized is also simple.

Your solution does not scale well and impractical – I‘ve tested configuration of this kind. Main hurdle – Couch does not always finish replication successfully, so sometimes you need to restart it. Restarts complicate situation dramatically since you must build batch queue that have out-of order execution and repeat policy.

Also there are a lot of problems of other kind, that are unsolvable using Couch only – we must control spoofing, rates, have to manage user accounts, send emails and so on.

**Comment by ptgamr** [comment]
@ermouth thank you :+1: I think I will give your solution a go!

**Comment by ermouth** [comment]
@ptgamr you are welcome. Also take a look at cloudwall.me – it can be useful to manipulate local PouchDB instances – or event to create your app itself )

**Comment by nolanlawson** [comment]
@ermouth Fair enough; I admit re-starting a dead replication task is a bit annoying in CouchDB. In any case, there are lots of options here! :)

**Comment by daleharvey** [comment]
In general pouchdb is very much setup towards having a database per user, I dont think the problems with this setup @ermouth mentions in stack overflow are particularly applicable. A lot of them look like problems of trying to use couchdb as an app platform and not a database

The shared access control problem is a common problem with not a lot of proven solutions for, using acls on a single database, replicating central databases on the server are ways people have dealt with it and your mileage may vary, in general I would swing the opposite way of ermouth though and do a solution with per user db's as a base

**Comment by ptgamr** [comment]
@ermouth I have a very neat implementation here: https://github.com/ptgamr/soundcloudify/blob/pouchdb/app/scripts/services/PouchDB.js

**Comment by ermouth** [comment]
@daleharvey Well, I did not say per-user DB approach is no way. But all the problems I‘ve listed are taken from real life – so they are applicable. A lot of developers, especially novices, who just discovered Couch, tend to think it‘s a silver bullet – I just argued why it‘s not.

> trying to use couchdb as an app platform and not a database
Well, don‘t you think there exist a reason for this fact? Try to google something about CouchDB based architecture – you‘ll find a lot of obsolete docs about couchapps and other approaches where Couch acts as an app platform – and nearly nothing more or less up-to-date where Couch is just DB.

**Comment by ermouth** [comment]
@ptgamr Nice! But you better hash user id in some way when create DB for user – Couch allows very limited subset of chars in DB names.

**Comment by daleharvey** [comment]
Discussion looks done, cheers

**Comment by bapatel1** [comment]
Is there a downside or limitation of having per user database on pouch-couch? I read some places that you have to keep number of buckets low (max 10 or something) else it might hurt performance or latency. Please let me know.

**Comment by danielfoxp2** [comment]
Sorry for up this thread. I thought here would be better to place my worries.

I have a very similar problem than @ptgamr. But his problem can be solved by one db per user strategy I guess.

I am new to couchdb so I am very confused. Without further ado, here is my problem:

I'm working on an offline first vuejs research app where people will be able to create questionnaires and do interviews using this questionnaires created. Some of the rules are:

* A questionnaire can be created/edited/removed only by the author of the research;
* A research can have the author and collaborators;
* The collaborators can only apply the questionnaires at an interview;
* An author of one research can be a collaborator in another one;
* An user can only see researches that he is an author or a collaborator;

So, clearly, I don't have a case of one db per user here. But I don't know how to go with couchdb.
I want to use PouchDB and CouchDB to leverage the automatic sync and such they have together. So I don't wanna lose those goodies by building a backend in the middle of them. If so, I would do it with postgres and avoid headaches.

Till now, I had establish a rule to id my documents like:

* **User** its id is always the higher one plus 10;
* **Research** its id is always the user id concatenated with a serial number starting at 1;
* **Questionnaire** its id is always the research id concatenated with a serial number starting at 1;
* **Sections** (inner parts of a questionnaire) its id is always the questionnaire id concatenated with a serial number starting at 1;
* **Questions** its id is always the section id concatenated with a serial number starting at 1;
* **PossibleAnswers** its id is always the question id concatenated with a serial number starting at 1;

Examples:
* Users will have ids like: **10**, **20**, **30**, **40**, **50**... always plus 10 the highest one.
* Research will have ids like: 10**1**, 10**2**, ..., 20**1**, 20**2**, ..., 100**1**...
* Questionnaires like: 101**1**, 102**1**, ..., 201**1**, 202**1**, ..., 1001**1**...
* Sections like: 1011**1**, 1021**1**, ..., 2011**1**, 2021**1**, ..., 10011**1**...
* Questions like: 10111**1**, 10211**1**, ..., 20111**1**, 20211**1**, ..., 100111**1**...
* Possible answers like: 101111**1**, 102111**1**, ..., 201111**1**, 202111**1**, ..., 1001111**1**...

These is to avoid id conflicts at the same time that I maintain some form of relation between all these items. But why not use the id as string and separated by dots like a question: '10.1.1.1.1'? Because I am following the react best practice for modeling data. Like:
```javascript
{ 
  data: {
    100: {
       id: 100,
       otherThing: 'whatever'
     },
    200: {
      id: 200,
      ...
    }
  },
  allIds: [100, 200]
}
```
This is a good way to speed up sorting and searching in objects etc... So, following this I am using the ids as number instead of string (that could be sorted in the wrong way).

But I don't want to download to the user 10 all documents from user 20, 30, 1000... I want him to see only what he can see as the rules above states. At the same time, if the user 20 is a colaborator of the research 3 of the user 10, I want that the user 20 to see that research when sync.

I am thinking at filtered replication but I couldn't think how to build this solution yet. So much new and confusing things that I feel like I'm overwhelmed. Can you guys give me some light on it, is this doable???

I'll will notify some of you guys here, only because I'm desperate, sorry if this had annoyed you.
@nolanlawson @daleharvey @ermouth 

Thanks in advance.

**Comment by zim32** [comment]
I know this is old post, but what if you make an http proxy between.browser and global db, intercept replicate requests add view or filter function to request and pass to original database?
