### ISSUE TITLE
Couchbase-Lite as a Pouch Adapter / Pouch as Couchbase-Lite API?

### ISSUE THREAD

**Issue by jfspencer** [pouchdb/pouchdb#3733]
I have been looking into non-storage capped alternatives to the sqlite plugin, primarily in search of a more performant alternative.

I tried setting up pouch with the [couchbase-lite-phonegap-plugin](https://github.com/couchbaselabs/Couchbase-Lite-PhoneGap-Plugin) thinking I could use an httpish arrangement. I get 404s from _changes

What is needed to get the [couchbase-lite-phonegap-plugin](https://github.com/couchbaselabs/Couchbase-Lite-PhoneGap-Plugin) to serve as an adapter for pouch or for pouch to act as an API for couches-lite?

I have the time to invest to get it done, just need to know where to start :)

**Comment by nolanlawson** [comment]
It would be a lot of work, not gonna lie. You'd have to write a custom PouchDB adapter, in the same vein as `idb.js`, `http.js`, etc. (check the source code under `lib/adapters`).

Alternatively, if you are using the HTTP API, then yeah, you should just be able to use `var remoteDB = new PouchDB('http://path/to/whatever') and then `localDB.sync(remoteDB)`. However I seem to recall there are some bugs in the HTTP API that prevent this (see https://github.com/couchbase/couchbase-lite-android/issues/227).

The reason the SQLite Plugin is slow is because Cordova has to continually serialize JavaScript objects into strings in order to pass them between the WebView and the native code. So that is not a problem you can easily avoid.

You can use IndexedDB or WebSQL if you want better performance than the SQLite Plugin. If you want to reduce space on-disk, you can use the `transform-pouch` plugin to compress data before storing it. Alternatively, the issue may be that you are doing too many small reads/writes to PouchDB &ndash; are you using the bulk APIs like `allDocs()` and `bulkDocs()` or are you using the non-bulk APIs like `get()` and `put()`?

**Comment by viskin** [comment]
I started to implement a test Phonegap-Couchbase-Lite-PouchDB app without knowing that there are known issues with this setup. Couchbase-Lite seems like reasonable configuration in Phonegap environment, as PouchDB will just REST the cordova plugin. I don't know is it better than SQLite plugin adapter, but one more alternative is better.

Anyway, IndexedDB or WebSQL is problematic on Phonegap because their storage is limited.

As my current work is to bring closer PouchDB and KendoUI, I tried to build demo app that shows them work with Couchbase Lite. I've [put it on github](https://github.com/terikon/kendo-pouchdb-app). It performs CRUD operations with PouchDB REST on Couchbase Lite.

So far the only problem I have is that db.put(doc) never works. Always throws error. Pretty serious problem indeed. But db.bulkDocs([doc]) works perfectly with same document.

Can it be the only problem? If so, fixing it may add one more great feature to PouchDB, and my POC project will pass.

**Comment by jfspencer** [comment]
I will take a look at your project. It would be awesome to use cbl as the
adapter. If I can get my tests up and running with it I'll post back on the
performance differences between the two.

**Comment by nolanlawson** [comment]
I've started some *very very tentative work* on a custom adapter for PouchDB, using WebSockets: https://github.com/nolanlawson/socket-pouch. You can use it as a reference implementation if you'd like to try to implement a custom CBL adapter.

In general, though, I think an easier fix would be to fix CBL to expose a more CouchDB-like REST API. https://github.com/couchbase/couchbase-lite-android/issues/227 would be a great place to start.

**Comment by nolanlawson** [comment]
Also again, I don't see any theoretical reason why a CBL adapter would be faster than the existing SQLite Plugin adapter. In both cases you have to serialize data between JavaScript and the native code, and in both cases you're talking to SQLite under the hood. Perhaps [the SQLite Plugin itself](https://github.com/litehelpers/Cordova-sqlite-storage) could use some love.

**Comment by jfspencer** [comment]
@nolanlawson Thats a good point, i'll reach out to the SQLite guys and see where  I can help with performance there. Thanks!
