### ISSUE TITLE
Alternating indexdb and websql adapters in the same browser

### ISSUE THREAD

**Issue by hakan1111** [pouchdb/pouchdb#3757]
Hi,
thought I would add another issue that we can not explain and get any new input on why/how it can happen. 
We are experiencing that pouchdb is using either indexeddb or websql in the same browser (of course running the same code).
As a result, data is saved in 2 different dbs and our users does not have access to all their data.

We are using PouchDB 3.3.1 right now.
Attaching a screen-shot from chrome to clarify the issue and to show that the same dbs are created in either idb or websql. 
Unfortunately I can not reproduce this, but as soon as I can I will update this issue.

@nolanlawson Can you give us any clues for when this could happen it would be great

BR /Håkan
![image](https://cloud.githubusercontent.com/assets/11521724/7274431/f43b9c12-e8fc-11e4-96fd-766258bef0d7.png)

**Comment by nolanlawson** [comment]
This bug should only occur during testing. If you clear all browser data (including local storage) and then stick with either websql or IndexedDB it will go away.

Long answer: we have a local storage flag to tell us if a database was ever opened in websql. If a websql-only browser like Android 4.3 gets updated to include IndexedDB, then your existing users don't lose data because we stick with websql for that database.

Let me know if that describes your issue. If not, please provide a reproducible test case. :)

**Comment by nolanlawson** [comment]
We should probably add a console message to let people know when we are forcibly downgrading to websql btw

**Comment by hakan1111** [comment]
Thanks for quick answer there Nolan, don't you ever sleep?

The sticky behaviour is there, ie if ever websql has been used Pouchdb will always use websql. My problem (which I am trying to reproduce 8-) ) is why - suddenly - websql is used instead of idb when (re)initalising the dbs. We do not force either idb or websql in our code (we just use the browser default) so we are searching for reasons for why/how this can happen.

The "data loss" I was talking about above occurs when data has been stored in idb in one session, and then suddenly - in a later session - a websql adapter is used instead. So there is historical data in indexeddb and new data in websql making the historical data unavailable (for the users of our app at least).

Again, sorry for not being able to provide reproducible test case, will work on that.

**Comment by hakan1111** [comment]
Another questions is what adapter(s) are currently supported for Chrome on iOS? It is not explicitly listed here -> http://pouchdb.com/adapters.html.
However the info note below suggests that Pouchdb does not use the idb adapter generally for iOS 8+. Is that still true and does it apply to Chrome on iOS?

**Comment by nolanlawson** [comment]
> Thanks for quick answer there Nolan, don't you ever sleep?

Not enough. :)

> The "data loss" I was talking about above occurs when data has been stored in idb in one session, and then suddenly - in a later session - a websql adapter is used instead.

That is really strange and I don't understand how that could happen. :/ Test case? :D

> Another questions is what adapter(s) are currently supported for Chrome on iOS?

Ah, so you're using Chrome on iOS. As far as I know, it is actually a UIWebView under the hood (**not** truly Chrome), so probably it will fall back to WebSQL. I'm not sure, though.

**Comment by nolanlawson** [comment]
Other things: please update to PouchDB 3.4.0, and also can you confirm that you are only seeing this bug in Chrome on iOS?

**Comment by hakan1111** [comment]
Confirmed that Chrome on iOS always uses the websql adapter in our tests at least. 

However, so far the bug appears only on Chrome Version 42.0.2311.90 m (64-bit) for Win 8.1, ie desktop.

**Comment by nolanlawson** [comment]
Ah, okay. Do you have a test to reproduce by any chance?

**Comment by hakan1111** [comment]
Found out how to trigger adapter:websql on Chrome/Win8.1. 
In Chrome you can change User Agent in development tools. So when you choose Apple iPad for example, then Pouch will start using websql - even when/if idb adapter has been used before. So this means that there will be data both in idb and websql dbs, but only websql dbs will be accessed by Pouch. 
Also - Pouch will from this moment always use websql adapter until cache is wiped (default Pouch behaviour). Even after you go back to default User Agent.

Right or wrong? Don't know, but at least we know now why it happens.

**Comment by nolanlawson** [comment]
Ah okay, this is understandable. Yes, if Chrome is imitating iPad, then based on the user agent, PouchDB will avoid using IndexedDB because Safari's implementation of IndexedDB is broken. (See [this code](https://github.com/pouchdb/pouchdb/blob/42c86b481b604961561f2caf27fd91d01d8dc92f/lib/adapters/idb/idb.js#L910-L922).) So that's how this happened. :)

**Comment by hakan1111** [comment]
OK, closing the issue

**Comment by leewalkergm** [comment]
I know this is very old but the workaround wasn't provided.

We recently came across this exact scenario and had to do the following from the dev tools console:
`
var db = new PouchDB("dbname");
db.destroy().then(function () { console.log("Success"); });
`

**Comment by nolanlawson** [comment]
So, the reason we do this is because browsers may start with WebSQL and then be upgraded to IndexedDB later (e.g. when Android updates from 4.3 to 4.4).

If we didn't do this, then people would lose data. Currently the only solution to the problem from a dev's point of view is to either 1) completely clear all browser data and try again, or 2) use different names for a WebSQL db vs an IndexedDB db.

**Comment by leewalkergm** [comment]
I completely understand it from the library point of view :)

Just providing a workaround for those in the same position - saving a bit of confusion/pain of them trying to work out how to do it.

**Comment by nolanlawson** [comment]
What exactly are you trying to do? If you want to remove all data from the browser, the easiest way is Chrome -> Dev Tools -> Application -> Clear Data.

**Comment by leewalkergm** [comment]
We had a user who used the chrome dev tools to emulate an iPad for their testing, which switched their system to using WebSQL instead of IndexedDB (where days worth of work was stored) and so we had to delete their WebSQL database for Pouch to switch back to IndexedDB.

**Comment by nolanlawson** [comment]
Yep, clearing out all browser data would work in that case.

**Comment by leewalkergm** [comment]
But as I said, it would also clear their days worth of work within the IndexedDB - Perhaps we should just say; our workaround is to clear the WebSQL db out so that you can continue to use a pre-existing IndexedDB.

**Comment by nolanlawson** [comment]
If users are emulating different user agents, then it's going to cause problems; I'm sorry but we have no real way to deal with that.

Another workaround is to delete the place in localStorage where it tells PouchDB to fall back to WebSQL:

![screenshot 2016-06-24 08 01 47](https://cloud.githubusercontent.com/assets/283842/16341448/eda1fd42-39e1-11e6-8b8d-3a075370eb7a.png)

Just delete that line with "websql" in it and PouchDB will use IndexedDB instead of WebSQL.

**Comment by paulocoghi** [comment]
This happened to me. In my case it was a feature, not a bug.

I was testing the responsive design of my project and selected iPhone 5 in Chrome Dev Tools/Device Mode.

Since PouchDB understood that I was using an iPhone, it stopped to use IDB and started to use WebSQL instead. From this moment on, it was left with two databases.

**A possibly better solution**
If such scenario is undesirable, identify where PuchDB is running using [window.navigator.platform](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorID.platform) seems to be more solid, since this property is [not spoofed when the userAgent string is changed](http://stackoverflow.com/questions/10527983/best-way-to-detect-mac-os-x-or-windows-computers-with-javascript-or-jquery).
