### ISSUE TITLE
Check if index is ready

### ISSUE THREAD

**Issue by chrisschaub** [pouchdb/pouchdb#3781]
What is the best way to check if an index is ready? I'm loading in a few hundred docs and they are not avail right away. I get a can't find useable index error from pouchdb-find. It would be great to load the data and then poll the db with a loading message to the user saying "rebuilding indexes" or something until the indexes are ready.

**Comment by nolanlawson** [comment]
We're working on making the indexing faster, so that hopefully this won't be an issue because the index will be ready quite fast. :)

In the meantime, though, no: there is no way to know if it is "ready." You can, however, use `stale: 'ok'` when you query and see if the number of results you get back is the number you expected, which can be used to approximate the build time.

**Comment by chrisschaub** [comment]
Thanks. I think I'll trap for the error saying can't find useable index and just retry.

**Comment by robertkeizer** [comment]
@nolanlawson It would be nice if events were emitted that handled this; Perhaps something for the mapreduce repository?

**Comment by nolanlawson** [comment]
@robertkeizer I'm probably going to end up speeding up the map/reduce code within the next few months (depends on how much free time I have; right now all my time is being eaten up by more serious `retry` replication issues :stuck_out_tongue: ). I'd rather wait for that instead of adding a new event system that we'd have to maintain.

**Comment by daleharvey** [comment]
Given our general shift is away from map / reduce, closing out any older feature requests on it for now
