### ISSUE TITLE
allDocs doesnt support start_key as alias for startkey

### ISSUE THREAD

**Issue by marten-de-vries** [pouchdb/pouchdb#3883]
CouchDB supports ``start_key`` as an alias for ``startkey`` for views. At the very least that should be supported in ``express-pouchdb``, but it would be nice if plain PouchDB supported it as well. (To make migrating from CouchDB -> PouchDB easier, that's where I encountered this).

Same for a few others, both url endpoints and parameters (like ``end_key``):
- http://docs.couchdb.org/en/latest/api/ddoc/views.html
- http://docs.couchdb.org/en/latest/api/database/bulk-api.html

**Comment by nolanlawson** [comment]
whoa, I've never seen those before. Yeah, I think PouchDB core should support these.

**Comment by daleharvey** [comment]
So given some [inspiration](https://medium.com/@kentcdodds/first-timers-only-78281ea47455) I decided to stop fixing this after writing the test and let a new contributor do the fix. Hopefully the following steps are reasonably clear. If you run in to any issues then feel free to [get in touch](https://github.com/pouchdb/pouchdb#getting-help). 

 * Clone the PouchDB repo and setup locally, there is a [guide](https://github.com/pouchdb/pouchdb/blob/master/CONTRIBUTING.md#building-pouchdb) to help out.
 * Ensure your local setup is working with 'npm test', it will take around 2 minutes and should pass
 * Go to `inserturlwhenmerged` and remove the `.skip` from the test
 * Run `GREP=3883 npm test`, this should now be failing
 * The first part that needs fixed is [/lib/adapters/http/index.js](https://github.com/pouchdb/pouchdb/blob/master/lib/adapters/http/index.js#L703), open that file and fix it to ensure if `start_key` is defined instead of `startkey` we use `start_keys` value
 * Once thats done and you run the test, there should be 1 passing and one failing, you will now need to add the same logic to [/lib/adapter.js](https://github.com/pouchdb/pouchdb/blob/master/lib/adapter.js#L652) to fix it for the other adapters aside from http (websql, leveldb, indexeddb)
 * Once the tests are passing, that is it done, commit and push your changes and celebrate :)

**Comment by Charlotteis** [comment]
So I tried to start this:
1) Cloned, setup and tested the pouchdb repo.
2) Copy and pasted the test you wrote to line 283 of `test.all_docs.js`
3) Found the mention of `startkey` in `adapters/http/index.js`.
4) Added new code to recognise `start_key` and get it's value.

I now have 1 test passing and one failing.
I am now looking at `adapter.js` but am not sure what to do there. I tried adding it to `incompatibleOpts` but it didn't seem to make the test pass.

Thank you so much for this issue, @daleharvey , I hope I can solve it.

**Comment by nickcolley** [comment]
yo @Charlotteis could you push your WIP to your fork so we can see the diff? :dancers:

**Comment by Charlotteis** [comment]
:wave: Hallo @nickcolley. Can see my work here: https://github.com/Charlotteis/pouchdb/tree/3883-allDocs-start_key

**Comment by nickcolley** [comment]
Looking good!

I made a little comment here regarding the http key: https://github.com/Charlotteis/pouchdb/commit/b5944756d453fca305bd6897952c1d8c1472f98c#commitcomment-12673704

Will leave for the other peeps *ducks out*

**Comment by nolanlawson** [comment]
fixed by f8629e3be86e619411598848b368ff9cd7846e56
