### ISSUE TITLE
Make auto_compation=true default?

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#3898]
So users almost never care about having outdated revisions stored locally and similiarly dont want to deal with when to compact, When this was originally made it was planned to be the default, should we make the switch to having it enabled by default, turned off as an option?

**Comment by nickcolley** [comment]
:+1: I think since it's important to keep used space to a minimum on user's devices this should be opt-out.

**Comment by nolanlawson** [comment]
(Sorry, I commented in #3899, but then I realized it's more useful to comment here.)

I'm fairly -1 on changing the auto_compaction default to true. I think it will be a confusing change for users, even in a major version, with no benefit other than (unmeasured benefits to) reduced space, and at the expense of extra CPU cycles to delete stuff for every `bulkDocs()`. The other big cost here is the cognitive overhead for users who have to figure out why a default was switched from false to true.

In my mind, software should do the safest thing by default, and then allow users to opt-in to more dangerous options. To me, `auto_compaction` is a dangerous option, because it removes the possibility of recovering lost revisions (or of using a plugin like [pouchdb-full-sync](https://github.com/nolanlawson/pouchdb-full-sync)). Basically we would be punishing users who don't read the documentation thoroughly enough (by deleting revisions they didn't realize would be lost) instead of rewarding users who read the documentation (by giving them an option to eke out more storage gains).

One of the big benefits of PouchDB/CouchDB over something like Firebase is that we *don't* just delete stuff willy-nilly, and I love being able to tell people, "PouchDB is the database that cares about your data." In practice, I also see plenty of users adding `{auto_compaction: true}` anyway, which shows that they do read the documentation and are happy to opt-in.

**Comment by daleharvey** [comment]
I very much agree that caring about users data is of the largest importance, but I dont think having storing every version of every document forever is a reasonable default. I think users that are using the archival features of pouchdb, maybe for a wiki or delta-pouch will need to know the implications of them doing so whereas the majority of users dont need to fetch outdated revs but are very worried about disk space limits and we should have defaults that make sense for the majority

**Comment by ermouth** [comment]
@daleharvey –1. Autocompaction becomes serious perfomance problem, especially when you use tablets or mobiles. 

@nolanlawson CouchDB has setting `revs_limit` that limits depth of revision tree stored (not the number of revisions saved). If Pouch could limit number of stored doc revs in similar way...

**Comment by nolanlawson** [comment]
How would this impact PouchDB Server? So far, the defaults have all been the same as CouchDB 1.x; this would be a big departure from that. @marten-de-vries may want to weigh in.

I wanted to see what kind of an impact auto-compaction has on storage size. I tested in Chrome and Firefox by measuring the actual disk space of the IDB files (`Library/Application Support/Google/Chrome/Default/IndexedDB` on Chrome 43, `Application Support/Firefox/Profiles/njmr67gw.dev-edition-default/storage/default` on Firefox 40).

I put together a silly app that `post`s 100 documents and randomly adds large-ish amounts of non-attachment data to them, creating 100 revisions. [Gist here](https://gist.github.com/nolanlawson/54db9ee55afdf4e08861). Result:

**Storage size**

| | no compaction | compaction | Details |
| --- | --- | --- | --- |
| Chrome | 180M | 86M  | 84248 bytes vs 11024, so **94%** reduction in size |
| Firefox | 11M | 1.4M | 87308 bytes vs 1388, so **98.4%** reduction in size |

**Speed**

| | no compaction | compaction | Details |
| --- | --- | --- | --- |
| Chrome |  276998.045ms  | 292760.806ms  | no-compaction is **5.3%** faster  |
| Firefox | 517492.18ms | 507749.95ms | auto-compaction is **2%** faster |

I also made [a jsperf](http://jsperf.com/pouchdb-auto-compaction) so you can test the speed yourself. The difference seems negligible in all browsers.

So color me impressed by auto-compaction. Maybe it is a sensible default.

@ermouth Adding `revs_limit` would be a great first patch. :)

**Comment by ermouth** [comment]
@nolanlawson please test with more real data and attaches – and then make decision. We all live in real world, where strings contain data and attaches from, say, built-in cam normally have megabyte sizes.

In these cases – from UI perspective – 100-200ms save time is ok, but even 400-500 ms looks like stall.

**Comment by nolanlawson** [comment]
@ermouth Hm, could you fork my jsperf to demonstrate? That jsperf is pretty good, btw, since it actually destroys the database before running the tests, and ensures that Safari shows the popup before the tests are run as well.

**Comment by ermouth** [comment]
@nolanlawson http://jsperf.com/pdbauto-long 
changed `i<100` to `i<1000` – and got x1.7 difference

**Comment by ermouth** [comment]
Sorry, disregard. Misinterpreted results – bit ill. Results are quiet same.

Can‘t do more thorough test right now, but definitely saw stalls with cloudwall and autocompact.

**Comment by nolanlawson** [comment]
@ermouth Was this before PouchDB 3.2.1? In 3.2.1 there was a huge performance improvement to auto-compaction: https://github.com/pouchdb/pouchdb/issues/3089

**Comment by ermouth** [comment]
@nolanlawson not sure, but think it was before 3.2.1. I‘ll fork cloudwall and re-test how it goes with autocompaction when recover.

**Comment by daleharvey** [comment]
@ermouth main thing to understand it the I am only proposing changing the default, if for performance reasons you really need to keep the current default you can.

But yeh, the storage improvement is not insignificant, similiarly performance improves with storing less. I am hoping we eventually move to a storage format that has not penalty on auto_compaction at all (ie it saves in constant time, the only difference is the more you save the more time it takes)

**Comment by nolanlawson** [comment]
@daleharvey I've toyed with the idea of writing a custom adapter that stores all documents as diffs. I'm also thinking of implementing it over the subset of IndexedDB that's actually supported by all 4 major browsers, so we can finally retire (or pluginify) the WebSQL adapter.

**Comment by ermouth** [comment]
@daleharvey I do understand. If your proposal does not impose any performance penalties, it can be reasonable for limiting environments. But – to notice – persistent storage is rather cheap resource to thrift.

Nevertheless, if you decide to – please, consider adding method returning PouchDB version to let apps know where they are and what PouchDB behaviour they can expect by default.

**Comment by nolanlawson** [comment]
@ermouth This would definitely be a major version release (e.g. 4.0.0) in order to avoid breaking stuff, since we follow semver.

**Comment by daleharvey** [comment]
> Nevertheless, if you decide to – please, consider adding method returning PouchDB 
> version to let apps know where they are and what PouchDB behaviour they can expect by default.

We have this available via `.info()`
```
db.info(console.log.bind(console))
null Object { doc_count: 0, update_seq: 0, idb_attachment_format: "binary", db_name: "mydb", auto_compaction: false }
```

**Comment by ermouth** [comment]
@daleharvey In fact it‘s not only about compaction. There are deprecated events, deprecated destroy and so on. 

Also to get info we need to init DB, that is not always suitable. So `PouchDB.version` as property or method looks more practical than detecting features using indirect ways. Code needed for such kind of detection is always weird and need permanent upgrade.

**Comment by daleharvey** [comment]
We have the version available via `PouchDB.version`

> PouchDB.version
> "3.5.0"

**Comment by daleharvey** [comment]
And as for differing default between pouchdb and couchdb, I would like to generally like to mirror our defaults but I do think couchdb to be used on the server is far less worried about disk space, which is considered a cheap resource whereas inside the browser it is very much not so and people are very much worried about hitting the various limits

**Comment by ermouth** [comment]
> I do think couchdb to be used on the server is far less worried about disk space
Disk space exhaustion is known profile of attack on CouchDB. Unprotected `_local/` requests, no log rotate for version prior to 1.6.1, large attachments – they all can be used to trigger denial of service or even stop server. Since it impacts many users, it‘s much more dangerous, than stopped client.

> inside the browser it is very much not so and people are very much worried
As I could observe end users do not worry at all – they expect everything just work. Nevertheless I can imagine scenario that can exhaust local storage – on Tessel-like devices for example or on mobiles when saving pictures. But I think in these cases app architecture must track the problem.

> PouchDB.version
Oh, I missed the moment when it appeared :( At least it‘s not documented.

I‘m stopping here, it became bit ping-pong, sorry.

**Comment by marten-de-vries** [comment]
For pouchdb-server/express-pouchdb I think we should keep auto_compaction=false since storage space is cheap there, and it's nice to have access to all the revisions there. But that's something we can just pass to the constructor in those projects explicitly, so no problem. We could even expose the option to the user in ``/_config``.

**Comment by daleharvey** [comment]
I will likely fold this into `idb-next` work
