### ISSUE TITLE
Binary or base64 attachments?

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3908]
It just occurred to me that #3804 and #3870 basically have two contradictory strategies for performance. One prefers fetching attachments as inlined base64-encoded strings, whereas the other prefers fetching them directly as binary in separate requests. (Not quiiiite directly, but once #3889 lands, then yes, directly as arraybuffers/blobs from XHR.)

I suppose the argument could be made that, the case of `_all_docs`, we are already fetching many documents in a single request, so the benefit of inlining attachments is high, whereas for `GET`, we are doing one-request-per-document anyway, so we might as well grab the attachments directly.

I admit I didn't do any performance comparison between the two strategies. I have a hunch that directly fetching attachments is better than inlining for both cases, but I have no data. Anyway, we would need to remove the inlining if we wanted to support CSG.

(Obviously the best strategy would be `multipart/mixed`, but I've determined we cannot support that in the browser because CouchDB sends back the data as `gzipped`, so we would lose any benefits by having to unzip stuff in JavaScript.)

@jo Do you have any thoughts on this?

**Comment by jo** [comment]
Because the performance benefit of both strategies mainly depend on the size of the attachments (for many small attachments it might be the best to fetch them inline) I would suggest to do both ;)

Consider a photo app which provides small thumbnails as well as larger images. For the thumbnails it will be better to fetch them all together in one bulk request (if they're rev-1 or in a single doc), while doing binary xhrs for the large images would be definitely more performant.

The problem with this dual approach is, of course, to determine the attachment sizes in advance. For the bulk rev-1 fetch for example we do not know the size before before the response.
A simple configure option alone would not solve the abovementioned example where both small and large size attachments exist in a single database.

I don't have a solution yet but I think replication performance is important enought to go that somewhat difficult route or at least prepare for a hybrid approach.

**Comment by nolanlawson** [comment]
Interesting points. I definitely agree that a hybrid approach would be best. I think, though, that it makes more sense to make this a global option  e.g. `prefer_inlining` for a few reasons:

1. If docs contain mixed large/small attachments, there's really no way to do two strategies for the two groups
2. It makes it easy to support CSG.
3. It's simpler. :) And for the thumbnail case you mention, users can simply have two separate DBs for the larger and smaller images, and use two strategies for each one.

Maybe this can be an option on the http adapter's constructor.

**Comment by nolanlawson** [comment]
Although: a counterpoint is: maybe users who are storing many small thumbnails should just avoid attachments altogether and inline directly. :)

**Comment by nolanlawson** [comment]
Fixed by 8207da7

**Comment by nolanlawson** [comment]
Eh sorry, reopening because we should discuss this more.

**Comment by jo** [comment]
I think point 1. could easily be resolved by `Math.max(sizes)` but I see your point. Simplicity matters.

For your counterpoint: *If* you can. I think don't like the _just don't use attachments_ argument. There might be cases where its better to use attachments. Also, consider the common (?) approach for document versioning via attachments.

Anyway, lets go with the `prefer_inlining` option until we find a better solution.

**Comment by nolanlawson** [comment]
Sounds good; I'll open an issue for that.
