### ISSUE TITLE
PouchDB 404's (without patching) in a Firefox Add-on

### ISSUE THREAD

**Issue by BigBlueHat** [pouchdb/pouchdb#3912]
I'm working on using PouchDB inside a Firefox Add-on where the database should live in the extension "space" (global to all web sites) and the script I'm injecting into the pages ([Annotator](http://annotatorjs.org/) should send it's content to the add-on for storage in that database.

However, IndexedDB is not provided "out of the box" to addons, so you get a 404 by default.

I discovered this blog post that allows you to patch PouchDB to get it to not 404:
http://siphon9.net/loune/2015/02/pouchdb-for-firefox-addon-sdk/

That does (from my current tests) let me get a working PouchDB instance inside the extension.

Is that something that could be provided as a shim? or would it need to be in the core?

Thanks!

**Comment by nolanlawson** [comment]
I think shimming it makes the most sense. Let's create a separate npm module and document it in the FAQs.

**Comment by BigBlueHat** [comment]
@nolanlawson are there good examples of shims for PouchDB? I did the copy/paste job mentioned in that blog post and it worked swimmingly. :swimmer: 

I'd love to have it available in npm as `pouchdb-firefox-addon-shim` (or something less verbose :wink:).

**Comment by nolanlawson** [comment]
@BigBlueHat Hm, it might be tricky to publish on npm due to the overloading of "require" here:

```js
if (typeof require !== 'undefined') {
  indexedDB = require('sdk/indexed-db').indexedDB;
  IDBKeyRange = require('sdk/indexed-db').IDBKeyRange;
  setTimeout = require('sdk/timers').setTimeout;
  clearTimeout = require('sdk/timers').clearTimeout;
  window = { btoa: require('sdk/base64').encode,
             atob: require('sdk/base64').decode,
             escape: require('sdk/querystring').escape };
  XMLHttpRequest = require("sdk/net/xhr").XMLHttpRequest;
}
```

@calvinmetcalf Do you know if there's some kind of trick like `derequire`, but to *re-insert* these require statements into a page?

Else it might make more sense to just put this in the FAQs/common errors.

**Comment by BigBlueHat** [comment]
@nolanlawson so that's not overloading require (afaik)...but it is assuming that require is running within the Firefox Jetpack-based add-on system. I don't think `derequire` would be needed.

I just removed the `if` statement and it worked fine in the browser (for instance).

Additionally, the new Firefox Add-on build system (`jpm` instead of `cfx`) actually uses `npm` packages:
https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Using_third-party_modules_%28jpm%29

So it should be good to go as a shim module.

**Comment by colinskow** [comment]
Why not just have the build script create a file called `pouchdb-firefox-addon.js`. Just concat the shim to the top of the normal release. This can be distributed in the same or a different Bower package.

**Comment by colinskow** [comment]
In fact, the shim could even be a separate file included before PouchDB.
<script src="pouchdb-firefox-addon-shim.js"></script>
<script src="pouchdb.js"></script>

**Comment by anaran** [comment]
@colinskow Yes, I think the concatenation was first suggested in http://siphon9.net/loune/2015/02/pouchdb-for-firefox-addon-sdk/ and works fine for me, in an add-on SDK addon, built with jpm, install in (hold on to your seat) thunderbird.

Loading the shim from a different module file does not work. The add-on SDK [toolkit loader](https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/_loader) follows the commonJS model and does not modify the global environment.

**Comment by anaran** [comment]
@BigBlueHat Have you also tried to sync your local Annotator add-on PouchDB to a couchdb instance? I was not able to find your actual Firefox Add-on code from your link above.

I can login and logout on my self-hosted couchdb instance using the session API.
I am using my home-grown XHR code since I was not able to get pouchdb-authentication to work for that purpose.

I can also create the db in couchdb when it does not exist (via the sync).

But no documents ever get synced or replicated to the empty couchdb from my local PouchDB documents stored via my Firefox add-on main script.

CouchDB logs just confirm I successfully authenticated as the user I expect. Even at couchdb log level debug I don't see any clues where the sync might get stuck.

Any help appreciated, as always. This would obvious be a big step forward, syncing Firefox add-on DB with some couchdb instance.

**Comment by anaran** [comment]
Hah, good news, I was just able to

    remoteDb.post(...)

and

    localDb.sync(remoteDb)...

my first PouchDB data from my Firefox Add-on to my couchdb server in a transfer using an authenticated session.

All I had to do was to extend the pouchdb shim to the following (top-level btoa is also accessed by pouchdb, Blob and URL are needed when syncing to remote couchdb):

```
if (typeof require !== 'undefined') {
    indexedDB = require('sdk/indexed-db').indexedDB;
    IDBKeyRange = require('sdk/indexed-db').IDBKeyRange;
    setTimeout = require('sdk/timers').setTimeout;
    clearTimeout = require('sdk/timers').clearTimeout;
    btoa = require('sdk/base64').encode;
    window = { btoa: require('sdk/base64').encode,
               atob: require('sdk/base64').decode,
               escape: require('sdk/querystring').escape };
    Blob = require('sdk/addon/window').window.Blob;
    URL = require('sdk/addon/window').window.URL;
    XMLHttpRequest = require("sdk/net/xhr").XMLHttpRequest;
}
```

**Comment by nolanlawson** [comment]
It sounds like there are workarounds that involve shimming. Closing this issue.
