### ISSUE TITLE
Docs wtih many large attaches fail to replicate from remote in 3.6.0

### ISSUE THREAD

**Issue by ermouth** [pouchdb/pouchdb#3962]
Docs that have lots of large attaches fail to replicate from remote, since browser limits number of simultaneous connections.
See screenshot here http://jquerymy.com/pouchdb/shot-361-1.png

**Comment by nolanlawson** [comment]
Yeah, this is a dumb mistake on my part due to the simultaneous fetches using `Promise.all` in `http/index.js`. I should limit those to 6 at a time to avoid browser limits.

Alternatively, this would be a good opportunity to introduce the feature to allow inlining (https://github.com/pouchdb/pouchdb/issues/3913), e.g. for people who have documents with many small attachments.

I still don't see how this explains #3961, though, since if a single request fails, then the entire `db.get()` should fail and thus replication should throw an error instead of inserting empty attachments.

**Comment by ermouth** [comment]
It really does not explain #3961 in any way, #3961 root post was induced by my stupid automated test that did not check if doc is present before enumerating attaches from all rows of `.allDocs`request . There were no docs – and surely no attaches ) Thats why I added UPD to disregard.

**Comment by nolanlawson** [comment]
UPD?

**Comment by daleharvey** [comment]
update I think

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/6a2955c8a4036cce24e4475e1e52bfc897fce228
