### ISSUE TITLE
Doc props like .constructor or .watch are lost in 3.2.1–3.6.0

### ISSUE THREAD

**Issue by ermouth** [pouchdb/pouchdb#3968]
Quite artificial example, but issue already took place ~year ago and was marked as fixed, see #2080

Repro: http://jquerymy.com/pouchdb/proploss2.html

Note, that result of the test is incorrect in all browsers, moreover result is different in FF and others.

**Comment by nolanlawson** [comment]
Yeah, the reason we use that jQuery 1.9.0 version of extends is because other libraries that we tried have bugs with Ember due to their manipulation of the global Object prototype (https://github.com/pouchdb/pouchdb/issues/2158). I admit this is a bad bug, though, and needs to be fixed.

**Comment by nolanlawson** [comment]
@calvinmetcalf @daleharvey What is the solution here? Should we hack `pouchdb-extend` to keep these properties in, or should we just replace `pouchdb-extend` with `JSON.parse(JSON.stringify(obj))`? Personally I wouldn't mind the latter, because it would also fix those errors where people are surprised by IndexedDB's handling of Dates and other special types compared to the other adapters.

**Comment by calvinmetcalf** [comment]
JSON.parse(JSON.stringify(obj)) is probably the easiest in all honesty

**Comment by nolanlawson** [comment]
^ I added a failing test, so anybody who would like to fix it is welcome to. :)

**Comment by ermouth** [comment]
JSON.parse(JSON.stringify(obj)) solution is very fast, also this approach solves race issue #3955, but it‘s always a deep clone, so in cases of large docs there can be significant GC-induced stalls.

**Comment by nolanlawson** [comment]
fixed by 870248e7b97a3a1a9c737abad8ebebf9b07ead3f
