### ISSUE TITLE
500/Object/unknown error primarily for Mobile Safari users

### ISSUE THREAD

**Issue by rarkins** [pouchdb/pouchdb#3972]
Many - but it seems not all - iOS Safari devices are producing this error:
```json
{"status":500,"name":"Object","message":"unknown"}
```

I also found a couple of occurrences in other browsers - one for Firefox/Windows and another for Chrome/Android. 

In Safari, it occurs on both iOS7 and iOS8 although most users have the latter. I cannot reproduce it using my own iOS devices so cannot debug it at this stage. 

I don't think that so many users would have private browsing enabled as was apparently the cause of #3581 so I don't think these are the same issue. 

Is it expected that error messages are so vague like this?

Using `angular-pouchdb` 2.1.0 with PouchDB 3.5.0

**Comment by corps** [comment]
I experienced a similar issue for awhile, too, especially with larger databases syncing.

The fix for me was to reduce the batch size.  It seems that the concurrent requests sent during syncing have a small chance of a race condition?  Or don't behave correctly if one or more of the requests happen to timeout?  All I'm certain is that I was able to inconsistently reproduce on mobile safari mostly, but also occasionally on desktop chrome and firefox, so I don't believe it to be an indexeddb or sqlite specific bug.  After reducing my batch size and making fewer concurrent requests, syncing slowed down but was more reliable and the issue went away.  Maybe give that a try?

**Comment by rarkins** [comment]
Actually you may be right. I just found a different "signature" of the same error being reported by Firefox for Windows plus Chrome for Android. I had missed it earlier as only a couple of occurrences compared to hundreds for the safari one.

**Comment by rarkins** [comment]
I have updated the title and description to reflect this. So seems it could be a concurrency or race condition like you suspect. Now I need to figure out if it's caused by the angular wrapper or something we're doing explicitly in our application code.

**Comment by nolanlawson** [comment]
The 500 error is basically the equivalent of PouchDB swallowing the original error and not reporting it in a meaningful way. (Yes, we should be better about reporting the error. :)) It's kind of impossible to diagnose unless you can catch the original error. Do you have a test to reproduce?

**Comment by rarkins** [comment]
Unfortunately it's happening in production and we can't reproduce it in dev *or* with our own iOS or Firefox hitting production. Hits lots of iOS users and occasionally Firefox. We're adding a check for localstorage capability before invoking pouch to rule out private browsing etc. But I really doubt that can explain all of them. 

Also wondering if we can user agent sniff temporarily and turn PouchDB debug up for mobile safari only, assuming we can reliably also capture that.

**Comment by nolanlawson** [comment]
Hm, if it's happening on both, then it's most likely a network error (since FX uses IDB but Safari uses iOS). Maybe it happens due to flaky connections? Maybe you can repro using bad wifi or a captive portal?

Obviously we should also work to provide better errors. If it's happening only in production, then how are your users reporting it to you? If we can figure out the best way to log/surface it, then maybe you can debug that way.

**Comment by nolanlawson** [comment]
Well shoot, now that I look at the code, it seems `"unknown"` should only be thrown for WebSQL/IndexedDB/LevelDB. So your guess is as good as mine.

It may be happening on iOS because the device has run out of storage space. Safari is known for throwing weird errors when storage gets low. If you can use the unminified PouchDB and set a breakpoint where the WebSQL error would occur (corresponding to [this line](https://github.com/pouchdb/pouchdb/blob/5ef48cd7af94302fa074ddc2b8bb736c7151d448/lib/adapters/websql/utils.js#L157)), then that would help.

**Comment by rarkins** [comment]
Users have not reported it actually - it just started showing up in our exception logging service as soon as we rolled out PouchDB. As best as I can tell, affected users would just lose all PouchDB-based "personalisation" on the site, e.g. Ability to create a favourites list. Shouldn't show any user-visible errors. This is no different/worse than if we rolled back the code, so I choose to keep it live. 

We have also now added a hook to our error reporting to  send a custom event to our site *analytics* service too, so I should hopefully be able to start performing a higher level analysis on its occurrence (eg % of mobile safari affected, etc). 

Happy to share vendor names of reporting and analytics services if it helps, but I don't think it adds anything.

**Comment by nolanlawson** [comment]
Yeah, I think what we really need is the source error, which doesn't seem to be getting logged.

**Comment by rarkins** [comment]
I'm surprised to say this seems like it *was* a duplicate of #3581 after all. After adding a check for localstorage (which iOS private browsing forbids), we eliminated all these errors on iOS. Note: we still get some on Firefox, but the title of this issue includes "Mobile Safari" hence I'm closing it.

FYI here is the localstorage check we added to our code prior to PouchDB initialisation:
```
var incognito = false;
/**
 * See https://gist.github.com/paulirish/5558557
 */
try {
  localStorage.setItem('test', 'test');
  localStorage.removeItem('test');
} catch (e) {
  incognito = true;
}
```
