### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#3987]
We have managed to get by with relatively minor issues thus far, but would like to have something explicit

**Comment by nolanlawson** [comment]
We have been low on contributors recently, so maybe having a CoC would help put people at ease. Also we did recently have some kerfuffles (that were resolved very amicably), which is another good reason to have our rules spelled out.

Should we just borrow/steal a CoC from CouchDB? cc @calvinmetcalf @marten-de-vries @nickcolley @janl @nslater

**Comment by marten-de-vries** [comment]
I wouldn't ascribe a lower amount of contributions to this personally (thinking that 'PouchDB works and is complete for 99% of the use cases' is a more likely reason). Still, an explicit CoC doesn't hurt.

As for which one exactly I don't have a strong opinion. I know the CouchDB & Ubuntu ones best, both would work, as would most others we could borrow probably: part of the effect comes from just having such an agreed upon document, regardless of the exact contents, it seems to me.

**Comment by calvinmetcalf** [comment]
anyone have a link to the couchdb one ?

**Comment by kxepal** [comment]
@calvinmetcalf [CouchDB CoC](http://couchdb.apache.org/conduct.html). Is was used as base for [ASF CoC](http://apache.org/foundation/policies/conduct.html).

**Comment by janl** [comment]
+1 on a CoC, and +1 on the CouchDB one, because I’m familiar with it. Any other popular one would also do.

**Comment by daleharvey** [comment]
Given our close relation to Couch, picking up the same CoC as theirs seems like a good idea, it had a lot of thought put into it and came from a similar position and an overlapping community.

I do think the CouchDB CoC is missing a section on the enforcement of the guidelines
 
> If you believe someone is violating this code of conduct, you may reply to them and point 
> out this code of conduct. Such messages may be in public or in private, whatever 
> is most appropriate. 

Should certainly always an option, but I think it should be stated that the maintainers of the project are agreeing to take on the responsibility of actively enforcing the code of conduct and not just waiting for the situation where someone feels victimised having to report it. 

I also think it should be clear what the enforcement looks like, from closing unproductive issues, advising people that they are breaking the code of conduct to temporary or permanent exclusion from participating.

There is also the issue of who is taking on that responsibility, obviously I am happy to be doing that but I can get stuff wrong, it seems like ideally it should be a few people however our most current active participants are not the most diverse group and it feels like we arent the best people to actually be making the decisions over how exclusionary something may possibly be. Maybe I can do it for now with a view to expanding more of the community who would be willing to do so, (at the same time as pushing for a more diverse set of contributors to try and avoid this problem in the future)

**Comment by janl** [comment]
@daleharvey great points! Let me explain the thinking behind what the CouchDB CoC has, as far as I remember:

- the “you” in “you may reply” is targeted at any community member, which includes the active maintainers. We tried to avoid painting active maintainers as an exclusionary group, because everybody is welcome to call for CoC enforcement, even if they are new. Anyone also should feel empowered to raise this against the active maintainers, should they trip up. Hence the slightly vague wording.

- *clarifying what enforcement looks like*: we opted to not spell things out, so it a) it can’t be up for debate and b) we don’t have to list every activity. GitHub Projects have a limited set of activities, at CouchDB we have a few more teams & infrastructure, so spelling it all out is too error prone for us. I do agree however that some phrasing like “including, but not limited to measures X, Y, X” could help here, and we’d accept [a PR against the CouchDB CoC](https://github.com/apache/couchdb-www/blob/asf-site/conduct.html) for parity :)

- *who should feel responsible*: I’m happy to help, as a semi-outsider of PouchDB, not just with an issues but also with reaching out to people who have better sensibilities with these things. — In addition, we could do a bit of hapi-like outreach to increase diversity in the project, so these roles then fill more naturally (without expecting marginalised people to pick up the slack).

**Comment by nslater** [comment]
+1 on adopting CouchDB's CoC

**Comment by daleharvey** [comment]
Ok I have started drafting something up @ https://github.com/pouchdb/pouchdb/pull/3996

The changes from the CouchDB CoC is largely changing project name where applicable, the only big change is the `Reporting Guidelines` space (https://github.com/pouchdb/pouchdb/blob/3987/CODE_OF_CONDUCT.md#reporting-guidelines) where I wanted to make it clear that 1. We will be actively enforcing this, not just waiting for people who feel victimised to speak up and 2. Clarify what can and may happen when the CoC is violated repeatedly because I think it needs to be stated

**Comment by gnarf** [comment]
You might want to look at Django's CoC also, its really well written for covering events and online spaces and IRC, etc.

**Comment by daleharvey** [comment]
Yeh the CouchDB one was very heavily inspired by the Django one, I should probably reformat to keep back in the highlights about the spaces it applies to, currently it doesnt mention events but there is a TODO in there to do so and I figured we would pull in Couch's when that is ready assuming it is agreeable which it is likely to be, Cheers

**Comment by janl** [comment]
@daleharvey LGTM +1

**Comment by nickcolley** [comment]
+1 for a CoC. 

Briefly discussed this with Nolan so happy to see this issue <3.

**Comment by zoepage** [comment]
+1 for a CoC

#3996 looks good to me :)

**Comment by daleharvey** [comment]
Ok happy with the concencus here, merged, thanks all :)

https://github.com/pouchdb/pouchdb/commit/269e236faf302a4065267f2d0f5d17bc67b38c10
