### ISSUE TITLE
Support fallback to in-memory adapter automatically

### ISSUE THREAD

**Issue by rarkins** [pouchdb/pouchdb#4011]
The example of using the in-memory adapter from http://pouchdb.com/adapters.html shows it being explicitly invoked, i.e. you need to know that you need to use it (old browsers, private browsing, etc). Is it an appropriate feature request that one day PouchDB itself supports the concept of falling back to in-memory support if the other options are detected as not available? Or do you think this intelligence/checking/retrying is better written as application-level code, not PouchDB-level?

We'll probably implement it at an application level but wanted to check if you think this is appropriate to push down the stack to PouchDB itself one day.

**Comment by daleharvey** [comment]
At this moment I think there are some complications with having it automatically fall back, especially due to the size of the package, I think for now its best done in the application logic but something to consider in future for pouchdb

**Comment by daleharvey** [comment]
Like I think it would make most sense to automatically fallback to the `http` adapter, if we cant save things offline then it sounds dangerous to default to memory where data may be lost, whereas falling back to http means the same api and data guarantees

**Comment by daleharvey** [comment]
For private browsing we most definitely dont want to fallback since it will be a nightmare to detect, this needs https://bugzilla.mozilla.org/show_bug.cgi?id=781982 fixed in firefox and then private browsing will '"just work"

For older browsers, falling back to localstorage when an application is normally based on indexeddb is going to have entirely different performance characteristics, so even if we were did rewrite a localstorage adapter that was small enough that we were comfortable adding to the build I still think we would want to think twice about it. However the list of devices that dont support indexeddb / websql is getting smaller by the day so I dont think there is going to be a huge amount of motivation to fix this, I think having the application manually deal with falling back to localstorage works for now and once they dont need to support ie 9, then nobody has to deal with it :)
