### ISSUE TITLE
pouchdb without leveldb

### ISSUE THREAD

**Issue by Gozala** [pouchdb/pouchdb#4019]
Managing pouchdb with an npm is quite painful because of the dependency on leveldb. For example travis spends most of it's time on pouch db install.

It would be nice if there were separate packages of pouchdb were available for node and browser so one would not need to carry all the dependencies from the other runtime. You could probably still unite both under general `pouchdb` package.

**Comment by jhs** [comment]
Hi, @Gozala. Is that the leveldown build that takes all that time.

I should hope that PouchDB could install with, say, memdown, for C-I and similar situations. Is that not the case?

**Comment by tohagan** [comment]
I noticed that leveldown in package.json is listed under both "dependencies" and "optionalDependencies".  I also noticed that "levelup" is added to "dependencies" so hopefully you don't really need "leveldown".

Note: "leveldown" depends on gyp that depends on Visual Studio on Windows platforms. Visual Studio is typically not available on end user's computers and usually forbidden on corporate Windows servers. I've lobbied extensively to remove Node -> gyp -> Visual Studio dependency. Removing the gyp dependency for PouchDb would be valued.

**Comment by tohagan** [comment]
The "leveldown" project now has this warning: 

* https://www.npmjs.com/package/leveldown

"It is *strongly* recommended that you use LevelUP in preference to LevelDOWN unless you have measurable performance reasons to do so. LevelUP is optimised for usability and safety. Although we are working to improve the safety of the LevelDOWN interface it is still easy to crash your Node process if you don't do things in just the right way."

**Comment by marten-de-vries** [comment]
Thanks for reporting. I just looked into this.

> I noticed that leveldown in package.json is listed under both "dependencies" and "optionalDependencies". I also noticed that "levelup" is added to "dependencies" so hopefully you don't really need "leveldown".

https://github.com/pouchdb/pouchdb/blob/master/package.json
I only see leveldown under 'optionalDependencies'. Also ``npm install --no-optional pouchdb`` doesn't compile leveldb for me, so that seems to work. Are you sure you are using the latest version?

**Comment by daleharvey** [comment]
Yup only seeing it as an optional dep here - https://github.com/pouchdb/pouchdb/blob/master/package.json#L43

**Comment by tohagan** [comment]
Hmm ... Sorry about that  ... I definately saw it, so I must have been look at an older branch. Sorry to waste your time.

**Comment by marten-de-vries** [comment]
No problem @tohagan, glad that solved the problem. :)

@Gozala is the ``--no-optional `` npm switch good enough for your use case too, or would you still argue to a completely leveldb-less pouchdb package?

**Comment by tohagan** [comment]
I think that --no-optional should be fine but I've not tested it.  In the end I switched to `nano` instead of PouchDb for this server side app. I only needed it to initialise a CouchDb on the server so PouchDb was overkill.

In the future I suspect my Node server will require PouchDb as I think I can speed up the initial client side syncing by creating a zipped SQLite database on the server, download it to the client and then create a client side PouchDb with the `createFromLocation` option.

**Comment by tohagan** [comment]
Weird ... I checked the "blame" and found where leveldb was made optional and the code change looked fine so not sure why I saw this.  Strrrange.

**Comment by daleharvey** [comment]
Ok so looks like this is working as expected, cheers

**Comment by theduke** [comment]
Apparently there was a regression here.

The PouchDB package now again has leveldb dependencies as non-optional!

**Comment by natew** [comment]
Yea I'm getting bitten by this now with an electron app!
