### ISSUE TITLE
Pouchdb not creating database file on windows

### ISSUE THREAD

**Issue by dilignt** [pouchdb/pouchdb#4051]
I'm unable to get pouchdb working on windows 8.1 and I'm wondering what the problem is.  I've managed to compile leveldb correctly so that no errors are returned when running pouchdb, and I executed the following code
```
var PouchDB = require('pouchdb');
var db = new PouchDB('./test.db');

db.post({testing:123}).then(
    function(val) {
        console.log(val); 
    }, function(err) { 
        console.log(err); 
    });

console.log(db);
```
The resulting output is
```
{ __opts: {},
  auto_compaction: undefined,
  prefix: '_pouch_',
  domain: null,
  _events: {},
  _maxListeners: 10,
  taskqueue: { isReady: false, failed: false, queue: [ [Function] ] },
  _adapter: 'leveldb',
  _db_name: './test.db',
  adapter: 'leveldb',
  replicate: { from: [Function], to: [Function], sync: [Function] },
  sync: [Function],
  then: [Function],
  catch: [Function] }
```
Which shows that the db.post.then() function is not called either with a return value or an error.  I notice that the taskqueue.isReady is false - could this have something to do with the problem?  Is there any way I can debug this issue?

I'm trying to build a Pouchdb database file on the server which I can then open from within a cordova mobile app.  Is this the right way to do that?

many thanks in advance

**Comment by nolanlawson** [comment]
On some Windows phones, you have to go into the settings and explicitly enable browser storage in order for IndexedDB to work.

**Comment by darkyen** [comment]
Actually there is a great way documented here https://msdn.microsoft.com/en-us/library/windows/apps/jj553412.aspx

`<meta name="ms-enable-external-database-usage" content="true"/>`

**Comment by nolanlawson** [comment]
Weird, there's nothing on that page about `msIndexedDB`. Also I'm surprised to find that we don't check for any prefixed variables.

I don't really understand what you're saying. So should we check for `msIndexedDB` and use that instead of `indexedDB`? Or is the fix just to add that HTML tag to every page? And is this only for Cordova apps or for live web pages?

If you could consolidate your learnings into a pull request (even if it's just an addition to our [common errors](http://pouchdb.com/errors.html) page, that would be super helpful. Nobody on the team has spent much time with Windows Phone or even has access to a device, so we're relying on the community for help here. (PouchDB is not a commercially-funded project.)

**Comment by darkyen** [comment]
@nolanlawson  Sorry about my english,
I had a hard time working with windows because there are differences between IE Desktop, WWAHost, IEMobile, WWAHostMobile which aren't properly documented and the whole documentation is extremely fragmented with windows 8, 8.1, 8.1 - Phone and now msdn moving to 10 apis. With 10 there are almost the same APIs everywhere since the app runtime "seems" to be the same (but further testing is required).
 
I found about the msIndxededDB here https://msdn.microsoft.com/en-us/library/windows/apps/hh781225.aspx so in my code i just shim it as 
`window.indexedDB = window.IndexedDB || window.msIndexedDB` further more while testing on windows phone myself I wasn't able to get either the IndexedDB or the msIndexedDB which let me to search more just to find that 8.1 store apps on phone do not have indexeddb which was also mentioned here. ( http://blogs.windows.com/buildingapps/2014/07/02/writing-a-sqlite-wrapper-component-for-universal-windows-apps/ ) so i ended up using SQlite on all platforms and IndexedDB only in google chrome. Pouch made the transition almost transparent.


@nolanlawson sure, I will consolidate my findings in common errors.

**Comment by dilignt** [comment]
I'm not using Windows phones, I'm using Pouchdb on my Windows 8.1 laptop,
running node.js on the command line.  Everything seems to work, but the
database file is not created and the db.post call never returns.  Do you
know why this doesn't work on my laptop?

**Comment by nolanlawson** [comment]
@dilignt Probably leveldown did not build correctly; I'm guessing. It has build problems on Windows.

@darkyen That's really unfortunate about 8.1 store apps. It makes no sense to me why they would disable IndexedDB, since they never supported WebSQL. The SQLite Plugin is okay, but it is rather hacky when the web platform has had a perfectly viable alternative for the past 5 years.

Can you provide a link explaining the 8.1/no indexedDB thing? I want to complain to some Microsoft devs.

Also, can you tell me which versions of Windows Phone use `window.IndexedDB` or `window.msIndexedDB`? We can fix that directly in our code, but I want to know which versions we are supporting via that mechanism.

**Comment by nolanlawson** [comment]
n/m, I found the 8.1 link: http://blogs.windows.com/buildingapps/2014/07/02/writing-a-sqlite-wrapper-component-for-universal-windows-apps/

**Comment by dilignt** [comment]
@nolanlawson Thanks for the reply.  I don't think it is a build problem with leveldown because I can execute the following code successfully
```
var leveldown = require('leveldown');
var db = leveldown('test.db');

db.open(function() {
    db.put('test', 'testing123', function() {
        console.log('done');
    });
});
```
This creates a directory test.db and successfully populates it with database files.

Is there anything else you can think of that I can do to debug this problem?  It's becoming a bit of a show-stopper for me - I need to make progress with it.

**Comment by daleharvey** [comment]
@dilignt try

```

new PouchDB('name', function (err, db) {
  if (err) {
    return console.error('failed to create database', err); 
  }
  db.post(stuff).then(....
});
```

And run with `DEBUG=* ./myscript`

**Comment by daleharvey** [comment]
It must be failing somewhere in https://github.com/pouchdb/pouchdb/blob/master/lib/adapters/leveldb/index.js#L115,L190, It may possible be leveldown integration or possible sublevel?

**Comment by dilignt** [comment]
@daleharvey thanks - I've got a bit further now.  Running your `DEBUG=*` I get
```
failed to create database [LevelUPError: Installed version of LevelDOWN (1.3.0) does not match required version (~0.10.0)]
```
I tried to install version 0.10.0 of leveldown but I get a whole load of compile errors
```
....
c) [C:\Users\Mike\AppData\Roaming\npm\node_modules\leveldown\build\leveldown.vcxproj]
          C:\Users\Mike\.node-gyp\0.12.7\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
C:\Users\Mike\AppData\Roaming\npm\node_modules\leveldown\node_modules\nan\nan.h(718): error C3861: 'NewSymbol': identifier not found (..\src\leveldown.cc) [C:\Users
\Mike\AppData\Roaming\npm\node_modules\leveldown\build\leveldown.vcxproj]
C:\Users\Mike\AppData\Roaming\npm\node_modules\leveldown\node_modules\nan\nan.h(725): error C2039: 'NewSymbol' : is not a member of 'v8::String' (..\src\leveldown.c
c) [C:\Users\Mike\AppData\Roaming\npm\node_modules\leveldown\build\leveldown.vcxproj]
          C:\Users\Mike\.node-gyp\0.12.7\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
C:\Users\Mike\AppData\Roaming\npm\node_modules\leveldown\node_modules\nan\nan.h(725): error C2228: left of '.As' must have class/struct/union (..\src\leveldown.cc)
[C:\Users\Mike\AppData\Roaming\npm\node_modules\leveldown\build\leveldown.vcxproj]
C:\Users\Mike\AppData\Roaming\npm\node_modules\leveldown\node_modules\nan\nan.h(725): error C2059: syntax error : ')' (..\src\leveldown.cc) [C:\Users\Mike\AppData\R
oaming\npm\node_modules\leveldown\build\leveldown.vcxproj]
C:\Users\Mike\AppData\Roaming\npm\node_modules\leveldown\node_modules\nan\nan.h(647): error C2660: 'v8::Object::New' : function does not take 0 arguments (..\src\le
veldown_async.cc) [C:\Users\Mike\AppData\Roaming\npm\node_modules\leveldown\build\leveldown.vcxproj]
..\src\iterator_async.cc(42): error C2039: 'New' : is not a member of 'v8::String' [C:\Users\Mike\AppData\Roaming\npm\node_modules\leveldown\build\leveldown.vcxproj
]
          C:\Users\Mike\.node-gyp\0.12.7\deps\v8\include\v8.h(1599) : see declaration of 'v8::String'
C:\Users\Mike\AppData\Roaming\npm\node_modules\leveldown\node_modules\nan\nan.h(747): error C2039: 'New' : is not a member of 'v8::String' (..\src\leveldown.cc) [C:
\Users\Mike\AppData\Roaming\npm\node_modules\leveldown\build\leveldown.vcxproj]
...
```
It looks like leveldown 0.10.0 doesn't like my nodejs version?   Any other suggestions?

**Comment by dilignt** [comment]
@daleharvey @nolanlawson So I must have somehow wrongly installed the pouchdb dependencies separately after earlier build failures, but I've now completely reinstalled pouchdb and it has now successfully built the dependencies and it is now working.

Thanks for your help :)

**Comment by daleharvey** [comment]
Oh sweet, thats good to hear, no problem

**Comment by nolanlawson** [comment]
I'm going to open a new issue for @darkyen 's problem, since this issue has been closed for awhile now.
