### ISSUE TITLE
Nolan's summer tasklist for PouchDB

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4054]
Coming back to PouchDB after my vacation, trying to figure out important stuff to work on. Feel free to vote or add your favorite issue, and I'll try to dedicate my weekends/evenings to it. :wink: 

* [ ] Update leveldown to 1.x, write migration to fix breaking changes
* [ ] Finish pouchdb-find, or at least add `$in` and `$elemMatch` which seem in demand
* [ ] Integrate pouchdb-find into relational-pouch/ember-pouch so people can have Ember queries
* [x] Profile express-pouchdb and figure out why it's so much slower than express-pouchdb-router
* [ ] Native secondary queries, sadly will probably not get to this anytime soon, and it may make more sense to just make mapreduce/pouchdb-find more stable

**Comment by nickcolley** [comment]
Maybe we could try and get pouchdb-find into the main site in the guide (or somewhere else)?

**Comment by gut4** [comment]
I think we really need new in-memory adapter. As [lokiJS](https://github.com/techfort/LokiJS) becomes better alternative.

**Comment by daleharvey** [comment]
+1000 on upgrading leveldown, it really worries me being stuck on old incompatible versions, although I do wish it did the migration for us

pouchdb-express-router is probably faster since it does vastly less things, the actual routing code is virtually identical

For secondary indexes, I think we have different ideas for how to implement them, will follow up in the relevant thread, but yeh that is something I really want to work on soon as well

As for my plan, I am mostly ignoring what I want and will be triaging all the existing issues and trying to fix them one at a time, hopefully closing them out faster than they come in and getting the number down a little, aside from that I want to work on secondary indexes and improving replication / streaming

**Comment by mnewmedia** [comment]
+1000 on upgrading leveldown also - i almost can handle every query by id so no need for pouchdb-find ;)

**Comment by nolanlawson** [comment]
Thanks for the feedback. More stuff I might put on my plate:

* [ ] - code coverage improvements. this is just good in general and I've been meaning to do it for awhile
* [ ] - React Native compatibility. so many people have been begging for this, although sadly it will probably mostly involve debugging React Native itself

**Comment by wishabhilash** [comment]
How about supporting RequireJS finally??? :D

**Comment by daleharvey** [comment]
@wishabhilash Would love to get more input for that @ https://github.com/pouchdb/pouchdb/issues/2891 or possibly even a patch, it sounds like its probably something simple however I dont think there are many pouchdb + requirejs users right now

I will close this out since the end of summer is in 2 hours !  http://days.to/summer/2015
