### ISSUE TITLE
Feature: Replication progress

### ISSUE THREAD

**Issue by hrishiballal** [pouchdb/pouchdb#4089]
It would be nice to have the ability to see into the sync / replication process and provide a % complete type information to the user. Currently there is no way to determine how much data has been synced. Perhaps this is by design in Couch DB (I am not a expert on CouchDB)

**Comment by nolanlawson** [comment]
I've been meaning to write a plugin to do this, but haven't had the time. You can definitely do it, using some combination of `update_seq` and/or `doc_count`.

**Comment by tohagan** [comment]
+1

**Comment by kxepal** [comment]
@nolanlawson to determine progress you need to use source update_seq and committed_update_seq from replication checkpoint. At least for CouchDB. For PouchDB you have to introduce them for checkpoints.

Using document counter is not good idea since replication could be filtered and you never know if all documents were replicated or not without additional O(n) check.

**Comment by nolanlawson** [comment]
`committed_update_seq ` is news to me. Is there a good description somewhere of how it works, so we can implement it? The docs just say "The number of committed update."

**Comment by kxepal** [comment]
@nolanlawson There is nothing much to document about: it's a update_seq recorded at the moment of checkpoint update.

**Comment by tohagan** [comment]
The [couchdb-replicator-status](https://github.com/nodejitsu/couchdb-replicator-status) app reports the status of all replication tasks in a CouchDb server.  [status.js line 138](https://github.com/nodejitsu/couchdb-replicator-status/blob/master/lib/status.js#L138) appears to compute a progress percentage that may be relevant for PouchDb.

**Comment by willholley** [comment]
I guess this only works for databases where update_seq is a monotonically increasing integer (i.e. not Cloudant / CouchDB 2.0)...

**Comment by kxepal** [comment]
@willholley Cloudant/CouchDB 2.0 still have monotonically increasing seq. It's not a number, but a number + hash. And while you have the number, you may calculate, a bit approximately, but still the progress.

**Comment by willholley** [comment]
@kxepal in Cloudant, the integer component of the sequence number there for compatibility with the CouchDB replicator and we advise people not to interpret it. I assume the same will be true in CouchDB 2.0? There is a "changes_pending" field in the active_task associated with a replication which might help, though.

**Comment by kxepal** [comment]
@willholley CouchDB replicator is update_seq format agnostic long ago - it injects own incremental integer to order received update_seqs, so compatibility is not a problem. But you're right: changes_pending field looks like as a good source of this information and it works correctly with both Apache CouchDB and Cloudant sources.

**Comment by mudcube** [comment]
`update_seqs` and `doc_count ` gives an idea of how many docs are remaining, but in the scenario of one 500kb document (or attachment) and another 50kb one the variables do not provide specific information on actual progress. What do you think about PouchDB tying into the xhr.onprogress / xhr.upload.onprogress listeners, and exposing some of that data to functions in the Api?

For an Api, what about having an EventEmitter?

```js
db.put(doc).on('progress', function(progress) { // float 0-1

}).then(function(result) {

}).catch(function(err) {

});
```

Ditto for:  db.get(), db.putAttachment(), db.getAttachment(), db.sync(), and db.replicate()

**Comment by nolanlawson** [comment]
I'm going to close this, since it actually is possible to do in a plugin.

@mudcube It's not actually necessary to have onprogress listeners on XHR; PouchDB uses small enough requests that the current event emitters are more than enough to implement this.

The one piece of the puzzle that I think everyone is missing in understanding this is `require('pouchdb/extras/checkpointer')`, which can tell you what the `_local` document is called that contains the current state of replication of a given database relative to other databases. It's a little arcane, but if you look at [checkpointer.js](https://github.com/pouchdb/pouchdb/blob/c22bc9d4e4e8c92ac021f027adbc518c9e263aaa/lib/replicate/checkpointer.js) you can get an idea of how this works.

**Comment by mudcube** [comment]
@nolanlawson When you mention the requests are small, does that include attachments? That would be awesome if they were sliced into chunks! 

Unfortunately, I'm noticing large XHR requests. For example posting 5 attachments of 2mb a piece using db.put() results in a single 10MB XHR request. Following the code in PouchDB, all the attachments within a single db.put() command are being combined into a single Blob (as per createMultipart).

A side note, I'm noticing the attachments are being converted from Blob -> Binary String (preprocessAttachments) -> Blob (createMultipart).  I'm wondering whether FormData() could be used to get around converting to Binary Strings?

**Comment by nolanlawson** [comment]
@mudcube Yep, currently attachments are all sent as one blob. CouchDB doesn't have a way I'm aware of to send up attachments partially, so my recommendation is usually to break up attachments yourself if you're worried about exceeding the available memory.

I'm not really familiar with FormData, but yeah, if we could avoid stringifying the blobs that would be awesome. :) Probably depends on what formats CouchDB supports; I know it supports `multipart/related` but not sure about `multipart/form-data` (reading [this](https://developer.mozilla.org/en-US/docs/Web/API/FormData)).

**Comment by mudcube** [comment]
@nolanlawson Sorry to continue beating this issue into the ground, but it's very important to me to have binary supported nicely within PouchDB. I am also willing to make these changes, but do not want to put in the effort unless the changes have the chance of being merged in to the codebase. Let me try to make the case one last time! :)

Say you have 10k documents—9,999 of these documents are 1k a piece, but one document is 100MB due to having large attachments. There is no way currently outside of PouchDB to get accurate progress reporting on replication. 9,999 documents could be uploaded very quickly, and using the update_seq method my code would assume we are 99% done, but in actuality, we are actually 1% of the way done! Considering this, do you think this feature is something that you'd be interested in integrating into PouchDB? 

On a side note, I investigated the issue of FormData further. It turns out CouchDB does accept multipart/form-data (for the sole purpose of allowing Futon/Fauxton to upload attachments) but CouchDB does not support accepting a POST cross origin. So stringifying blobs continues to be the best way.

**Comment by nolanlawson** [comment]
Hmm, it's possible to implement something like what you describe, but it would probably involve measuring the attachments before you download them, using the metadata from the document itself. It's doable, but it only has value for people with documents of wildly varying sizes and with attachments (which is not everybody).

Have you considered writing a custom replicator? I actually did this myself for the [pouchdb-full-sync](https://github.com/nolanlawson/pouchdb-full-sync) plugin - I just copy-pasted the code from `src/replicate` and changed the way it worked. You could do the same thing to inject whatever progress indicator code you want. That way, you wouldn't need to worry about whether or not it'd be merged it into PouchDB core. :) (Not saying it's a bad idea, just that in a codebase as large as PouchDB's, everybody wants everything, so the plugin system is designed to keep the core codebase from growing to 100MB :smiley:.)

**Comment by mudcube** [comment]
Ahh, that's a great point, I'll take that route. Thanks for the example and explanation :+1:
