### ISSUE TITLE
genReplicationId fails if the root / is html

### ISSUE THREAD

**Issue by olafura** [pouchdb/pouchdb#4094]
PouchDB starts trying again and again to get the uuid from the root, and since the ajax code tries to parse it as JSON it fails,

http adaptors api.id is the problem it needs a try catch to use genDBurl if it fails.

chttp also doesn't seem to have a uuid in the json but that can probably be added.

I can provide a patch for this if you want.

**Comment by daleharvey** [comment]
A patch for this would definitely be welcome, thanks, I think the first thing that would need to be fixed is a try / catch around the JSON parse in ajax.js, we have had an issue open for a while on that (https://github.com/pouchdb/pouchdb/issues/2670)

The http api.id function could then ignore any errors from the callback and use the uuid if available, if not just the host

**Comment by kxepal** [comment]
Why PouchDB ever tries to get remote UUID?

**Comment by nolanlawson** [comment]
@kxepal Seems it was ported from Erlang (see [these lines](https://github.com/pouchdb/pouchdb/blob/324c087b77c8dd2b06b7ccc942b370d46cc7a0db/lib/replicate/checkpointer.js#L187-L234)). But I'm unfamiliar with this part of the codebase; @daleharvey?

**Comment by daleharvey** [comment]
So I cant tell if the couchdb implementation was changed significantly or this was just a mistake, however I am going to guess it was written that way to prevent failure in the case of the remote database hostname switching itself when we only stored the checkpoint on one node. 

It fairly certainly isnt needed now, but changing it isnt untrivial, need to make sure peoples existing checkpoints remain stable so a patch to just fallback correctly would be fine, then another to take the remote uuid fetch out, looks fairly certain that isnt what the current couch implementation looks like - https://github.com/apache/couchdb-couch-replicator/blob/master/src/couch_replicator_utils.erl#L86


https://github.com/apache/couchdb-couch-replicator/blob/master/src/couch_replicator_utils.erl#L86

**Comment by kxepal** [comment]
@nolanlawson referenced part is about checkpoint docs comparison. They don't have any UUID nor require additional requests to do.

@daleharvey CouchDB implementation is about that replicator uses local UUID for replication ID generation: not source nor target ones (imagine server A runs remote-remote replication). So, for PouchDB that would be all the same: generate own UUID at once and store it in the db or somewhere else.

**Comment by olafura** [comment]
@kxepal It will be interesting reading through how CouchDB does this.

I'm wondering if my patch is good enough for now.

@daleharvey We are getting an error through to id, but I'm wondering if there is going to be too many corner cases trying to get to the uuid. Couchapps are a popular way of using PouchDB and they are the ones that are breaking. And with us we can't even use the ip because it's behind an reverse proxy :)

**Comment by kxepal** [comment]
@olafura It's simple. Let's  see on replication id generation [functions](https://github.com/apache/couchdb-couch-replicator/blob/master/src/couch_replicator_utils.erl#L86-L113).

First there was version 1 which used hash based on `[Hostname, Source, Target]` - where Hostname is literally hostname of the computer where CouchDB that serves replication is running. It had a flaw, since on the same host you may have multiple CouchDBs served on different ports - all of them for the same Source and Target falls into collision state with each other.

So, then replication version 2 was created that accounted port on which CouchDB is served in hash: `[Hostname, Port, Source, Target]`.  But it had a flaw: it requires replicator to act as a server as well, not a client to generate the ID - CouchDB replicator had to ask mochiweb server on which port is serves. That's not good since replicator is basically CouchDB client, not a some server instance. Second, same instance may be accessible on different ports, even multiple ones or just migrate from one to another. This eventually invalidates all the checkpoints.

So, then replication version 3 was created. It uses server UUID thing which is generated on the very first server start. UUIDs are unique (if you have two identical UUIDs generated on different hosts - ask for the prize) and precisely identifies everyone, including replicator peer. If UUID changed, much likely replicator is different and not related to previous one.

Ideally, there should be used ReplicatorUUI, SourceUUID and TargetUUID, but it's not possible by now due to compatibility reasons.

So, returning to your #4114 patch - it seems you just use remote peer full URL as an ID which will easily cause collisions with other PouchDB instances that will replicate with the same peer by the same URL.

**Comment by nolanlawson** [comment]
fixed by 9c03e0f212b3a23e4d72962be2545382caaa3090
