### ISSUE TITLE
API page takes a long time to load

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4117]
This doesn't seem to be an appcache issue, because it happens every time you load http://pouchdb.com/api.html

It seems there's a lot of synchronous JavaScript that's running, because this page can get quite slow for the initial load. On a ~2008 era Linux-running Toshiba laptop I'm playing around with, it takes up to 15 seconds to load. Any way to speed this up?

**Comment by nickcolley** [comment]
Shouldn't be taking 15seconds that's awful.

The page loads and then promise and callback examples get merged (incase you don't have javascript).

![image](https://cloud.githubusercontent.com/assets/2445413/9058591/424bf070-3a9a-11e5-85a0-211c8a6b4542.png)

I'll take a look at this, looks like we should batch the updates rather than doing them one at a time.

**Comment by daleharvey** [comment]
clientHeight is going to force a reflow on every access, if this is happening predender then its probably what is being costly. Its weird that it is blocking the render since we have everything in the footer, but yeh its very noticeable for me but hopefully shouldnt be too hard to fix

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/253609994e99911d4be6f3fa8971826335de1c0a

I think it can likely be faster, but this is a huge improvement
