### ISSUE TITLE
Difference in handling dates in WebSQL and IDB

### ISSUE THREAD

**Issue by redpandatronicsuk** [pouchdb/pouchdb#4126]
When persisting an object as: `db.put({_id: 'foo', bar: new Date()})` and then retrieving it, e.g. `db.get('foo').then(function(doc) { console.log(typeof doc.mydate) } )`, with WebSQL, the above code would print 'string' and with IDB it would print 'object'.

**Comment by daleharvey** [comment]
Yeh its been an open question for quite a while on PouchDB, CouchDB will also convert dates to strings whereas indexeddb will maintain the types. We could convert all dates to strings, but if we have the chance to give back user the same data they give us it seems wrong to do that, although it would be far more consistent across adapters

**Comment by nolanlawson** [comment]
I did document this in the common errors, but maybe it needs higher discoverability: http://pouchdb.com/errors.html#could_not_be_cloned

A lot of people have been bitten by this, but I've been hesitant to write a fix for IndexedDB because it would basically require doing `JSON.parse(JSON.stringify(doc))` on all documents, which would reduce performance of the IndexedDB adapter.

**Comment by daleharvey** [comment]
So yeh, I am also fairly hesitant about converting users data, it has a performance impact and also feels somewhat wrong, I can see situations where people would prefer to use what they want. we fallback well and users can ensure themselves that they use json data to be consistent. 

Opened a PR to make this a bit more explicit / visible - https://github.com/pouchdb/pouchdb/pull/4143

**Comment by nolanlawson** [comment]
documented by 382d71b857536971ef177420f99b8b6febb91d3f
