### ISSUE TITLE
leveldown not available

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#4131]
Seen an increasing number of intermittent test failures with this, @gr2m reported this on twitter as an issue with node_modules being cached incorrectly across architectures

**Comment by daleharvey** [comment]
https://travis-ci.org/pouchdb/pouchdb/builds/74392759 3/50 runs failed, leveldown fails to install and since its an optional dependency it carries on

**Comment by daleharvey** [comment]
Filed - https://github.com/Level/leveldown/issues/211

**Comment by gr2m** [comment]
@daleharvey I think what makes it hard is that PouchDB is silencing the error if `leveldown` cannot be loaded here: https://github.com/pouchdb/pouchdb/blob/master/lib/adapters/leveldb/index.js#L11-L13

Maybe we can log the error, unless it's a simple "file does not exist" thing? I can't recall it exactly, but I remember hacking this file and logging the message, and it helped me understand that leveldown was installed, but couldn't be loaded due to wrong binary bindings

**Comment by daleharvey** [comment]
Some comments on the related bug, so leveldown was straight broken in iojs for a while, it looks fixed however it requires g++ 4.8 which isnt available by default in travis. We can enable 4.8 in travis and all should be good again.

@gr2m Yeh havent been able to get to the point where install passes but leveldown isnt usable, if theres something we can do to provide a better error here would be good, although I believe the try / catch is on purpose for users of non leveldown backends

**Comment by gr2m** [comment]
> I believe the try / catch is on purpose for users of non leveldown backends

Yeah I think so, too. But maybe we could add a debug log output?

**Comment by doruchiulan** [comment]
Hi guys, sorry to disturb your discussion with my problem:

I am trying to use PouchDB in a PhoneGap project with a JxCore(Node.js) backend. I am able to run the project in the desktop but PouchDB does not start on my iOS emulator.

I think it is related to this issue. I might have a wrong configuration of my project because I combine a bunch of technologies. But here is the log I got from GapDebug:

```
LevelPouch@/Volumes/Home/Users/doruchiulan/Library/Developer/CoreSimulator/Devices/219E98C8-1EF8-4AA3-9E3F-CFDAF82725B9/data/Containers/Bundle/Application/C094682A-8AEE-4837-9D37-D95CB0F6B4AB/PAJC.app/www/jxcore/node_modules/pouchdb/lib/adapters/leveldb/index.js:128:21
PouchDB/promise<@/Volumes/Home/Users/doruchiulan/Library/Developer/CoreSimulator/Devices/219E98C8-1EF8-4AA3-9E3F-CFDAF82725B9/data/Containers/Bundle/Application/C094682A-8AEE-4837-9D37-D95CB0F6B4AB/PAJC.app/www/jxcore/node_modules/pouchdb/lib/constructor.js:148:5
tryToUnwrap@/Volumes/Home/Users/doruchiulan/Library/Developer/CoreSimulator/Devices/219E98C8-1EF8-4AA3-9E3F-CFDAF82725B9/data/Containers/Bundle/Application/C094682A-8AEE-4837-9D37-D95CB0F6B4AB/PAJC.app/www/jxcore/node_modules/pouchdb/node_modules/lie/lib/resolveThenable.js:24:5
tryCatch@/Volumes/Home/Users/doruchiulan/Library/Developer/CoreSimulator/Devices/219E98C8-1EF8-4AA3-9E3F-CFDAF82725B9/data/Containers/Bundle/Application/C094682A-8AEE-4837-9D37-D95CB0F6B4AB/PAJC.app/www/jxcore/node_modules/pouchdb/node_modules/lie/lib/tryCatch.js:8:17
safelyResolveThenable@/Volumes/Home/Users/doruchiulan/Library/Developer/CoreSimulator/Devices/219E98C8-1EF8-4AA3-9E3F-CFDAF82725B9/data/Containers/Bundle/Application/C094682A-8AEE-4837-9D37-D95CB0F6B4AB/PAJC.app/www/jxcore/node_modules/pouchdb/node_modules/lie/lib/resolveThenable.js:27:16
Promise@/Volumes/Home/Users/doruchiulan/Library/Developer/CoreSimulator/Devices/219E98C8-1EF8-4AA3-9E3F-CFDAF82725B9/data/Containers/Bundle/Application/C094682A-8AEE-4837-9D37-D95CB0F6B4AB/PAJC.app/www/jxcore/node_modules/pouchdb/node_modules/lie/lib/promise.js:25:5
PouchDB@/Volumes/Home/Users/doruchiulan/Library/Developer/CoreSimulator/Devices/219E98C8-1EF8-4AA3-9E3F-CFDAF82725B9/data/Containers/Bundle/Application/C094682A-8AEE-4837-9D37-D95CB0F6B4AB/PAJC.app/www/jxcore/node_modules/pouchdb/lib/constructor.js:77:17
@/Volumes/Home/Users/doruchiulan/Library/Developer/CoreSimulator/Devices/219E98C8-1EF8-4AA3-9E3F-CFDAF82725B9/data/Containers/Bundle/Application/C094682A-8AEE-4837-9D37-D95CB0F6B4AB/PAJC.app/www/jxcore/models/User.js:5:10
Module.prototype._compile@module.js:520:10
Module._extensions[".js"]@module.js:550:1
Module.prototype.load@module.js:347:7
Module._load@module.js:314:5
Module.prototype.require@module.js:379:10
require@module.js:397:12
@/Volumes/Home/Users/doruchiulan/Library/Developer/CoreSimulator/Devices/219E98C8-1EF8-4AA3-9E3F-CFDAF82725B9/data/Containers/Bundle/Application/C094682A-8AEE-4837-9D37-D95CB0F6B4AB/PAJC.app/www/jxcore/routes/users.js:4:12
Module.prototype._compile@module.js:520:10
Module._extensions[".js"]@module.js:550:1
Module.prototype.load@module.js:347:7
Module._load@module.js:314:5
Module.prototype.require@module.js:379:10
require@module.js:397:12
@/Volumes/Home/Users/doruchiulan/Library/Developer/CoreSimulator/Devices/219E98C8-1EF8-4AA3-9E3F-CFDAF82725B9/data/Containers/Bundle/Application/C094682A-8AEE-4837-9D37-D95CB0F6B4AB/PAJC.app/www/jxcore/app.js:4:13
Module.prototype._compile@module.js:520:10
Module._extensions[".js"]@module.js:550:1
Module.prototype.load@module.js:347:7
Module._load@module.js:314:5
Module.prototype.require@module.js:379:10
require@module.js:397:12
internal_methods.loadMainFile@main.js:214:5
JXMobile.executeJSON@main.js:233:7
@eval:1:1
```

What I do to init PouchDB:

```
var PouchDB = require('pouchdb');
var model = require('modella');
var pouchAdapter = require('modella-pouchdb');
PouchDB.debug.enable('*');
var db = new PouchDB('suitDB'); // , {db: require('leveldown-mobile')}
```

Can you give me a hint where to head on. I am pretty stuck and I don't know what exactly I am doing wrong because I am at start with node + javascript and my head is pretty messy at the moment.

Thanks!

**Comment by nolanlawson** [comment]
I know that the Thali project managed to get leveldown to compile for JxCore, but I'm not 100% sure how they did it. You might want to [check out their project](https://github.com/thaliproject/Thali_CordovaPlugin) for inspiration.

**Comment by nolanlawson** [comment]
Here's something I found: maybe you can use [leveldown-mobile](https://github.com/Level/leveldown-mobile) instead of the default leveldown? This is one of the reasons we made leveldown an optional dependency; you can use other *down adapters as described here: http://pouchdb.com/adapters.html#pouchdb_in_node_js

**Comment by doruchiulan** [comment]
Hi, thanks for your help!

I also found leveldown-mobile but I dont know if I install it correctly.

Should I install them in PouchDB's node_modules or it doesnt matter ? Also I have to to something else other than installing the package and change the PouchDB constructor to use another adapter ?

**Comment by marten-de-vries** [comment]
You should be able to just follow the steps under In-memory in http://pouchdb.com/adapters.html#pouchdb_in_node_js , replacing ``memdown`` with the module you want to use (``leveldown-mobile``) everywhere.

So yes, no need to put the module in PouchDB's ``node_modules``. (That won't even work because your code wouldn't be able to access it there).  And apart from the ``db`` option in the constructor, no other changes should be necessary. And even that can be abstracted away through [PouchDB.defaults()](http://pouchdb.com/api.html#defaults).

**Comment by doruchiulan** [comment]
I've followed the instructions, now I get this error : 

CustomError: undefined
   at @/Users/sam/Library/Developer/CoreSimulator/Devices/F084B9B7-33A1-4668-8665-25E9FA66172B/data/Containers/Bundle/Application/752E695E-9EE6-47C3-8749-F1743E650C7F/Hello World.app/www/jxcore/node_modules/pouchdb/node_modules/levelup/node_modules/errno/custom.js:22:25
   at Module.prototype._compile@module.js:520:10
   at Module._extensions[".js"]@module.js:550:1
   at Module.prototype.load@module.js:347:7
   at Module._load@module.js:314:5
   at Module.prototype.require@module.js:379:10
   at require@module.js:397:12
   at @/Users/sam/Library/Developer/CoreSimulator/Devices/F084B9B7-33A1-4668-8665-25E9FA66172B/data/Containers/Bundle/Application/752E695E-9EE6-47C3-8749-F1743E650C7F/Hello World.app/www/jxcore/node_modules/pouchdb/node_modules/levelup/node_modules/errno/errno.js:312:25
   at Module.prototype._compile@module.js:520:10

**Comment by daleharvey** [comment]
So we need to upgrade leveldown to be supported in master iojs, once that is done we should be all good by adding g++4.8, so this is waiting on https://github.com/pouchdb/pouchdb/pull/4236 to get merged

**Comment by daleharvey** [comment]
Actually this is straight up fixed by https://github.com/pouchdb/pouchdb/pull/4236, so closing as a dupe

**Comment by danse** [comment]
Until the current master will be released, you can [enabled g++ in Travis](https://github.com/danse/sense-dispatch/commit/1f18e6aec06b6ff5b35b1f8c9cdbacef2bc50a16) as a workaround if your tests are failing

**Comment by daleharvey** [comment]
Yup we did https://github.com/pouchdb/pouchdb/commit/f046750b0b9189c65a0620c2ee98b475b7e58285 which looks mostly the same
