### ISSUE TITLE
getting eventEmitter memory leak when updating from 3.6.0 to 4.0.0

### ISSUE THREAD

**Issue by barbalex** [pouchdb/pouchdb#4141]
this is the error message:

    (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
      EventEmitter.addListener @ events.js:142
      EventEmitter.once @ events.js:174
      prepareForDestruction @ constructor.js:44
      (anonymous function) @ constructor.js:156
      tryCode @ utils.js:14
      (anonymous function) @ utils.js:34
      (anonymous function) @ index.js:803
      Item.run @ browser.js:62
      drainQueue @ browser.js:33

here is my app.js containing the code that uses pouchdb on startup: https://github.com/barbalex/ae/blob/master/src/app.js

**Comment by nolanlawson** [comment]
Yes, we are adding slightly more listeners to the `PouchDB` constructor in 4.0.0 than we used to in 3.6.0, in order to properly handle `'destroy'` events. If you are creating lots of `PouchDB` objects (as I see you are), then you will need to add:

```js
PouchDB.setMaxListeners(20);
```

I would happily accept a pull request to the [common errors page](https://github.com/pouchdb/pouchdb/edit/master/docs/errors.md) to explain this issue. :)

**Comment by barbalex** [comment]
thanks!
