### ISSUE TITLE
Automated performance testing

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4152]
What we have right now: performance tests that are run ad-hoc by contributors when they feel like it.

What I want: a dedicated machine somewhere to run the performance tests for each commit and show a graph with the performance changes over time.

I know we run our tests in Travis, but that has a few issues; 1) the hardware may change between tests, so it's not consistent, 2) the information is not surfaced very well, so we ignore it, and 3) the tests don't even finish for Firefox because they time out.

I'm willing to set up an EC2 somewhere to do this, unless someone else is interested. I'm not sure how I'd integrate it into Github, but even just a bot to add a comment to each PR with a link to some website somewhere would be nice.

**Comment by daleharvey** [comment]
Yup would love this, its non trivial but would be super useful, we can have it send status to github PR's the same way coveralls does

We also have like 3000 performance test results @ https://pouchdb.cloudant.com/performance_results, while the results are possibly not hugely useful, it would likely be a good exercise to get them visualised in a way that did highlight any regressions

**Comment by nickcolley** [comment]
Be happy to donate for any expenses for this :dollar: :+1:

**Comment by redgeoff** [comment]
I’m looking forward to seeing these tests included into PouchDB. For now, I’ve created a separate project that automates the creation of environments that can be used for tests that run against both remote and local instances of CouchDB. The local environment uses vagrant and the remote environment uses a VPS instance like AWS’s EC2.

I’m surprisingly happy with the results as when I ran similar tests over a year ago they were significantly slower (great job, PouchDB team!). In summary, assuming a data set of 10,000 docs where each doc was changed 100 times, I found that it took about 63 seconds to perform an initial replication with a remote CouchDB instance. Furthermore, when I used pouchdb-load, I was able to perform initial replications in just 5.8 seconds! From what I have read, once CouchDB 2 becomes stable we can expect PouchDB to use the new bulk_get API to replicate at speeds comparable to using pouchdb-load, right?

It would be helpful if you have a couple free minutes to review https://github.com/redgeoff/pouchdb-replication-benchmark/blob/master/app/benchmark.js to make sure that my benchmarking tests are opitimzed as one would expect. I’m planning on writing a blog post that summarizes my findings so that others have an easier time understanding the current and future capabilities of PouchDB.

**Comment by nolanlawson** [comment]
> From what I have read, once CouchDB 2 becomes stable we can expect PouchDB to use the new bulk_get API to replicate at speeds comparable to using pouchdb-load, right?

Yep. :)

> It would be helpful if you have a couple free minutes to review

Looks great to me, although you may want to experiment with different batch_sizes. There tends to be a sweet spot depending on the size of your documents. Also, you don't really need to have a simultaneous changes feed alongside the two replications; just listen for events on the replication itself.

**Comment by redgeoff** [comment]
Cool, looking forward to CouchDB 2!

Yeah, I'll include a note about tweaking the batch_sizes. Thanks.

**Comment by redgeoff** [comment]
For anyone interested, I've written a summary of my benchmarking tests at [Is PouchDB Fast Enough for My App?](https://medium.com/@redgeoff/is-pouchdb-fast-enough-for-my-app-5e36d28a831f#.wz5u5dh4s) For more details or to run the tests yourself, see [pouchdb-replication-benchmark](https://github.com/redgeoff/pouchdb-replication-benchmark).
