### ISSUE TITLE
Build Issue with Node

### ISSUE THREAD

**Issue by jkrot** [pouchdb/pouchdb#4173]
I am getting a build issue after trying to install this package, using python 3.4.3 and updated Node,js 
![error2](https://cloud.githubusercontent.com/assets/124587/9318643/1c068abc-450b-11e5-8719-c63cb77e0154.PNG)

**Comment by nolanlawson** [comment]
Looks like it's failing because you need Python installed? Also I'll warn you: folks have had difficulties installing leveldown on Windows; some have turned to using `sqldown` with `sqlite3` instead.

**Comment by jkrot** [comment]
Thats the think I installed python 3.4.3 and added it to path.

**Comment by daleharvey** [comment]
Awesome so its working? reopen if there are any more issues, cheers

**Comment by jkrot** [comment]
No it was failing even with Python installed and added it path.  It was the first thing I tried.

**Comment by jkrot** [comment]
So I tried dorking around with the older version of python and looks like the build doesn't like python3 and I just get the leveldown error with python2.
![python2](https://cloud.githubusercontent.com/assets/124587/9333262/938a4870-458e-11e5-8a15-76e3fcca0277.PNG)

**Comment by nolanlawson** [comment]
There's also `leveldown-prebuilt` which may work for you on Windows. I would tend to recommend against `sqldown` as a backend because it is quite a bit slower than `leveldown`, although I admit something that works is better than something that doesn't. :)

In general, the "use leveldown on Windows" story is not so great nowadays, so any help with that would be very much appreciated! You may want to check out https://github.com/Level/leveldown/issues/207

**Comment by jkrot** [comment]
In the meantime I am just avoiding leveldown atm but doesn't seem like a longterm solution, one issue at a time :-).

**Comment by nolanlawson** [comment]
Yeah you can use memdown to test locally, then if/when you deploy... use Linux? :/ I realize that's not a satisfying answer, but I haven't seen much movement toward Windows support in leveldown, and it's been a known issue for awhile.

**Comment by jkrot** [comment]
Yeah I am just going to close this one out, the documentation here was really helpful in at least working around it.  http://pouchdb.com/api.html#extras
