### ISSUE TITLE
Blob store

### ISSUE THREAD

**Issue by cshum** [pouchdb/pouchdb#4197]
Instead of putting all buffers into *DOWN database, a separated blob storage is likely a better choice especially for pouchdb server.

https://github.com/maxogden/abstract-blob-store

**Comment by calvinmetcalf** [comment]
Since we don't stream anything the benefits are likely to be minimal over
using leveldb especially as we'd lose any sort of atomicity. That being
said making a plugin that eschews couchdb compatibility for faster blob
storage might be useful.

**Comment by nolanlawson** [comment]
Agree with @calvinmetcalf. Also atomicity is important, although if we had a streaming API we could still use the md5sum to verify the contents of the Buffer. Also we could write the Buffers before starting any Level transactions... lots of ways to do it.

It's worth noting, though, that this would only make sense for the LevelDB adapter, since in WebSQL and IndexedDB there's no streaming API, so we're already using the most efficient storage method for each.

**Comment by daleharvey** [comment]
Yeh its unlikely we want to do this in core PouchDB althoug we may want to make this pluggable in future, if somone starts working on it we can open a discussion for it then
