### ISSUE TITLE
Restructured nav and content

### ISSUE THREAD

**Issue by zaccolley** [pouchdb/pouchdb#4200]
The nav structure seems confusing in parts as there's duplication so its unclear where i should be for certain info.

So maybe:
1. Rename "Guides" -> "Getting Started"
2. Rename "Learn" -> "About"
3. Take the intro from "Getting Started" and merge into "About".
4. Merge 'Getting Start Guide', '#Installing' and '#Using PouchDB' into "Getting Started"
5. Remove 'API' from "About"
6. Structure nav like: "About | Getting Started | API |  Blog | [Download]"

then the flow for actions could be something like:

I want to find out about PouchDB -> About
I want to install and use PouchDB -> Getting Started
[from Getting Started] I want a simple tutorial -> (currently) http://pouchdb.com/getting-started.html
[from Getting Started] I want a more advanced/comprehensive tutorial -> (currently) http://pouchdb.com/guides/

Just my thoughts coming to it with fresh eyes, what do people think?

**Comment by nolanlawson** [comment]
Thanks for the commentary! It is nice to get fresh eyes on these things. :)

The Getting Started/Guide split is indeed kinda confusing, and mostly stems from historical reasons (the Getting Started precedes the Guide by a few years).

While I do like putting Getting Started up top-level, I'm not so sure about removing the Guide from the top-level as well. My inspiration was [Ember.js](http://emberjs.com/), which has About | Guides | API | Community | Blog | Builds. I like having the Guides top-level because sometimes people get started while skipping that stuff, then they realize later "Oh wait, maybe I should read the guide on attachments before I start trying to use attachments."

Maybe move Getting Started to the top-level and call it Get Stated? (Because it's shorter?)

**Comment by nolanlawson** [comment]
As for Learn -> About, and removing API from About, agree 100%.

**Comment by James-Byrne** [comment]
I can work on this if there has been a decision on how you want the pages structured.
