### ISSUE TITLE
Build an eval-less and Function-less version of pouchdb.js

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4202]
This would be useful for Firefox extensions, Chrome apps, and other environments where these things aren't allowed. Then we would just document that mapreduce/filter functions don't work.

**Comment by nolanlawson** [comment]
Proposal: let's just do a special `browserify` script that swaps out

1) mapreduce
2) any instance of `new Function()`

... and throws an error if you try to access those. We can call it `pouchdb.noeval.js` and `pouchdb.noeval.min.js`. Sound good?

**Comment by marten-de-vries** [comment]
Wouldn't it be easier to make browserify just ignore evalView.js & evalFilter.js? If that's not possible for some reason, then your solution seems fine too. :)

**Comment by nolanlawson** [comment]
Yep, we could add it to the `browser` member in `package.json` and force Browserify to ignore it all the time, but then those functions would be unavailable for people who need it. :) eval-less is really a very niche use case; I imagine this stripped-down version only being useful for 1) people developing for exotic environments, and 2) people not using map/reduce who want a slightly smaller build.

I'm envisioning using command-line arguments to the `browserify` CLI to ignore those files only for this particular build.

**Comment by marten-de-vries** [comment]
Yes, the ``--ignore`` browserify option was what I had in mind.

**Comment by nolanlawson** [comment]
ahh cool, didn't know about that option

**Comment by BigBlueHat** [comment]
I'm currently using PouchDB in a Web Extension (and encouraging others too), but I'm realizing that we're all going to hit a wall (at least with Mozilla...) when it comes time for editorial/code review due to this issue.

Maybe it's time for a `pouchdb-webextension` option? 😀 

Pretty sure the only thing that needs to "come out" is the Map/Reduce bit--which is already planned to be optional/extracted at some point.

My ideal, though, would be to keep Map/Reduce as an available indexing option, but have it work without `eval()` and `new Function()`...and without giving up functionality. "But I can dream...can't I?" 😄

**Comment by nolanlawson** [comment]
Unfortunately even with removing the mapreduce plugin there are still some uses of eval() and Function() within pouchdb core (e.g. changes filters). The only way to fix this right now is to do a global browserify transform (or the equivalent in webpack/rollup/etc.) and remove the eval()s (or change them to e.g. `$eval()`).

Actually I just remembered I've written a browserify transform to do exactly this :smiley:. You can use: https://github.com/nolanlawson/global-replaceify

And do e.g.:

```js
browserify(/* ... */).transform('global-replaceify', {
  replacements: {
    eval: '$eval',
    Function: '$Function',
    // etc.
  },
  global: true
});
```
