### ISSUE TITLE
LevelDB without streams

### ISSUE THREAD

**Issue by cshum** [pouchdb/pouchdb#4205]
Since PouchDB does not expose streams at all, would it make sense to consume [LevelDOWN](https://github.com/Level/abstract-leveldown) API directly (which exposes an iterator instead of stream), so that Node Stream library does not need to be included?

I am a fan of streams. But the only place I see stream being used in PouchDB is when reading results through [LevelUP](https://github.com/Level/levelup).

**Comment by daleharvey** [comment]
Very sorry for missing this, our main focus on size is in the native browser builds, in general the levelDB ones are for Node, testing or other instances where size is less important (cordova packaged apps). 

If you want to try this out and it turns out an improvement then that would be awesome and very happy to look at a PR for that, but judging from activity it doesnt seem there is a huge amount of interest in tracking this in core. Thanks (and sorry again)
