### ISSUE TITLE
Fig has been replaced by Docker Compose

### ISSUE THREAD

**Issue by matsprea** [pouchdb/pouchdb#4237]
Since [Fig has been replaced by Docker Compose](http://www.fig.sh/) the [TESTING.md](https://github.com/pouchdb/pouchdb/blob/master/TESTING.md) doc should be updated to use [Docker Compose](http://docs.docker.com/compose/).

**Comment by daleharvey** [comment]
@matsprea Are you actively using this, want to fix the docs for it?

I dont believe there are many people using this, the docker install is vastly more complicated than just installing pouchdb and there is always `pouchdb-server` or `pouchdb-express-router` if people get stuck with testing couchdb. 

I think we should give this a week, if anyone is up for maintain the docs + fix.yml then happy to accept a patch, otherwise I would rather remove it and not confuse people with unmaintained documentation

**Comment by matsprea** [comment]
@dahjelle I'm not using this right now. I just find it because I would like to contribute to the project so I was reading the docs.

I'll try to update the docs for this, I'll come back in a couple of days hopefully with a patch.

**Comment by daleharvey** [comment]
ok great, if you have any issues contributing please feel free to ask any questions, will be happy to help

**Comment by daleharvey** [comment]
@matsprea Also if you arent currently using docker and are looking for a place to contribute, then @nolanlawson has written up all the steps for https://github.com/pouchdb/pouchdb/issues/4265 and may be more suitable for you.

If nobody who is actively using docker + pouch is maintaining this then its probably best to get rid of

**Comment by daleharvey** [comment]
And removed, cheers - https://github.com/pouchdb/pouchdb/commit/ef23b4fd7b4d3e853844e4b6247c3405b569a5ac
