### ISSUE TITLE
More resilient approach to namespacing level dbstores.

### ISSUE THREAD

**Issue by nickcolley** [pouchdb/pouchdb#4248]
https://github.com/pouchdb/pouchdb/pull/4246

At the moment we get the name of the function, which could change since we have no control over third parties.

We need a way to have something that won't break down the line...

**Comment by daleharvey** [comment]
And to quote the background for this

> So the thing is that Function.name is really a hack, and we are exploiting 
> the fact that most of the *down adapters have names like MemDOWN 
> and LocalStorageDOWN that make them easy to identify. But in fact there's 
> nothing stopping them from exporting anonymous functions if they feel like it.

> I'd suggest that instead of providing a Function.name shim, we just rewrite the 
> part of the code that checks for it.

**Comment by daleharvey** [comment]
So taking a look at the code, this is actually fine, the function name we use is not persisted, its used as a key to a map of currently open databases, if the name changes between invocations of the database then it is supposed to be a cache miss because it is a different (and possibly incompatible) implementation. if / when level / mem / etc down change their function name they will still be passing the same function when opening databases within the same instance, so all is fine.
