### ISSUE TITLE
Auto Batch?

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#4302]
In our application we automatically convert multiple "get" calls in the same tick into a single "allDocs" call witth "keys" behind the scene without the caller of "get" knowing the difference.

However, since PouchDB doesn't do this already by default I'm a bit unsure whether there is a good reason not to do this?

**Comment by daleharvey** [comment]
It mostly just hasnt been an optimisation that has come up. Although it is the type of optimisation that makes me slightly uncomfortable. The smarter we try to be the less control the client has over what we do and the less chance the db layer underneath us gets to to these type of magic optimisations.

Another reason that at least I havent looked at it is that my major performance issues are in replication and indexing, which are slower on an order of magnitude and can be on the end of much bigger wins. Plus as you mention its fairly easily fixed by the consumer of the api

**Comment by tohagan** [comment]
Sounds like an intercept wrapper on the existing API that you'd deploy as a plugin (so core PouchDB is unchanged). Would that work?

**Comment by nolanlawson** [comment]
This is exactly the kind of optimization that the underlying storage engine ought to be taking care of (IMO). (I do believe IndexedDB already does this anyway in most browsers, because calling `IDBObjectStore.get()` multiple times in the same turn of the event loop is faster than `IDBCursor`.) 

Also in my experience there is not a big difference between multiple `PouchDB.get()`s in the same turn of the event loop vs one `PouchDB.allDocs()`; in fact, if you use `keys` it is implemented more-or-less like a bunch of concurrent `get()`s, because I performance-profiled and didn't see any difference between the two.

**Comment by tohagan** [comment]
So then perhaps it's value may be more in the http adapter than in the storage adapter?

**Comment by daleharvey** [comment]
Yup agreed if this was to be done I think its best done in plugin land or user code, PouchDB core is aiming to be as straightforward as possible and adding code to try to auto correct for inefficient use of the api leads to complications (we certainly dont want to add artificial 10ms delays for example).

There isnt any particular reason to avoid it that I can think of, but its certainly something as an app developer I would want to be controlling rather than have it magically done under me.
