### ISSUE TITLE
PouchDB wrongly flags + as illegal character for database name

### ISSUE THREAD

**Issue by colinskow** [pouchdb/pouchdb#4314]
```js
new PouchDB('http://localhost:5984/my+database')
  .catch(function(err) {
    console.log(err);
  });
```

Responds...

```
{ [illegal_database_name: Database encountered an unknown error]
  status: 400,
  name: 'illegal_database_name',
  message: 'Database encountered an unknown error',
  error: true,
  reason: 'Name: \'my database\'. Only lowercase characters (a-z), digits (0-9), and any of the characters _, $, (, ), +, -, and / are allowed. Must begin with a letter.' }
```

**Comment by willholley** [comment]
This error is just passed through from CouchDB in this instance. It will work if you percent-encode the +:

    new PouchDB('http://localhost:5984/my%2Bdatabase')
    .catch(function(err) {
       console.log(err);
    });

**Comment by daleharvey** [comment]
I am fairly sure we purposefully dont url encode the database name, but I cant quite think of why right now

**Comment by daleharvey** [comment]
Nope, cant think of any reason to not do this

**Comment by daleharvey** [comment]
fixed in https://github.com/pouchdb/pouchdb/commit/94c7276adfe0ce36b6471874cb60d5bdbcebdacf

**Comment by lupomontero** [comment]
This breaks things when a database name contains a `/`, which is valid as far as CouchDB is concerned (ie: user databases in Hoodie are named `user/randomid`).

Before [this change](https://github.com/pouchdb/pouchdb/commit/94c7276adfe0ce36b6471874cb60d5bdbcebdacf) we could work with database names like this, but not now. Consider a CouchDB server being served in a subdirectory (ie: `http://foo.com/_couch/`), and a database called `user/bar`, so the URL would be `http://foo.com/_couch/user%2Fbar`.

```js
// pre 5.1.0 this worked, now it gets double encoded
var db = new PouchDB('http://foo.com/_couch/user%2Fbar');

// now, without encoding PouchDB will think `bar` is the database name
var db = new PouchDB('http://foo.com/_couch/user/bar');
```

This is because `PouchDB` is splitting the url using `/` as the separator, and then encoding the last part. From [source](https://github.com/pouchdb/pouchdb/blob/master/lib/adapters/http/index.js#L88):
```js
  // Split the path part of the URI into parts using '/' as the delimiter
  // after removing any leading '/' and any trailing '/'
  var parts = uri.path.replace(/(^\/|\/$)/g, '').split('/');

  // Store the first part as the database name and remove it from the parts
  // array
  uri.db = encodeURIComponent(parts.pop());
```

A possible solution would be to check for the presence of `%` in db name before it is encoded with `encodeURIComponent()` as suggested by @colinskow [here](https://github.com/pouchdb/pouchdb/commit/94c7276adfe0ce36b6471874cb60d5bdbcebdacf#commitcomment-13837545). Something like:

```js
  uri.db = parts.pop();
  if (uri.db.indexOf('%') === -1) {
    uri.db = encodeURIComponent(uri.db);
  }
```

I will send PR shortly.

cc/ @daleharvey
