### ISSUE TITLE
Option to include (or not) attachment data in replication

### ISSUE THREAD

**Issue by cquillen2003** [pouchdb/pouchdb#4362]
Image attachments are very large in comparison to their associated CouchDB/PouchDB documents.  A few hundred images in a database can easily exceed the storage capacity of IE and Mobile Safari, so it would be great to have the option to not include attachment data when replicating or syncing.

**Comment by kxepal** [comment]
Option to not include attachments or modify in any way documents during replication breaks the meaning of the word "replication" since target will be not a replica of source, but a product of F(source). And second replication without such option will produce conflicts for all documents which may not be available since they'll have lesser revision.

You can keep attachments and their metadata in separate databases while both documents shares the same id. Metadata is light and replicates fast, while images are big and could be fetched by demand.

**Comment by cquillen2003** [comment]
To clarify, I want the attachment stubs (metadata) to always replicate, but make replicating the attachments themselves (the binary data) optional.  It seems this would align perfectly with the CouchDB/PouchDB API as it relates to attachments because attachments are not included by default when fetching a document, only the attachment stubs are.

Also, not including attachments in a replication seems kinda like a filtered replication - a standardized filtered replication.

**Comment by daleharvey** [comment]
Yup this is a long requested feature, I actually filed this myself almost 2 years ago, will dupe

**Comment by mmpowers** [comment]
I had until now assumed we could do this.  Now I'm going to need it.  Could this be as simple as ignoring the binary during replication if an option is set?  Or perhaps storing a dummy binary value holding the URL to the attachment at the replication source, and fetching the attachment on demand if needed?

**Comment by nolanlawson** [comment]
Yep, you could also do this trick yourself by not using attachments and simply storing the md5sum, then keeping the attachments in a separate server. Incidentally this is how npm  does it, because they ran into scaling issues with CouchDB attachments.

**Comment by daleharvey** [comment]
So the actual option to not fetch the attachment would be fairly simple, it would be an option to control https://github.com/pouchdb/pouchdb/blob/master/lib/replicate/getDocs.js#L25 (may need a few other small changes)

I dont think we should store urls to the remote attachments etc, with `attachments: false` the user will at least see the stubs I believe so knows there are supposed to be attachments there, they can manually pick them up from the remote if they wish

**Comment by daleharvey** [comment]
Another thing would be to ensure that this option became part of the replication id, so if the user did another replication without that option, it would fill in the attachments

**Comment by mmpowers** [comment]
I have a federated use case, where a few supernodes replicate all attachments, but the edge nodes won't.  If you store the originating url, you can ensure that records that are replicated across the edge nodes all still know where to go to find a supernode that has the attachment when it's needed.

**Comment by daleharvey** [comment]
The edge nodes should still know where to find the data as it knows where it has replicated from though right? Just an option to not fetch attachments sounds fairly trivial but something that modified the document contents during replication while it is also something that sounds great it does sound a lot trickier, we would have to ensure those modifications did not get replicated back onwards for example

We do have a plugin[1] that would fulfill the case of modifying attachments to urls on the way in, but it would likely be quite wasteful since it would still fetch the attachments.

It may be possible to implement the "dont fetch attachments" option, then additionally use something like filter-pouch to additionally store the urls

[1] https://github.com/nolanlawson/transform-pouch

**Comment by mmpowers** [comment]
In my use case, given supernode A and edge nodes B and C, if C replicates a record with attachments from B, C will be unable to know where to get the attachments.  If the attachment url accompanied the record, C (and D and E etc etc) would know it can fetch from A.

**Comment by diana134** [comment]
Hi, new-ish web dev here, and I could really use some guidance.

We're using a slightly custom version of Pouch in our web app, and we need the option to replicate without attachments. We have a fairly narrow use case, so it only has to work with websql, and an instance of Pouch only ever replicates from the server's Couch instance. Also we always want to replicate from Couch without attachments, there will be no subsequent `replicate.from` with `attachments: true`.

I've modified replication to accept an attachments option, and I can replicate documents with attachments to Couch, and documents without their attachments from Couch. 

The issue I'm now facing is trying to get the attachments from Couch outside of replication. I've got the server sending the attachments, but Pouch doesn't seem to be getting them, so I'm not sure if I've broken Pouch or I'm just not requesting the attachments properly.

If I've broken Pouch I suspect the issue is either what I've done in `adapters/websql/bulkDocs.js` around line 315:
```javascript
preprocessAttachments(docInfos, 'binary', function (err) {
    if (err) {
      return callback(err);
    }
    db.transaction(function (txn) {
      tx = txn;
      // verifyAttachments(function (err) {
      //   if (err) {
      //     preconditionErrored = err;
      //   } else {
          fetchExistingDocs(websqlProcessDocs);
      //   }
      // });
    }, unknownError(callback), complete);
  });
```

or in `adapters/websql/index.js` around line 835:
```javascript
api._getAttachment = function (attachment, opts, callback) {
    var res;
    var tx = opts.ctx;
    var digest = attachment.digest;
    var type = attachment.content_type;
    var sql = 'SELECT escaped, ' +
      'CASE WHEN escaped = 1 THEN body ELSE HEX(body) END AS body FROM ' +
      ATTACH_STORE + ' WHERE digest=?';
    tx.executeSql(sql, [digest], function (tx, result) {
      // websql has a bug where \u0000 causes early truncation in strings
      // and blobs. to work around this, we used to use the hex() function,
      // but that's not performant. after migration 6, we remove \u0000
      // and add it back in afterwards
      console.log(sql, digest);
      console.log(result);
      if (!result.rows.length){
        // this happens if we didn't replicate down attachments
        // we want to return an error so the application
        // can decide what to do
        // TODO is this an ok error to return?
        callback(errors.error(errors.MISSING_STUB));
      } else {
        var item = result.rows.item(0);
        var data = item.escaped ? websqlUtils.unescapeBlob(item.body) :
          parseHexString(item.body, encoding);
        if (opts.binary) {
          res = binStringToBlob(data, type);
        } else {
          res = utils.btoa(data);
        }
        callback(null, res);
      }
    });
  };
```

And this is how I'm requesting the document with its attachment from Couch (my grasp of this is loose at best, so this is likely wrong):
```javascript
myCouch.get(req.doc_id, { attachments: true }, function(err, body) {
	if (err) {
		console.log("failed to get attachment for " + req.doc_id);
		console.log("reason: " + err + "\n");
		res.json(false);
	} else {
		res.write( JSON.stringify( { "docs": [ body ] } ) + "\n" );
		res.end();
	}
});
```

**Comment by daleharvey** [comment]
@diana134 Yup to be honest the effects of touching that part of the code can be fairly confusing and not surprised at all if it affects your ability to fetch attachments.

I expect the easiest way to patch this would be to change https://github.com/pouchdb/pouchdb/blob/master/lib/replicate/getDocs.js#L25 to `attachments: false`

**Comment by MathiasVandePol** [comment]
Thank you very much @daleharvey . The attachements: false worked wonderfully and made sync working again. Replication got timed out. Thanks!

**Comment by nolanlawson** [comment]
@MathiasVandePol A 412 indicates that you tried to insert a stub attachment that the target database didn't already know about. Typically this is a race condition if the following occurs:

1. You fetch a document with `{attachments: false}`
2. Somehow the database is modified to remove the attachment (e.g. deletion + compaction)
3. You insert the same document with the stubs, but the attachments are now unkonwn

**Comment by nolanlawson** [comment]
Whoops, didn't mean to close, this would still be a good enhancement.

**Comment by Thommas** [comment]
Why not use Filtered replication for this ?

> Server-side filtering, again, takes nothing more than a JS function, but it's executed by CouchDB. This will prevent documents from going over the wire in the first place! So obviously we prefer this one.

http://pouchdb.com/2015/04/05/filtered-replication.html

**Comment by cquillen2003** [comment]
@Thommas I'm attaching photos (and other files) to contact records, address records, etc.  I want the contact and address information in PouchDB, but not the attachments.  This will prevent storage limit issues because the contact and address records are tiny in comparison to their file attachments.

So I don't think filtered replication will work in this case because it would filter out the contacts with attachments.

**Comment by pts-davidpark** [comment]
i have a simple use case: replicate from the source to target with no attachments whatsoever. Is there a way to not fetch attachments when getting in bulk from the source?

**Comment by daleharvey** [comment]
There is, we actually fetch the attachments seperately, there isnt an option to do that in replication though, that is what this bug is

**Comment by buhrmi** [comment]
Hey guys. Is anybody thinking/working on this? I think it would be really cool to have a pouchdb config option to not include attachments by default and offer an easy way to load them "on demand".

**Comment by nolanlawson** [comment]
No, nobody is working on this. Although if you’d like you could fork the pouchdb-replication package from within PouchDB’s codebase and make a modified version that did attachments:false. :)

**Comment by broerse** [comment]
@nolanlawson Can I talk to you about this? I like to have an `attachments:false` option for replication. I am willing to hire someone to add this. Like to know what problems an option like this will create.

**Comment by jamesmfriedman** [comment]
I've now come across the same issue. This is specific in my case to replication from couch to a browser environment. In my ideal scenario

- The attachment documents would still replicate from local to remote normally upon creation
- The attachment would not replicate from server to local until "getAttachment" was called.

The reason for this is definitely slightly coupled to my use case, there is lots of meta data that a user would want to see and will only need to see attachments if they actively go to a "media" page.

With how it currently works, the user is forced to download all of the media all the time which is bad for bandwidth and performance. I'm aware I can implement some of the workarounds proposed in this thread and others, but it seems like this would be a fairly common issue people would come across, and a good value add.

**Comment by knubie** [comment]
I've had to implement this myself recently for my own app. It's pretty hacky and involves disabling some safety checks in the indexeddb adapter, but it works for my use case. If anyone's interested you can find the code here: https://github.com/knubie/pouchdb/commit/bd50a440de6da512a523612f7f15ffce134b2100

If there's enough interest, maybe we can turn this into a PR and rewrite the hacky bits.

The biggest difficulty was getting stubs to save locally, because there are verification checks that run in the adapter to make sure stubs have a full attachment counterpart in the database.

Also I wrote this before I knew that @garrensmith 's PR existed, so maybe I'll go back and take a look at that as well.

**Comment by broerse** [comment]
@knubie We are still very interested in this too. Implementing an `unfetched: true` flag is a very simple but powerful option. The problem is the PouchDB maintainers like to stay CouchDB API compatible so the PR has to be on the CouchDB side first.

**Comment by knubie** [comment]
@broerse Just read through the PR #7185. Looks very similar to mine, with the addition of the `unfetched: true` property, which as you say I think it very important. I think I'll add that to my own branch now.

@broerse Do you know if this is actively being worked on in CouchDB?

**Comment by broerse** [comment]
@knubie I don't know but will ask on Monday at the CouchDB Meetup in Berlin.

**Comment by garrensmith** [comment]
Just to set the record here, CouchDB isn't planning to implement anything like this. It is a nice idea, but I think we would first need to make the replicator pluggable in pouchdb and then implement a new replicator in PouchDB that doesn't replicate attachments.
