### ISSUE TITLE
Blog post comparing _bulk_get replication to older replication

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4440]
PouchDB 5.0 introduced faster replication via `_bulk_get`, set to be debuted in CouchDB 2.0 and already in PouchDB Server 1.0. I would love to see a blog post from someone in the community (not me or Dale! :smiley:) comparing the old replication to the new one.

Ideally this would involve a simple test to replicate some remote database to a local one, and compare the time taken to replicate the same amount of data. Probably the server should actually be remote (not on `localhost`), since the whole perf boost of `_bulk_get` comes from the assumption that latency is the biggest problem, and therefore the number of HTTP requests should be reduced.

My suggestion for how to go about this would be:
1. Set up an EC2/Digital Ocean/whatever server somewhere
2. Set up PouchDB Server 1.0.0 on it
3. Sync NPM skimdb (https://skimdb.npmjs.com/registry) to it (you can use the Fauxton web UI)
4. Set up a demo HTML page that syncs the PouchDB Server database, using PouchDB 5.0.0
5. Set up the same demo page using PouchDB 4.0.3
6. Compare the two!

You'd have to be sure to blow away the browser data between each test (I recommend [ClearBrowserData](https://chrome.google.com/webstore/detail/clearbrowserdata/apehfighfmpoieeniallefdeibodgmmb) for Chrome and [Clear Recent History](https://addons.mozilla.org/en-US/firefox/addon/clear-recent-history/) for Firefox), but other than that, it should just be a matter of timing the two. It takes long enough to sync npm that the difference should be pretty clear.

It may also be interesting to compare different browsers, or even to compare a sync in Node.js, since different browsers have different limits on how many simultaneous HTTP requests they allow, and in Node.js AFAIK there are no limits.

Either way, I'd really like to see more blog posts from the community on pouchdb.com! It's been the Dale and Nolan Show for too long. :smiley:

**Comment by garrensmith** [comment]
+1. This would be really interesting to see.

**Comment by dholth** [comment]
I did an experiment back in March with my own _bulk_get implementation. We were looking for a good balance between replication speed and memory usage by setting different batch_size / batches_limit. The script would replicate, destroy(), and try again with the next parameters. I also suspect that SPDY or HTTP/2 combined with better parallelism in PouchDB is almost as much of an improvement as _bulk_get.

On Desktop Chrome at home (50ms ping), I tried several batch_size / batches_limit and did a one-way replication to the local machine.

At the office this would run substantially faster because the round trip time is close to zero.

batch 128 limit 1 Begin
batch 128 limit 1 finished in 256.486s
{"doc_count":4851,"update_seq":25022,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}
batch 128 limit 16 Begin
batch 128 limit 16 finished in 165.273s
{"doc_count":4851,"update_seq":25022,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}
batch 128 limit 32 Begin
batch 128 limit 32 finished in 158.269s
{"doc_count":4851,"update_seq":25022,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}
batch 128 limit 64 Begin
batch 128 limit 64 finished in 160.144s
{"doc_count":4851,"update_seq":25022,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}
batch 256 limit 1 Begin
batch 256 limit 1 finished in 181.508s
{"doc_count":4851,"update_seq":25022,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}
batch 256 limit 16 Begin
batch 256 limit 16 finished in 132.229s
{"doc_count":4851,"update_seq":25022,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}
batch 256 limit 32 Begin
batch 256 limit 32 finished in 133.27s
{"doc_count":4851,"update_seq":25022,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}
batch 256 limit 64 Begin
batch 256 limit 64 finished in 133.498s
{"doc_count":4851,"update_seq":25022,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}
batch 512 limit 1 Begin
batch 512 limit 1 finished in 141.995s
{"doc_count":4851,"update_seq":25022,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}
batch 512 limit 16 Begin
batch 512 limit 16 finished in 125.586s
{"doc_count":4851,"update_seq":25022,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}
batch 512 limit 32 Begin
batch 512 limit 32 finished in 114.336s
{"doc_count":4851,"update_seq":25022,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}
batch 512 limit 64 Begin
batch 512 limit 64 finished in 114.961s
{"doc_count":4851,"update_seq":25022,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}

Another run, with different sizes

batch 256 limit 1 Begin
batch 256 limit 1 finished in 166.993s
{"doc_count":4851,"update_seq":25022,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}batch 256 limit 2 Begin
batch 256 limit 2 finished in 144.926s
{"doc_count":4851,"update_seq":25022,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}batch 256 limit 4 Begin
batch 256 limit 4 finished in 133.663s
{"doc_count":4851,"update_seq":25022,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}batch 256 limit 8 Begin
batch 256 limit 8 finished in 127.691s
{"doc_count":4851,"update_seq":25022,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}batch 512 limit 1 Begin
batch 512 limit 1 finished in 134.963s
{"doc_count":4851,"update_seq":25022,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}batch 512 limit 2 Begin
batch 512 limit 2 finished in 112.934s
{"doc_count":4851,"update_seq":25022,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}batch 512 limit 4 Begin
batch 512 limit 4 finished in 109.622s
{"doc_count":4851,"update_seq":25022,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}batch 512 limit 8 Begin
batch 512 limit 8 finished in 114.497s
{"doc_count":4851,"update_seq":25022,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}

With bulk-get plugin turned off. Recent improvements in PouchDB have increased parallelism in sync; probably works best when HTTP/2 is available - it was during this test - mitigating the effect of so many connections.

batch 128 limit 1 Begin
batch 128 limit 1 finished in 296.165s
{"doc_count":4850,"update_seq":25019,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}
batch 128 limit 2 Begin
batch 128 limit 2 finished in 203.291s
{"doc_count":4850,"update_seq":25019,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}
batch 128 limit 4 Begin
batch 128 limit 4 finished in 160.733s
{"doc_count":4850,"update_seq":25019,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}
batch 128 limit 8 Begin
batch 128 limit 8 finished in 237.519s
{"doc_count":4850,"update_seq":25019,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}
batch 256 limit 1 Begin
batch 256 limit 1 finished in 191.707s
{"doc_count":4850,"update_seq":25019,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}
batch 256 limit 2 Begin
batch 256 limit 2 finished in 145.278s
{"doc_count":4850,"update_seq":25019,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}
batch 256 limit 4 Begin
batch 256 limit 4 finished in 129.026s
{"doc_count":4850,"update_seq":25019,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}
batch 256 limit 8 Begin
batch 256 limit 8 finished in 145.974s
{"doc_count":4850,"update_seq":25019,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}
batch 512 limit 1 Begin
batch 512 limit 1 finished in 171.137s
{"doc_count":4850,"update_seq":25019,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}
batch 512 limit 2 Begin
batch 512 limit 2 finished in 140.229s
{"doc_count":4850,"update_seq":25019,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}
batch 512 limit 4 Begin
batch 512 limit 4 finished in 171.344s
{"doc_count":4850,"update_seq":25019,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}
batch 512 limit 8 Begin
batch 512 limit 8 finished in 177.513s
{"doc_count":4850,"update_seq":25019,"idb_attachment_format":"base64","db_name":"a","auto_compaction":false}

**Comment by nolanlawson** [comment]
@dholth Yep, that's cool and your implementation definitely inspired the Couch/Pouch one, but I think the blog post would be more compelling if it used the official _bulk_get. :)

**Comment by smith-kyle** [comment]
I'm new in terms of contributions to pouchdb but I've made open source contributions so I don't know if this appiles to me:
I tried to run these test as described but my pouch server is killed during sync. Any ideas what's going on?

**Comment by garrensmith** [comment]
Hi Kyle,

What errors do you see in the logs/console out?

Cheers
Garren

All misspelling thanks to my iPhone

**Comment by willholley** [comment]
Just trying some perf testing with bulk_get against skimdb replicated from PouchDB Server in EC2. 

A couple of observations:
1. There are lots of POSTs to _bulk_get with an empty set of docs (payload is {docs: []}). Seems like that’s a wasted call we should skip.
2, skimdb is probably a bad example to test against because most docs only have 1 revision (it looks like PouchDB 4.0.3 tries to do some optimisation around rev 1 documents?).

This was running PouchDB in Chrome and FF - in both tests (PouchDB 4.0.3 and PouchDB 5.0) I was getting replication throughput of around 150 docs/sec.

**Comment by nolanlawson** [comment]
@willholley The empty `docs` payload is definitely a bug; we ought to fix that.

As for seeing the same throughput, are you waiting for replication to complete 100%? By design the replicator will try to replicate first-gen documents first using `allDocs()`, so if you only watch e.g. the first 25% of replication, then the speed will appear to be the same because it is fetching only using that efficient method. If you wait for replication to finish at 100% and then measure that, though, the difference ought to be pretty stark.

I forget the exact numbers, but when I was testing npm-browser.com using bulk loading, I was seeing differences of ~10 minutes vs 2 hours. I'd be very very surprised if you see no difference. Also are you sure you're using PouchDB Server 1.0.0?

**Comment by willholley** [comment]
testing with the currently nightly removes the spurious bulk_get POSTs. It sounds like we don't really expect any perf improvements for databases with primarily first-gen documents. For reference, my first testing run:

Movies demo - http://52.30.249.131:5984/movies-demo), 5995 docs

### Server

AWS EC2, Europe West (Dublin)
m4.xlarge running PouchDB 1.0.1
~15ms latency client -> server

# Results

## PouchDB 4.3 - movies demo

115 docs/sec (52s)
153 docs/sec (39s)
127 docs/sec (47s)
127 docs/sec (47s)

508 requests per run

## PouchDB 5.0 - movies demo

105 docs/sec (57s)
63 docs/sec (1m 34s)
142 docs/sec (42s)
142 docs/sec (42s)

572 requests per run

**Comment by willholley** [comment]
and with PouchDB nightly (different internet connection so better throughput in both tests):

# Results (Home)

## PouchDB 4.3 - movies demo

239 docs/sec (25s)
124 docs/sec (48s)
230 docs/sec (26s)
249 docs/sec (24s)
260 docs/sec (23s)

508 requests per run

## PouchDB nightly - movies demo

199 docs/sec (30s)
69 docs/sec (1m 26s)
162 docs/sec (37s)
230 docs/sec (26s)
146 docs/sec (41)

502 requests per run - note that only 4 are bulk_get

**Comment by nolanlawson** [comment]
> 508 requests per run

What are all these requests, then? In my own testing it was mostly GETs, which is what _bulk_get is supposed to fix.

**Comment by willholley** [comment]
_changes, _all_docs and checkpoints

**Comment by nolanlawson** [comment]
OK I understand now. I just checked your database, and you have 5995 documents, of which 5993 are generation-1. So yeah, you shouldn't see any difference between master and 4.0.3.

`_bulk_get` will *only* run for gen-2+ documents; for gen-1 it is still more efficient to use the _all_docs trick. Here is the [best explanation of the algorithm](https://web.archive.org/web/20131028211333/https://github.com/couchbaselabs/TouchDB-iOS/wiki/Replication-Algorithm), via the old TouchDB docs.

**Comment by nolanlawson** [comment]
For the record, I find skimdb to be a better test, because it contains 201400 docs, of which 148815 are gen-1 but 52585 are gen-2+.

**Comment by willholley** [comment]
Y running the same test on skimdb now

**Comment by willholley** [comment]
I found pouchdb-server too unstable on AWS to replicate skimdb. However, with CouchDB nightly:

## PouchDB 4.0.3 - skimdb

89 docs/sec (37m 13s)
122269 requests

## PouchDB 5.0.1 - skimdb

100 docs/sec (33m 1s)
13030 requests, 1600 of which were bulk_get

**Comment by kxepal** [comment]
Huge win on requests amount reduction, but not for the overall time. I guess you can get better numbers with more unstable network when retries will happens eventually.

**Comment by nickcolley** [comment]
Maybe it's worth defining the typical usecase and what network conditions you'd have with that.

Mirroring what @kxepal has said, I'd think a more useful comparison would be a connection with high latency and flakey requests, a bad 3g connection on a train etc.

**Comment by willholley** [comment]
I was discussing these results with my colleagues implementing bulk_get support for Cloudant Sync. One reason that we don't see the expected performance improvement in PouchDB is because PouchDB < v5.0 implements an optimisation for generation 1 revisions (https://github.com/pouchdb/pouchdb/blob/8132c76b0a79b75a1ca7f19d1b85943869f6e47d/lib/replicate/getDocs.js#L79 and https://github.com/pouchdb/pouchdb/blob/8132c76b0a79b75a1ca7f19d1b85943869f6e47d/lib/replicate/getDocs.js#L7).

We're not sure that this optimisation is correct because you could have conflicts at generation 1 so should still need to check that there are no further revisions to replicate (e.g. check with _revs_diff). Without that optimisation, we should see a much better result from the _bulk_get addition. Obviously, if the optimisation is incorrect then we should remove it if bulk_get mitigates the performance issues.

**Comment by daleharvey** [comment]
I am very surprised that change in the number of requests didnt show a more measurable performance increase, was this via localhost? any time I have looked at this previously, reducing the number of requests has had a significant impact.

I think it would be worth testing with the all_docs optimisation removed as well, it seems like if we have any mix of gen-1 + gen-2 docs it means it is going to split them up into seperate requests instead of a single request, maybe only use gen-1 optimisation when bulk_docs is not supported (little tricky since the optimisation is transparent)

**Comment by nolanlawson** [comment]
> We're not sure that this optimisation is correct because you could have conflicts at generation 1

Literally never occurred to me, but you're right. It's funny, though, because that optimization has been kicking around since TouchDB, and nobody brought it up before.

I would definitely be down for removing it once we get bulkDocs in. But for the time being the allDocs optimization is huge for our CouchDB 1.x users and removing it would probably slow their apps down a lot while not providing much benefit because conflicts in gen-1 is a huge edge case. (Speaking of which, if we could get `_bulk_docs` into CouchDB 1.7 that would alleviate a lot of concerns.)

Like everyone else said, I'm still just massively surprised that it doesn't improve the performance much; the number of requests has been reduced by 90% but the total time only reduced by 10%. npm-browser doesn't take anything like 33 minutes (more like 10 minutes) and it's built on top of pouchdb-load, downloading dump files from Amazon S3.

**Comment by dholth** [comment]
Any replication benchmark needs to include the latency to the remote
database and whether or not SPDY or http/2 is in use. Those factors have
a big impact on performance. What's the ping time to the server.?

For example, you could try running the benchmark in Chrome's mobile
device emulator which has a network throttling feature that adds latency
to the connection. I would try multiple times with the same bandwith and
different latency.

On Tue, Nov 3, 2015, at 07:59 AM, Nolan Lawson wrote:
>> We're not sure that this optimisation is correct because you could
>> have conflicts at generation 1


> Literally never occurred to me, but you're right. It's funny, though,
> because that optimization has been kicking around since TouchDB, and
> nobody brought it up before.


> I would definitely be down for removing it once we get bulkDocs in.
> But for the time being the allDocs optimization is huge for our
> CouchDB 1.x users and removing it would probably slow their apps down
> a lot while not providing much benefit because conflicts in gen-1 is a
> huge edge case. (Speaking of which, if we could get _bulk_docs into
> CouchDB 1.7 that would alleviate a lot of concerns.)


> Like everyone else said, I'm still just massively surprised that it
> doesn't improve the performance much; the number of requests has been
> reduced by 90% but the total time only reduced by 10%. npm-browser
> doesn't take anything like 33 minutes (more like 10 minutes) and it's
> built on top of pouchdb-load, downloading dump files from Amazon S3.


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/pouchdb/pouchdb/issues/4440#issuecomment-153344186

**Comment by willholley** [comment]
I mentioned it earlier in the thread:
AWS EC2, Europe West (Dublin)
m4.xlarge running CouchDB master.
~15ms latency client -> server

Chrome's mobile device emulator is a good shout - I'll run some tests with that enabled.

**Comment by kartikagarwal1993** [comment]
@nolanlawson Hey, the discussion here seems to be too old. Is the requirement still in place. If so then the steps that you mentioned are still a best way to approach this issue?

**Comment by nolanlawson** [comment]
I think we'd still be interested to see exactly what the performance benefits of CouchDB 2 vs CouchDB 1 are, yes. :) Especially if it turns out it's not much, then that informs us that we still have some work left to do!
