### ISSUE TITLE
Emit and query

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [pouchdb/pouchdb#4472]
Hello PouchDb team,

I am reading a lot about emits and query but not sure if I grasp the right track.
Can you advise if I understand right with below code:
```
			new PouchDB('ConsumptionDataLocal')
			.then(function (db) {
				var map = function(doc) {
				  if (doc.contentType = 'Calorie' && doc.startDate > '2015-09-09') {
				    emit(doc.startDate, parseInt(doc.energySport));
				    }
				};
				var reduce = function(keys, values, rereduce) { 
					return parseInt(((15.3*75.6)+parseInt(localStorage.basaalIndex))+(sum(values)*3.5*75.6*0.005)); 
				};
			  db.query({map: map, reduce: reduce}, {reduce: true, group: true, group_level: 1}, function(err, response) {
			    console.log(JSON.stringify(response.rows));
			  });
			});

```
Kind regards,
Mario

**Comment by nolanlawson** [comment]
Calling LocalStorage from within your `reduce` is probably a bad idea; also I recommend against using `reduce` if you are getting confused, because PouchDB implements `reduce` entirely in-memory, so you can just not use `reduce` and then aggregate the results yourself in your own code.

Also for testing this stuff out, I highly recommend just running a CouchDB and using the web UI to test out map/reduce queries on some test data; it is a great way to learn. :)

**Comment by nolanlawson** [comment]
Also another issue I notice is that you are using `query()` but you are not passing in any arguments like `startkey` or `endkey`, which means you might as well just use `allDocs()` to read the entire database into memory and then work with it as a javascript object.

I highly recommend reading stuff I've written about this, like http://pouchdb.com/2014/04/14/pagination-strategies-with-pouchdb.html and http://pouchdb.com/2015/02/28/efficiently-managing-ui-state-in-pouchdb.html

**Comment by MarioVanDenEijnde** [comment]
Hello Nolan,

Hum. OK. 
I have read the first one but not the second.
I haven't thought about pagination but I presume you mean to use it like a filter to get only the documents I need.
And question: if I should not use reduce and group then I can only go for a "forEach" appraoch to sum on groups do I?
Or do I have a better alternative?

Kind regards,
Mario

**Comment by nolanlawson** [comment]
In general the map/reduce API is very very complicated, which is why we wrote [pouchdb-find](https://github.com/nolanlawson/pouchdb-find) as a replacement.

The main issue I am seeing with your code is that you are reading the entire database into memory in order to do queries, which is throwing away a lot of the benefits of having a database in the first place. E.g. imagine if you had a MySQL database, but instead of doing `SELECT * FROM person WHERE name = 'Mario'` you just did `SELECT * FROM person` and then filtered your data in Java/PHP/Perl/etc. That is what you are doing when you use map/reduce without `startkey`/`endkey`/`key`/`keys` etc.

Judging by your code, you probably want some kind of `pouchdb-find` query. Maybe try playing around with [Learn you pouchdb-find](http://nolanlawson.github.io/pouchdb-find/) and see if you can create a query that works for you?

Also if you could explain in English what the query you're trying to do is, then perhaps someone in the IRC/Slack channel could help you, but Github issues is not a very good venue for these kinds of questions so I would really recommend moving this discussion to IRC/Slack. :) http://slack.pouchdb.com/
