### ISSUE TITLE
Can PouchDB store locally only a small amount of data from a remote CouchDB instance?

### ISSUE THREAD

**Issue by jmellicker** [pouchdb/pouchdb#4473]
Looking through the docs, it wasn't clear to me if the local PouchDB is always a mirror of the entire remote CouchDB, or if the local instance can be restricted only to specific queries on the (huge) remote DB.

**Comment by daleharvey** [comment]
By default it is a full mirror, there are 2 main options to reduce the amount of data, the main one is filtered replication where you can specify a function and only replicate documents that pass that function, the other is `since` where you can say you only want more recent documents to be replicated, there are some docs @ http://pouchdb.com/api.html#replication about all the options, if you have any more questions feel free :) cheers

**Comment by jmellicker** [comment]
Thanks Dale!
