### ISSUE TITLE
Question about use with UpUp (and service workers in general)

### ISSUE THREAD

**Issue by chenkie** [pouchdb/pouchdb#4513]
Hello! I've got my local and remote databases wired up, and they are syncing just fine. However, when I introduce [UpUp](https://github.com/TalAter/UpUp) and a service worker gets registered, it seems the connection to the remote DB breaks down. The console shows that the error is unknown:

![screen shot on 2015-10-26 at 19-29-54](https://cloud.githubusercontent.com/assets/1847678/10747199/19d77d52-7c18-11e5-9575-778dd91f1d51.png)

Note: this error is thrown immediately after the SW is registered, and isn't limited to the app being tested "offline". Also, CORS is definitely enabled and working fine.

I might be missing something obvious, but is there anything I need to do in particular to make PouchDB play with service workers?

Thanks! :)

**Comment by marten-de-vries** [comment]
Looking through the code of UpUp, it seems like its proxying implementation explicitly states that no cors should be used: https://github.com/TalAter/UpUp/blob/master/src/upup.sw.js#L27 .

You could try to hack UpUp's implementation. E.g. by checking for http://localhost:5984/ , and if so, enabling the CORS flag of the service worker. But I've got no experience with a set up like this, so that's just a guess.

**Comment by chenkie** [comment]
Thanks! I tried a couple things without much luck. I've got an issue open on the UpUp repo. We can close this if you like :)

**Comment by daleharvey** [comment]
Cool cheers, also opened a PR to remove that warning https://github.com/pouchdb/pouchdb/pull/4572 because it was confusing people
