### ISSUE TITLE
Weird Downgrading message all of a sudden

### ISSUE THREAD

**Issue by chino23** [pouchdb/pouchdb#4515]
I've been using PouchDB with websql for over a year now.

Suddenly, a few minutes ago, this happens:

    PouchDB is downgrading "userdata01" to WebSQL to avoid data loss, because it was already opened with WebSQL.

Which is funny as I've never seen that before. And Adapter is clearly stated as websql:

    external.database = new PouchDB(dbName, {adapter: 'websql', auto_compaction: true });

And that's the weird part. Looking at https://github.com/pouchdb/pouchdb/commit/655049730f0500a2461c01225642dd0ea7555586

It seems that it checks that adapterName === 'idb' but that can't be the case. And why all of a sudden?

**Comment by chino23** [comment]
oh and this happens every time now I start the app

**Comment by nickcolley** [comment]
Hey @chino23,

Has your environment changed recently? It sounds like maybe your browser has updated changing the behaviour of PouchDB potentially.

**Comment by chino23** [comment]
Hi @nickcolley,

not really. I've updated to PouchDB 5 and angular 1.4.7 (from 1.4.6) but that was yesterday. And it just happened today.

What might be the case though... I had an error and it threw me 3000+ (!) document update conflicts. After that it started. Did that maybe damage the database?

**Comment by chino23** [comment]
oh and I'm on Chrome but don't think it has updated, as I haven't restarted when it suddenly happened

**Comment by chino23** [comment]
I use a different database now but even then, the message appears every time. Although it's a brand new created database

**Comment by nolanlawson** [comment]
@chino23 Are you only seeing this on one browser? It does indeed sound like your browser may have gotten corrupted somehow. If you open in Firefox or Chrome Canary or another browser, do you see the same message?

**Comment by chino23** [comment]
Just downloaded latest Canary and checked. 

Same thing.

I don't get it. How can a different browser with a new database be affected by this?

**Comment by chino23** [comment]
Ok Investigating a bit. Switched to the unminified version and debugged.

Looking at line 10749 onwards:
````
  if (opts.adapter) {
    adapterName = opts.adapter;
  } else if (typeof opts !== 'undefined' && opts.db) {
    adapterName = 'leveldb';
  } else { // automatically determine adapter
    for (var i = 0; i < PouchDB.preferredAdapters.length; ++i) {
      adapterName = PouchDB.preferredAdapters[i];
      if (adapterName in PouchDB.adapters) {
        if (skipIdb && adapterName === 'idb') {
          // log it, because this can be confusing during development
          console.log('PouchDB is downgrading "' + name + '" to WebSQL to' +
            ' avoid data loss, because it was already opened with WebSQL.');
          continue; // keep using websql to avoid user data loss
        }
        break;
      }
    }
  }
````

So it goes in, and opts.adapter is 'websql' so it works and skips the whole part.

Then, the line gets triggered again with opts.adapter undefined, then it goes down to the downgrading part.

That made me think why that is. So I found the reason.

I have this line to create my database:
````
external.database = new PouchDB(dbName, {adapter: 'websql', auto_compaction: true });
````
And with just that, it works fine.

However, I want a local sync one way during development to check my database in Futon, therefore I have as well
````
PouchDB.replicate(dbName, 'http://adminuser:adminpass@127.0.0.1:5984/' + dbName, {live: true}); 
````
The second line invokes that error. But it's just done as described in the API on the website, and I have used this for a while months ago without error. Did something change with PouchDB 5?

**Comment by nolanlawson** [comment]
Can you please provide a live test case to reproduce? It sounds like the issue is that if you just open two databases with `adapter: 'websql'` you'll see the error message.

To be clear, this error message is not an error; it's just for debugging. It sounds like you *want* to use WebSQL, meaning that you aren't being "downgraded "at all. However I agree that the error is confusing.

Yes, the constructor changed in PouchDB 5, so maybe that's what you're running into. Without a test case, though, I'm really not sure what's going on...

**Comment by daleharvey** [comment]
So `PouchDB.replicate(dbName, 'http://adminuser:adminpass@127.0.0.1:5984/' + dbName, {live: true});` is going to do a new `PouchDB(dbName)`, the new constructor will pick idb as that is the default in chrome, see you have an existing database in websql and 'downgrade' to ensure no data is lost

You can `PouchDB.replicate(external.database` to remove the warning, as Nolan said nothing is broken per se, its just a warning.

Also any particular reason for using webSQL in chrome? idb is the default since its the focus for us / vendors etc

**Comment by nolanlawson** [comment]
Ohhh yeah thanks @daleharvey  you're right. So the fix is:

```js
var myDB = new PouchDB('dbname', {adapter: 'websql'});
PouchDB.replicate(myDB, 'http://....', {live: true});
```

@daleharvey I know it's probably bad for the web community to keep hanging on to WebSQL, but I've gone on the record several times recommending WebSQL over IndexedDB for performance-critical applications. In Chrome, `allDocs()` still performs much better in WebSQL than IndexedDB; in my tests it was as high as 40x faster (see [this](https://github.com/pouchdb/pouchdb/issues/3921#issuecomment-107954085)). The problem is essentially the lack of joins in IDB; I've talked about it a lot [here](http://discourse.wicg.io/t/indexeddb-2-0-performance-improvements/916) but I think ultimately the solution for us will be to move to your proposed "single objectStore" system and avoid joins altogether. (I would go so far as to use a single objectStore for *everything* and just prefix ala LevelDB; that way we could support Safari as well.)

That said, I do think the defaults are best in most browsers. IDB is also better at storing attachments due to the native Blob support.

**Comment by chino23** [comment]
Thanks, using 
````
PouchDB.replicate(external.database
````
works actually, that's what i was looking for.

@nolanlawson, @daleharvey Yes, yes, I know, I'm guilty of hanging on to the old webSQL where I'd love to switch to IDB. But at the moment, it's a performance thing, as this is really crucial for me. 

Before release I'll do some more extended performance tests and see if I can make the switch to IDB but as I've seen now, webSQL seems so much faster from the benchmarks Nolan has put up, since I do big allDocs, sadly...

**Comment by schamp** [comment]
I was getting this issue even though I specified {adapter: 'websql'} and it turned out it was because I was including <script src="http://cdn.jsdelivr.net/pouchdb/latest/pouchdb.min.js"></script> so that the PouchDB Inspector Chrome plugin would work.  (I'm using browserify and require('PouchDB') in my app code).

Commenting out that <script> include made these errors go away, I guess because I can't explicitly call out the websql adapter for the DB that the inspector plugin creates.

I thought I'd mention it in case it would be useful to anyone else.
