### ISSUE TITLE
Replicate.on('beforeChange')

### ISSUE THREAD

**Issue by filoozom** [pouchdb/pouchdb#4549]
Hello,

I'd like to get the difference between the old and the new documents that get replicated via ```PouchDB.replicate()```. I need to remove old files from the local storage, but I need to know the name of the file for that, which is contained in the old document.

I tried something like : 
```
localDB.replicate.from(remoteDB).on('change', function(info) {
    info.docs.forEach(function(change) {
        localDB.get(change._id, function(doc) {
            // Already the new data
            removeFile(doc.picture);
        });
    });
});
```

But ```doc``` already contains the new data.
How could I do this ? Would it be possible to implement a ```.on('beforeChange')``` event ?
I guess I could just use ```localDB.changes()```, but the replication process gets kind of complicated then because I'd need to always fetch the current revision of a document before updating it, and the sequence numbers of both databases wouldn't be in sync.
Or should I just replicate one document after acknowledging a change ? But that doesn't seem like a good solution.

**Comment by tohagan** [comment]
An alternative approach that you might consider is to treat your docs as a sequence of delta changes and then use a map/reduce view to collapse the changes to the current state of each doc.  To apply a change to the view you now send add/remove delta docs. The localDB.changes() is now a sequence of add and remove deltas that will include the doc.picture file paths you want to add/remove.

**Comment by nolanlawson** [comment]
The way the changes feed is currently implemented, I think it would be prohibitively complicated to add this feature. It also introduces some questions that can't be answered very easily - for instance, if a change came in because you are resolving conflicts, then which document was the "previous" document? The previous winner, or the parent revision of the current winner? (They're not the same thing necessarily!) Also what happens if you're doing auto_compaction? That previous document no longer exists, because we just removed it.

I would recommend @tohagan's approach, which I think is well-documented here: http://pouchdb.com/2015/02/28/efficiently-managing-ui-state-in-pouchdb.html. You can also use `stale:ok` to pull out stale data from map/reduce queries, meaning that if you absolutely need to see some old view of the data, you can use that. You can also just not remove the fields when you update your documents, i.e. add an `"oldFilename"` field

**Comment by tohagan** [comment]
You might also want to have a look [Delta Pouch](https://github.com/redgeoff/delta-pouch)
