### ISSUE TITLE
PouchDB inspector for Firefox?

### ISSUE THREAD

**Issue by andysaini** [pouchdb/pouchdb#4570]
Suddenly it's missing from the firefox addons page, could you provide an alternate download location?

**Comment by daleharvey** [comment]
Gonna guess its something to do with the new signing requirements? @marten-de-vries however you can build it and looks like there is a link to it on https://github.com/pouchdb/pouchdb-fauxton-firefox-addon

**Comment by davidmricardo** [comment]
I'm in a windows 10 environment. I just build the extension. How do I install it?

**Comment by nolanlawson** [comment]
Last I checked the Firefox extension is no longer supported because Firefox changed their extension format and removed the old Pouch extension from the store.

@marten-de-vries is the one to ask about this, but I believe in the future we can use a single codebase because both Firefox and Edge have converged on a format more similar to Chrome extensions.
