### ISSUE TITLE
Want to know Indexed DB Storage size (pouch DB)

### ISSUE THREAD

**Issue by binalpanchal** [pouchdb/pouchdb#4590]
Can we know actual pouch Db storage size?
I can store pouch Db's documents and attachments in Indexed DB.So,
 I don't have exactly idea for the storage size. How much size is occupied by Indexed DB.

**Comment by nolanlawson** [comment]
Unfortunately, the web platform has no API for exposing this information. And in fact, IndexedDB can be very unpredictable, since it's built on LevelDB. For instance, you can `compact()`, and then at some unspecified point in the future, LevelDB will *actually* remove old files.

In the future, this will be solved by the Quota Management API: http://www.w3.org/TR/quota-api/
