### ISSUE TITLE
PouchDB client is going in loop when change feed is asking for changes with syncgw.

### ISSUE THREAD

**Issue by sudhanitk** [pouchdb/pouchdb#4604]
SyncGW Release version: 1.1.1-10
Couchbase Release version: 4.0.0-4047
PouchDB version: pouchdb-5.0.0
1) Client requests the list of docs “since=0”.
pouchdb:http GET http://1.2.3.4:8080/pttdata/_changes?timeout=25000&style=all_docs&since=0&limit=100 +2ms
SEC7118: XMLHttpRequest for http://1.2.3.4:8080/pttdata/_changes?timeout=25000&style=all_docs&since=0&limit=100&_nonce=1447414039671 required Cross Origin Resource Sharing (CORS).
2) Sync GW responds with list of changes and last_seq as “231427::231614”

3) Client requests again with the last seq number 

GET
pouchdb:http GET http://1.2.3.4:8080/pttdata/_changes?timeout=25000&style=all_docs&since=231427%3A%3A231614&limit=100 +3ms
SEC7118: XMLHttpRequest for http://1.2.3.4:8080/pttdata/_changes?timeout=25000&style=all_docs&since=231427%3A%3A231614&limit=100&_nonce=1447414039770 required Cross Origin Resource Sharing (CORS).
File: WebDispatcher
SEC7119: XMLHttpRequest for http://1.2.3.4:8080/pttdata/_changes?timeout=25000&style=all_docs&since=231427%3A%3A231614&limit=100&_nonce=1447414039770 required CORS preflight.

Sync GW responds with list of changes and last_seq as “231427::231614”
200 OK Response

Sync Gw logs as below
 2015-11-22T23:26:54.195-06:00 HTTP: #523919: GET /pttdata/_changes?timeout=25000&style=all_docs&since=231427%3A%3A231614&limit=100&_nonce=1448256410641 (as 919591803633)
 2015-11-22T23:26:54.195-06:00 Changes: MultiChangesFeed({*}, {Since:231427::231614 Limit:100 Conflicts:true IncludeDocs:false Wait:false Continuous:false Terminator:0xc217607ce0 HeartbeatMs:0 TimeoutMs:25000}) ... (to 919591803633)

4) With the last_seq in (3), client is in loop requesting GET similar to (3). 

is last_seq “231427::231614” is causing PouchDB to go in loop? 
how to avoid this kind of infinite loops?

Logs are attached in https://gist.github.com/anonymous/39408c5635dfc25bb95e

**Comment by willholley** [comment]
Are you saying that the response from CSG in (3) returns a last_seq of 231427::231614 (i.e. the same as was passed to since)? If the response contains changes then the last_seq should change, else a loop will indeed be generated between PouchDB and CSG.

If not, are you able to provide a HAR / network trace of the interaction?

**Comment by arunvelayudhan** [comment]
@willholley I work with @sudhanitk. Attached the network file (this is in XML format for the loop issue). Two key observations we would like to share.
1) Sync Gateway does send the last_seq as mentioned in the since sequence and pouchDB is able to handle if the last_seq was returned as a "numeric" and everything looks fine. A snapshot is shown below

Request	GET /pttdata/_changes?timeout=25000&style=all_docs&since=0&limit=100&_nonce=1448507362444 HTTP/1.1

response
{"results":[
{"seq":219656,"id":"dc1k1ziie11g7s6_MonitoredGroups","changes":[{"rev":"1-fa7363d5aee03d8ba8034435c58180ab"}]}
,{"seq":219658,"id":"dc1k1ziie11g7s6_CAuditLog","changes":[{"rev":"1-31c7302bec87b8d13b5111a502bdac8b"}]}
,{"seq":272237,"id":"s919591803679_ClientProfile.doc","changes":[{"rev":"23-2d689fbeda4038241f038d4d0676433d"}]}
,{"seq":272240,"id":"s919591803679_pv5.0_ConfigProfile.doc","changes":[{"rev":"15-4edabffec804e6af1d5a8eded23036f7"}]}
],
"last_seq":"272240"}

Request	GET /pttdata/_changes?timeout=25000&style=all_docs&since=272240&limit=100&_nonce=1448507362696 HTTP/1.1

{"results":[
],
"last_seq":"272240"}
l
2) In the second scenario last_seq is returned by sync gateway as "last_seq":"396111::396988". In this case, pouchDB is going in loop.  The attached network dump pls look for "last_seq":"396111::396988". 


[NetworkDataPouchDBLoop.txt](https://github.com/pouchdb/pouchdb/files/44927/NetworkDataPouchDBLoop.txt)

**Comment by willholley** [comment]
curious. In other _changes implementations, last_seq either progresses or no results are returned. Reading the paragraph on compound sequences at https://github.com/couchbase/sync_gateway/wiki/Sequence-Handling), it sounds like a _changes loop may be possible with CSG but it should be temporary. Is this right @jchris?

**Comment by willholley** [comment]
from the log above, the interesting request is:

    GET http://103.249.47.248:8080/pttdata/_changes?timeout=25000&style=all_docs&since=396111::396988&limit=100&_nonce=1448339151840

    {
        "results":[
            {"seq":"396111::396988","id":"s919591803635_ClientProfile.doc","changes":[{"rev":"7-bf5f0aef484ebe7a8718086fc6f41488"}]}
        ],
        "last_seq":"396111::396988"
    }

**Comment by arunvelayudhan** [comment]
@willholley A similar response couchlite client is able to handle. A follow up thread with CSG team is initiated. Pls see below.
https://github.com/couchbase/sync_gateway/issues/1309

**Comment by nolanlawson** [comment]
Appears to be a dup of https://github.com/pouchdb/pouchdb/issues/4602, which has been closed due to an upcoming fix on the CSG side of things. Please reopen if I'm mistaken.
