### ISSUE TITLE
PouchDB map reduce not finding docs with startkey

### ISSUE THREAD

**Issue by garrensmith** [pouchdb/pouchdb#4609]
This is also relevant to https://github.com/nolanlawson/pouchdb-find/issues/94

If I have a list of docs something like this:

```js
{ _id: 1, name: 'Captain Falcon'},
{ _id: 2, name: 'Donkey Kong'},
{ _id: 3, name: 'Fox'},
{ _id: 4, name: 'Jigglypuff' },
{ _id: 5, name: 'Kirby'},
{ _id: 5, name: 'Link' },
{ _id: 7, name: 'Luigi'},
{ _id: 8, name: 'Mario' },
```

And I create a map function like this:

```js
function (doc) {
   if (doc.name) { emit(doc.name, 1); }
}
```

Then do a query with options like this:

```js
 {
   startkey: 'a',
   include_docs: true
}

```

I get zero results back when in fact it should return all the docs.

But if I change the options to

```js
{
   startkey: 'A',
   include_docs: true
}

```

It returns all the docs. But the original options of `startkey: 'a'` works in pouchdb.

I'm happy to try and debug and fix this myself. I just need a few points to know where to look.
Here is a gist with the code to repeat this:

https://gist.github.com/garrensmith/08f3ffb122400b2a59e3

**Comment by willholley** [comment]
if you add some lower case values to this e.g.

    { _id: 9, name: 'mario' }

and query the entire view with options:

    {
        include_docs: true
    }

it seems that 'mario' is ordered last instead of first. It looks like something is up with the view collation.

**Comment by nolanlawson** [comment]
@garrensmith The issue here is CouchDB string ordering, which is based on libicu, and is different from ASCII string ordering, which is used by PouchDB (in all of: JavaScript string ordering, IndexedDB, WebSQL, and LevelDB - yes, they are all the same, which I was very happy about when I implemented PouchDB map/reduce!).

Basically CouchDB goes

    a A b B c C d D e E...

Whereas PouchDB goes

    A B C D E ... a b c d e ... 

This is a known issue and will never be fixed. So probably what you want, to be safest, is:

```js
{startkey: '\u0000'}
```
