### ISSUE TITLE
FileSystemAPI adapter

### ISSUE THREAD

**Issue by mudcube** [pouchdb/pouchdb#4631]
I've been working on a FileSystemAPI (FS) adapter for PouchDB. The goal is to improve support for Mobile devices (I'm working on a Cordova app). It's been a big learning experience for me, PouchDB is such a dense and complex project—a few false starts later, things are falling into place! I'm opening this thread to get advice to help me along the way.

The current vision is to create a WebSQL/FS hybrid adapter. This would provide fast native blob storage on iOS/Android devices (using `cordova-plugin-file` and `sqlite`). All files being written to the attach-store would be sent to the FS, the rest of the data would be written to WebSQL. 

I'm starting writing the WebSQL/FS adapter now (I recently wrote a complete IndexedDB/FS version only to realize it was the wrong path). My current strategy is to add a folder `/adapters/websql-fs/`. Then write a file called `storage.js` into both `/websql/` and `/websql-fs/`. `storage.js` will contain methods to create/close/destroy the datastore and methods to count/get/put/delete objects (this is a summary of all methods used by the `attach-store`). The `/websql-fs/index.js` includes a clone of `/websql/index.js` with the custom storage commands. By keeping it in the main project the additional support for large blobs in Cordova projects should take up around 200 lines. Does this seem like something the maintainers are interested in merging into the master?

Any thoughts, concerns or advice on this strategy would be appreciated!

Also curious; can you think of a use case for a IndexedDB/FS hybrid? My feeling is not, but now that it's pretty much done, it's worth asking you experts :)

btws, Interesting note the [FileSystemAPI](http://w3c.github.io/filesystem-api/) is getting another look by the W3C, rebuilt using Promises. I don't think this would have much use in PouchDB since IDB/FS blob read/write speeds probably would be similar, but worth throwing out there for fellow storage enthusiasts!

**Comment by mudcube** [comment]
Any ideas of the best way to handle bulkDocs? WebSQL requires everything within a transaction to be fired within its own timing. Writing/ready to/from FS means going outside of WebSQLs timing. Here's two possible solutions:
* Some preprocessing could be done to ensure all data is ready when bulkDocs is called.
* A stub could be written to WebSQL and then it wouldn't matter FS was on its own timing. The only issue here is that WebSQL could not call FS.get within a transaction (luckily it's not in bulkDocs)

**Comment by nolanlawson** [comment]
Hey, interesting project. I have a few notes here:

1. Last I checked the FileSystem API was dead in the water, but who knows - specs get dropped and picked up again all the time.
2. Writing your own adapter as a separate plugin is easy! It has been done in many projects, including [worker-pouch](https://github.com/nolanlawson/worker-pouch), [socket-pouch](https://github.com/nolanlawson/socket-pouch), and [pouchdb-replication-stream](https://github.com/nolanlawson/pouchdb-replication-stream)). Feel free to steal the code; in particular note that way I use `PouchDB.adapter()`. :)

So because this is doable as a plugin, I'm going to close this issue. But I look forward to seeing an adapter over the FileSystem API. Neat stuff!
