### ISSUE TITLE
Files not accessible on Coveralls

### ISSUE THREAD

**Issue by tmct** [pouchdb/pouchdb#4635]
When viewing a pouchdb build on Coveralls, the files themselves aren't currently accessible, as was previously spotted on this issue: https://github.com/pouchdb/pouchdb/issues/4107#issuecomment-127277712.

Someone's found the configuration/fix and described it here: https://github.com/javaslang/javaslang/issues/13#issuecomment-55326220

Would be nice to see the line-by-line coverage :) Please could you try applying this? Thanks.

**Comment by nolanlawson** [comment]
We opened an issue on Coveralls. It got closed, but the bug is still there, so I don't know what the issue is, but you might try reopening it on Coveralls: https://github.com/lemurheavy/coveralls-public/issues/263

For the record, checking out the code and running `npm i && COVERAGE=1 npm t` will generate a nice coverage report that you can open in a browser.
