### ISSUE TITLE
QuotaExceededError in PouchDB with brand-new unpacked Chrome extension

### ISSUE THREAD

**Issue by stuartpb** [pouchdb/pouchdb#4637]
Not sure what caused this, but deleting the IndexedDB manually via `indexedDB.deleteDatabase` fixed it (DevTools was showing it as having no records, so odds are it wasn't actually hitting the quota). Figured it's probably worth noting that this happened, in case it's an underlying bug in Chrome or something

**Comment by nickcolley** [comment]
I think this is the error that is thrown when you reach the limit of your database. Are you storing a lot of data?

Related: https://github.com/pouchdb/pouchdb/issues/4531#issuecomment-156598191

We should look at adding this to http://pouchdb.com/errors.html

**Comment by stuartpb** [comment]
It seems that this may have actually been caused by me accidentally briefly using up all of my drive's disk space, doing unrelated stuff outside of Chrome.

In any case, it should be possible to delete a database without getting stopped by this error

**Comment by nolanlawson** [comment]
Please reopen if still an issue. As a side note, quota management is very very weird in IndexedDB, across all browsers. Hopefully the Quota Management API will fix this 🌈_someday_🌈.

**Comment by stuartpb** [comment]
The only real issue is that I wasn't able to delete the database (or any other content) through PouchDB because of the quota failure, due to Pouch trying its write test before letting me take any other operation. Maybe the tests could be deferred until they're relevant?
On Dec 12, 2015 5:42 PM, Nolan Lawson <notifications@github.com> wrote:Please reopen if still an issue. As a side note, quota management is very very weird in IndexedDB, across all browsers. Hopefully the Quota Management API will fix this 🌈someday🌈.

**Comment by nolanlawson** [comment]
PouchDB actually starts functioning very poorly when the quota is reached, when in my mind is a separate issue. E.g. IndexedDB in different browsers starts to fail in unpredictable ways, because the browser starts randomly throwing away data.

I admit it's a larger problem and we don't have a good cross-browser solution to it, because the behavior is undefined when the limit is reached. Imagine if you had a relational SQL database where tables might randomly lose rows, or entire tables disappear, and you get the idea.
