### ISSUE TITLE
Add typescript definition

### ISSUE THREAD

**Issue by iron9light** [pouchdb/pouchdb#4640]
typescript is more and more popular these days.
And visual studio code can use this info for intelligent code completion.

**Comment by nickcolley** [comment]
Hey @iron9light,

Non of the core contributors to PouchDB use Typescript as far as I know so that's why it's not a big focus in core, however there's other community members working on this over here for example:
https://github.com/AGBrown/pouchdb.d.ts

It looks like the definition is out of date but should be good for you to jump in and help update if you wanted to contribute but I'll let @AGBrown guide you there.

Hope this helps.

**Comment by iron9light** [comment]
That really great start point. I'm newbie at pouchdb. I will try this tsd first and see if I can help.
Thanks all you guys.

**Comment by nickcolley** [comment]
Yeah, that's cool! Ping us if you want to talk about anything, here or https://github.com/pouchdb/pouchdb#getting-help

**Comment by AGBrown** [comment]
For reference here. 

 - The project lost some traction due to lack of uptake, but I am still supporting it and accepting PRs. 
 - I have opened AGBrown/pouchdb.d.ts#37 to address the question of our minimum supported version as PouchDB has moved on a whole major version since I started it. 
 - Note that my original issue for DT about this was borisyankov/DefinitelyTyped#4328.

Please post issues and questions about the d.ts into [pouchdb.d.ts](https://github.com/AGBrown/pouchdb.d.ts) and we'll reply there.

**Comment by naivefun** [comment]
+1 in case it gets attraction
