### ISSUE TITLE
there was not enough remaining storage space

### ISSUE THREAD

**Issue by first-leon** [pouchdb/pouchdb#4650]
My code work in opera, firefox, chrome. But not work in KDE Konqueror, KDE Rekonq and KDE Plasma Widgets. In Rekonq i view rhis error:
![error](https://cloud.githubusercontent.com/assets/5301065/11762311/14439374-a104-11e5-827e-ab1bd1d92df7.png)

In preferences size of storage:
![rekonq](https://cloud.githubusercontent.com/assets/5301065/11762345/2592cf40-a105-11e5-9b32-20303f879e0a.png)

And i test this page http://dev-test.nemikor.com/web-storage/support-test/, and Rekonq have:
"localStorage: limited to 2551 k characters"
"sessionStorage: unlimited storage"

I use pouchdb-5.1.0.js

**Comment by nolanlawson** [comment]
Yes, storage limits exist, and PouchDB has no control over them: http://pouchdb.com/faq.html#data_limits

Sorry about that! I hope you find a good workaround. Also keep in mind that the `size` option may work for Konqueror, assuming it works the same as Safari.

**Comment by first-leon** [comment]
Yes, limits exists and it is normal.
But i create 1 record (1-2kB size) and have error.

I verify in Kubuntu 15.10 AMD64 and Kubuntu 14.04 AMD64.

**Comment by nolanlawson** [comment]
It sounds like a bug with Konqueror then, because there is no way that one document equals 5000kb, unless it is storing it in a very inefficient way.

I recommend testing with something like Dexie/LocalForage and see if you reach similar limits with very small document sizes. PouchDB adds some overhead due to the revisioning model, but it's not much.

To be quite honest, you are probably the first person to have ever seriously tested IndexedDB in Konqueror. I wasn't even aware there were any Konqueror users left. [Wikimedia reporting from March of 2015](http://stats.wikimedia.org/archive/squid_reports/2015-03/SquidReportClients.htm) puts them at less than 0.01% of all web traffic.

**Comment by nolanlawson** [comment]
Oh wait sorry, you will want to test LocalForage rather than Dexie, since it appears Konqueror does not support IndexedDB and only supports WebSQL.

**Comment by first-leon** [comment]
I not using Konqueror, it is test only.
But i create KDE Plasma Web Applet and it is not work.
In Plasma Applet i do not show error (not possible debug), but plasma web applet using qtWebKit.
And i suggested that in konqueror and used similarly.
I could be wrong...
