### ISSUE TITLE
Reset PouchDb

### ISSUE THREAD

**Issue by RPallas92** [pouchdb/pouchdb#4662]
Hi, 

I destroyed all the DBs, with PouchDB("db_name"),destroy(). Next time the app is launched, It throws an exception NotFoundError (IndexedDb error, ObjectStore does not exist), and then Pouch can't sync anything.

This exception is thrown at line 3393 (v 5.1.0) (onUpgradeNeeded)

```js
    var txn = idb.transaction([
      META_STORE,
      DETECT_BLOB_SUPPORT_STORE,
      DOC_STORE
    ], 'readwrite');
```

Is it possible to reset the state of PouchDB without uninstalling the web app? Maybe deleting localStorage and indexedDb?

Thanks

PD: It's a WinJS native app (it uses IE 11)

**Comment by josete89** [comment]
+1

**Comment by jlopezmartinez** [comment]
Same problem! Any solutions?

**Comment by abrilrobles** [comment]
+1

**Comment by daleharvey** [comment]
Are these all on WinJS? `.destroy()` is pretty much a direct call to `indexedDB.deleteDatabase()` which should wipe the database completely

**Comment by RPallas92** [comment]
Yes, all on WinJS. Seems like the objectStores are deleted, but in the onUpgradeNeeded throws an exception

**Comment by daleharvey** [comment]
I was referring to the "+1's", its quite strange to see an issue picked up by a few people this quickly. As for your steps, are you doing the `destroy`, completely shutting down the app and starting it from fresh, are there no other background instances open?

**Comment by nolanlawson** [comment]
@daleharvey My guess is that this is due to race conditions in Microsoft's implementation of IndexedDB. Especially when it comes to destroying/opening databases, there are a lot of bugs in there.

However, this might also be WinJS specific. To everyone involved in this bug, I'd like to ask a big favor:

1. Make a (small!) demo WinJS app that demonstrates this issue
2. Upload the source code to a repo in Github
3. Describe steps to reproduce (take screenshots if you can!)
4. Post it here, and then file an issue on [Microsoft Connect](http://connect.microsoft.com/)

The short answer is that PouchDB is an unfunded open-source project, most of the bugs you describe are *probably* in Trident/EdgeHTML, and Microsoft has a team of people who are paid to fix these kinds of issues. However, they have trouble fixing them, because everybody files bugs on projects like PouchDB and not on Microsoft themselves. Also, people rarely file issues with reproducible test cases.

So please: **be a hero and write a reproducible test case for this!** If so many people are running into it, it should be easy. :)

**Comment by daleharvey** [comment]
Sorry, without reproducing we cant fix this, hopefully the bug gets picked up in the edge test failures (or is already fixed :))
