### ISSUE TITLE
Paste service for PouchDB

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#4730]

**Comment by daleharvey** [comment]
Some people use http://bl.ocks.org/, there is also http://paste.pouchdb.com/, jsbin, jsfiddle, codepen and recently https://tonicdev.com. I would like a canonical way for users to as easily as possible post snippets to reproduce problems they are having with PouchDB (why I made paste.pouchdb.com).

I would lke to discuss if there was any way to get us to the ultimate paste service for pouch that we would happily recommend to anyone

bl.ocks: 
  + Quite close correlation between what is posted and what is run on the page
  - Lot of setup involved in getting to pouchdb code (ie make html page, give correct filenames etc)
  - Have to manually open console
  - Runs code on existing domain (ie if you refresh the page you dont get clean storage)
  - Not particularly possible to customise, but open source

paste.pouchdb.com: 
  + Goes straight to writing pouchdb code, no setup
  - Unfamiliar UI
  - Have to manually open console
  - Runs code on existing domain (ie if you refresh the page you dont get clean storage)
  + Can make it do whatever we want

jsbin: 
  + Widely used and familial UX
  + Has console helper
  - Requires manually adding the pouchdb library
  - Runs code on existing domain (ie if you refresh the page you dont get clean storage)
  + Possibly to customise and open source

**Comment by daleharvey** [comment]
I was previously opening this to ask what features we could have on paste.pouchdb.com that would make people want to use it, but I found out that jsbin actually supports indexeddb now (and therefore pouchdb), given the popularity and familiarity of jsbin I think its likely the better choice for pointing people towards.

I am not totally familiar with jsbins customisation options, but having some way to send people to a predefined template somewhat like http://jsbin.com/sosafijaru/edit?js,console, that has pouchdb included and js + console open seems pretty ideal from a users point of view. The only primary issue for me would be that rerunning the code has to deal with old data, fixing that could be complicated (or how it is fixed may be incompatible with the rest of jsbin and not get merged). However all paste services currently have to deal with that

**Comment by daleharvey** [comment]
@remy Hey, thanks for the awesome work on jsbin, I am looking around at making it easier for pouchdb users to post snippets and seems like jsbin is a really good fit

I was just wondering is it possible to have users open a template bin, basically I would like users to open http://jsbin.com/sosafijaru/edit?js,console but not have to clone the bin in order to share it, if it could be at some stable / vanity url that would also be ideal. 

Also would it be possible to add PouchDB (latest) to the list of libraries?

**Comment by nickcolley** [comment]
Agree that the current 'paste' services we recommend are not that easy to use so I'd really love if we could work with jsbin to make it easier for people to share PouchDB snippets etc, I think if it can work with the core adapters it makes sense.

@remy Dale has mentioned support for IDB now, do you know if WebSQL is functional too? Thanks :+1:

**Comment by daleharvey** [comment]
@nick-thompson yup webSQL works too http://jsbin.com/sosafijaru/edit?js,console

**Comment by nolanlawson** [comment]
I like the idea of a JSBin template, since it's such a well-known service. In general, though, I think just allowing our users to give us reproducible code snippets in whatever format they want is the best approach. (Otherwise they're unlikely to make the effort to learn a new system.)

E.g. people will just often send me their production sites, which is fine as long as I can reproduce the issue. It's a bit annoying to trim it down, and most of the time it turns out to be an error on their end, but it's better than nothing. :)

**Comment by daleharvey** [comment]
Yup I mean people can submit using whatever way they want, I just want to make sure there is a super convenient way that we can point people to

**Comment by nickcolley** [comment]
Other thing to consider is that we could use jsbin for the examples inline potentially too.

http://jsbin.com/help/how-can-i-embed-jsbin

**Comment by remy** [comment]
Hey, so, chiming in.

Regarding a template, what you've got is a good starting point, but there's definitely value in having the URL linked to your own account - that way you can update the template yourself.

For some context before I move on to your other points:

- Being logged in, you can create a bin, and you're given a url. If you share that url without a snapshot number, it'll load the *latest* bin. This is useful for making sure your user is directed to the latest version all the time. 
- If you share a snapshot, this will remain locked in the state it was in the snapshot, i.e. very good for finished demos that you're likely to want to freeze.
- I can't remember if the panels are saved to the bin's preferences or the user's prefs (i.e. if you don't add `?js,console` does it open the panels *you* left open when you saved the bin (certainly I remember coding something like this, but I suspect it was under an alpha flag). I can see this being useful to you, in that you'd want to direct users to the JS + console panels by default.
- Data when in the editor view, is stored on `null.jsbin.com` - but when it's on the full output (i.e. without the jsbin editor), then the data will be stored on `output.jsbin.com` - I suspect this won't be a problem since it's demo code, but it's worth being aware of. If you have a vanity url, then the data will be stored against that origin.
- Embedding is free to all users, but https embedding requires a pro account. Also, when a bin is embedded, the user is able to change the code in real-time in the embed (i.e. to experiment) so it's not a read-only version of the code (this is an intentional feature) - obviously this doesn't save over your original bin.
- It may be of interest, but @rodneyrehm was able to automate the creating of bins for his a11y.js project using the API feature on jsbin (note that this is also a pro feature that required enabling of the [experiments](http://jsbin.com/help/experimental-features#api) - he also wrote a [node module](https://github.com/rodneyrehm/jsbin-sync) to manage some of this, but I don't know the details).
- There's also an API in progress that allows embedded demos to inject different code into the same embedded bin, a bit like this [demo video](https://www.youtube.com/watch?v=sZs7Xlh0iMw).

Regarding this comment:

> basically I would like users to open http://jsbin.com/...?js,console but not have to clone the bin in order to share it

...when you, Dale, own the bin, *as soon as* the user starts typing, it will clone a copy to their account (or create an anonymous clone), so that they're able to keep their changes. This is a normal feature of jsbin. It is possible to send them to a URL that doesn't clone, but this it's fully featured as yet and kind of goes against jsbin's normal behaviour. i.e. if the user is at all familiar with jsbin, they wouldn't expect their changes to be discarded.

I'm sure there's other bits and questions, etc, but I thought that this might be useful.

**Comment by nolanlawson** [comment]
As for adding PouchDB to the list of libraries: https://github.com/jsbin/jsbin/pull/2662

**Comment by rodneyrehm** [comment]
> Other thing to consider is that we could use jsbin for the examples inline potentially too.

As Remy said, I've automated that for [ally.js](http://allyjs.io). Using [jsbin-sync](https://github.com/rodneyrehm/jsbin-sync), all of the example documents are tracked in the project's repository and simply  [published](https://github.com/medialize/ally.js/blob/master/package.json#L60) to jsbin.com as part of deploying the website. E.g. [focusable.example.html](https://github.com/medialize/ally.js/blob/master/docs/api/query/focusable.example.html) and [jsbin.com/wotudik/](https://jsbin.com/wotudik/). This part of the process is generic and easily applicable to PouchDB.

During the build of the website the [cheerio](http://cheeriojs.github.io/cheerio/) based [metalsmith](http://www.metalsmith.io/) plugin [inject-examples.js](https://github.com/medialize/ally.js/blob/master/build/metalsmith/plugins/inject-examples.js) mutates the simple list of example links to proper jsbin embed codes (e.g. [source](https://github.com/medialize/ally.js/blob/master/docs/api/query/focusable.md#examples) and [output](http://allyjs.io/api/query/focusable.html#Examples)). This part of the process is a quick-n-dirty hack that likely only fits the ally.js project.

@jzaefferer has expressed similar goals for the jQueryUI docs. They need a greater control over different versions (versions of jQueryUI, not versions of the bins) of examples published to jsbin.com, for which we were thinking about (ab)using jsbin's tags: rodneyrehm/jsbin-sync#1. Even if you don't need to support docs/examples for multiple versions of PouchDB, solving that issue should simplify things for you.

It would be lovely if we could all work together to find a common solution for embedding examples in our docs.

> I was just wondering is it possible to have users open a template bin, basically I would like users to open http://jsbin.com/sosafijaru/edit?js,console but not have to clone the bin in order to share it

Again I wanted the same thing for ally.js and it turned out that jsbin already did that for me. Considering any bin already is a template for everyone but the author/owner. I just opened the ally.js demo https://jsbin.com/wotudik/edit?html,css,js,output and edited the background color, the browser window's URL automatically changed to https://jsbin.com/qamofijozo/edit?html,css,js,output - ready to copy'n'paste. I don't think it gets any easier than that.

**Comment by daleharvey** [comment]
@remy @rodneyrehm Thanks so much that is super useful, will focus on getting setup for pasting right now but looks very promising for more featured tutorials etc.

I dont think this is possible right now as far as I can tell, so would consider this a feature request but I would love to be able to specify the id / url of the bins, so like

pouchdb.jsbin.com/starter-template
pouchdb.jsbin.com/filter-example

Even if it was only available via the API

Setting up a pro account now, thanks :)

**Comment by rodneyrehm** [comment]
> I dont think this is possible right now as far as I can tell, so would consider this a feature request but I would love to be able to specify the id / url of the bins, so like […]

being able to specify the url slug - likely to be limited to the vanity domain - would probably be an even simpler approach to solving rodneyrehm/jsbin-sync#1

Note that vanity URLs seem to be output-only: https://rodneyrehm.jsbin.com/wotudik/. As soon as you want to show the editor, you get redirected https://rodneyrehm.jsbin.com/wotudik/edit/

**Comment by boucher** [comment]
Hey everyone. Don't want to derail your conversation, but if there's anything we can do to make Tonic easier for you to use when sharing pouchdb code, we'd love to hear it. Obviously we work a bit differently than things like jsbin: code is running in node.js, not the browser. That has some benefits and probably some downsides here.

**Comment by daleharvey** [comment]
Thanks @boucher, for this I was mostly worrying about reproducing and sharing bugs in browser environments, but we definitely want to have good support for tonic as well.

As for jsbin I have ordered a pro account so we can get pouchdb.jsbin.com, the custom slugs are an open feature and there seems to be a workaround @ https://github.com/jsbin/jsbin/issues/2057

Will get a 'starter template' up and link to it when available

**Comment by daleharvey** [comment]
Noting https://emberjs.jsbin.com/?js,console that @nickcolley pointed out to me today, this setup is pretty much perfect

**Comment by daleharvey** [comment]
So a fancy jsbin isnt going to do much for us, the pro account doesnt come as the emberjs stuff is like, right now paste.pouchdb.com is working fine for me, may try improving the UI somewhat but no need to track, cheers
