### ISSUE TITLE
intercepting bulkdocs in a plugin breaks indexes

### ISSUE THREAD

**Issue by AgDude** [pouchdb/pouchdb#4775]
I have created a basic test on JSBIN using the example code from the [api docs](http://pouchdb.com/api.html#plugins):
http://jsbin.com/pagebi/1/edit?js,output

You can see this test passes if you comment the line where the plugin is attached. Open developer tools to see that "callback" is undefined.

**Comment by AgDude** [comment]
This also applies to the more general case of queries:
http://jsbin.com/pagebi/5/edit?js,output

**Comment by AgDude** [comment]
I have traced this down a bit more, and have a workaround. This results from a call at `mapreduce/index.js` in `saveKeyValues`, where no callback is provided. I am not entirely clear on why this raises an exception only when there is an interceptor in place, but I can work around it by passing `noop` if there isn't a callback.

Consider this issue then to better handle an undefined callback.

Here is an updated jsbin with the workaround:
http://jsbin.com/pagebi/6/edit?js,output

**Comment by nolanlawson** [comment]
Yeah, unfortunately the adapter "spec" is undefined right now, but in general the adapter functions have to be very fault-tolerant and handle a wide variety of inputs (e.g. no callbacks, which in the case of `saveKeyValues` is due to using the promise form of the API).

In general, if you are trying to override built-in functions in PouchDB with your own versions, you will need to ensure that they are as fault-tolerant as the originals. Thanks for the steps to reproduce, but I'm not really sure what we could do here except better define the contract of plugins (which BTW were not really designed to be able to override built-ins like `bulkDocs`s, so this is the first I've seen of something trying to do that).

Out of curiosity, why is your plugin overriding `bulkDocs`?

**Comment by AgDude** [comment]
I want to automatically strip angularjs private properties from the object. For example `$$hashkey`.

**Comment by nolanlawson** [comment]
@AgDude Ah okay, in that case you should maybe look into [transform-pouch](https://github.com/nolanlawson/transform-pouch). It's designed to do exactly what you want (modify documents before insertion in the database) - e.g. [crypto-pouch](https://github.com/calvinmetcalf/crypto-pouch) uses it under the hood to encrypt and decrypt documents. Hope that helps! :)

**Comment by AgDude** [comment]
Thanks for the link. That is exactly what I wanted! I didn't know it existed.

**Comment by nolanlawson** [comment]
Awesome! :) Glad that helps.
