### ISSUE TITLE
SecurityError: DOM Exception 18 with Chrome on iOS

### ISSUE THREAD

**Issue by dsmeltz** [pouchdb/pouchdb#4876]
I know this has been reported and fixed before.  It has reared it's ugly head again with either the latest version for Chrome on iOS  or iOS itself.

The issue happens after you call "new PouchDB" and then try to call the ".info" method for the database.  I tried lowering the initial database size, but that didn't seem to have any effect.

We were using Pouch 3.4.0 and didn't receive any error, but it was silently failing.  After upgrading to 5.2.1, the error was able to be caught.  The received error is seen in the screen grab below.

Versions being used:
PouchDB: 3.4.0 and 5.2.1
iOS: 9.2.1
iOS device: iPad Air 2
Chrome for iOS: 48.0.2564.104

![smallpoucherror](https://cloud.githubusercontent.com/assets/1830600/12918644/0496ed8a-cf0e-11e5-865c-eda28421b167.PNG)

**Comment by nickcolley** [comment]
Thanks a lot for the report!

We're not currently testing 9.x in Travis, https://github.com/pouchdb/pouchdb/blob/master/.travis.yml#L82, we should look at trying to get this tested.

Sounds like you're using Safari for iOS?

There's a WKWebView issue with a similar error https://gist.github.com/nolanlawson/08eb857c6b17a30c1b26#uiwebview

Which can be worked around with https://github.com/nolanlawson/fruitdown

**Comment by dsmeltz** [comment]
We're using Chrome not Safari, if it makes a difference.

**Comment by nickcolley** [comment]
@dsmeltz

I think here you'll have to use Fruitdown to support that use case since IndexedDB is flakey on WKWebView.

I doubt it's worth raising a bug report with Chrome to roll back to the UIWebView since "The crash rate was reduced by 70% and Javascript execution is now dramatically faster!"

If you'd like to contribute you could add this error message to the common errors page to help future people.

**Comment by dsmeltz** [comment]
More information:  I tried the latest FireFox and it has the same issue.  I wonder if it uses WKWebView also?

**Comment by nolanlawson** [comment]
I saw [this issue on the WebKit bugtracker](https://bugs.webkit.org/show_bug.cgi?id=137760). Undoubtedly it is because of Chrome switching to WKWebView.

Unfortunately there is not much we can do. The current workaround is to use the FruitDOWN adapter in cases where neither WebSQL nor (bug-free) IndexedDB are available, such as WKWebView.

**Comment by nolanlawson** [comment]
Found the blog post announcing the WKWebView switch: http://blog.chromium.org/2016/01/a-faster-more-stable-chrome-on-ios.html

**Comment by brianb-cp** [comment]
Why is this closed? PouchDB does not work on Chrome or Firefox (80% of market) when on iOS (75% of mobile). Are you guys abandoning the browser space and only focusing on apps?

**Comment by daleharvey** [comment]
a quick note that iOS is very far from 75% of the market, but we do have an open bug for this already - https://github.com/pouchdb/pouchdb/issues/2875. 

It is however hard for us to do anything about this, Apple doesnt provide any reasonable way for web applications to store data as it currently stands, Nolan has done a great job filing bugs, making steps to reproduce and keeping track of the fixes (https://gist.github.com/nolanlawson/08eb857c6b17a30c1b26).

I am working on a new indexeddb adapter that 'might' work in safari but its likely quite far away, there is currently the fruitdown adapter and happy to take suggestions or patches as we very definitely want to support ios based browsers.

**Comment by nolanlawson** [comment]
Also I'll note that it was Firefox and Chrome's decision to go with WKWebView over UIWebView. I talked with them about it on Twitter - basically they were happy to throw away browser storage because the gains from performance and other APIs were more important in their eyes.

There's not much we can do if browsers decide to sabotage their own storage capabilities.
