### ISSUE TITLE
[how-to?] Debounce the replication when localDB changes.

### ISSUE THREAD

**Issue by ronyrun** [pouchdb/pouchdb#4896]
Hello, 

Sometimes users make changes on their localDB and the replication is processing for each change.
The repliction execution is slowing down the User experience on the application (Mobile IONIC).

Is there a way to debounce the replication process with a debounce of 30seconds ?

Thank you, 
Ron

**Comment by daleharvey** [comment]
live replication is designed to work immediately, if you want to debounce changes then I think the most sensible way would be to manually start and stop the replication process when you want it to run, how does that sound?

**Comment by ronyrun** [comment]
Does a replication launch consume a lot of I/O ?
If I do that for every 'debounce relaunch', don't you think it will cost me a lot of I/O ? (I'm on Cloudant)

**Comment by nolanlawson** [comment]
This is a good example IMO of why PouchDB should be used inside of a web worker. Database operations only negatively impact the user experience if they run on the UI thread.

My recommendation is [worker-pouch](https://github.com/nolanlawson/worker-pouch) (using `replicate.to('http://remote')` instead of `replicate.to(new PouchDB('http://remote'))` to ensure the remote database object is also created inside the web worker), or better yet, isolate PouchDB to a web worker and then communicate using normal message-passing with the worker. Alternatively, Dale's suggestion is a good one.

**Comment by ronyrun** [comment]
Thank you for your answer, I'll try the worker-pouch.
Also acordingly to this issue : https://github.com/nolanlawson/worker-pouch/issues/6

We can't ensure the remote database object to be created inside the web worker, if I'm right.

I'll have to go with 
```
var local = new PouchDB('local', {adapter: 'worker'});
var remote = new PouchDB('http://wherever');
local.sync(remote, ...);
```

**Comment by nolanlawson** [comment]
@ronyrun You can ensure that the HTTP-based PouchDB is created inside the web worker:

```js
var local = new PouchDB('local', {adapter: 'worker'});
var remote = 'http://wherever';
local.sync(remote, ...); // implicitly this will create an http-based PouchDB inside the worker
```

Although honestly worker-pouch is just a convenience for folks who don't want to mess with web workers. The best solution is just to run PouchDB entirely inside a web worker.
