### ISSUE TITLE
npm package is too large

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#4907]
We're thinking of switching from PouchDB to some other alternative for the single reason that installing it from npm when we do our deployments is taking waaaaay to much time.

Could we have more modular npm packages? e.g.

```bash
npm install pouchdb-core
npm install pouchdb-http
```

**Comment by nolanlawson** [comment]
Yeah, I've been thinking about this. it's on [my todo list](https://gist.github.com/nolanlawson/7953d9aaebbbe8cb382b).

Basically what we need is to break PouchDB into smaller submodules that can each be independently published to npm, then use something like [lerna](https://www.npmjs.com/package/lerna) to tie them together.

To be honest I would even support adding pouchdb-server, express-pouchdb, pouchdb-collate, and the `extras` API to the project in order to support this (i.e. monorepo), but I'd need a solid gameplan and ask @daleharvey's opinion.

**Comment by nolanlawson** [comment]
BTW lerna is what Babel uses to run its mono-repo. Basically it handles all the pain of `npm link` and doing multiple `npm install`s of modules that rely on each other. I like the concept; it would remove a lot of the hacky bash scripts in pouchdb-server and express-pouchdb.

**Comment by daleharvey** [comment]
Yeh I have always wanted at the least `pouchdb-http` to be installable standalone, I believe its possible as a workaround now to opt out of having leveldb installed but cant find how right now. Having separate packages would be ideal.

I do think we should preserve the `pouchdb` package as it is right now, so users dont need to make a decision of which adapters they need to install and we have a sensible default but allow people more efficient installs if they opt in.

**Comment by nolanlawson** [comment]
Agreed, the `pouchdb` package should be batteries-included. But advanced users should be able to pick-and-choose.

**Comment by daleharvey** [comment]
Dupe - https://github.com/pouchdb/pouchdb/issues/5128
