### ISSUE TITLE
Possible race condition in map/reduce

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4908]
See https://github.com/pouchdb/pouchdb/pull/4900#issuecomment-186359787. We should change the test back to the way it was before https://github.com/pouchdb/pouchdb/commit/0ddeae6b6c44fa12b83c5348df6947e3ce28c28c and try to get the code to pass.

**Comment by garethbowen** [comment]
Sorry I should have commented in the PR.

That test was changed because otherwise the `throw-max-listeners-error` module throws and fails tests. This is because the query function now fires off a one-shot changes request to check that the ddoc cache is up to date. The workaround I used was to register these listeners in serial thus giving the changes request a chance to complete and deregistering the listener before the next listener was registered. As this is a test only module I think the only regression in production would be getting a "too many listeners" warning in the console.

The listener that's registered is to clean up if the db is destroyed. This is really useful for continuous changes feeds which emit a cancel event when the db is destroyed allowing listeners to clean up. However for the one-shot changes feeds will either succeed or fail depending on whether they get in just before or just after the db destroyed event so don't really need to be notified if the db is destroyed.

Would it make sense to only register the [db.destroyed listener](https://github.com/pouchdb/pouchdb/blob/master/src/changes.js#L47) if the changes feed is continuous? If so, making this change will fix the test.

**Comment by nolanlawson** [comment]
Ah okay, that makes sense. The way we typically get around the max listeners error is to increase the number of listeners for the given `db` object. There's an example here: https://github.com/pouchdb/pouchdb/blob/21e1346e11e611f1d312f468a711389038b04287/tests/integration/test.compaction.js#L1528-L1530

So it seems we could fix the test by merely reverting to the old test and then increasing the listeners.

**Comment by nolanlawson** [comment]
0ddeae6 was reverted, so this is no longer relevant. The test is back to the way it was.
