### ISSUE TITLE
get allDocs without design view

### ISSUE THREAD

**Issue by leorsida** [pouchdb/pouchdb#4943]
Hi

im write a query to retrive all record on couchdb with 

`mydb.allDocs({include_docs: true, attachments: true, startkey: '_design\uffff' }).then(function(doc) {
				q.resolve(doc);
			}).catch(function (err) {
				q.reject(err);
			});`

but i get always an empty result (i have 4 records).
is there a solution to retrive all docs without design documents?

**Comment by nolanlawson** [comment]
Your query looks correct to me. I'd check the Network tab to make sure that it's sending the right request to CouchDB and that you really do have 4 documents that are not design docs.

Also a protip: you can use `q.when()` instead of wrapping PouchDB promises yourself; there is a good writeup in this blog post: http://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html

Let me know if that solves your issue! Closing for now; please reopen if necessary.

**Comment by bleuscyther** [comment]
@nolanlawson it does not work with descending.

**Comment by enzoaeneas** [comment]
if I use guids as my _id, it will not work either. I had to use:
`{
        'include_docs': true,
        'endkey': '_design',
        'options.inclusive_end': false
    }`

**Comment by colin-guyon** [comment]
Hi, so the doc here is not correct when talking about filtering out design documents in `allDocs` with `{startkey: '_design0'}` https://pouchdb.com/2014/05/01/secondary-indexes-have-landed-in-pouchdb.html.
I tried what @enzoaeneas suggested and it worked better
