### ISSUE TITLE
node-websql uses _pouchdb_ prefix for databases

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#4966]
This should never have slipped through; not sure how I didn't notice.

It can be fixed as easily as adding `.use_prefix = false` to the websql adapter, when running in Node. It should be a one-line code change.

Normally I'd consider this a breaking change, but if we can get this patch out quickly I'd consider it a patch. The feature only shipped in 5.3.0.

**Comment by daleharvey** [comment]
Why is using the prefix considered a bug?

**Comment by nolanlawson** [comment]
In Node we don't use a prefix, so that it's easier to rimraf as necessary. In the browser we do use it, to avoid conflicting with other IDB/WebSQL libs.

TBH if I could go back in time I'd say we should never have supported prefixes for any adapter (users should just be expected not to let their IDB/WebSQL libs conflict), but now we're in this situation.

**Comment by daleharvey** [comment]
Sounds good to me, I still think its a good idea to prevent conflicting names in the browser, I am regularly using localForage etc in combination with PouchDB, I think others are too and it was something that came up early and was hugely confusing, that fix looks good though, fixed in https://github.com/pouchdb/pouchdb/commit/121a5274f38775c3bcc9e87569fb90f13d5cae52

**Comment by nolanlawson** [comment]
Fair enough; it's not something I'm going to push hard for. It just bugs me in the code that `_prefix `keeps popping up everywhere, but it's not a big deal.
