### ISSUE TITLE
sync not works when i am offline then go online

### ISSUE THREAD

**Issue by do7a15** [pouchdb/pouchdb#4978]
sync not works when i am offline then go online

var opt = { continuous: true };
var sync = PouchDB.sync(mydb, remotedb, opt);
sync.on('change', function (info) {
     console.log("sync");
});

**Comment by do7a15** [comment]
what is the difference between 
1 - var opt = {live: true,  retry: true};
and
2 - var opt = { continuous: true };
???

**Comment by daleharvey** [comment]
`live` and `continuous` mean exactly the same thing, we added live because `continuous` was too hard to spell, they mean that when all the documents have been fetched in a replication the replicator will not complete, but sit and wait for more changes.

`retry` means when the replicator sees failures (like when you are offline), it will not stop trying to replicate but continue to retry fetching documents until it succeeds. 

If you want to start sync offline then have it work when you go online then you need `retry: true`, at this moment you will also need `live: true` since we dont support retrying non live replications, but thats a bug

**Comment by froatsnook** [comment]
> If you want to start sync offline then have it work when you go online then you need retry: true, at this moment you will also need live: true since we dont support retrying non live replications, but thats a bug

@daleharvey Is this still true?  It's still worded like this in the documentation and I didn't find any relevant commits with "retry" in the title.  My system is currently setup to do an initial sync with `live: false` and then start the `live: true` replication (and both have `retry: true`).

**Comment by daleharvey** [comment]
Yup still true, needs some work to work without live: true
