### ISSUE TITLE
Remove UA-sniffed cache-busting entirely

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5020]
I think #5010 demonstrates how dangerous it is to try to guess a browser's cache policy – it can change at anytime. Furthermore, it lulls users into a false sense of control, because the `cache` parameter only affects them in some browsers and not others. And the only real benefit of UA-sniffing is that the URL looks nicer when they inspect in the dev tools (and keep in mind - we're also assuming they use Chrome or Firefox as their dev tool).

So what I'm saying is:

1. Pretty URLs
2. Consistent cache strategy

^ pick 1.

**Comment by nolanlawson** [comment]
I'm happy to discuss this, but I feel pretty strongly that we should remove the UA sniffing altogether.

**Comment by daleharvey** [comment]
> And the only real benefit of UA-sniffing is that the URL looks nicer when they inspect in the dev tools 

We didnt used to have the UA sniffing, and I agree its problematic, however it doesnt just get us pretty urls, the main reason we added the UA sniffing was because the CORS caching is based on the url, so adding `?nonce=` ensured every url is unique and each requests needs a CORS check, without the `nonce` the requests to all shared urls (`_changes` etc) have a cached cors policy so it reduced the number of requests we make by a fairly huge amount if I remember, will need to retest but I think it was a pretty significant performance increase

**Comment by ermouth** [comment]
There is another point. Seems that requests like `http://couch.db/dbname/` (I mean pinging DB root) with _nonce can not be passed correctly through CouchDB native rewrites, at least for 1.6.1.

**Comment by nolanlawson** [comment]
@ermouth That's a good point, but is the solution to just have a site that's broken in IE/Safari but works in Chrome/Firefox? I suppose in some cases that's okay (Electron etc.) but I tend to prefer fixing all browsers if possible.

**Comment by nolanlawson** [comment]
> will need to retest but I think it was a pretty significant performance increase

Forgot about this. I think this is reason enough to keep the UA-sniffed cache-busting in. At the very least we can give a perf boost to Firefox and Chrome. OK!
