### ISSUE TITLE
Filtered replication bug?

### ISSUE THREAD

**Issue by redgeoff** [pouchdb/pouchdb#5026]
Steps to replicate:

1. Make sure you have Admin Party enabled
2. Download https://gist.github.com/redgeoff/2ed9016a9e556fa536a82d63df86a871
3. Visit index.html in a browser
4. Check the `classes_failure` DB in Futon and you'll only see a design doc and [no class doc](https://gist.github.com/redgeoff/2ed9016a9e556fa536a82d63df86a871#file-index-html-L74)

If instead of https://gist.github.com/redgeoff/2ed9016a9e556fa536a82d63df86a871#file-index-html-L52, we use https://gist.github.com/redgeoff/2ed9016a9e556fa536a82d63df86a871#file-index-html-L53 then the code appears to work, but this is essentially disabling the filter. Interestingly enough, as soon as you https://gist.github.com/redgeoff/2ed9016a9e556fa536a82d63df86a871#file-index-html-L53 you can subsequently use https://gist.github.com/redgeoff/2ed9016a9e556fa536a82d63df86a871#file-index-html-L52 and it appears to work, which makes me think there is some "setup" that fails when you initially have the filter enabled.

Am I doing something wrong or is something broken?

Using a view instead of a filter appears to work, but my end goal is really to use a filter with query params (left out of this example to keep things simple).

**Comment by nolanlawson** [comment]
Yeah this definitely looks like a bug. If you could add a test case and ideally even fix it, that would be awesome.

A good starting place would be [this test case](https://github.com/pouchdb/pouchdb/blob/fd880917cfdbdaf7fac60b7f36af00aa5dac4299/tests/integration/test.replication.js#L3872-L3904), which actually looks very similar to the code you posted, so I'm not sure why it's succeeding in one case but failing in the other…

**Comment by willholley** [comment]
I'll test this now but at first reading, the test appears to:

 1. Create a live replication from local to remote using a filter function which only passes when `doc.group === 'Math'`. The filter does not yet exist.
 2. Create a live replication from the remote to the local using the same filter (also does not yet exist)
 3. Create the design document/filter on the remote database.
 4. Create a document with `group: 'Math'` on the local database.
 5. Wait for the remote -> local database to fire a `paused` event.
 6. Test that the remote database contains the document added in (4)

A possible the hole here is the design document containing the filter never replicating to the local database (since the replication filters out design documents).

**Comment by willholley** [comment]
I confirmed that the document replicates if either the filter is changed to allow design documents through or it is manually injected into the local database. However, the `read()` method is firing before the document is replicated, so the test still breaks. I don't think there is a bug here though.

**Comment by redgeoff** [comment]
I just wanted to point out that createDDoc uses a direct connection to
CouchDB to bypass any filtering.

Also, if you remove the filter from the "to" replication then it seems to
work. I think this is a hack though.

**Comment by redgeoff** [comment]
I don't think the filter should have to include design documents as:
1. If you go straight to CouchDB (without PouchDB), you'll see the filter
working properly
2. If you have design docs stored locally then you have to add more logic
to your code to filter them out
Of course, maybe I am misunderstanding how server side filters are supposed
to work with PouchDB.

**Comment by willholley** [comment]
The filter needs to exist on the source side of the replication so, for
bidirectional replication, it will need to exist in the local pouchdb and
the remote Couch. When it doesn't exist in the local pouch the replication
to couchdb will fail and your doc won't be uploaded.
On 18 Apr 2016 3:21 p.m., "Geoff Cox" <notifications@github.com> wrote:

I don't think the filter should have to include design documents as:
1. If you go straight to CouchDB (without PouchDB), you'll see the filter
working properly
2. If you have design docs stored locally then you have to add more logic
to your code to filter them out
Of course, maybe I am misunderstanding how server side filters are supposed
to work with PouchDB.


On Mon, Apr 18, 2016, 07:12 Geoffrey Cox <redgeoff@gmail.com> wrote:

> I just wanted to point out that createDDoc uses a direct connection to
> CouchDB to bypass any filtering.
>
> Also, if you remove the filter from the "to" replication then it seems to
> work. I think this is a hack though.
>
> On Mon, Apr 18, 2016, 01:52 Will Holley <notifications@github.com> wrote:
>
>> I confirmed that the document replicates if either the filter is changed
>> to allow design documents through or it is manually injected into the
local
>> database. However, the read() method is firing before the document is
>> replicated, so the test still breaks. I don't think there is a bug here
>> though.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pouchdb/pouchdb/issues/5026#issuecomment-211278052>
>>
>

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/pouchdb/pouchdb/issues/5026#issuecomment-211401437>

**Comment by redgeoff** [comment]
That makes sense but then wouldn't you need your app to filter out design
docs at a layer above PouchDB? (Assuming that you don't want the design
docs displayed to the user)

**Comment by willholley** [comment]
@redgeoff you shouldn't need to perform filtering in the app layer in most cases. What is it you're trying to achieve?

**Comment by daleharvey** [comment]
Feel free to carry on discussion, but looks like this is not a bug, cheers
