### ISSUE TITLE
Update documentation for the SQLite Plugin

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5063]
Based on https://github.com/pouchdb/pouchdb/issues/5047, there are two changes I'd like to make:

1. mention the `location` key for the SQLite Plugin, which is now required (yay breaking changes with no semver!)
2. mention that you can just use [SQLite Plugin 2](https://github.com/nolanlawson/cordova-plugin-sqlite-2) instead, and that it's our recommended approach because it actually passes our test suite on both iOS and Android.

**Comment by nolanlawson** [comment]
Oh also we will need a new release to fix the `location` issue. It's fixed in master but not in the latest release.

**Comment by schamp** [comment]
I can take this one.  Can you please elaborate on your comment about needing a new release?  Will that affect what I should put in the documentation?

**Comment by nolanlawson** [comment]
That would be awesome! :) About the new release, I was just trying to point out that the `location` fix does not actually work in the current release of PouchDB, but will be fixed in the next one.

But anyway, if you make your change to the docs, we'll just push those doc changes when we do the new release.

**Comment by schamp** [comment]
Sounds good.  Just so I'm clear, passing 'location' works now, and the fix is going to allow the user to also pass 'iosDatabaseLocation' in the constructor arguments?  I ask because I was using this plugin, and  `{ adapter: 'websql', location: 2 } `worked for me, but `{ adapter: 'websql', iosDatabaseLocation: 'default' }` didn't.  But the SQLite Plugin page indicates 'location' is deprecated, and 'iosDatabaseLocation' is preferred.

I'm looking at the option docs as described here:  https://github.com/pouchdb/pouchdb/blob/9c25a2351c51507e75b5a785a1fcb2c6dad66c33/docs/_includes/api/create_database.html

But I don't see iosDatabaseLocation included there.

Also, I see 'location' included in the example at https://github.com/nolanlawson/cordova-plugin-sqlite-2/blob/master/perf/www/index.js, but I don't see that the location option is being actually dealt with when creating the DB itself:  https://github.com/nolanlawson/cordova-plugin-sqlite-2/blob/master/src/javascript/index.js

So am I missing something, or will the location param be ignored as it appears with Cordova SQLite Plugin 2?

I just want to make sure I am clear about that in the docs update.

**Comment by nolanlawson** [comment]
Ah you're right, I messed up. I just double-checked, and the current release does indeed support `location`, as well as `createFromLocation` and `androidDatabaseImplementation`. However, it doesn't support any other options.

In the next version of PouchDB, any options you pass to the PouchDB constructor will be passed verbatim to the SQLite Plugin. This way we don't need to make a change every time the SQLite Plugin makes a change.

SQLite Plugin 2 has no `location` option. I made a point of not including any special options like that in order to keep things simple. :)

**Comment by schamp** [comment]
No worries.  You might add a note in the SQLite Plugin 2 docs about why no location is necessary -- folks coming from v1 might be confused / concerned about it.

I'll note how options will be passed through verbatim, and give some examples, that should cover it, I think?

**Comment by schamp** [comment]
I'll also make a note in the docs/_includes/api/create_database.html indicating that any options given will be passed through to the plugin.

**Comment by nolanlawson** [comment]
8e50e326cb0ec8f51435ad0fbf36e1fb99905c27
