### ISSUE TITLE
Native SQLite Adapter

### ISSUE THREAD

**Issue by gooodguy** [pouchdb/pouchdb#5068]
Hi,

thank you very much for incredible PouchDB. It is really a high quality open source project. This is what I like most about the project: 1. the flexibility that comes with the adapters 2. the possibility to switch between remote and local databases 3. the documentation.

My questions is: I want to create a mobile app that has a webview. I am considering to use PouchDB (+ SQLite Adapter) to exchange data between the native container and the webview. I want to insert data directly into the SQLite Database in a way that it is compliant with PouchDB. In other words I want to create a native SQLite Adapter. How to do that?

I am also open for alternative approaches/ideas.

**Comment by nolanlawson** [comment]
Thanks for the kind words! :)

Unfortunately it's not possible to directly use the underlying database while simultaneously using the PouchDB API. You must exclusively use the PouchDB API in that case.

However, there is in fact an adapter for SQLite on Cordova (I recommend [SQLite Plugin 2](https://github.com/nolanlawson/cordova-plugin-sqlite-2) since it is faster and less buggy than the original), but you cannot directly access the PouchDB database via SQL because PouchDB creates its own revision semantics on top of the underlying database to enable syncing (think of it as a database-on-a-database). Hope that explanation helps!

**Comment by RobertoMalatesta** [comment]
Hi @nolanlawson,
I just stepped in to PouchDB and I'd like to pose a question that can be seen as naive, so excuse myself in advance:

Let's say I have a SQLlite-based web service (implemented in Python with securities and checks) where once authenticated I can execute any kind of query by sending a (encrypted+tokenized) JSON request.

I'd like to use PouchDB on the front and (a)syncronously keep a server store of the PouchDB API, what's the best way to do so?

Thanks for all the good bytes.

--RM

**Comment by nolanlawson** [comment]
Hi, this is actually a question we get a lot, and the unfortunate answer is that PouchDB cannot sync with existing databases; instead you need to use PouchDB _on top of_ that database (as a mere adapter) and communicate with it using the PouchDB API. This is due to the fact that PouchDB implements revision semantics _on top of_ databases, which is the source of the magic sync sauce. :) More details here: https://pouchdb.com/faq.html#sync_non_couchdb

**Comment by RobertoMalatesta** [comment]
Thank you for the quick and clear answer.
I'll have a look at the API to see if it can fit my needs.

-- RM
