### ISSUE TITLE
RangeError: Maximum call stack size exceeded(…)

### ISSUE THREAD

**Issue by JoellyR** [pouchdb/pouchdb#5101]
Im getting the following error:

`RangeError: Maximum call stack size exceeded(…)`

This seems to be happening while trying to use transform-pouch to add encryption using the following code:

```
patientDb.transform({
      
    incoming: function (doc) {

        Object.keys(doc).forEach(function (field) {
        if (field !== '_id' && field !== '_rev') {
            doc[field] = encrypt(doc[field].toString());
          }
        });
        return doc;
      },
      outgoing: function (doc) {

        Object.keys(doc).forEach(function (field) {
          if (field !== '_id' && field !== '_rev') {
            doc[field] = decrypt(doc[field]);
          }
        });
          
        return doc;
      }
    });
    function encrypt(text){
      var encrypted = CryptoJS.AES.encrypt(text, 'secret key 123');
      return encrypted;
    };
    function decrypt(text){
      var bytes  = CryptoJS.AES.decrypt(text, 'secret key 123');
      var decryptedData = bytes.toString(CryptoJS.enc.Utf8);
      return decryptedData;
    };
```
There error seems to be caught on line 2861 in pouchdb-5.3.1.js : 
```
    var promise = new PouchPromise(function (fulfill, reject) {
      var resp;
      try {
        var callback = once(function (err, mesg) {
          if (err) {
            reject(err);
          } else {
            fulfill(mesg);
          }
        });
        // create a callback for this invocation
        // apply the function in the orig context
        args.push(callback);
        resp = func.apply(self, args);
        if (resp && typeof resp.then === 'function') {
          fulfill(resp);
        }
      } catch (e) {
**        reject(e);**
      }
    });
```

**Comment by willholley** [comment]
are you able to expose the application exhibiting the behaviour? I can't see anything obvious in the code that would lead to this on its own but it suggests some kind of infinite recursion.

**Comment by JoellyR** [comment]
> are you able to expose the application exhibiting the behaviour? I can't see anything obvious in the code that would lead to this on its own but it suggests some kind of infinite recursion.

Sorry but the app is a P.O.C for my workplace and there are strict rules about exposing work to outside sources... though i will try to create an example app to replicate the issues, and i may use a remote db such as couch but it is local so you may have to make changes to that. Would that be okay?

**Comment by JoellyR** [comment]
>  are you able to expose the application exhibiting the behaviour? I can't see anything obvious in the code that would lead to this on its own but it suggests some kind of infinite recursion.

Here is a simplified ionic app displaying the same issues that i was facing: 

[https://github.com/JoellyR/PouchDbMaxRange](url)

**Comment by nolanlawson** [comment]
What device were you running this on? Stack overflow errors will differ based on the device and its available memory.

**Comment by JoellyR** [comment]
The error seems to occur on an iOS device and also when using `ionic serve` to run the project on the browser

**Comment by nolanlawson** [comment]
I'm sorry for the late reply. I managed to reproduce with your demo app (using both the iOS Simulator and dekstop Chrome) and was able to deduce that this was a problem with the `encrypt()` function being called inside of the `incoming` method.

In your app you're encrypting the `name` field of the document using [this function](https://github.com/JoellyR/PouchDbMaxRange/blob/1086031e4905753420856d809f0903ba8a511eaa/testapp/www/js/app.js#L51-L54). This ends up creating a very complex object that probably has circular references inside of it; it looks like this:

![screenshot 2016-05-23 20 29 58](https://cloud.githubusercontent.com/assets/283842/15491458/60c91132-2125-11e6-9c26-1b6cd46819c1.png)

Whatever you store in PouchDB needs to be a non-complex object without recursion – a good rule of thumb is that if you can call `JSON.parse(JSON.stringify(object))` and you get the same object back, then it's OK to store in PouchDB.

Since this is neither a bug in PouchDB nor a bug in pouchdb-transform AFAICT I'll close the issue. Hope that helps!
