### ISSUE TITLE
Pouch DB 4.0.2 not opening DB with Cordova SQLITE on Android

### ISSUE THREAD

**Issue by gaurav-chandra** [pouchdb/pouchdb#5124]
I have the following code:
```
ionic.Platform.ready(function(){
            // Creates the database or opens if it already exists
            _db = new PouchDB('mhh',{adapter: 'websql'});
            _db.info().then(function (d) {
                console.log('DB opened');
                console.dir(d);
                $rootScope.$broadcast('db:ready');
            }, function (err) {
                console.log('DB ERROR');
                console.dir(err);
            });
        });
```

And I am using cordova-android 5.1 and cordova-sqlite-storage 1.4.0.

When I run the app, the DB is never opened. But when I shift the adapter to "idb", DB is opened and running smoothly.

What could be the reason? I need sqlite to store lot of data.

**Comment by nolanlawson** [comment]
Is this on Android or iOS? Note that we only recommend the SQLite Plugin for iOS - on Android, it's almost always better to use IndexedDB.

The SQLite Plugin added a breaking change recently that requires you to add `{location: 'default'}` to the PouchDB constructor in order for it to work. That is probably the error you're running into, although I'm not sure since you didn't post an error message.

Another thing to note is that there is now the [SQLite Plugin 2](https://github.com/nolanlawson/cordova-plugin-sqlite-2) I wrote, which has better support for PouchDB due to not introducing breaking changes, and is also faster. Try using that, and if it doesn't solve your problem, let me know!

If not, here are some guides that may help you out:

- http://gonehybrid.com/how-to-use-pouchdb-sqlite-for-local-storage-in-ionic-2/
- http://gonehybrid.com/how-to-use-pouchdb-sqlite-for-local-storage-in-your-ionic-app/
- https://github.com/nolanlawson/pouchdb-ionic

**Comment by gaurav-chandra** [comment]
It is for Android as mentioned in the issue text and title. And I am using the second link as guide. (http://gonehybrid.com/how-to-use-pouchdb-sqlite-for-local-storage-in-your-ionic-app/)

The problem is that I need to use sqlite to store lot of data. AFAIK there is a limit in indexdb.

I will try with location param.

**Comment by gaurav-chandra** [comment]
Adding {location: 'default'} solved the problem. Thanks a ton.

**Comment by nolanlawson** [comment]
There is no limit in IndexedDB on Android. Although data does sometimes fall out of the cache, since it's not durable storage, so perhaps SQLite is the best bet in your case.
