### ISSUE TITLE
Coverage testing broken

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#5151]
```$ npm run build-as-modular-es5 && COVERAGE=1 npm test```

gives me 
```
Error: Cannot find module '../../lib/replicate/generateReplicationId'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
```

**Comment by daleharvey** [comment]
This is working in CI, so not entirely broken, but I cant get it to work, we should get this to a `npm run test-coverage`

**Comment by nolanlawson** [comment]
The `build-as-modular-es5` will hopefully go away with the monorepo. It was kind of a nasty hack anyway.

I believe the reason it's failing in your case is because it's re-running `npm run build` (or maybe `npm run build-node`) but only when not in Travis, probably due to [build-node.sh](https://github.com/pouchdb/pouchdb/blob/57664a52621518530977d08039391d58ef1fc39a/bin/build-node.sh). If you run with `TRAVIS=1` it will probably work.

**Comment by nolanlawson** [comment]
https://github.com/pouchdb/pouchdb/pull/5152
