### ISSUE TITLE
Store HTML

### ISSUE THREAD

**Issue by injectless** [pouchdb/pouchdb#5159]
I'm looking for a DB storage for an app built on NW.js or Electron, and PounchDB seems to be suitable.

Long story short: I want to make something like Sublime Text (I don't know exactly how it works, so I will make a guess)
  · Creating a new TAB, all content inside is store in localStorage/IndexedDB/...
  · When the file needs to be saved, it stores the content in localStorage and then create the file.
  · If the file already exists, the localStorage content overwrites it.

 You might wondering why I'm not using files directly, and it's because the first request: We don't know if the user will save the file, but we don't want to lose all the content if the app is closed.

 Searching the web, I find that is bad practice to pass HTML content (is for WYSIWYG editor) through JSON, but I can't think of other solution.. I'd have to use encodeURI and decode when retrieve the data to the #editor or the file saved.

 So..
 How would you do a «Notepad - Sublime Text» editor using PounchDB, or NeDB, or LimvoDB using Electron/NW.js engine?

 I'm using:
 · Electron
 · Angular
 · I don't know yet what DB should I choose.

Thank you!

PD: I saw the sync function and it blew my mind away.
       Is it possible to store .HTML files in PounchDB and then synchronize it with CouchDB?

**Comment by nolanlawson** [comment]
You can store .html files as either plain text or as attachments; it really depends on how large you expect the files to be, but in the case of HTML my guess is that plaintext would be fine.

Your plan sounds fine; just store a JSON object like

```js
{
  _id: 'myid'
  html: '<html>yolo</html>'
}
```

And that should work fine. :)

Closing since this sounds more like a question rather than an issue; you might try stackoverflow/slack/mailing list if you'd like more general feedback on your idea, but it sounds good to me.
