### ISSUE TITLE
`adapter` vs. `db` option

### ISSUE THREAD

**Issue by colinskow** [pouchdb/pouchdb#5163]
To me it has always been confusing to have to use `{db: memdown}` on node vs. `{adapter: 'websql'}` in the browser. Can we move everything to the `adapter` option which makes the most sense?

**Comment by nolanlawson** [comment]
I agree it's confusing. Unfortunately it's a bit difficult to separate those two, because what's happening is that `adapter: 'leveldb'` actually refers to the adapter (LevelDOWN) layer, whereas `db` is the *DOWN implementation used under the hood (MemDOWN, LevelDOWN, LocalstorageDOWN, etc.).

Luckily in the monorepo rewrite (#5137) this will become a separate module called `pouchdb-adapter-memory` and `pouchdb-adapter-leveldb` and the whole adapter/db thing will become an implementation detail. Users will deal only with `adapter` and no longer with `db`. It's there internally, but just not exposed.

Closing, please take a look at the monorepo work and let me know what you think. :)
