### ISSUE TITLE
Cannot handle 401 error during live replication

### ISSUE THREAD

**Issue by sbroadhead** [pouchdb/pouchdb#5172]
I would like any exceptional errors that happen during PouchDB<->CouchDB replication to notify my app to log the user out (since the problem is likely to be caused by stale login data or expired CouchDB credentials). This includes attempting to access a non-existent database, or 401 errors indicating incorrect credentials. I can use the `paused` event from the replicator to see errors that happen during the replication process, but there doesn't seem to be a way to handle 401 Unauthorized errors that happen during replication. Try as I might, they always get reported as unhandled promise exceptions.

From the cursory glance at the source, it seems likely that the change handler's error events do not get propagated to the replication handler's listeners, and that the 401 error is happening from within the changes feed.

Is this a bug/oversight, or am I missing an event that I can handle?

**Comment by nolanlawson** [comment]
It's undoubtedly an error if those exceptions don't bubble up, yes. Although it's kind of unclear what should happen in the case of `retry` replication (I'll assume you're using `retry`), because in principle PouchDB is supposed to retry on any kind of error, but in the case of 40x's it may make more sense to just throw the error and let the user handle it.

**Comment by axul** [comment]
I'm having the same issue while usign pouchdb <--> sailsjs (JWT auth)<-> couchdb.
My frontend gets the 401 unauthorized from couchdb if I'm not signed in (normal behavior) but I'm not being able to handle it.

**Comment by nolanlawson** [comment]
Unfortunately right now the solution is to use something other than `retry` replication to ensure the user is authorized, then do `retry` replication after that.

**Comment by axul** [comment]
Could you be a little more specific for a newb here? :( my code:

         var replicateOptions = {
            live: true,
            retry: true,
            auto_compaction: true,
            ajax:{
              headers: {
                'Authorization': 'JWT ' + $LocalStorage.get('token')
              },
              withCredentials: false
            },
          };
          
          this.syncHandler = this.db.sync(remoteCouch, replicateOptions);
          this.syncHandler
          .on('error', function(err){
            console.log(err);
          })
          .on('denied', function(err){
            console.log(err);
          })
          .on('paused', function(err){
            console.log(err);
          })
          .on('complete', function(err){
            console.log('complete');
            console.log(err);
          });

         var changesOptions = { since: 'now', live: true};

          this.db.changes(changesOptions).on('change', function(){
            console.log('hi');
          });

I'm not 100% clear on the sync event handler, when sync is working, i get `paused` triggered constantly, if y try to sync without credentials, then `complete` is triggered and I get the `401`. but I don't think that is why `complete` is for.

Sorry, maybe I'm asking dumb questions.

**Comment by mkazlauskas** [comment]
Hey, I'm into the same issue.

I think completing on 40x is fine. However, we need better documentation of events. Personally I'm confused with `error`, `denied` and `completed`. Gettting 401 on `completed` is fine, but it makes me wonder why not `denied` or `error`. Specifying cases like that would allow users to implement proper handling and it won't be considered a bug.

**Comment by nolanlawson** [comment]
Hm yeah, my understanding is that `denied` would be called for any 40x errors. If not, that's a bug.

**Comment by axul** [comment]
Also, when the `sync`starts, It would be nice to edit the extra ajax headers in each cycle. For example: say I would like to update the credentials when syncing, or update if expired.

**Comment by mkazlauskas** [comment]
@axul that's being discussed [here](https://github.com/pouchdb/pouchdb/issues/5322)

**Comment by gillez** [comment]
Hi, I'm having a similar issue as discussed in this thread, except that I'm not even seeing the completed event.  I've got live and retry set to true.  When the credentials are all fine, then syncing is good.  However, if the credentials are cleared (can happen if the user logs off in a different browser) then I can see 401 errors in the console.  However, these do not get propagated and the sync continues to repeat.  I would like to catch the 401 so that I can return to the log in screen.

My sync function is as follows:

     function sync(remoteDatabase) {
        syncHandle = database.sync(remoteDatabase, {
          live: true, retry: true
        }).on('denied', function (err) {
          // a document failed to replicate (e.g. due to permissions)
          console.log("SYNC DENIED!", err);
        }).on('error', function (err) {
          // handle error
          console.log("SYNC ERROR!", err);
        }).on('paused', function (err) {
          // replication paused (e.g. replication up to date, user went offline)
          console.log("PouchDB Sync PAUSED => ", err);
        }).on('change', function (info) {
          // handle change
          console.log("PouchDB Sync CHANGED => ", info);
        }).on('active', function (info) {
          // replicate resumed (e.g. new changes replicating, user went back online)
          console.log("PouchDB Sync ACTIVE => ", info);
        }).on('complete', function (info) {
          // handle complete
          console.log("PouchDB Sync COMPLETE => ", info);
        });
      }

If I log off in a different browser, I get the following message in the console:

Failed to load resource: the server responded with a status of 401 (Unauthorised)

However, none of the above events are fired (not even paused, which was being received when it was syncing).

Can anyone please help with detecting the 401?

Thanks,
Giles

**Comment by coderroggie** [comment]
I'm having the same issue as @gillez on version 5.4.4.

**Comment by gillez** [comment]
Can anyone help with this?  I'm using v5.0.0, but @coderoggie confirms the same issue with v5.4.4 (which I'm not using at the moment because of #5379).

**Comment by anowak** [comment]
After spending some time trying to fix this, I think that `denied` is not the correct event to emit here. What we experience here is an unrecoverable error: failing to fetch a checkpoint on a remote database.

The documentation says that `denied` event is emitted when 'a document failed to replicate due to validation or authorization errors' and looking at how it is handled (for instance, it does not effect in rejecting the returned promise), my impression is that its purpose is to signal 'business errors' (as opposed to failures) stemming from unsuccessful server-side validation.

Per documentation, `complete` should be triggered for live replication only if it's cancelled, so emitting this event and wrapping the authorization errors is also wrong way to go. So I propose to emit `error` if authorization error occurs on replication start.

**Comment by anowak** [comment]
I submitted #5421 as a proposed solution to this.

**Comment by dharders** [comment]
@axul

`sync()` currently doesn't emit errors on the `paused` event, even though **it says it does in the docs**. See open issue #4592

Have you tried `replicate.to()` and `replicate.from()` together instead, as currently they're more reliable ?

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/0e14d2213cebe5798c0e34d5faab21b815cc6427

**Comment by axul** [comment]
@dharders thanks! yeah I used replicate and I got errors on pause

**Comment by gillez** [comment]
Thanks for fixing this guys.  I haven't tried it yet but will give it a go asap.
