### ISSUE TITLE
React Native (iOS). Cannot save the image attachment: Can't find variable: FileReaderSync

### ISSUE THREAD

**Issue by andreip-svitla-sge** [pouchdb/pouchdb#5179]
I am trying to save the image from a device camera to a PouchDB. Camera plugin returns me an image path in format "file://". I tried to use it either directly or by fetching its binary data into a Blob object and saving it as an attachment.

It returns ReferenceError: Can't find variable: FileReaderSync error all the time. 

The only way to save the attachment is use a base64 encoding. But API docs say that the recommended way is a saving attachment as Blob. My images are 2Mb in size and so base64 works slow. 

Does anyone knows how to store images as Blobs in  iOS / React Native.

Thanks

**Comment by nolanlawson** [comment]
The error is that ReactNative does not have either `FileReader` or `FileReaderSync`. You'll need some way to polyfill this for ReactNative, or alternatively to use a Node-based version rather than a browser-based version.

I'll note that PouchDB does not have official support for React Native, although there are lots of attempted solutions floating around out there (including some lazy stuff I wrote).

**Comment by nolanlawson** [comment]
Closing because this issue should be fixed in an external third-party plugin for React Native, not within PouchDB itself. We have no way to fix this within the core code. Assuming you are using https://github.com/stockulus/pouchdb-asyncstorage-down, the fix would be to add a FileReader polyfill over there.
