### ISSUE TITLE
Upgrading from pre-release - db location help

### ISSUE THREAD

**Issue by chrisschaub** [pouchdb/pouchdb#5185]
Hi. I have an app using pouch db over websql ...

var pDB = new PouchDB('myDb', {adapter: 'websql'});

The pouchdb version is 3.5.1-prerelease, and the sqlite version is

io.litehelpers.cordova.sqlite, version 0.7.7

Can you clarify where the DB location was based on my declaration? Is it in Documents or Library... I just want to push an upgrade to my app with latest pouchdb and sqllite-2 for cordova, but want the db's to be in same location. I've looked at the doc, but not clear to me. Thanks!

**Comment by nolanlawson** [comment]
The location is decided by the SQLite Plugin. They have actually changed their location several times over recent releases, so you'll probably want to look at [their README](https://github.com/litehelpers/Cordova-sqlite-storage) for an explanation.

With [SQLite Plugin 2](https://github.com/nolanlawson/sqlite-plugin-2), I removed the `location` parameter entirely, preferring to save to one location, in order to make things simpler. However, you do need to upgrade from the existing location. I wrote [a script to demonstrate how to migrate](https://github.com/nolanlawson/cordova-plugin-sqlite-2#migrating-from-the-original-sqlite-plugin), but unfortunately it will depend on which version of SQLite Plugin 1 you used when you published your app, since the location changed so many times.

If you're unsure, you can run the app in the Android emulator or the iOS simulator and see where the SQLite Plugin 1 is writing files. Hope that helps; drop by the PouchDB Slack/IRC channel if you need more help! Closing this issue since it's not strictly related to PouchDB.

**Comment by chrisschaub** [comment]
It seems that my version uses libs + LocalDatabase. And your new plugin
uses libs + NoCloud. My version of sqlite is 0.7.7.

On Fri, May 20, 2016 at 1:35 PM, Nolan Lawson <notifications@github.com>
wrote:

> The location is decided by the SQLite Plugin. They have actually changed
> their location several times over recent releases, so you'll probably want
> to look at their README
> <https://github.com/litehelpers/Cordova-sqlite-storage> for an
> explanation.
>
> With SQLite Plugin 2 <https://github.com/nolanlawson/sqlite-plugin-2>, I
> removed the location parameter entirely, preferring to save to one
> location, in order to make things simpler. However, you do need to upgrade
> from the existing location. I wrote a script to demonstrate how to migrate
> <https://github.com/nolanlawson/cordova-plugin-sqlite-2#migrating-from-the-original-sqlite-plugin>,
> but unfortunately it will depend on which version of SQLite Plugin 1 you
> used when you published your app, since the location changed so many times.
>
> If you're unsure, you can run the app in the Android emulator or the iOS
> simulator and see where the SQLite Plugin 1 is writing files. Hope that
> helps; drop by the PouchDB Slack/IRC channel if you need more help! Closing
> this issue since it's not strictly related to PouchDB.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pouchdb/pouchdb/issues/5185#issuecomment-220685131>
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by nolanlawson** [comment]
Yup, that migrate script should work perfectly for LocalDatabase -> NoCloud.

**Comment by chrisschaub** [comment]
Great. This is not going to be easy to test though, simulating an upgrade
in the dev space, not live in app store. Would you be willing to add back a
parameter to pass in the db location? It would help legacy applications a
lot.

On Fri, May 20, 2016 at 9:19 PM, Nolan Lawson <notifications@github.com>
wrote:

> Yup, that migrate script should work perfectly for LocalDatabase ->
> NoCloud.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pouchdb/pouchdb/issues/5185#issuecomment-220753465>
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by nolanlawson** [comment]
No, I prefer not. I prefer to avoid the whole `Location` trouble right from the start.

In order to test, yes, you will need to install v1 of your app and then install v2 and make sure the migration occurs. You can use `adb install -r myapp.apk` to reinstall an APK file in the same way that Google Play would.

**Comment by chrisschaub** [comment]
Ok, but it's not an issue with Play right? Just iOS? Just double checking,
thanks!

On Mon, May 23, 2016 at 11:56 AM, Nolan Lawson <notifications@github.com>
wrote:

> No, I prefer not. I prefer to avoid the whole Location trouble right from
> the start.
>
> In order to test, yes, you will need to install v1 of your app and then
> install v2 and make sure the migration occurs. You can use adb install -r
> myapp.apk to reinstall an APK file in the same way that Google Play would.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pouchdb/pouchdb/issues/5185#issuecomment-221030706>
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by nolanlawson** [comment]
Whoops, thought you were talking about Android. Yeah, I have no idea how to test that with iOS, sorry.

**Comment by chrisschaub** [comment]
And just to verify, Android is not affected. This database location was an
iOS only issue? Thanks.

On Mon, May 23, 2016 at 12:10 PM, Nolan Lawson <notifications@github.com>
wrote:

> Whoops, thought you were talking about Android. Yeah, I have no idea how
> to test that with iOS, sorry.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pouchdb/pouchdb/issues/5185#issuecomment-221034049>
>



-- 
Christopher Schaub
http://chris.schaub.com
