### ISSUE TITLE
RFC: move pouchdb-server et al into PouchDB core

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5192]
Here are the modules I propose we move into PouchDB core:

* [ ] pouchdb-collections
* [ ] pouchdb-collate
* [ ] pouchdb-server
* [ ] express-pouchdb
* [ ] pouchdb-express-router
* [ ] pouchdb-find

Open question is whether we should preserve the git history when we move them back in. It might be a nice gesture to contributors to those modules to include their changes, but we'd have to do a merge, which would break our single lineage.

BTW I plan on waiting until post-5.4.0 to do this, because I want to make sure we have a stable 5.4.0 release with the existing architecture.

**Comment by marten-de-vries** [comment]
Preserving git history when merging also helps with finding why something was introduced. Even if the commit message is unhelpful, the time of the change and the state of the code at that point often gives hints. If the old repo can only be hidden/put into read only mode instead of removed that would work too for that use case, but not sure if Github supports that (maybe by moving to a to-be-created pouchdb-deprecated user?).

**Comment by daleharvey** [comment]
`pouchdb-collections` `pouchdb-collate` `pouchdb-find` should pretty certainly be moved into monorepo, they are very much coupled to pouchdb development.

I am not so sure about the various servers, they are not a core part of the pouchdb project and I think merging them in may give the impression that they are (ie we will now be responsible for maintaining compatibility with whatever couchdb features pouchdb-server replicates). It makes working on those projects more complicated and have very little advantage. 

Did we fix the complications with testing pouchdb-server with the (current patch) version of pouch? it seems so @ https://github.com/pouchdb/pouchdb/blob/master/tests/misc/express-pouchdb-minimum-for-pouchdb.js, but if not then it should be fixed in pouchdb-server as it hasnt been a problem for pouchdb-express-router

**Comment by nolanlawson** [comment]
Not sure what you mean by complications, but there's still [lots of janky scripts](https://github.com/pouchdb/pouchdb-server/blob/82ab4138b20fa3a7732f2b4c2b7d47fe4a01d564/bin/test-pouchdb.sh) in the pouchdb-server and express-pouchdb codebase. (Lerna would make those obsolete.)

I don't think putting pouchdb-server changes our maintainership status any more than having it in the `pouchdb` GitHub org, where it presently resides. However, it does make it much easier to test pouchdb-server and express-pouchdb in one place, as opposed to the current system, where we run the same tests 3 times in 3 repos and they may become out of sync without us noticing. Keep in mind that I'm also advocating we move `pouchdb-express-router` into core as well, because it's the same problem (running the same test in 2 repos).

IMO the biggest downside to this change is 1) potentially losing git history, and 2) increased build time due to all the dependencies of express-pouchdb. However, another thing I'd like to do is move all of @marten-de-vries's small repos into core as well, where they're easier to find and modify. I know in the past @gr2m has mentioned that he found it difficult to contribute to pouchdb-server because of its hypermodularity.

That said I'd be fine with moving pouchdb-collections and pouchdb-collate in first, then pouchdb-find, and then working on the others later since they're controversial.

**Comment by marten-de-vries** [comment]
Not sure if moving 'my' submodules of express-pouchdb is a good idea, as they have separate test suites. More chances of Travis breaking down accidentally (e.g. due to upstream bugs in mocha/eslint/babel etc.), and its runtime would increase too (although only marginally).

But anyway, we can figure that out later. The order @nolanlawson names sounds like a good start.

**Comment by daleharvey** [comment]
As an approach I think starting with collections / collate / find is definitely the best start. As for the complexity at this early stage its going to handwavey and hard to pin down however I do feel like there are 2 sides to the monorepo (all in one repo) vs modularisation (everything its own repo) debate and there is going to be a line somewhere in the middle. I suspect that pouchdb monorepo being used to serve the core API and `pouchdb-server` (and its 10 - 20 dependencies) being their own monorepo is that line.

Basic complexities include it being hard to find things, yesterday I was looking for users of `_getAttachment`, at one point in time `$ grep -r "._getAttachment" ./src` would have given me the exact 4 results, now `$ grep -r "._getAttachment" ./packages` is pages long (partly due to us using es6, not strictly monorepo, but still related). As was the bug I filed with `websql` being broken affecting my ability to work on `indexeddb`, there are extra platform and version issues with everything being put together as well as the general cognotive overhead.

I do think its still to early to make the call on how much these things are going to cost and whether its worth it, my gut feeling is that a pouchdb-server monorepo would be the best solution, but lets get the rest in, live with the monorepo for a while and make the harder calls a little further out.

**Comment by garrensmith** [comment]
What about creating a new server monorepo. This would include express-server and pouchdb-server along with the other modules they require. That would make testing and maintaining them a lot easier.

**Comment by marten-de-vries** [comment]
@garrensmith I'm ok with it, but it's a bit more complex than for the main repo. The submodules of pouchdb-server (including express-pouchdb, but also pouchdb-show etc.) are not internal APIs. As such, we can't break semver for them. Also, they each have their separate test suites next to the large ones of pouchdb/couchdb. These would all need to run on Travis.

That said, I'm not sure if these are really obstacles. I need to get more familiar with monorepo tooling.

**Comment by garrensmith** [comment]
Interesting. I'm not that familiar with how all the plugins relate. The main thing I'm finding is that I'm trying to fix the pouchdb-server tests and its really tricky since they are all so inter related. From my talks with @nolanlawson yesterday he was confident a monorepo could solve it to some degree.

**Comment by nolanlawson** [comment]
Yeah I've changed my thinking on this; I think a monorepo of pouchdb-server/express-pouchdb/pouchdb-auth/etc. would be a good idea, but maybe that's too much to stuff into the main PouchDB monorepo.

@garrensmith what this would fix is all the nastiness of `npm link` or `ln -sf` that you probably see in the `bin` scripts inside of both pouchdb-server and express-pouchdb. Those things are incredibly flaky and finicky.

**Comment by garrensmith** [comment]
I would like to think it will help. If we could have one test setup for express-pouchdb and pouchdb-server that would help a lot. Along with being able to work on both of them at the same time without needing npm link. I'm finding it pretty slow going trying to fix the tests at the moment. But that is also because I'm still learning the codebases. 

All misspelling thanks to my iPhone

**Comment by nolanlawson** [comment]
I'd be perfectly happy with a `pouchdb-server` monorepo with all changes in there. You may want to check out [lerna import](https://github.com/lerna/lerna/pull/173) for this, assuming it's important to keep the original Git history.

**Comment by garrensmith** [comment]
Great. I think I will first try and get the tests fixed and after that look at a monorepo

All misspelling thanks to my iPhone

**Comment by gr2m** [comment]
I agree, I would not adding it all to PouchDB core, but make a PouchDB Server monorepo instead

**Comment by daleharvey** [comment]
We we have https://github.com/pouchdb/pouchdb/issues/5295 for the non `-server` related repos, and looks like we are in agreement + work has started on the monorepo for pouchdb-server https://github.com/pouchdb/pouchdb-server/pull/143 so closing this one, cheers all
