### ISSUE TITLE
RFC: How to implement native secondary indexes

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#5216]
Opening a new discussion solely to figure out how to let [pouchdb-find](https://github.com/nolanlawson/pouchdb-find) users benefit from native secondary (indexeddb) indexes, will paste in the current discussion so far

So not on a lot of peoples radar but this is now passing 100% in chrome + fx so taking a look at what native support for `pouchdb-find` would look like.

In an ideal world we are compatible with current pouchdb find, which looks like 
 
```
db.createIndex({
  index: {fields: ['name']}
}).then(function () {
  return db.find({
    selector: {name: {$gt: null}},
    sort: ['name']
  });
});
```
User defines an index which operates on existing data at runtime then has the ability to use that index for queries. The issue here is that index creation in indexedDB is done at schema creation time and requires version update to the schema which we currently use in pouch to handle data format migrations.

Supporting that will require us closing idb on index creation and doing a schema upgrade (in the cases we need one), figuring it all out is hurting my head so right now I want to focus on the more basic case of predefined indexes and if we get that working, figuring out if we can / want to backport that to get runtime definition support (not 100% sure we will)

So by predefined indexes I mean code that looks like

```
var db = new PouchDB('data', {indexes: ['name']});
db.find({
    selector: {name: {$gt: null}},
    sort: ['name']
});
```

We can store some version / index information in the database, however the issue is that we need to know the version of the database we are opening before we open it in order to trigger schema upgrades. Right now the only proposal I can think of is

### Proposal 1. Multiple databases

Right now (in idb-next) we use 2 core objectStores, `DOC_STORE` and `META_STORE`, `META_STORE` contains some persisted information about the database (mostly its update_seq), we can split `META_STORE` into another idb database that stores an `IDB_VERSION` as well as the current indexes, any time we see a difference in the `indexes` options, we bump the `IDB_VERSION` and create / delete the relevant indexes.

Cons: 

  * Managing multiple database can be tricky, ensuring they get closed / error handling as well as ensuring they are updated in a consistent manner

**Comment by daleharvey** [comment]
And from @nolanlawson 

> Awesome!! :tada: Any chance the performance issues were sorted out too?
> 
> As for pouchdb-find, I'm still of the mindset that we can't really solve the problem of dynamic indexes by closing/reopening the database, because I suspect it will fail in multi-tab environments or worker/serviceworker environments (race conditions). I also imagine this will have wonky effects in Edge due to race conditions in opening/closing DBs.
> 
> I say we should punt on pouchdb-find/mapreduce for now and just continue with dependentDbs etc., for the time being anyway. Also once the monorepo is merged, we can ship this adapter as an optional adapter and hopefully start to get feedback from early adopters.
> 
> Also I'm not against the idea of multi-DB - it's a nice way to take advantage of parallellism, and I think inside of `__pouchdb_` we can do whatever we want.

**Comment by asutherland** [comment]
I would suggest just using a single index or object store whose keys are Arrays where the first element is your index identifier.  This creates a lexical sub-range that, thanks to the way key ordering works in IndexedDB, is bound by the range `IDBKeyRange.bound([indexId], [indexId, []], true, true)`.  Ideally whatever you're using for indexId is somewhat compact and unique already.

If using an index, the key could just be [indexId, selectedOrderedValue1, selectedOrderedValue2, ...].  If using an object store, the key would want to include your docId/whatever as the last value in the array so that you can delete the keys.

pouchdb-find seems powerful enough that it might make sense to use a separate object store so that you can store everything the selector picks out that you don't put in the (index) key array in the value.  (You may also want to put the stuff you put in the key in the value too if you're doing something like using getAll and so what you get back won't include the key along with the value.)  The rationale is similar to that of a covering index in SQL where you can perform additional filtering without loading the entire row.  This would mean you have to handle deleting the values from your index object store yourself which means being able to re-derive the key paths at delete time.  I think that's compatible with pouchdb semantics, but it does mean you have to have the actual record you're deleting from disk in memory.  I expect the existing view infrastructure requires this already?

**Comment by nolanlawson** [comment]
I would also echo @asutherland's suggestion. An artificial index would have a few benefits:

- indexes can be created/deleted/modified at runtime
- will work in IE/Edge, i.e. a browser that doesn't have multiEntry/compound/deep keys. Else we have to just say that certain pouchdb-find features aren't supported (i.e. indexing on `['complex', 'keys']` or `'deep.keys.like.this'` or multiple keys that map to the same document) or that Edge isn't supported.
- we can control the semantics and implement pouchdb-find exactly as it works in Mango rather than relying on IDB's underlying implementation or creating a conversion layer between the two (i.e. by using `pouchdbCollate` strings instead of arrays)

The biggest downside I can see is performance, because we're essentially rebuilding IndexedDB's indexes on top of it (how ironic). We'd also need to manage the indexes ourselves and update them whenever documents change.

I think the performance issue is still an open question, though. We should probably run some benchmarks first to get an idea. For all we know, artificial indexes actually outperformn built-in indexes.

OTOH I don't mind the idea of indexes in the `PouchDB` constructor, and I think it might be a nice workaround.

**Comment by beidson** [comment]
> however the issue is that we need to know the version of the database we are opening before we open it in order to trigger schema upgrades. Right now the only proposal I can think of is

I'm not really sure what the goal is here, but it sounds like you're asking for "an easy way to always be able to upgrade the schema to add an index".

Maybe I'm missing something obvious here and that's *not* what you're asking for, but that's easy.

    var request = indexedDB.open(dbName);
    request.onsuccess = function() {
        indexedDB.open(dbName, request.result.version + 1).onupgradeneeded = function() {
            // Add your index here.
        }
    }

You can do that as many times as you want, in practice, since databases can be versioned up to 2^64.

**Comment by asutherland** [comment]
I agree benchmarks are probably the best answer especially if you have a good example to test on and can do it on realistic and/or worst-case hardware (old mobile phones, for example).  But in the abstract, and speaking as someone really only familiar with Gecko's implementation...

In general, the benefit of built-in indexes over hand-rolled indexes using object stores are:
1. They automatically can handle the indirect lookups without any roundtripping.  By definition a hand-rolled index is going to require at least two requests.  The new IDBKeyRange.includes https://developer.mozilla.org/en-US/docs/Web/API/IDBKeyRange/includes can result in massively improved performance for fetching using n keys versus n separate get() requests in some implementations.  Specifically, it works great for Gecko's SQLite-backed IndexedDB.  It is new so this may be of little help in general.
2. The fact that they're automatic in terms of creating the index records and automatically deleting them when you delete the object store value is pretty nice.

The benefits of hand-rolled indexes are:
1. Great in the case where you are either performing secondary filtering like where a covering index would be useful in SQL and you're expecting a meaningful number of records to fail to match.  If you were using a native index, you would have had to load the records which are likely significantly larger than your index's digest and which also would require a random access to get to.  (Whereas Gecko IndexedDB values are stored consecutively in the btree thanks to our use of WITHOUT ROWID.  This also makes record size important since a downside of WITHOUT ROWID is that B*-Trees are no longer used, see http://www.sqlite.org/withoutrowid.html for more.)
2. Potentially quite useful when you don't need all of the records all at once.  For example, virtual scrolling implementations can benefit from knowing the number of items in the list and some useful metadata that might have been stashed in the index like item height.
3. The automatic aspects of native indexes don't come for free.  You have to store the keys in your object, which can add up if the value you're persisting wouldn't otherwise contain those values at those locations.  And unless you are changing the schema every time the user adds an index, you probably are going to be storing those index keys redundantly in wasted space in your object.  (Although you can leverage that an index need not emit a value.)  There may also be other additional book-keeping done by the implementation under the hood as-is the case in Gecko.
4. By doing the index at a higher level, you can do higher level things like amortize index update costs by deferring the updates until a later time and leveraging existing journals (if pouchdb maintains that aspect of old couchdb).  This of course adds all kinds of complexity and can be a bit pie-in-the-sky, but it's worth keeping in mind.

**Comment by daleharvey** [comment]
@beidson So my problem with that is we need to use that version number to handle our own schema migrations, for example right now we are at POUCHDB_VERSION=7, if we did a release at 7, the user defined their own indexes a few times, rolls up to 10, we then release another pouchdb with a migration that goes to 8 .... We could have pouchdb migrations bump the version by 1000 where as index changes are 1 and hope the user doesnt grow larger than that, but seems fragile.

@asutherland @nolanlawson The artificial index solution is essentially what map reduce currently is, its a fair amount of code and a large amount of complexity despite being optimised for being simple and reusing as much code as possible and users are still repeating that it is almost unusably slow. There are ways to speed up our current implementation however from what I have looked at, `pouchdb-find` maps to indexes fairly closely to indexeddb's indexes, I have fairly large doubts that doing anything than trying to expose already built in functionality is going be able to complete in terms of the size / performance tradeoffs, but yeh will get it implemented first and see what it ends up looking like

**Comment by beidson** [comment]
> So my problem with that is we need to use that version number to handle our own schema migrations, for example right now we are at POUCHDB_VERSION=7, if we did a release at 7, the user defined their own indexes a few times, rolls up to 10, we then release another pouchdb with a migration that goes to 8 .... We could have pouchdb migrations bump the version by 1000 where as index changes are 1 and hope the user doesnt grow larger than that, but seems fragile.

Especially if PouchDB scheme upgrades are rare, you could play lots of number tricks to still get the same effect.

e.g.
Assume PouchDB will never have more than 1000 scheme versions while using IDB. (If you're only now on V7, that seems like a safe bet)

So the bumps for user indexes are in the 10,000's+.

IDB version 1 == PouchDB v1
IDB version 7 == PouchDB v7
IDB version 10007 == PouchDB v7 with the first user index configuration
IDB version 20007 == PouchDB v7 with the second user index configuration
...
IDB version 10520007 == PouchDB v7 with the 1052'ed user index configuration
IDB version 10520008 == PouchDB v8 with the 1052'ed user index configuration.

You could give way more than 1000 versions to PouchDB and still never exhaust the IDB version namespace.

And yes, I did this in decimal for illustration, instead of binary, which could be even more efficient with the available versions.

**Comment by beidson** [comment]
s/scheme/schema/ DYAC

**Comment by daleharvey** [comment]
@beidson Doh yeh you are right, I got the order in which we should increment the version the wrong way round. However last question, do you think its worth doing that over having 2 seperate databases? I see them having mostly the same advantages / disadvantages except 2 databases is conceptually simpler

**Comment by beidson** [comment]
I don't think 2 databases is the way to go.

At an abstract level, you lose ACIDity.
At an implementation level you add complexity.
At the platform level you'll get competing i/o instead of serialized.
I could probably come up with more cons, but it's lunch time :)

**Comment by dfahlander** [comment]
Nolan tweeted me for some feedback so I'll try to do my best and throw some thoughts in here. if they could be of any value.

I liked @beidson's approach that would keep the dynamic indexes native and still be able to add them dynamically. I would suggest to test this out in practice though before going for that solution. There might be issues with IE/Edge and Safari (as always ;) because they don't react to `upgradeneeded` event, which in practice means that when reopening the db with a higher version number. the open() request will be blocked if another tab has the same DB open. Could be worked around using various communication strategies between your PouchDB instances, such as:

1. Record all PouchDB instances in a static array and trigger versionchange event manually. Works only when the blocking connections resides in the same window but not when in a worker or other window.
2. If service worker or shared worker is supported, use it as a intermediate communication channel to tell other PouchDB instances to close down.
3. Fallback strategy: Have a dedicated objectStore to poll regulary for custom events. When `onblocked` is fired, add an item to this store telling the blocker to close and reopen the db. This would make the database block no more than, say 10 seconds at most to the cost of db requests every 10th second.

Maybe 1 and 3 is enough to keep the code simple. Could have suggested to trigger the `storage` event by writing to localStorage, but it also fails to trigger between different browser processes in IE, and it couldn't be used in worker.

**Comment by beidson** [comment]
> There might be issues with IE/Edge and Safari (as always ;) because they don't react to upgradeneeded event, which in practice means that when reopening the db with a higher version number. the open() request will be blocked if another tab has the same DB open.

This is no longer an issue in WebKit.

**Comment by dfahlander** [comment]
That's good news. Then it's just IE and Edge that is problematic.

**Comment by daleharvey** [comment]
Thanks for the input, gonna give this a shot now and will report back in https://github.com/pouchdb/pouchdb/issues/5207

**Comment by nolanlawson** [comment]
> The artificial index solution is essentially what map reduce currently is, its a fair amount of code and a large amount of complexity despite being optimised for being simple and reusing as much code as possible and users are still repeating that it is almost unusably slow

My hunch about this slowness was that it's due to using PouchDB for the artificial index, with all of the overhead of revisions etc. I could be wrong, though.

That said, there is indeed no way that artificial secondary indexes could be faster than native secondary indexes, so maybe opting for the fastest possible approach is the best idea, since historically we've seen so many complaints about PouchDB's speed. Maybe we can't afford to _not_ choose the fastest possible option.
