### ISSUE TITLE
PouchDB 's option clone behavior breaks request's agent option

### ISSUE THREAD

**Issue by yaronyg** [pouchdb/pouchdb#5231]
### Environment (Node.js/browser/hybrid app/etc.)

Node.js
### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

N/A but I'm testing on OS/X
### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

N/A but I'm using LevelDB
### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

PouchDB
### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

``` Javascript
var ForeverAgent = require('forever-agent');
var PouchDB = require('pouchdb');
var express = require('express');
var expressPouchdb = require('express-pouchdb');
var http = require('http');

var dbPath = "foo";

var DefaultPouch = PouchDB.defaults({
  prefix: dbPath
});

var actionAgent = new ForeverAgent();

var app = express();
app.use('/db', expressPouchdb(DefaultPouch));
testServer = http.createServer(app);
testServer.listen(0, function () {
  var serverPort = testServer.address().port;
  var url = 'http://127.0.0.1:' + serverPort + '/db/bar';
  var pouch = new DefaultPouch(url , {
    ajax: {
      agent: actionAgent
    }
  });
  pouch.get('blah')
    .then(function () {
      console.log('It\'s a miracle!');
    })
    .catch(function (err) {
      console.log(err);
    });
});
```

When I check the source code what appears to be happening is that PouchDB's clone function that it uses on arguments turns the agent class into an object with some properties (but it's not a class anymore). This gets passed all the way down to Node's HTTP library who eventually tries to call a method on the agent but it's an object not a class so the method call fails, which throws which eventually causes PouchDB to return the bulk doc error for some reason.

So either we need to fix clone so it properly detects this situation and doesn't clone (e.g. check for optionValue.constructor and if it is there then assume this is a newable object and we can't clone it) or we need to change the docs so they clearly state that we don't support the agent option in ajax in the case of Request.

**Comment by nolanlawson** [comment]
We had to do a similar fix for worker objects. In general, I think it might be wise to not even bother cloning the options that are passed in to `new PouchDB()`, since there are tons of use cases where a plugin would want to pass something fancy in here (a worker, a custom object, etc.).

@yaronyg In the meantime, a workaround you can use is to pass in a function that _returns` the thing. Functions do not get cloned by the cloning algorithm. You can also attach it to the pouchdb object using `db._mythingie = whatever`.

**Comment by nolanlawson** [comment]
Actually since:
- it's nearly impossible for the clone algorithm to catch every possible custom object, and 
- because I think we're doing the maximum possible [in these lines](https://github.com/pouchdb/pouchdb/blob/5e214c33375a03ae6f50399cb0c926cb6195c124/packages/pouchdb-utils/src/clone.js#L32-L34), and
- because there are workarounds described above, and
- because this only affects plugin authors,

I'd be inclined to close this as a wontfix. I certainly don't think it would be a good idea to add logic to PouchDB core to detect custom objects from other libraries.

**Comment by yaronyg** [comment]
Please keep in mind that this scenario has nothing to do with a custom plugin. This is about using PouchDB's advertised behavior as specified in  https://pouchdb.com/api.html#create_database which states "These are passed verbatim to request (in Node.js) or a request shim (in the browser), with the exception of:"

Thali was depending on this statement being true so that we could pass in our own pool object using the agent option. There wasn't a line of custom plugin anywhere here and that's why none of the work arounds will work as we are just trying to use request as designed and as PouchDB explicitly claims will work. Again, this was about use request as request is explicitly designed to be used (e.g. the agent option) in a manner that PouchDb's specs explicitly states should work.

So I believe we only have two options:

Change the docs - We can clarify the docs that we perform transformations on the objects that are submitted in a new PouchDB request and therefore certain features in request.js such as agent won't work and aren't available.

Fix the code - We can either remove clone when used on options passed into the constructor or we can white list objects that request expects.

**Comment by nolanlawson** [comment]
Good point. Yeah, since we have a special relationship with `request`, it would make sense to support `request`'s special options object here.

**Comment by daleharvey** [comment]
So the main thing we do cloning for is people editing objects their wrote to the database between calling `.put` and it hitting the database could easily leave us in an invalid state, we just ended up doing it everywhere by default, however thinking about it I dont think you are right and we do not particularly need to clone the constructor options

**Comment by daleharvey** [comment]
So I thought this might be a nice easy patch but its going to be a bit of work, we depend on the cloning quite a lot, a failing test would be super useful

**Comment by yaronyg** [comment]
I have a bunch of meetings today but I'll try to submit a failing test later today.

**Comment by yaronyg** [comment]
BTW, @daleharvey I did give a 100% repo of the issue when I filed the bug above. It's short and sweet. Just look at the first entry in this thread. Or do you want a test that we can put into PouchDB's test suite? This is trickier than it sounds as it will require us to use a server and at least the HTTP adapter. Nothing like that is in, for example, test.constructor.js. But it doesn't seem like that big a deal. So do you want a test where we, for example, try to get info on the test db using testUtils.adapterUrl hard coded to the HTTP adapter? I could then put that into test.constructor.js since this is a constructor issue. Please just let me know. Thanks!

**Comment by daleharvey** [comment]
Yeh I meant one that can be put into the test suite, it doesnt need to be that much more complicated than the example you have, we have `/tests/components` that are simpler for these type of tests (see https://github.com/pouchdb/pouchdb/blob/master/tests/component/test.deletion_error.js) its mostly the extra deps that I would like to avoid

**Comment by andrew-aladev** [comment]
What was a reason of creating your own deep `clone` function? Why not [`node clone`](https://github.com/pvorb/node-clone/blob/master/clone.js)? I see the only reason is:

```
// special case: to avoid inconsistencies between IndexedDB
// and other backends, we automatically stringify Dates
```

This code has nothing to do with `clone`. You are hiding this _feature_ from people and this is bad.

**Comment by daleharvey** [comment]
The code predates `node-clone` is pretty much the reason if I remember (our is based of jquery's implementation). As mentioned above its not really a problem of the clone implementation but that we are trying to clone things at all that we shouldnt. I have tried doing it a couple of time, its tricky since its fairly embedded thoughout a bunch of our code but doable. Happy to help if this is something you want to fix.

As for the `Date` special case, we went back and forth on this for a while (https://github.com/pouchdb/pouchdb/issues/4126) from that bug we actually agreed to not process dates, I cant find the bug that caused us to change our mind however but if you really want to be able to store dates in indexeddb then please file a bug with your use case and we can discuss the tradeoffs, but please avoid using moral absolutes

**Comment by yaronyg** [comment]
@andrew-aladev figures out that this was fixed [here](https://github.com/pouchdb/pouchdb/commit/a3736c7d455b5a0133fc594a395e1800d90ac010) so we should be able to close.

**Comment by nolanlawson** [comment]
@daleharvey I can't find the bug either, but it was death by a thousand cuts. So many people testing in Chrome and then assuming things would work in Safari and then getting surprised. It made more sense to just enforce identical behavior everywhere.
