### ISSUE TITLE
Uncaught exceptions causing map reduce unit test failures

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#5266]

**Comment by daleharvey** [comment]
```
test.mapreduce.js-utils
    ✓ callbackify should work with a callback
    ✓ fin should work without returning a function and it resolves
    1) "after each" hook for "fin should work without returning a function and it resolves"

  2041 passing (6m)
  38 pending
  1 failing

  1)  "after each" hook for "fin should work without returning a function and it resolves":
     TypeError: finalPromiseFactory(...).then is not a function
      at packages/pouchdb-for-coverage/lib/index.js:9:320363
```

So these were hard to spot because only time the intergration tests and mapreduce tests run together are during coverage tests, it needs them both to be included and in CI our coverage tests are expected failures, so reproduce `npm run test-coverage`

**Comment by daleharvey** [comment]
@yaronyg @nolanlawson Is it the test or the global listener thats broken here, having a little trouble understanding whats expected although this is a small unit test so should figure it out

**Comment by daleharvey** [comment]
Pushed a temp commit to disable this because it looks like it should be easy enough to fix however I dont want to regress coverage (it looks like we already did)

**Comment by yaronyg** [comment]
The short answer is that the test doesn't appear to be using the utils.fin function correctly. And the new code found the bug. Which is actually kind of cool.

It's worth understanding exactly what happened here so that the new functionality helps you. During the time that the test ran there was an unhandled rejection error. Now this is tricky and understanding why will make the new functionality more useful. The way promises work is that if while a promise is running there is an exception then that exception gets turned into a promise rejection and that promise rejection, if not handled, then triggers the unhandled rejection listener. Once the test is done the after hook checks to see if the listener tripped and if it does it fails the after hook and returns the error.

In this case exactly what happened is that finalPromiseFactory is expected to be a function that returns a promise. But in the test code the finalPromiseFactory is a function that returns an empty object. So when the fin code tries to 'then' the output this caused an exception (specifically finalPromiseFactory(...).then is not a function) which was then turned into a promise rejection which nobody had a catch for and so tripped the listener who then reported. Exactly as things are supposed to work. Thankfully the fix is trivial:

replace 'return {};' with 'return Promise.resolve()' and everything will be fine.

BTW, technically the every next test ('fin should work without returning a function ad it rejects') is also wrong. The reason it's not 'failing' is because '.should.be.rejected' adds  catch handler. So even though the exact same exception is happening for the exact same reason you don't get an error because it's being caught. The fix, btw, is the same.

Which points out that both of these tests are not, I think, sufficient. They should be checking that the returned value is the expected value. That would have hinted that something was wrong.

**Comment by daleharvey** [comment]
So yeh I seen that `finalPromiseFactory` was excepting a promise, however I feel like Nolan probably didnt do this by mistake and was testing specifically how it handled this case, either way I think we need to wait for Nolan to say what the intention of the test is before fixing

**Comment by daleharvey** [comment]
ping @nolanlawson would be good to get your thoughts on this, is the test broken or do we want to be throwing an uncaught exception here and need it handled in the test?

**Comment by nolanlawson** [comment]
I didn't actually write that test; it was written by @neojski. I'm fine with disabling it, since it's just testing a utility function rather than PouchDB's own test suite.

In fact I would be fine with simplifying `utils.fin` since it seems it has code paths that are only hit in our unit tests and not in the integration tests, meaning there is extra unnecessary code in there.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/c681889721c919d8e018d8e7c2cff8b10dbba873
