### ISSUE TITLE
Consider removing SQLite from default install in PouchDB

### ISSUE THREAD

**Issue by cdaringe** [pouchdb/pouchdb#5287]
Hi all,

I never use SQLite.  I always use memdown.  It seems inconsistent that I have to install memdown to use it as an adapter, but on every new `npm i` i have to compile some C code for a SQLite plugin that I don't use.

What are people's thoughts towards moving the SQLite adapter out just like the other non-default adapters?

Thx!

Chris

**Comment by daleharvey** [comment]
I would prefer not to have to install this for my default test env, its been causing problems and I never need it but not sure about how that works with our monorepo setup, at the very least it should be an optional dep

**Comment by nolanlawson** [comment]
So, that would definitely be a breaking change. Right now both `websql` and `leveldown` are optional dependencies (check `packages/pouchdb/package.json` to see).

In fact this is exactly the problem that custom builds are intended to solve. You can create your own custom build that uses only an in-memory adapter and doesn't require `websql` or `sqlite3`. I actually wrote one here to demonstrate: https://github.com/nolanlawson/pouchdb-memory (look at `index.js`, see how simple it is 😃 )

Closing because I consider this fixed; the `pouchdb` package should always be a kitchen sink unless we want to make a breaking change.

**Comment by nolanlawson** [comment]
@daleharvey I agree it sucks to have to install it while testing/developing, but I think this is a cost we pay with the monorepo In PouchDB v6 we'll remove the `extras` and when we do, the `pouchdb` package won't have `websql` or `sqlite3` anymore.
