### ISSUE TITLE
iOS storage is not cleared after PouchDBs are destroyed

### ISSUE THREAD

**Issue by VladyslavGoloshchapov** [pouchdb/pouchdb#5329]
### Environment

Hybrid - ionic on iOS

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

Hybrid - Safari

### Adapter

WebSQL

### Server 

not relevant - replication is not standard

### Please describe your issue.

Issue is very easy to reproduce on iOS device (iphone, ipad). 
I am starting my app, which uses custom protocol to sync with CouchDB. Then user clicks button which initiates destroying all created Pouch DBs. They are all successfully destroyed. Using debugger, I can see that all DBs are destroyed. But if you go to Device Settings->General ->Storage&iCloud Usage->Storage->Manage Storage->{{app name}}, you can see that storage size is same or even slightly bigger than one before all DBs were destroyed.

**Comment by daleharvey** [comment]
Is this an icloud thing? is your data being backed up despite it being deleted locally, not sure there is anything we can do about this inside pouchdb, on `db.destroy()` we delete all data from the database only leaving the empty tables (theres no way to delete the tables)

**Comment by nolanlawson** [comment]
The issue here is that SQLite doesn't _actually_ shrink its own size until some set of criteria have been met. Normally it's done automatically in periodic intervals.

You can actually force it yourself by using the `VACUUM` command, but up to now we have not exposed this in PouchDB's API because it has limited usefulness. (May make sense as a plugin, though.) Hopefully that answers your question!
