### ISSUE TITLE
DOM Exception 18 on iOS 9.3.2, chrome 51.0.2704.64

### ISSUE THREAD

**Issue by wheresrhys** [pouchdb/pouchdb#5340]
It appears to be identical to this issue, which was filed as fixed last year on iOS 8 https://github.com/pouchdb/pouchdb/issues/3382

**Comment by wheresrhys** [comment]
Logging out `db.adapter` I get `'websql', so it's being created successfully and it's hard to detect the failure early and fallback to http. I'm having to attempt a `.put()` and then redefine the db after it fails

**Comment by nolanlawson** [comment]
In principle this should have been fixed by [these lines of code](https://github.com/pouchdb/pouchdb/blob/6beb9aed0c6d0342a2b557c38c01d23c5de45592/packages/pouchdb-adapter-websql/src/valid.js#L16-L50) (see #5197 for backstory). Apparently we aren't detecting Chrome's UA correctly. Can you run that code on Chrome for iOS and see what we need to modify to make it correctly detect WKWebView?

**Comment by wheresrhys** [comment]
Here are the results of all the relevant functions:

UA: Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X)
AppleWebKit/601.1 (KHTML, like Gecko) CriOS/51.0.2704.64 Mobile/13F69
Safari/601.1.46
hasLocalStorage: true
isChromeApp: false
canOpenTestDB: false
isValidWebSQL: false

... no backtick on iPhone keyboard

**Comment by wheresrhys** [comment]
I just realised there's a good chance I was using a pouchdb version prior to this fix. It could easily be 3 weeks since I ran npm update. Feel free to close this issue

**Comment by nolanlawson** [comment]
Hopefully that's the issue. `isValidWebSQL` should be false, in which case neither `websql` nor `idb` will be determined to be valid (you have to use fruitdown or localstorage-down instead).

**Comment by nolanlawson** [comment]
Please reopen if that's not the issue.
