### ISSUE TITLE
Documenting db option

### ISSUE THREAD

**Issue by yaronyg** [pouchdb/pouchdb#5384]
Head on over to https://pouchdb.com/api.html#create_database and notice that the adapter option is documented but the db option is mentioned in note 3. It is it intentionally that it's so obscure (even though it is then used in an example)? Or should it be listed as a top level option with adapter?

**Comment by nolanlawson** [comment]
The `db` option should be removed from the documentation entirely, since it's no longer even necessary thanks to the custom builds. Every first-party supported *down adapter is not available as its own pouchdb adapter (e.g. `pouchdb-adapter-localstorage`).

Essentially `db` is an internal API only relevant to `pouchdb-adapter-leveldb-core`, as demonstrated in every pouchdb package that uses some *down adapter. (There is also another internal API, `migrate`. `websql-core` has a similar one called `websql`.)

**Comment by yaronyg** [comment]
But look att https://github.com/pouchdb/pouchdb/blob/master/packages/pouchdb-adapter-leveldb/src/index.js it looks like we are still using db internally? So when we need to create our own package for leveldown-mobile don't we effectively just set db?

**Comment by nolanlawson** [comment]
Yes, it's still used internally. So dependents of `pouchdb-adapter-leveldb-core` need to know about it, but everyone else doesn't. It should be documented in the README for that module (which is a very very esoteric module that most will never hear about).
