### ISSUE TITLE
TypeScript users are not happy

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5389]
Normally I wouldn't consider this our issue, but given the popularity of Angular 2 and Ionic 2, I think we should consider this our issue.

We keep getting complaints about TypeScript+PouchDB integration, and apparently it comes down to the definition files. It seems there are lots of them out there, but none of them are very up-to-date.

Looks like we need to send someone out to update the DefinitelyTyped definitions. That someone may or may not be me. 😅

Prior art:

* https://github.com/AGBrown/pouchdb.d.ts
* http://definitelytyped.org/docs/pouchDB--pouch/globals.html

I'm not sure which dts file is the most up-to-date, but we should probably start with that and then submit it as a PR to DefinitelyTyped. Note that I'm not proposing we move the dts file in-house and maintain it ourselves, just that we put the effort in, since the TS community seems to need some help here.

Related: https://github.com/AGBrown/pouchdb.d.ts/issues/41
[Discussion on Twitter](https://twitter.com/nolanlawson/status/745682266009931776)

**Comment by geppy** [comment]
I'd like to update the TS definitions, and I'd be willing to maintain them if that's desired.  Would you rather I send a PR here or to DT?

**Comment by Bouzmine** [comment]
I don't know if that is related to definitions but TypeScript compiler gives me a warning when importing PouchDB as so : 
```javascript
import * as PouchDB from 'pouchdb';
```

> Error TS2307: Cannot find module 'pouchdb'

But it works. It's just annoying as I try to have as few errors as possible (and this is the last one I'm not able to remove).

I think this error message means PouchDB isn't adapted for ES6 Module Importing or something.

**Comment by nolanlawson** [comment]
The main PouchDB package is distributed as CommonJS, but your bundler ought
to be happy with that, since that's the case with 99.9% of npm.

This sounds like it's not a TypeScript issue. What bundler are you using?
SystemJS?

**Comment by Bouzmine** [comment]
I'm using Browserify.

**Comment by nolanlawson** [comment]
If you have a small sample project that reproduces, that would be helpful. By default, Browserify doesn't have support for ES6 modules so I'd need to at least know which Browserify transform you're using.

**Comment by Bouzmine** [comment]
Depending on what you consider small sample, you could check out the [project](http://github.com/bouzmine/metho) I'm currently working on (5 500 lines). I think everything is there in the gulpfile

**Comment by nolanlawson** [comment]
Looking at your code, it seems the bug is that you didn’t `npm install pouchdb`. I should see it in `package.json`, but I don’t…

Also just a protip: you don’t need to check Cordova plugins into version control. You can ignore everything in the `plugins` and` `platforms` directories.

**Comment by nolanlawson** [comment]
Looking at your code, it seems the bug is that you didn’t `npm install pouchdb`. I should see it in `package.json`, but I don’t…

Also just a protip: you don’t need to check Cordova plugins into version control. You can ignore everything in the `plugins` and `platforms` directories.

**Comment by Bouzmine** [comment]
@nolanlawson Sorry, my `package.json` is not up to date(it's on my todo list), but I did install it. Thanks for the tip.

If I can clarify, on packages which are optimized you can do : 
```javascript
import PouchDB from 'pouchdb';
```

On those which aren't you do : 
```javascript 
import * as PouchDB from 'pouchdb';
```

And I triggers an error.

Thanks for the tip.

**Comment by nolanlawson** [comment]
Hm, I think you may be confusing default exports with normal exports. If you do:

```js
import * as PouchDB from 'pouchdb'
```

Then it's assumed there's a _non-default_ export from the `'pouchdb'` module called `PouchDB`. However, what's actually happening is that PouchDB exports a default module called `PouchDB`.

I tried your example on [some sample code](https://gist.github.com/nolanlawson/df9f34654deaac218651b5c118220746) using both Babel+preset-es2015 and Rollup, and they both confirmed that your code won't work, so there seems to be some consensus on this.

The only thing you can do is `import PouchDB from 'pouchdb'`.

**Comment by Bouzmine** [comment]
I tried using `import PouchDB from 'pouchdb'`, didn't work. My solution works apart from firing an error. You could try on a new Ionic 2 TypeScript project (ˋnpm install ionic` and then ˋionic start test --v2 --ts`).

**Comment by nolanlawson** [comment]
@Bouzmine I followed your instructions but didn't see any TypeScript files in the project. I also checked out your project, but I don't understand how to run it.

Can you please provide a simple test case to reproduce this error? If it's something I can just copy-paste into my terminal, that would be ideal. :)

**Comment by Bouzmine** [comment]
1. Create the project like I just said
2. TypeScript files are in `app/pages/` folder
3. To compile the project and view it in the browser run `ionic serve` (it's where you'll see your TypeScript errors
4. Add the import `import * as PouchDB from 'pouchdb'` (after npminstalling it)
5. See the error in your Terminal

**Comment by ozexpert** [comment]
i'm actually on angular2 + ionic, but i'm doing this to bypass compile error, but it works fine. 

```
declare var PouchDB: any;
```

**Comment by nolanlawson** [comment]
@Bouzmine there's no `app` or `pages` directory after I do `ionic start test --v2 --ts`. I'm using ionic 1.7.16.

If you could tell me how to run your `metho` project that may work too. Keep in mind I know approximately nothing about Ionic 2 or Angular 2 and so I don't even know how to run these projects.

**Comment by ozexpert** [comment]
@nolanlawson do this for sample app
```
ionic start cutePuppyPics --v2
```

**Comment by nolanlawson** [comment]
OK, I've gotten a little bit further. I found [the directions for Ionic 2](http://ionicframework.com/docs/v2/getting-started/installation/). You have to `npm install -g ionic@beta` which I had not done.

So it looks like PouchDB isn't the only module that has the error (`TypeScript error: app/app.ts(5,21): Error TS2307: Cannot find module`). If you `npm install lodash` you get exactly the same error.

For lodash you can apparently fix it by doing `npm install -g typings` and then `typings install lodash`. For PouchDB, though, our typings are out of date, so you have to modify your `typings/index.d.ts` file yourself. Unfortunately I cannot figure out what to add. I tried adding this:

```typescript
declare module 'pouchdb' {
  var PouchDB: any;
  export default PouchDB;
}
```

Unfortunately it looks like whatever ES6 modules -> CommonJS transpiler Ionic is using expects PouchDB to export `module.exports.default` when in fact it exports `module.exports`. So it tries to grab `PouchDB.defaults` and ends up with `undefined`. What a mess.

**Comment by nolanlawson** [comment]
OK, I figured it out. You have to do `import * as PouchDB from 'pouchdb'`. I don't know why that is (my understanding of the ES6 module spec is that it's equivalent), but whatever.

Here's [a demo app](https://github.com/nolanlawson/pouchdb-ionic-2-typescript-demo) to demonstrate how to use it. Note, though, that as soon as you create a database (`var db = new PouchDB('foo')`), TypeScript starts to give you plenty of new warnings, so you'll probably have to `any`-ignore those as well. Hopefully someone will update the DefinitelyTyped definitions soon.

**Comment by nolanlawson** [comment]
BTW if you use Visual Studio Code or Atom, it immediately figures out that you're using TypeScript and shows you errors in the code. It's pretty convenient.

**Comment by DrMabuse23** [comment]
```bash
typings search pouchdb
Viewing 1 of 1

NAME          SOURCE HOMEPAGE           DESCRIPTION VERSIONS UPDATED                 
pouchdb/pouch dt     http://pouchdb.com             1        2016-06-08T10:18:05.000Z

> typings install dt~pouchdb/pouch  --save --global
pouchdb/pouch
└── (No dependencies)
```
did you try this ?

**Comment by nolanlawson** [comment]
@DrMabuse23 I'm told the DefinitelyTyped definitions are out of date: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/pouchDB/pouch.d.ts
@AGBrown was working on an update: https://github.com/AGBrown/pouchdb.d.ts

**Comment by dpogue** [comment]
If you're confused about `import pouchDB from 'pouchdb'` vs `import * as PouchDB from 'pouchdb'`, https://gist.github.com/dpogue/8df7fc2f2422642243a0bb7a10ad7793 should help explain what the various import styles correspond to in CJS.

**Comment by robwormald** [comment]
Here's some background (I work on angular core) if it helps:

Modern typescript (post 1.5) and basically every ionic2 and angular2 user are using `external` typescript definition files - you can think of these basically as ES6-style type definitions. So if I author a library in Typescript, something like
```typescript
export interface AmazingOptions {
	jump: boolean;
	howHigh:number;
}

export function doAmazingThings(options:AmazingOptions){
  return true;
}

export class MyAmazingLibrary {
	constructor(options:AmazingOptions){}
	doGreatThings(){}
}

```
and then I run it through the TS compiler with settings:
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "declaration": true,
        "moduleResolution" : "node"
    },
    "files": [
		"index.ts"
	]
}
```
I end up with two files:

The commonJS transpiled .js file:
```js
"use strict";
function doAmazingThings(options) {
    return true;
}
exports.doAmazingThings = doAmazingThings;
var MyAmazingLibrary = (function () {
    function MyAmazingLibrary(options) {
    }
    MyAmazingLibrary.prototype.doGreatThings = function () { };
    return MyAmazingLibrary;
}());
exports.MyAmazingLibrary = MyAmazingLibrary;
```
and the d.ts file that goes along with the file
```typescript
export interface AmazingOptions {
    jump: boolean;
    howHigh: number;
}
export declare function doAmazingThings(options: AmazingOptions): boolean;
export declare class MyAmazingLibrary {
    constructor(options: AmazingOptions);
    doGreatThings(): void;
}
```
At this point, I can just ship this, as-is, to npm and it just works. 

A user can `npm install my-awesome-package` and use my code
```typescript
import {MyAmazingLibrary, doAmazingThings} from 'my-awesome-package'
```
and because typescript is using the same module resolution strategy as node, it just works.

Less awesome and significantly more kludgy is the old-style `ambient` type definitions, which are typically dealt with through definitelyTyped. Its sort of a necessary workaround, but the typescript community as a whole (especially packages being authored and consumed today) are on the external/npm style path - the Typescript team has done a lot to align with the rest of the javascript ecosystem as a whole recently and its been great.

You said on twitter it was no-go for your team to ship to npm, but i'll just say here that that is by *far* the best way going forward, as it means a single, up-to-date source of truth for consumers. It would mean maintaining one `index.d.ts` file per package (probably), but imo that's far preferable to dealing with third parties and out-of-date definitions (per this thread!)

...Of course, you could always just rename all the files in the repo to `.ts` and just run `tsc` instead, incrementally adding types as you go, but I'll save that preach for another issue ;-)

**Comment by DrMabuse23** [comment]
👍

**Comment by robwormald** [comment]
re: running tsc on the existing codebase, I picked a random package that didn't have any dependencies (pouchdb-merge), renamed the src files to `.ts` and ran `tsc` on them:

```
$ tsc -p packages/pouchdb-merge/
packages/pouchdb-merge/src/merge.ts(83,9): error TS2322: Type 'string' is not assignable to type 'boolean'.
packages/pouchdb-merge/src/merge.ts(96,9): error TS2322: Type 'string' is not assignable to type 'boolean'.
packages/pouchdb-merge/src/merge.ts(229,17): error TS2346: Supplied parameters do not match any signature of call target.
```
Those errors pop up because TS is clever and sees the recast from boolean on line 69 to string on 83/96...
<img width="646" alt="screen shot 2016-06-26 at 1 06 21 am" src="https://cloud.githubusercontent.com/assets/534930/16361146/3ebbcd8a-3b3a-11e6-8d2d-f27073b04ce5.png">

So, because I know better than TS, I tell it it can be either (union)
```
var conflicts:string | boolean = false;
```
run again, no errors, and now my `lib` directory has .js and .d.ts files, ready to rock:
<img width="524" alt="screen shot 2016-06-26 at 1 08 47 am" src="https://cloud.githubusercontent.com/assets/534930/16361155/a4542cf0-3b3a-11e6-803b-b283fe7dd781.png">

Couple of random files for illustration
```js
//index.js
"use strict";
var collectConflicts_1 = require('./collectConflicts');
exports.collectConflicts = collectConflicts_1.default;
var collectLeaves_1 = require('./collectLeaves');
exports.collectLeaves = collectLeaves_1.default;
var compactTree_1 = require('./compactTree');
exports.compactTree = compactTree_1.default;
var merge_1 = require('./merge');
exports.merge = merge_1.default;
var revExists_1 = require('./revExists');
exports.revExists = revExists_1.default;
var rootToLeaf_1 = require('./rootToLeaf');
exports.rootToLeaf = rootToLeaf_1.default;
var traverseRevTree_1 = require('./traverseRevTree');
exports.traverseRevTree = traverseRevTree_1.default;
var winningRev_1 = require('./winningRev');
exports.winningRev = winningRev_1.default;
var isDeleted_1 = require('./isDeleted');
exports.isDeleted = isDeleted_1.default;
var isLocalId_1 = require('./isLocalId');
exports.isLocalId = isLocalId_1.default;
```
```typescript
//index.d.ts
import collectConflicts from './collectConflicts';
import collectLeaves from './collectLeaves';
import compactTree from './compactTree';
import merge from './merge';
import revExists from './revExists';
import rootToLeaf from './rootToLeaf';
import traverseRevTree from './traverseRevTree';
import winningRev from './winningRev';
import isDeleted from './isDeleted';
import isLocalId from './isLocalId';
export { collectConflicts, collectLeaves, compactTree, isDeleted, isLocalId, merge, revExists, rootToLeaf, traverseRevTree, winningRev };

```
a snip from `merge.js`, showing the interop between commonJS and ES modules 
```js
//snip
function merge(tree, path, depth) {
    var newTree = doMerge(tree, path);
    var stemmed = stem(newTree.tree, depth);
    return {
        tree: stemmed.tree,
        stemmedRevs: stemmed.revs,
        conflicts: newTree.conflicts
    };
}
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = merge;

```
and the corresponding typedef
```typescript
declare function merge(tree: any, path: any, depth: any): {
    tree: any;
    stemmedRevs: string[];
    conflicts: any;
};
export default merge;

```
Interesting to see there that TS has inferred that stemmedRevs is an array of strings w/o any type information at all, and annotated "any" to the types it doesn't know anything about. This is the sort of thing that can (optionally) be incrementally added.

Just sayin'. We have a similar mono-repo many-package setup on angular2, and the amount of cycles we save with typechecking is kind of crazy. ymmv, of course, but I would have a hard time going back at this point.

/preach over

**Comment by dpogue** [comment]
Moving to TypeScript would probably end up breaking the existing API, particularly for the [main pouchdb module](https://github.com/pouchdb/pouchdb/blob/master/packages/pouchdb/src/index.js).

That code looks like this:
```javascript
import pouchDB from './pouchdb';
export default pouchDB;
```

Which currently generates:
```javascript
module.exports = pouchDB;
```

Whereas TypeScript would generate:
```javascript
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = pouchDB;
```

**Comment by nolanlawson** [comment]
@dpogue. Thanks for your Gist. I just tested Babel (https://gist.github.com/nolanlawson/df9f34654deaac218651b5c118220746) and can confirm that the interop story for default exports from CJS is even more complicated than that. Babel only works correctly if you do `import foo from 'foo'` rather than `import * as foo from 'foo'`. Rollup has full interop last time I checked (assuming you use the CJS plugin). In fact TS seems to be the odd one out here.

**Comment by nolanlawson** [comment]
@robwormald Thanks for hopping in. I also spoke with @DanielRosenwasser and was told that it's better for library authors _not_ to ship their own `index.d.ts` files, unless they are well-versed in TypeScript and prepared to maintain it. (Otherwise it can grow out-of-date relative to DefinitelyTyped/typings/etc.) Curious to know your thoughts on that.

As for migrating PouchDB's codebase over to TypeScript, I appreciate you going to the effort to show us how we could do it. I have lots of worries about TypeScript as a community, though, and this is probably going to be kinda a rant, but here goes:

I've been doing a lot of reading on TypeScript's interop story with the larger JS community &ndash; https://github.com/typings/typings/issues/322, ["Definitely Typed shouldn't exist"](http://blog.johnnyreilly.com/2015/09/authoring-npm-modules-with-typescript.html), and ["The future of typings"](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/) were especially helpful. Everything I've read, though, has made me concerned about where TypeScript stands relative to the rest of the npm ecosystem. I've already shared these concerns with @DanielRosenwasser, but in brief:

1. TypeScript works best when there are type definitions.
2. 250,000+ npm packages do not have type definitions.
3. TypeScript's solution to this problem is to have community-maintained typings for npm packages.

Problems with this approach:

1. **It doesn't scale.** The community can only reasonably maintain typings for the top ~100 npm packages (Lodash, Moment, Mocha, etc.), meaning the "long tail" is inaccessible or cumbersome in TypeScript.
2. **It's not future-proof.** The community can maintain very good typings for `foo-module` v2.0.0, but as soon as `foo-module` ships 3.0.0 (or even 2.1.0), you need to change all the typings. The current plan is to only ever maintain one version of the typings for every npm package, meaning TypeScript users are expected to always be on the latest version of everything. Good luck picking up an old TypeScript project after 6 months!
3. **It's a burden for library authors.** Authors of the top ~100 npm packages can always expect the community to spring into action to maintain their typings. However, the "long tail" of modules (e.g. PouchDB) will be pressured to maintain their own `.d.ts` files, or else lose out on TypeScript users. However, since `.d.ts` files are tedious to maintain if the code is authored in JS, there's additional pressure to just migrate the codebase over to TypeScript. I know y'all think TypeScript is awesome, but imagine if CoffeeScript, ClojureScript, Elm, and GWT were all making the same demands of us.

So in short, it looks like TypeScript will be able to carve out a nice little niche within the npm ecosystem, where users can comfortably enjoy TS-authored packages and the top ~100 npm packages. Maybe this can even be a good developer experience; you certainly don't need all 250,000 packages to write a webapp.

However, as soon as TS users venture out into the long tail, they will be frustrated because typings do not exist. As evidence, I submit a [GitHub search for "typescript support"](https://github.com/search?utf8=%E2%9C%93&q=typescript+support&type=Issues&ref=searchresults) showing tons of issues on tons of repos asking the author to provide definition files. Honestly, you might as well just write a bot to comb through npm and open an issue on all ~250,000 packages, because you'll save module authors a lot of confusion trying to figure out what a `.d.ts` file is and why they should write one. (I'm not joking; you could link to https://github.com/typings/typings/issues/322 and that would be really helpful).

So anyway, that's my perspective. Personally I think TypeScript is a neat language, and I may even contribute to the DefinitelyTyped/typings files for PouchDB, but as of right now, it's a non-starter for us to migrate the codebase over or to maintain our own `index.d.ts`. We don't want to put that maintenance burden on ourselves; if the TS community wants definitions, they should be the ones to maintain them.

Sorry for the rant, but maybe my concerns can be helpful in shaping the future direction of DefinitelyTyped/typings/etc. Honestly I think it'd be neat if TypeScript succeeded, but it sure seems like it has a long road ahead of it. And in the short term, existing problems will only be exacerbated by novice users coming in from Ionic 2 and Angular 2 (e.g. see the flailing around in this thread). Hoping TypeScript can find good solutions to these problems. :smiley:

**Comment by robwormald** [comment]
@nolanlawson no worries on the rant (I hadn't truly expected to convince you)

Just a couple of points though - I wholly agree with the annoyances of TS for packages that aren't authored in TS.

> I know y'all think TypeScript is awesome, but imagine if CoffeeScript, ClojureScript, Elm, and GWT were all making the same demands of us.

My personal view a year ago would have been "never typescript" because it was, as you describe it, "a niche language" which had all sorts of weird special modules and classes. 

As of 1.5 though, it's *just* ES6 javascript + type annotations, as opposed to the other languages listed above - and as such if you're already going through the overhead of having a toolchain (because transpilation), our argument would be why not go the extra 10% and get the benefits of typechecking, even on your own codebase? 

@staltz puts it well here - http://staltz.com/all-js-libraries-should-be-authored-in-typescript.html 

Thanks for looking into this, in any case.

**Comment by nolanlawson** [comment]
@robwormald Thanks; that's an interesting read. I'll definitely continue looking into TS and may even use it for my next small project. :)

> As of 1.5 though, it's just ES6 javascript + type annotations

Right now PouchDB is just ES5 + ES6 modules, which we've chosen because it offers the smallest possible ES5 bundle ([via Rollup](http://pouchdb.com/2016/01/13/pouchdb-5.2.0-a-better-build-system-with-rollup.html)). Combined with the fact that it's a 6-year-old codebase, you can see our reluctance vis-a-vis TypeScript.

Maybe if TS gains more steam, though, then migrating will be inevitable. I can certainly see the benefits of types as I click around in VS Code. Reminds me of my Java days (and yes I mean that in a good way; I like the types :smiley:).

**Comment by robwormald** [comment]
We do the same with Rollup and TS, so I'm with you on that (we go TS -> ES6 -> Rollup). 

Give us a shout when you (inevitably) want to do this, we'll help you out ;-)

**Comment by nolanlawson** [comment]
Oh sweet! :) Curious then why `import PouchDB from 'pouchdb'` doesn't work out of the box with `module.exports = PouchDB`? (see discussion above). I thought Rollup could interop with CJS `module.exports` just fine via `rollup-plugin-commonjs`...

**Comment by DrMabuse23** [comment]
@nolanlawson "using Typescript in my next small project" :) for me its like Heroin and i try babel etc. but typescript is the solution for clean readable code

**Comment by dpogue** [comment]
> Oh sweet! :) Curious then why `import PouchDB from 'pouchdb'` doesn't work out of the box with `module.exports = PouchDB`? 

Apparently this is intentional on the part of the TypeScript team (despite going against the behaviour in the ES modules spec): https://github.com/Microsoft/TypeScript/issues/6296 😢

**Comment by DanielRosenwasser** [comment]
> despite going against the behaviour in the ES modules spec

There is nothing in the ES spec that mentions interop behavior between CommonJS and ES Modules. That said, that is something we're trying to tackle at the moment as the interop behavior becomes concrete. In the mean time, you can use `--allowSyntheticDefaultImports` to assure TS that the default refers to the module's `modules.exports`.

**Comment by DanielRosenwasser** [comment]
For the record, I should clarify what I said, and given that I've had some time to reflect on it, I have some more thoughts.

There's **a ton** of benefit to maintaining declaration files because it supports not only TypeScript users, but general JavaScript users as well. For instance, JavaScript support in Visual Studio, VS Code, and elsewhere can and will be powered by `.d.ts` files as time goes on. Because declaration files describe your API, JS users can get great completion and other tooling support as they consume your library.

So I think it's not just a matter of supporting the TypeScript community - it's about supporting *the JavaScript community as a whole*, and that includes TypeScript users.

Now given that, the question is who is going to write that declaration file. I'm going to claim that library authors know their library's API well enough that they're probably the best people to author it.

But my concern is of the possibility where a library author accepts a declaration file and isn't actively maintaining it. If something is wrong with a `.d.ts` file, you're tying the turnaround time of a fix to the cadence at which you're okay with publishing to npm. (though for you guys that might not even be a problem). I basically don't want you to blindly accept a `.d.ts` without understanding how it's describing your library. So allowing your users to contribute to this process through DefinitelyTyped is another great approach where the `.d.ts` files will naturally get better over time.

So @nolanlawson let me give a better answer. Give TypeScript a try. Once you know the language better, see how comfortable you'd be writing a declaration file, or bringing one in to your library. What it boils down to is just describing your API, which is pretty simple (and which could even use to generate your website's docs if you wanted). As I've mentioned, you can feel free to reach out if you need.

**Comment by AGBrown** [comment]
I may as well chip in as I ~~wasted~~ spent 10s of days of my life writing [AGBrown/pouchdb.d.ts](https://github.com/AGBrown/pouchdb.d.ts) at one point.

**First**: the DT version of pouch.d.ts is *still* awful. It hasn't significantly changed since I "had to get annoyed enough to just write it." (to quote [Steve Ognibene](https://twitter.com/nycdotnet/status/745714010394329088)). I have not contributed to that file ...

**Second**: why haven't I PR'd [AGBrown/pouchdb.d.ts](https://github.com/AGBrown/pouchdb.d.ts) into DT? Actually I did start to raise it at DefinitelyTyped/DefinitelyTyped#4328 and AGBrown/pouchdb.d.ts#14 but I never caught up with the pouchdb api versions, the d.ts was never fully complete as a d.ts api spec, and I was worried the d.ts still had issues. Was it better than the DT version? Sure in a lot of ways. Was it going to cause the pouchdb team to be peppered with questions like "the d.ts says this but it doesn't work help plz k thx bye"? Probably. I've never met @nolanlawson and didn't want him to hit me the first time I did.

**Third**: why isn't pouchdb.d.ts up to date? Well, I started it in April 2015. I quickly got overwhelmed by the depth of the pouchdb api and eventually I got very frustrated by typescript, particularly tooling (I'm looking here at the early versions of VSCode which I haven't touched since then). I also started to question the premise of DT in that it tries to be/should be a single (increasingly unmanageable) github repo that represents the entire javascript community's libraries in d.ts form. The cracks started to show (in me, not DT) when I had to start shaving yaks like updating chai.d.ts in order to move on with pouchdb.d.ts. Sticking with javascript was just easier in the end, and I wasn't getting paid to change the world with typescript.

Is that last point relevant? Well, it and a bunch of recent (positive) life changes are why I am not, and will never be, the most active developer on my pouchdb.d.ts. I'm happy to merge (good, non time consuming) PRs though, or just hand it over to someone else (@geppy, @robwormald)?

### My view on creation of a pouchdb d.ts? Well, if anyone cares...

It is totally possible just to do things like this to get going:

    declare var PouchDB: any;

but for a d.ts that is either official or semi-official I believe this is pointless (and the noise that the current DT file generates probably agrees with this). As has been alluded to above and on twitter:

> Steve Ognibene 
> ‏... a .d.ts file is documentation.
> https://twitter.com/nycdotnet/status/745979472541847553


> Brandon Paddock 
> ... I'm referring to the editor picking up TS definitions (from .ts or .d.ts files) in your project and using it to provide rich IntelliSense and other features.
> https://twitter.com/BrandonLive/status/745729455977431040

the `d.ts` is an api spec so it should document the api. If the return of a method is not really "any" but a "string or a number" then it should say that. This was why my opening public goal for https://github.com/AGBrown/pouchdb.d.ts was: 

> To make typescript use of pouchdb:
> 1. self-documenting through typescript intellisense;

I felt this was achievable by writing a d.ts and ensuring all parameters and return types were typed (and not just with `any`) and by ensuring that we could write the entire pouchdb test suite with typescript using the d.ts file to prove it worked. Some of that proof was "soft" - whilst writing a test, what intellisense feedback did the d.ts give us - was it correct, and helpful? Some of it was "hard" - if we couldn't output the test's js, then the d.ts was wrong. The soft feedback is not exactly regression testable, which is a shame.

There were other goals too (like properly supporting every pouchdb version, not just the latest), but they are irrelevant given I never completed the first one.

We got a long way but the issue I had with the initial effort on pouchdb.d.ts was that it was just me doing it, and later @fredgalvao joined in. By the time we had got 80 % of the way there the amazing pouchdb team were already moving on with the minor versions, and then major versions. 

### Things that slowed us down ...

Documenting pouchdb through d.ts is not without its challenges. The api is large (see, for example, discussions about thenable and callbacks between us and the pouchdb team), the plugins are many (and I haven't even got round to working out how to support plugins yet), and it often feels like there is a large impedance mismatch between a typed d.ts and the very flexible and powerful pouchdb js source code. 

On a positive note the pouchdb team have never failed to give instant, and very helpful feedback when I had questions. 

The pouchdb.d.ts repo needs more, and more capable, dev time to keep up with pouchdb (since I wrote that d.ts both pouchdb, and typescript, have moved on, and so have I; I am neither a typescript or pouchdb expert at the moment).

### </rant>

I would appreciate people taking a look and see if the pouchdb.d.ts is an 80%-there starting point for an up to date d.ts. If not, and the community wants to start over, or it is now too dated to be recoverable then I'll also be grateful for the feedback as I can delete the repo and stop feeling continuously guilty for not updating it, and not really responding to new questions about it (and @nolanlawson would probably also be grateful as he can stop pointing people at it when they ask for a d.ts).

@nolanlawson if you want to play with typescript, maybe the way to learn is "by doing" and you and I can spend a small amount of time going over the current d.ts to work out the gap between it and pouchdb vLatest?

**Comment by daleharvey** [comment]
So if anyone wants to write + maintain pouchdb.d.ts then I would be happy to have that hosted in this repo or on definitelytyped, whichever they decided was best. I would be against (and it looks like in agreement) with writing PouchDB in anything other than standard JavaScript. 

However the best person to write a pouchdb.d.ts is someone who is motivated to do so and interested / knowledgable in pouchdb+typescript, it is most certainly not the responsibility of existing maintainers and I do not think trying to convince maintainers of the benefits is going to be a sustainable solution. 3rd party libraries would do well to work with existing standard JavaScript with little to no friction.

**Comment by geppy** [comment]
@nolanlawson Perhaps this is the wrong place to respond to [your comments on TypeScript](https://github.com/pouchdb/pouchdb/issues/5389#issuecomment-228610251), but from my perspective:

- The versioning problem [is being solved with TypeScript 2.0](https://github.com/Microsoft/TypeScript/issues/9184#issuecomment-226246759), which would have you do `npm install pouchdb@5.4.4 @types/pouchdb@5.4.4`.
- Other languages and toolkits could reasonably reuse TypeScript definitions (I've personally done this).
- As @DanielRosenwasser noted, users of vanilla JavaScript users can benefit from TypeScript definitions (WebStorm already enables this).

It seems to me that one way to dramatically simplify the definitions would be to write separate definitions for the callback-based API and the `Promise`-based API.  I'm assuming that it's fairly uncommon for both styles to be used in the same project.  I'm going to go ahead and try that approach.

**Comment by AGBrown** [comment]
@geppy. I thought that, but then had people tell me they actively used both in the same project. Even some of the pouch tests used both in the same test (iirc).

**Comment by nolanlawson** [comment]
@AGBrown Thanks for your perspective. I would strongly encourage you to just open a PR on DefinitelyTyped ASAP, because it is far more up-to-date than the version in DT and currently your version isn't available via `typings search pouchdb`, meaning it effectively doesn't exist for the vast majority of TypeScript users. Your work is hugely appreciated, and I think any contribution you make will benefit TypeScript+PouchDB users enormously. If nothing else, submitting to DT will make it clear that your version should be the starting point for any future enhancements.

@geppy I missed the thing about versioning. That's very good to hear. It seems to me to be the biggest weakness in TS out of everything I listed, so I'm happy it's being addressed. As for TS having benefits outside of TS... meh. GWT and CoffeeScript all claimed the same thing. (I remember the GWT slogan about ["faster than possible" JavaScript](http://juixe.com/techknow/index.php/2008/06/16/google-io-gwt/), and CoffeeScript arguing that it output [faster JS and less code](http://webcache.googleusercontent.com/search?q=cache:uRaMiOuF4nUJ:readwrite.com/2011/01/07/interview-coffeescript-jeremy-ashkenas/+&cd=2&hl=en&ct=clnk&gl=us), etc.)

For the callback vs promise discussion, I'm not really sure why it's problematic; if you include a `callback` in the args, then it's callback-style, and if omit the `callback`, then it's promise-style. Yes we have historically mixed them in our tests, but I'd be happy to take a PR to make each test only use one or the other (honestly we may drop the callback API at some point and go promises-only, although for now I think callbacks are useful for beginners and old-school Node fans).

**Comment by nolanlawson** [comment]
@AGBrown I propose we resolve this issue by opening a PR on DefinitelyTyped with your version.

**Comment by AGBrown** [comment]
> I propose we resolve this issue by opening a PR on DefinitelyTyped with your version.

@nolanlawson Ok, I'll put that on my queue for the week and get it done asap.

>  @daleharvey I would be happy to have that hosted in this repo or on definitelytyped, whichever they decided was best.

@daleharvey. I think that DT is best being kept as a snapshot and not the primary repo for many reasons. We can just submit the latest `master` to DT whenever it is updated and merged to `master`. 

As for the existing pouchdb.d.ts, if (*if*) you want to start with that then as I mentioned before I'm happy if you want to keep it where it is (as we talked about before with @nolanlawson) or if you now want to absorb it into https://github.com/pouchdb.

**Comment by nolanlawson** [comment]
For now let's just keep it in your repo. Eventually it should get merged
into DT/typings.

**Comment by nolanlawson** [comment]
Closing; we've created a `#typescript` Slack channel and will continue to iterate there.

**Comment by AGBrown** [comment]
@robwormald, @DanielRosenwasser I think we'd really appreciate you looking in on [pouchdb.slack/typscript](https://pouchdb.slack.com/messages/typescript/details/) and joining in with the discussion on how we move this forward (if you have time, of course).
