### ISSUE TITLE
json object null in Cordova SQLite Plugin 2

### ISSUE THREAD

**Issue by rtholmes** [pouchdb/pouchdb#5413]
### Environment (Node.js/browser/hybrid app/etc.)

Browser with current PouchDB 5.4.4 source.
### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

Chrome.
### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

websql with new cordova sqlite plugin 2: https://github.com/nolanlawson/cordova-plugin-sqlite-2
### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

None.
### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

In `api._get` (called by `batchTask.sqlCallback(self, massageSQLResult...`):

```
var item = results.rows.item(0);
metadata = safeJsonParse(item.metadata);
```

Raises an unhandled exception. If I `JSON.stringify(item)`:

`"{"seq":null,"deleted":null,"data":null,"rev":null,"metadata":null}"`

Unfortunately,  `safeJsonParse` throws an uncaught exception because item.metadata above (the str param) is null:

```
function safeJsonParse(str) {
  if (str.length < 5e4) {
    return JSON.parse(str)
  }
  return slowJsonParse(str)
}
```

I'm not sure if this is a result of the sqlite plugin returning the wrong value or if PouchDB should be checking to make sure that the item is complete before trying to parse it.

**Comment by nolanlawson** [comment]
The SQLite Plugin does not run in Chrome (unless you mean Chromium WebView on Android). This looks like a bug in the WebSQL adapter for the browser, not SQLite Plugin.

Do you have a test case to reproduce by any chance?

**Comment by rtholmes** [comment]
Sorry for being unclear @nolanlawson . This is running in a Cordova app. The useragent within the app is ```"Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MOB30M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/51.0.2704.81 Mobile Safari/537.36"```.

The error message itself (caught by ```window.onerror```) is:
```Error in Success callbackId: SQLitePlugin1486841933 : TypeError: Cannot read property 'length' of null```; the plugin itself is ```cordova-plugin-sqlite-2 1.0.4 "SQLitePlugin"```.

The app formerly used ```cordova-sqlite-storage``` and worked fine (I only use the plugin to get around durable storage limits), but I migrated over to the new plugin for better perf. Since it was a migration I never changed the PouchDB instantiation code:
```new PouchDB(name, {adapter: 'websql', auto_compaction: true, location: 'default'}); ```

The database is large (>1800 docs) and the error arises at the end of a ```Promise.all``` that handles a large number of reads from PouchDB. I will see if I can create a minimal test case, but I do not know if it will be easy to do.

**Comment by dozer247** [comment]
I've come across this error as well,  in my case the document has 5642 array items
and i get the following error
```
Error in Success callbackId: SQLitePlugin815980181 : TypeError: Cannot read property 'length' of null
index.js:152365 
Window Error: Uncaught TypeError: Cannot read property 'length' of null in file:///android_asset/www/cordova.js at line 314
cordova.js:314 
Uncaught TypeError: Cannot read property 'length' of null(…)
  safeJsonParse @ pouchdb.cordova-sqlite.js:3665
  (anonymous function) @ pouchdb.cordova-sqlite.js:2720
  (anonymous function) @ sqlite-plugin.js:4439
  onSuccess @ sqlite-plugin.js:4741
  callbackFromNative @ cordova.js:293
  (anonymous function) @ VM44:1

```
The same code runs fine in my iOS cordova application. I've created a small sample app that produces the error

Here are my details
### Issue
I'm trying to do a document update first by doing a get document request followed by a put document request.
I then get an error 
Uncaught TypeError: Cannot read property 'length' of null in file:///android_asset/www/cordova.js at line 314


### Info
- Environment: Cordova android app using pouchdb 6.0.7
- Platform:android 6.0.1
- Adapter:  sqlite using android cordova-plugin-sqlite-2 plugin
- Server: none

### Reproduce
You can clone my github repository at 
[CordovaPouchDBTest](https://github.com/dozer247/CordovaPouchDBTest
)
and run `cordova build `
import the project into android studio and run the app on a device

or  create a cordova project
```
cordova create PouchDBTest
cd PouchDBTest/
cordova platform add android
cordova plugin add cordova-plugin-sqlite-2 --save
```
copy the www directory from my github repository at [CordovaPouchDBTest](https://github.com/dozer247/CordovaPouchDBTest
) to your www directory under PouchDBTest

and run `cordova build `
import the project into android studio and run the app on a device

**Comment by nolanlawson** [comment]
@dozer247 This looks like a bug in the SQLite plugin. The reason I say this is that your bug is that the json object is null rather than throwing a stack exceeded error when we try to parse it. Can you confirm that this occurs only with the plugin and not with IndexedDB/WebSQL? 

Thanks for the repro; I will file a bug on cordova-plugin-sqlite-2.

**Comment by dozer247** [comment]
Yes, it looks like it only occurs with the cordova-plugin-sqlite-2 plugin.

**Comment by nolanlawson** [comment]
@dozer247 I have successfully tracked this down. What you're running into is the Android [1MB limit on Cursors](http://stackoverflow.com/q/5406429/680742), which apparently leads to empty data in the cordova-plugin-sqlite-2 although arguably it should be a more easy-to-diagnose error.

I repro'd your example, and the document you are storing is 3884322 bytes, or 3.88MB. PouchDB is not really designed for storing single documents of this size; a better approach would be to split it up into smaller documents or to use attachments.

**Comment by nolanlawson** [comment]
If you see "Cursor Window is full" in your Android logs, then that indicates you have hit the limit.

**Comment by CatchSandeepVaid** [comment]
@nolanlawson - The link which you shared (1MB limit on Cursors) suggests that "Generally you should avoid blobs in SQLite as they perform poorly; instead save the blob data as a file and store the location of the file in your DB."

But as we are using PouchDB-CouchDB Sync feature, we have to store our videos in pouchdb only. 
On android, after compression our 15 sec video is of 2.4MB and we are getting this error. What can we do in this situation?

**Comment by nolanlawson** [comment]
In this situation you can either 1) use IndexedDB which stores Blobs directly and is thus more efficient than SQLite in this case or 2) don't store your BLOBs in SQLite.

**Comment by CatchSandeepVaid** [comment]
@nolanlawson - 
1) we can't used indexeddb as it's not supported well on iOS (v10).
2) if we dont store blob in sqllite, then how we will sync it with couchdb using pouchdb-couchdb sync mechanism ?

**Comment by nolanlawson** [comment]
If your problem with SQLite is on Android, then you could use IndexedDB for
Android and SQLite for iOS. I think this is actually a great idea because I
mostly wrote the cordova-plugin-sqlite-2 for iOS. You don't really need it
for Android.

If you don't store the binaries in PouchDB then yes you would have to sync
those yourself.

-----
Nolan Lawson
http://nolanlawson.com
https://github.com/nolanlawson

**Comment by CatchSandeepVaid** [comment]
Yes this makes sense.. I ll try this tomorrow and let u know if it works smoothly.. Thanks Nolan.

**Comment by CatchSandeepVaid** [comment]
@nolanlawson  - Is IndexedDB well supported on all android devices? Moreover does it have some data size limitation (like 200MB) or it supports unlimited storage like sqlite?

**Comment by CatchSandeepVaid** [comment]
@nolanlawson -
1.  On Android (5.1), i used indexeddb(idb) adapter with PouchDB. After 200MB sync, i get the  error "pouchdb.min.js:7 Database has a global failure DOMException: An attempt was made to add something to storage that exceeded the quota."
I think the limit for indexeddb is around 200MB. So in my case, using indexed db is not an option as we are supporting data > 200 MB.

2. Second option which u suggested that i should not store blob's in pouchDB and sync them myself. I think this is too tedious for me to implement + here i wont be using pouchDB sync magic. 

3. What we are trying now is: Using cordova-plugin-video-editor plugin, we are compressing video while capturing. We are able to compress video (5sec video takes 0.5MB) without degrading video quality too much. With this approach, we will be able to support only max (around) 8 sec video as we have to adhere to sqlite 1MB limit on android. 

Thoughts?

**Comment by nolanlawson** [comment]
IndexedDB quota is based on available storage on the device, see: https://developer.chrome.com/apps/offline_storage

> Second option which u suggested that i should not store blob's in pouchDB and sync them myself

Put the md5sum hashes in PouchDB, and then sync the blobs separately... yes, you lose the replication magic, but you can just fetch video files on-the-fly. Then you can store metadata in SQLite and blobs in IndexedDB. I dunno, this is what I would do. :)

Compression sounds like a good approach. With an app that syncs 200MB you are reaching the limits of what any mobile app can reasonably do... even Android by default caps its native apps to 50MB (although games can have more if you create add-ons).

**Comment by nolanlawson** [comment]
As for support, Pouch supports IDB in Android 4.4+.

**Comment by CatchSandeepVaid** [comment]
@nolanlawson 
Just to give u some background about my app, my app(built using ionic) is data collection hybrid app (which includes images and videos as well). This app works in iOS and now we have to support android 4.4+ as well. It works in offine mode and for sync i am using pouchdb(adapter=websql/sqlite) magic. This app is for my clients only (not a general app which can be used by anyone). Currently Data size of my app is around 500MB but it can go to 2GB or even more. Currently i am using single couchdb/pouchdb database but when the size goes in GB, i am thinking of splitting it into multiple databases (say 1 per client or 1 per clients project etc.) so that sync can be smooth and we can support selective sync also.

My main question is "how can i support video of say 40 sec (>few MB's) on android and ios?

1. I still didnt got whats the exact quota limit for IndexedDB?

2. 
> Put the md5sum hashes in PouchDB, and then sync the blobs separately

 - Can you please provide me more details on this? Moreover you wrote 

> "you can just fetch video files on-the-fly"

 As my app should work with offline with all data available, i think i cant fetch videos on-the-fly, instead they should be part of some sync process. Right?

3. The 50MB limit which u are taking about is for .apk size and has nothing to do with the data size of the application. Is my understanding correct or am i missing something?
   On android, using sqlite, with compression, i can support only 7-8 sec of video (size ~=0.9 MB) considering i have to adhere to 1MB limit of sqlite.
   FYI: Now google has increased this .apk size limit from 50mb to 100mg (https://android-developers.googleblog.com/2015/09/support-for-100mb-apks-on-google-play.html).
   
   Sorry - I know i have asked too many questions in this post :)

**Comment by CatchSandeepVaid** [comment]
@nolanlawson - Moreover i researched bit more on indexedDB limitation and i think due to these limitations, its not suitable for my app:

1. Storage Limit - It seems, IndexedDB has limit of  6% of the available space on the user's hard drive. 
[](http://stackoverflow.com/questions/10988569/what-are-the-storage-limits-for-the-indexed-db-on-googles-chrome-browser)

2. Not completely Durable - When the limit is reached, chrome (webkit) removes some data (see attachment)
![indexeddb limitation](https://cloud.githubusercontent.com/assets/6469422/22106893/07c9b884-de71-11e6-9809-a42ce7fbc4e2.jpg)

**Comment by nolanlawson** [comment]
The standard solution for this in Chrome is to use the Durable Storage API: https://storage.spec.whatwg.org/ . The Firefox API you mention (https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria) is non-standard and is only supported in Firefox AFAIK, whereas Durable Storage is on track to be supported in all the browsers.

**Comment by CatchSandeepVaid** [comment]
@nolanlawson  - 
1. Can u please let me know how can i use durable storage API + indexedDB + pouchDB such that i get unlimited persistent storage?

2.  In your earlier post, you wrote:
> Put the md5sum hashes in PouchDB, and then sync the blobs separately.
Can you please provide me more details on this?

**Comment by nolanlawson** [comment]
I'm not an expert on the durable storage API; I would have to read the spec to understand how it works. It's a bit new. :)

As for "syncing separately," I mean just calculate an md5sum of the Blob (e.g. using the spark-md5 module) and then store that in PouchDB, then handle the blobs themselves yourself. You can use something like LocalForage to store blobs in IDB.

**Comment by CatchSandeepVaid** [comment]
Regarding "syncing seperately" approach - Can these 2 processes (sync video docs & sync other docs) be part of same sync process? As from user experience perspective, currently we are providing single sync button to user and when he presses this button, we show him infomation like sync started, progress percentage, any error, sync completed etc...

I think either
1. Single Sync Button For User - We need to write a wrapper code which will internally start these 2 syncs, combines their events info (start, progress percent, error, complete etc..) and present combined info to user. 

2. Give 2 separate sync buttons to users. 

I would prefer approach 1). Can you please comment on am i on right path OR am i missing anything?

**Comment by ajayambre** [comment]
@CatchSandeepVaid I am working on a similar ionic application and facing similar issues. Can you please guide/help me and share your experiences?

**Comment by arcadius** [comment]
Just for those having same issue with `cordova-plugin-sqlite-2`,
I have switched to the original `cordova-sqlite-storage` and things seem to be working now
