### ISSUE TITLE
'style' option in sync/replicate API

### ISSUE THREAD

**Issue by htejwani** [pouchdb/pouchdb#5439]
Hi Nolan,

I would like to know if there is any specific reason why the 'style' option that is passed to the changes API, is not exposed in the sync/replicate API. In the sync APi code, the value for 'style' option is hardcoded to 'all_docs'.

We get a  memory leak when there are multiple conflicts in a document and all revisions of the document are downloaded while syncing with the remote server. If there can be an option to change this value to 'main_only' via the API, it would solve the problem for us. Please let us know your thoughts

Thanks in advance.

**Comment by nolanlawson** [comment]
This is a deliberate design decision. If there are conflicts, then those conflicts are supposed to be replicated to all nodes so that conflict resolution can be done client-side. Out of curiosity, what's your use-case that requires only some conflicts to be replicated?

As a side note, it's also possible to write custom replicators. Here's an example: https://github.com/nolanlawson/pouchdb-full-sync

**Comment by htejwani** [comment]
Thanks for your answer. We would like to sync only winning revision and ignore conflicts completely. That's the reason I would like to have it configurable via the API.

**Comment by willholley** [comment]
@htejwani you're probably better off either resolving conflicts proactively (so the bodies don't get synced) or, even better, trying to avoid conflict generation in the first place. Conflicts are an important part of the CouchDB replication model but can lead to performance problems if they go unchecked. 

What's the scenario where your application generates conflicts?

**Comment by nolanlawson** [comment]
Seems answered
