### ISSUE TITLE
PouchDB queries is blocking dom in low configured machine.

### ISSUE THREAD

**Issue by kumarisoni** [pouchdb/pouchdb#5478]
Here is my code to test pouchdb queries:

**Main file:**
var myAudio = new Audio("http://www.stephaniequinn.com/Music/Allegro%20from%20Duet%20in%20C%    20Major.mp3");
myAudio.play();
var worker = new Worker('worker.js');
worker.postMessage("start worker");
worker.addEventListener('message', function(e) {
   console.log('Worker said: ', e.data);
}, false);

**worker.js**

importScripts("pouchdb-5.2.0.min.js");

self.addEventListener('message', function(e) {
    queryDocs();
}, false);

function queryDocs(){
    localDB.allDocs({
        include_docs: true,
        attachments: true
    }, function(err, response) {
        if (err) { return console.log(err); }
        self.postMessage("returned docs:", response);
   });
}

**Steps:** 
1.I am running this in a node.js app, which is playing an audio. 
2.Now , while playing audio I have to query pouchDB.I am limiting the cpu to 60% for all instances of the app with command "cpulimit -p <processId> -l 60.(To test it with low configuration.So that It should work on low configured machine without stuttering)

**Issue:**
 If "cpulimit" command is not used then it's working fine means I am able to query the pouchdb without audio stuttering , but if I am limiting the cpu using command "cpulimit"., then audio is stuttering.

**Expected result:**
How can I make it work on low configured machine without stuttering?

**Comment by daleharvey** [comment]
How many documents do you have and how many attachments / how large are they? paging the results or fetching without attachments and reading them later may help? not sure there is much we can do on the pouch side, its just reading what its being told to

**Comment by nolanlawson** [comment]
PouchDB blocks the DOM due to IndexedDB, and there's nothing we can do about it because it's how the browser works. I wrote a blog post about it here: https://nolanlawson.com/2015/09/29/indexeddb-websql-localstorage-what-blocks-the-dom/

Luckily there is a solution: use PouchDB inside of a web worker. I did this in an open-source webapp (http://www.pocketjavascript.com/blog/2015/11/23/introducing-pokedex-org) for which the code is all available online so you can see how I did it. Other resources to help you out:

- https://github.com/nolanlawson/promise-worker
- https://github.com/nolanlawson/worker-pouch

Please let me know if I misdiagnosed your problem; I'm not sure because you say "the DOM is blocked" but you also say you're using Node.js - I assume the server is Node.js but the DOM blocking is occurring in some browser?

Please reopen if this doesn't describe your issue.

**Comment by kumarisoni** [comment]
I am simultaneously trying to compile the same codebase for both the tablet, as well as the desktop, using cordova, and node webkit respectively. The problem occurring is in the node webkit environment, where I believe the code is run in node and not in the webkit browser. 
I tried using  the pouchdb webworker version which you have mentioned, but it does not give significant improvements. 
Main file:
<html>
<head>
    <script src="pouchdb-5.2.0.min.js"></script>
    <script src="pouchdb.worker-pouch.js"></script>
    <script>
          var localDB = new PouchDB('mydb', {adapter: 'worker'});
          function fetchDocs() {
              localDB.allDocs({include_docs: true,attachments: true}, function(err, response) {
                  if (err) { return console.log(err); }
                  console.log(response);
             });
          }
   </script>
</head>
<body>
    <button onclick="fetchDocs()">Click me</button>
</body>
</html>
I am using this code within node-webkit. As far as I understand, in node-webkit, the javascript is executed in nodejs and not in the browser context. so, I have implemented pouchdb within a worker in node-webkit and this is also blocking the dom.
One of the reasons I feel that this might not be working based on what i have read on the internet is  that web workers do not work in node js. Is that correct ? 

Would you recommend I use leveldb instead of indexeddb ?

**Comment by kumarisoni** [comment]
I am simultaneously trying to compile the same codebase for both the tablet, as well as the desktop, using cordova, and node webkit respectively. The problem occurring is in the node webkit environment, where I believe the code is run in node and not in the webkit browser. 
I tried using  the pouchdb webworker version which you have mentioned, but it does not give significant improvements. 

I also implemented pouchdb within a worker in node-webkit and this is also blocking the dom.
One of the reasons I feel that this might not be working based on what i have read on the internet is  that web workers do not work in node js. Is that correct ? 

Would you recommend I use leveldb instead of indexeddb ?

**Comment by nolanlawson** [comment]
> I also implemented pouchdb within a worker in node-webkit and this is also blocking the dom.

PouchDB can work in two ways on node-webkit: in "browser mode" or in "Node mode." You can figure out which is which by printing `new PouchDB('my database').adapter`. If the adapter is leveldown, then it's Node.

> One of the reasons I feel that this might not be working based on what i have read on the internet is that web workers do not work in node js. Is that correct ? 

Web workers do not exist in Node.js, you are correct.

So, this is a very complex issue becuase you are using both Cordova and Node-Webkit. It's subtely different in both.

In Cordova you also don't have support for Web Workers, so if you want the database to run on a background thread, you would need to use SQLite Plugin or SQLite Plugin 2, the problem being that it will still probably block the DOM due to overhead of serializing data sent between the native layer and the WebView.

Node-Webkit may or may not support web workers; I don't know. If you run PouchDB in "Node mode," however, then it should run in a background thread. If not, you may want to look into Electron, which I am certain does run "Node mode" JavaScript in a background thread.

`worker-pouch` may end up continuing to block the DOM depending on your use case, because it doesn't isolate PouchDB 100% in the worker, but more like 70%. Hence why I typically recommend people to avoid it if they can and run PouchDB 100% inside the web worker.

Another possibility is that this issue has been completely misdiagnosed and it's something else blocking your DOM. Did you try running the Chrome profiler to see what the longest-running JavaScript operations are?

Happy to try to advise you here, but this is a very complicated problem and there are no easy answers.

**Comment by kumarisoni** [comment]
@nolanlawson ,
Thanks for the clarification, I checked in chrome profiler, pouch.worker-pouch.js is the longest running script.
When I am printing new PouchDB('mydatabase').adapter, I am getting "idb" .If I am using worker version of pouchdb with adapter worker , then it's printing "worker".
I used pouchdb in childprocess .Here it is printing "leveldb".
It  seems to be solving the problem of blocking Dom if pouch related queries are done in child process.
I feel this issue is occurring due to blocking of indexdb.
So, closing issue #5478 for now.
