### ISSUE TITLE
WebSQL crashes when attachments are >1GB

### ISSUE THREAD

**Issue by adamlofts** [pouchdb/pouchdb#5500]
### Environment (Node.js/browser/hybrid app/etc.)

hybrid app

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

Android

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

WebSQL (cordova-plugin-sqlite-2)

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

CouchDB

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

I got this traceback. I think PouchDB is trying to sync an attachment.

`
TypeError: Cannot read property 'length' of null
    at parseHexString (file:///android_asset/www/build/web/static/pouchdb-5.4.5.js?__version=623165004:5795:47)
    at SQLTask.sqlCallback (file:///android_asset/www/build/web/static/pouchdb-5.4.5.js?__version=623165004:7139:9)
    at file:///android_asset/www/plugins/cordova-plugin-sqlite-2/dist/sqlite-plugin.js:4439:19
    at onSuccess (file:///android_asset/www/plugins/cordova-plugin-sqlite-2/dist/sqlite-plugin.js:4741:5)
    at Object.callbackFromNative (file:///android_asset/www/cordova.js:293:58)
    at processMessage (file:///android_asset/www/cordova.js:1081:17)
    at processMessages (file:///android_asset/www/cordova.js:1104:9)
    at pollOnce (file:///android_asset/www/cordova.js:973:9)
    at pollOnceFromOnlineEvent (file:///android_asset/www/cordova.js:960:5)"`

If I set a breakpoint in the transaction handler I can see that result.rows is:
`WebSQLRows {_array: Array[1], length: 1}`

and results.rows.item(0) is:
`Object {escaped: null, body: null}`

**Comment by nolanlawson** [comment]
Can you provide a test case to reproduce? Just looking at it, it seems like somehow we wrote empty attachments to the database, but I'm not sure without a test.

One piece of advice I can give you is that cordova-plugin-sqlite-2 is not really designed to be used in Android; IndexedDB is almost always a better option except in rare cases.

**Comment by adamlofts** [comment]
I agree with your assessment. I don't have a test case since I didn't catch the issue when adding attachments. I'll see if I can reproduce manually.

The reason I used the plugin is because I want to be able to store large amounts of data (> 1GB).

**Comment by adamlofts** [comment]
I've started to look through the attachment code and whilst I don't think this is the root cause of the issue this line looks suspect to me:

https://github.com/pouchdb/binary-util/blob/master/index.js#L75

This code returns an empty ArrayBuffer if the environment fails to read the blob. Wouldn't it be better to propagate an error if the reader fails? Would you accept a patch to convert this function to return a promise?

Do you know why insertion performance is bad with big databases? 1GB would seem OK for a pure SQLite database. Can you point me in the direction of any potential performance improvements I could look into?

**Comment by nolanlawson** [comment]
It probably would be better to propagate an error, but IIRC that code path doesn't allow for any error. It just assumes that the blob was stored correctly, which ideally it should have been.

You could submit a PR, but it'd be tricky to test unless you can find a test case where we store an invalid blob, in which case we'd want to just patch the code so we don't store an invalid blob. :wink:

1GB will be a problem for the SQLite Plugin because 1) Cordova plugins need to stringify all messages between WebView and native context, and 2) WebSQL has an API limitation where everything needs to be stringified. So you're passing 1GB of strings around basically. This is why IndexedDB is better on Android anyway (except for the whole "no durable storage" thing, but there's no workaround for that until browser vendors ship the new Storage APIs).

**Comment by nolanlawson** [comment]
Did you look into preloading BTW? Another option would be to write native Java code to build up the database, then let the JavaScript app take it away from there.

**Comment by adamlofts** [comment]
One possible chain of events which may cause FileReader to fail would be:
1. User selects a file with a FileInputElement.
2. App stores a reference to element.files
3. File is deleted from filesystem (e.g. by the OS)
4. App tries to pass element.files to PouchDB.putAttachment()

Pretty hard to write a test case for that :) Do the test cases allow for injecting a TestFileReader which always throws an error when reading the blob? The idea would be to propagate the error all the way up to putAttachment.

Appreciate the info regarding WebSQL performance. The reason I haven't looked into preloading is that insertion performance is not a huge issue for me so far. It takes a long time to replicate the db initially but I'm not so worried about a slow initial load if the data is persistent.

The main issue I've been hitting is poor reduce performance for which I have a plan to write a custom indexer. My reduce functions are all just counting the number of docs with a given tag so a custom indexer can just keep a running total and avoid a full table scan.

**Comment by nolanlawson** [comment]
Hm, yeah, I see how corruption could happen that way. When you pass an Blob into PouchDB, we actually [copy it immediately to another Blob](https://github.com/pouchdb/pouchdb/blob/37fe1bc5a482b230fe9aa810a5419cbcde06da40/packages/pouchdb-utils/src/cloneBinaryObject-browser.js). Ideally we would prevent the entire transaction from writing if the underlying Blob changed at all during that operation. 

I don't think the FileReader is the right part of the code to address this, though. We ought to throw an error at write time rather than read time, because that would limit the damage of the corrupt attachments and ensure empty attachments don't get written to disk in the first place. Keep in mind that that FileReader code only gets touched during insertion in the case of WebSQL/LevelDB and not IndexedDB, since in IndexedDB we just directly pass the Blob to IDB.

So we would still need a solution for IDB. One potential solution would be to compare the md5sums of the uncopied Blob to the that of the copied Blob after cloning. However this can still fail if the Blob is already corrupted by the time PouchDB starts copying it. So the only way I can think of is to have the user pass in an md5sum and ask us to verify its integrity before committing to disk, but really this just passes the problem onto our users, in which case we could also solve it more simply by just asking users to verify their own Blobs before they pass them into PouchDB.

So ultimately given PouchDB's inability to solve this problem in its current design, I feel like that's the correct solution here. Unless you can think of something else. Admittedly it's a very hard problem.

**Comment by nolanlawson** [comment]
For your indexer BTW, one solution would be to prebuild the index as well and also pass that in as a SQLite file. Keep in mind that PouchDB map/reduce indexes are basically just separate PouchDBs using the pouchdb-collate project under the hood, which you can implement yourself if you so desire.

**Comment by adamlofts** [comment]
I'm able to reproduce the issue with an attachment. Unfortunately I can't share the attachment with you but hopefully I can describe the issue. The attachment is approx 2Mb in size. I think it is getting stored in the DB correctly but `Cursor.getType()` is returning `Cursor.FIELD_TYPE_NULL`.

It seems that Android has a 1MB limit when reading BLOBs from the DB.

http://stackoverflow.com/questions/12716859/retrieve-large-blob-from-android-sqlite-database

Weirdly though if I try to write a simple test case the attachment is truncated rather than NULL. I guess that is still a bug.

`
document.addEventListener("deviceready", function () {
  PouchDB.debug.enable('*');

  var db = new PouchDB('' + new Date, {adapter: 'websql'});
  var buf = new ArrayBuffer(1024 * 1024 * 2);
  for (var i = 0; i < 1024 * 1024 * 2; i += 1) {
    buf[i] = 0xF1;
  }
  db.put({
    _id: 'x',
    _attachments: {
      a: {
        content_type: 'application/pdf',
        data: new Blob([buf])
      }
    }
  }).then(function (res) {
    return db.get(res['id']);
  }).then(function(doc) {
    console.log(doc);
    return db.getAttachment(doc['_id'], 'a');
  }).then(function(a) {
    console.log(a);
  });
}, false);
`

**Comment by nolanlawson** [comment]
Ah, that explains it. Yeah, I wouldn't recommend trying to store attachments > 1GB, especially since they need to be serialized as strings and sent from the WebView to the native view, meaning you need >1GB in memory which will crash on older Android phones.

We considered a system in PouchDB where we automatically shard attachments for the user, but never got around to it. In this case a better solution is 1) using IndexedDB, or 2) breaking up attachments yourself.

**Comment by adamlofts** [comment]
Hi Nolan. The issue was with an attachment > 1 MB (not 1 GB) due to a corresponding limit in the SQLiteDatabase Cursor (http://stackoverflow.com/questions/5406429/cursor-size-limit-in-android-sqlitedatabase). So this problem only affects the sqlite-2 plugin on Android.

**Comment by nolanlawson** [comment]
Sorry, typo.

In any case, I'm not sure this is an issue that PouchDB can/should try to solve at the WebSQL level. Conceivably we could split up large Blobs for our users, but perhaps it makes more sense to ask users to handle this themselves, since you may run out of memory anyway if you are slinging around >1MB attachments.

For now I will say that this issue should be closed, because the long-term solution for PouchDB and the web platform as a whole is to move towards IndexedDB and native Blob support, since this avoids both the attachment memory issue and the Android SQLite BLOB limit issue.
