### ISSUE TITLE
Database backend in node

### ISSUE THREAD

**Issue by hemendra-srivastava** [pouchdb/pouchdb#5510]
### Environment (Node.js/browser/hybrid app/etc.)
Node.js

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)
Node Webkit

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)
Looking for a good adapter

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)
Couchdb

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!
I am looking for a good crossplatform database backend to use with pouchdb and node webkit. Specifically, i plan to run this database in a child process, and thus need it to run with node js and not in the browser context.
I tried leveldb, and though it works painlessly on linux, i do not understand how i will be able to compile it with nw-gyp on the client machine, since i am packaging everything as an exe and i require it to run on windows without much issue.

I tried looking for other backends, and found a couple of embedded databases, 
https://github.com/louischatriot/nedb
http://ejdb.org/

I was wondering if i can integrate these with pouchdb, by writing say, a levelup adapter. Could you help me out as to how i should proceed with this. 

Regards,
Hemendra

**Comment by hemendra-srivastava** [comment]
P.S. I also tried sqldown, but was unable to get it working with node webkit.

**Comment by nolanlawson** [comment]
SQLdown is not very well tested, but you could try https://www.npmjs.com/package/pouchdb-adapter-node-websql

BTW there is a sample project that shows how to use PouchDB with Node WebKit. It worked on a Mac last time I checked, but I'm not sure about Linux or Windows: https://github.com/nolanlawson/pouchdb-nw-hello-world

Another option that I've heard people have success with is using Electron instead of Node WebKit.

**Comment by nolanlawson** [comment]
Closing since this sounds like more of a NW issue than a PouchDB issue; I don't know off the top of my head how NW handles native modules and whether you're supposed to compile them on the client or during the build process, but my assumption would be that you're supposed to do it during the build process, i.e. build it on Windows and then build the .exe that way. Let me know if that info helps.
