### ISSUE TITLE
New 5.4.x version with updated request dependency?

### ISSUE THREAD

**Issue by the-t-in-rtf** [pouchdb/pouchdb#5528]
[snyk](https://snyk.io/) reports vulnerabilities against 5.4.5 based on the use of the older version of `request`.  I see it's already updated in master.

I know you're working on the next major version, but any chance of getting a 5.4.6 release with the updated dependencies?

**Comment by nolanlawson** [comment]
Sure, I was planning on doing a 5.4.6 this weekend.

**Comment by the-t-in-rtf** [comment]
Great, thanks.  Is there another ticket I can watch for that, or will you close this one when that's done?

**Comment by nolanlawson** [comment]
I'll close this one.

**Comment by wtgtybhertgeghgtwtg** [comment]
Why is `request` a dependency, anyway?  It looks like it's only used in tests, so couldn't it/shouldn't it be a devDependency?

**Comment by KlausTrainer** [comment]
Hi @wtgtybhertgeghgtwtg!

PouchDB can run not only in browsers, but in Node.js as well. There, it will use `request` instead of `XMLHttpRequest` or `fetch`.

Since a couple of months, we now have PouchDB custom builds. With them, you can choose a PouchDB package that only contains the bits that you need. You can even go wild and build your own; for instance a custom build without WebSQL support, if that's what you want :)

See the [custom build announcement](https://pouchdb.com/2016/06/06/introducing-pouchdb-custom-builds.html) on the PouchDB blog, and the [custom builds documentation](https://pouchdb.com/custom.html).

**Comment by KlausTrainer** [comment]
@wtgtybhertgeghgtwtg also see [pouchdb-server](https://www.npmjs.com/package/pouchdb-server).

**Comment by daleharvey** [comment]
released

**Comment by the-t-in-rtf** [comment]
@daleharvey, I don't see a new 5.4.x release.  I assume by "released" you meant "addressed in a later release of 6.x"?

**Comment by daleharvey** [comment]
Yup thats what I meant

**Comment by the-t-in-rtf** [comment]
Thanks.  6.0.2 works fine for me.
