### ISSUE TITLE
websql not finding bindings for electron

### ISSUE THREAD

**Issue by bgrayburn** [pouchdb/pouchdb#5535]
### Environment (Node.js/browser/hybrid app/etc.)

Electron (in main process)

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)
OSx

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

WebSQL

### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

pouchdb with websql

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!
I installed `websql` from npm, required with `require('pouchdb/extras/websql')`, and added to PouchDB instantiation with `{adapter: 'websql'}`.
Getting this error when I try to start an electron app.

`Error: Cannot find module  '...<project folder path>/node_modules/sqlite3/lib/binding/electron-v0.37-darwin-x64/node_sqlite3.node'`

I installed sqlite3 using `npm install sqlite3` but true to the error, there is no electron-v0.37... folder in the sqlite3/lib/binding folder.

**Comment by bgrayburn** [comment]
I was able to replicate this problem in the [hello-electron-with-pouchdb](https://github.com/nolanlawson/hello-electron-with-pouchdb) example by replacing the version number for electron-prebuilt in package.json to `^0.37.8` then `npm install`ing followed by `npm run start`

**Comment by nolanlawson** [comment]
Yeah you have to specify the exact Electron version when installing on both the command line and in `package.json`. It's an unfortunately common source of bugs.

I.e. if you change the version to 0.37.8 then you're also going to need to change the` postinstall` script to use 0.37.8 as well. Caret versions are unrecommended because you have to know the exact version number.

I'm working on a fix to hello-electron-with-pouchdb to make it so you only have to define the version number once; I opened an issue here: https://github.com/nolanlawson/hello-electron-with-pouchdb/issues/2

**Comment by nolanlawson** [comment]
Unfortunately sqlite3 is apparently broken in the latest version of Electron (or latest version of sqlite3, I can't tell). I opened another issue to track that: https://github.com/nolanlawson/hello-electron-with-pouchdb/issues/2
