### ISSUE TITLE
Remove Lerna

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5545]
Based on discussion with @boennemann I think we can remove our Lerna dependency and vastly speed up our build times by avoiding `lerna bootstrap`.

We already don't use Lerna for building (because `lerna run` is slow due to running multiple processes, so I wrote one big top-level build script) or for publishing (because I didn't take enough time to grok the Lerna docs on this, we're not using `version: independent`, and I found a bash loop with `npm publish` to be simpler), so `lerna bootstrap` is the only thing we're currently using it for.

@boennemann pointed out that we can achieve the same effect as `lerna bootstrap` with a few changes:

- `packages/` becomes `packages/node_modules`, and due to how `require()` works this means that inter-dependencies are automatically resolved.
- Common dependencies go at the top-level `package.json` (separate from `devDependencies` used for building). At publish time, we just substitute the version numbers in the sub-packages' `package.json` with the version number from the top level. One trick we can do here is to scan the JS files for `import`s and automatically add the correct dependencies, which means there's no more need to update the same dependency multiple times in multiple sub-packages, nor will we have bugs like we had with `js-extend` where we were accidentally using different versions in different sub-packages. If this trick doesn't work, we can also just include `*` versions in the `package.json`s and then replace those at publish time.

@boennemann wrote up his ideas here: https://github.com/boennemann/alle#readme

**Comment by garrensmith** [comment]
I'm going to hold off on the pouchdb-server monorepo work until we have a good solution for pouchdb.

**Comment by yaronyg** [comment]
In which case doesn't this mean that Express-PouchDB is now unworkable for the duration? The old code won't build tests because of PouchDB and the new code isn't finished?

**Comment by garrensmith** [comment]
Hi Yaron, I'm really struggling to find time to work on this. You welcome to continue the work. Otherwise I'll pick it up once Nolan has come up with a better way of managing monorepo's

All misspelling thanks to my iPhone

**Comment by yaronyg** [comment]
Garren, that is totally fair and I should have prefixed the message with "and this isn't a complaint". This is an open source project, if someone wants something the default is that they should bloody well do it themselves (in this case, if I want Express-PouchDB passing tests then I better get busy and fix the repo!). The purpose of my question was just to make sure I understand the situation properly. That right now Express-PouchDB can't accept PRs because it can't run tests and those tests won't run until the repo situation is fixed.

But in a way I'm kind of in the same place you are. Even if I wanted to fix it, how should we fix it? At this point I would just finish with Lerna and live with PouchDB-Server. But my guess is that what we'll do is continue to make fixes to [my fork](https://github.com/yaronyg/pouchdb-server/tree/thali-release) and probably even publish a version from there as thali-express-pouchdb and then switch back to mainline Express-PouchDB once the situation about what to do in the repo becomes clearer.

**Comment by garrensmith** [comment]
Thanks Yaron. The master branch of express-server and pouchdb-server are working fine and passing all tests but the tests do sometimes fail due to timeouts. The Lerna branch just needs a fair amount of cleaning up before it's ready. I might have a bit of time tomorrow or Thursday to look. I'll try get it closer to done and let you know. 

All misspelling thanks to my iPhone

**Comment by yaronyg** [comment]
Sorry for being a pain Garren but I'm missing something. I went to https://github.com/pouchdb/express-pouchdb and ran npm test and 10 tests passed and 5 immediately failed causing the test to abort due to 'timeout of 2000ms exceeded'. 5 tests failed like that. I'm using npm 3.10.5 with node 6.3.0. That doesn't seem like a transient failure. Were you expecting it to usually work (with an occasional failure). Or am I in the wrong repo or branch?

**Comment by nolanlawson** [comment]
Fixed in 9b51141a4a54ec79ac774c6117b5aa4c986d785b

**Comment by cdaringe** [comment]
wait WAT!  how... are... you... even! :)

where exactly are dependencies getting re-injected into `package.json`s?  Immediately pre-publish, only temporarily?  This is _exciting_ stuff. 👍
