### ISSUE TITLE
batch_size is not respected when using doc_ids during replication

### ISSUE THREAD

**Issue by samhcorney** [pouchdb/pouchdb#5576]
### Environment (Node.js/browser/hybrid app/etc.)

Browser
### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

Chrome 52.0.2743.116 (64-bit)
### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

WebSQL
### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

CouchDB
### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

When replicating or syncing from a remote CouchDB server with the following options only the first 10 documents are replicated...

`localDB.replicate.from( remoteDB, { doc_ids: [ 16_IDS_HERE ], batch_size: 10 } );`

The issue seems to come about when specifying both ids and batch_size together.

**Comment by nolanlawson** [comment]
In other words, the bug is the `batch_size` is not respected when you also use `doc_ids`.

**Comment by wholien** [comment]
@nolanlawson if I want to work on this, what parts of the code should I look at?

**Comment by nolanlawson** [comment]
Most likely this part of this code: https://github.com/pouchdb/pouchdb/blob/9c46dec6717182d93f3992de8235ed60051fac3f/packages/node_modules/pouchdb-replication/src/replicate.js#L380-L387

Step 1 is to figure out what CouchDB does if you give it a lower `limit` than the number of `doc_ids` when calling `_changes`, and check that the behavior matches PouchDB's `changes()` function. If it matches, then the fix is in that link above. If not, then we'll need to fix PouchDB's `changes()` function, which is located in `pouchdb-core` in `changes.js`.
