### ISSUE TITLE
Drop records in response to browser storage limit?

### ISSUE THREAD

**Issue by gordonbrander** [pouchdb/pouchdb#5596]
### Environment (Node.js/browser/hybrid app/etc.)

Browser.
### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

All.
### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

All.
### Server (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)

N/A
### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

It looks like Pouch will [throw an error](https://github.com/pouchdb/pouchdb/issues/892) if the [browser storage limits have been reached](https://pouchdb.com/faq.html#data_limits) [a] [b], but I am unclear on what to do next in this case.
- How does Pouch handle this case? Does it refuse to write to database, or does it drop records currently in database to make room?
- Is there a way to drop documents from the local db (but NOT delete from CouchDB)?
- Is the answer "delete locally, but be careful not to replicate back to CouchDB"?

My specific case: I'm doing filtered replication against a fairly large database and am hoping to sync a rolling buffer of most recent documents to local DB.

Thanks!

[a] https://pouchdb.com/faq.html#data_limits
[b] https://github.com/pouchdb/pouchdb/issues/892

**Comment by nolanlawson** [comment]
TBH we don't have a strong story here. Every browser throws a different kind of error at different limits and in different ways. Some of them you can't even respond to as a developer (e.g. the Safari popup).

Ultimately we're trying to fix this at the spec level with the "persistent storage API" but in real-world terms the best thing to do is just to never hit the limit.

That said, I would love a PR to PouchDB to research all these browser storage limit errors and harmonize the way we emit errors, if possible.

**Comment by gordonbrander** [comment]
@nolanlawson ok, this might be something I could help with, but I need a better idea of how the Pouch/Couch syncing model works.

Pouch seems to be designed around the idea of being a replica of the CouchDB. Handling the case where Couch is bigger than Pouch means breaking with this model somewhat.

- Do we have a clear story for how the Pouch/Couch syncing works in cases where Pouch is a subset of the CouchDB?
- Pouch sends a rev to Couch to determine who is "out of date", correct?
- What if Pouch is a subset (filtered, limited) version of Couch? Does this rev-based approach still work?  How would it decide what to sync, what too keep, what to drop?

Apologies if any of these are dumb questions -- I haven't much experience with the details of Couch's syncing model.

**Comment by daleharvey** [comment]
The ability to have a rolling window of replicated documents is one of the most requested features of PouchDB, its quite a tricky problem since everyones use case is slightly different but its possible to do right now, and something we definitely want to improve the story on. 

The main issue right now is the lack of purge, purge entirely destroys a record, gives you back its space and unlike `delete` does not replicate back to the source, so implementing that (https://github.com/pouchdb/pouchdb/issues/802) would be a huge step towards making those use cases easier. In the meantime without changes to pouchdb its possible replicate the effects of purge by using your own rolling database, basically replicate your local database with a filter to another local database and destroy the original, that way your filter can say "last X documents" or "documents since June" etc and they will not exist within the new database

**Comment by daleharvey** [comment]
When we have purge implemented I think we may be able to do something along the lines of having the replicator use purge locally when it sees remote documents deleted (without conflict), also possibly purge documents locally that no longer match a replication filter

**Comment by gordonbrander** [comment]
Seems that if purge existed, it would be relatively easy to write the rolling database logic on a case-by-case basis, no?

**Comment by daleharvey** [comment]
Yup I think purge will be the base for any improvements we want to make around this use case

**Comment by nolanlawson** [comment]
this seems covered by #802
