### ISSUE TITLE
[Question] How much overhead does requesting a doc along with `revs_info` adds?

### ISSUE THREAD

**Issue by danielo515** [pouchdb/pouchdb#5605]
### Environment (Node.js/browser/hybrid app/etc.)

Browser

### Browser/platform (Chrome/FF/Safari/Edge/iOS/Android/etc.)

Chrome,FF,Android

### Adapter (IndexedDB/WebSQL/LevelDB/etc.)

Default

### Please describe your issue. Test cases (e.g. JSBin) are very helpful!

Hello,

I want give my users the option to see a document's revisions. At first I tough about loading the document, and when the list of revisions is requested then load the revisions list. But, since requesting the revisions list also returns the document, I was thinking about doing it in one go.

So, instead of

```js
db.get('MyDoc')
.... something happens, revisions are required ....
db.get('MyDoc',  { revs_info: true})
```

Just do
```js
db.get('MyDoc',  { revs_info: true})
```

But I'm a bit worried about performance and memory footprint. I think the difference in memory is not big (at the end, is just an array of objects) but I am not so sure about fetching performance.

Any guidance is very welcome.
Thanks in advance.

**Comment by nolanlawson** [comment]
You would have to benchmark this to figure it out, and it may differ from adapter to adapter. I imagine the overhead is not that high, though, since it's just pulling up metadata basically.

Closing since this is a question rather than a clear issue; I'd invite you to do a benchmark in various browsers using `performance.now()` and see what kind of effects you get. 😃
