### ISSUE TITLE
Documentation: valid database names 

### ISSUE THREAD

**Issue by danielo515** [pouchdb/pouchdb#5610]
Hello 

I really miss a section about naming the databases. I need to know which kind of names are allowed, valid and invalid characters and that stuff. 

According to couchdb documentation valid names are all lowercase, but in pouch I have used names like MyDatabase and they worked. That's why I'm opening this issue, because it seems to differ on PouchDB. 

Regards

**Comment by willholley** [comment]
Agree we should document what is allowed locally.

Others may disagree, but I think it's ok for different implementations to have different restrictions around database names - PouchDB can't control what Cloudant/Couchbase/CouchDB enforce, and there's no requirement for database names to be consistent on either side of a replication.

**Comment by danielo515** [comment]
Not to mention that local databases and remote ones are created separately. I mean, you don't create a local database and then you "upload" it, you have to create remote database specifically for the backend you are going to connect to, so you should consider the limitations there, but not locally.

Also in some situations and offline apps you may let the end-user name the database so the less restrictions the better.
Regards.

**Comment by danielo515** [comment]
Thanks for the information @stale bot
It's sad to see that a documentation requirement will be closed just because not enough activity is registered

**Comment by daleharvey** [comment]
@danielo515 thats what the stale bot is there for, if you want to make this change yourself then would be happy to help you do it. If you dont want to make the change then would rather you dont make us track it

**Comment by danielo515** [comment]
I think the initial intention was to fix the problem. For that matter an issue is a very good reminder and a way to document an improvement.
Automatically closing all kind of issues seems like an antinatural solution. It should, for example, ignore documentation issues, as they are not un hurry but are good to have track of.

**Comment by daleharvey** [comment]
The documentation can always improve, things can always be faster, we could always support more platforms etc. Having to maintain a large backlog of issues is a huge overhead for maintainers, so much so that I have avoided even filing bugs in the last few months to a year because I know that I wont get to fix all of them and the rest will be added to a big list for me to maintain. 

stalebot allows us to track what people are working on, the entire bug list can be understood and bugs are certain to be 1. relevant, not some discussion point from last year, and 2. noticeable, not lost in a list of hundreds, thousands even millions

So as said, if you want to contribute then I would be happy to help you out, if you do not want to contribute then if you could leave the bug tracking to the ones that do, cheers

**Comment by danielo515** [comment]
Hello @daleharvey ,
Of course I will not tell you how to manage your issues, I'm just exposing my point of view about this particular topic. All what you have said is true. I'm just worried about this problem not being fixed in the present nor in the future.
When people wants to contribute to certain project, taking a look at easy to implement issues (and this is one of them) it's a good starting point.
Of course my point of view is narrow since I don't have any product/library of such success.

I would like to contribute to resolve this. If you point me to:
1. The part of the code that I can check to deduct the valid names
1. The part of the documentation where I should add this information
1. Guidelines to contribute

Regards

**Comment by daleharvey** [comment]
The only thing we check is that the name is a string @ https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-core/src/constructor.js#L58 Otherwise we defer to the implementation, indexeddb has not restrictions as far as I know and couch has http://docs.couchdb.org/en/2.1.1/api/database/common.html#put--db, I think it would be best if we didnt specify the name rules (that may go out of sync) but refer them to the relevant couchdb / indexeddb docs

This should go @ https://github.com/pouchdb/pouchdb/blob/master/docs/_includes/api/create_database.html#L11 and the contributing guide is @ https://github.com/pouchdb/pouchdb/blob/master/CONTRIBUTING.md
