### ISSUE TITLE
iOS Chrome silently fails

### ISSUE THREAD

**Issue by ksmithut** [pouchdb/pouchdb#5642]
### Issue
I was upgrading to version 6.x on one of my side projects, and noticed that on iOS Chrome, nothing was running. Once I removed pouchdb from my build, it started working again.

### Info
- Environment: browser
- Platform: iOS Chrome
- Adapter: Whatever is selected? Could be a part of the issue
- Server: N/A

### Reproduce
Include pouchdb 6.x (6.0.4 used) into a webpack build (may still break without webpack). This is incredibly hard to debug because iOS only really supports remote debugging on Safari. I ended up using [weinre](http://people.apache.org/~pmuellr/weinre/docs/latest/), but no error was output to the console. I ended up just going through my module tree and once I removed pouch, my build started working.

**Comment by nolanlawson** [comment]
PouchDB does not support iOS Chrome or iOS Firefox out of the box, because both of them use WKWebView, which has broken IndexedDB support and no WebSQL support.

Currently the only workaround is to use the localstorage adapter or the memory adapter if you want to support iOS Chrome/Safari. When iOS 10 comes out, it'll also be fixed because Apple will have re-enabled WKWebView.

Have you seen a difference between v5 and v6? In my recollection, both of them should fail, although they may fail in different ways, which is what I believe you're seeing.

**Comment by ksmithut** [comment]
v5 seems to work fine, but I haven't done any migrating. I'm just using the `pouchdb` package, but perhaps I should be using `pouchdb-browser`?

I'm fine closing this, especially since it's not officially supported. I just need to read the migration guides and eat my vegetables.

**Comment by nolanlawson** [comment]
@ksmithut That's really odd; v5 shouldn't be doing anything different here from v6. In fact it should fail in iOS Chrome. What adapter is it using under the hood? Can you check by running `db.adapter`? Also try doing `db.allDocs()` and make sure it's actually storing data.

**Comment by ksmithut** [comment]
Oh, you're right. Nothing is actually saved in v5 either. _feeling sheepish_. The difference is that in v5, the rest of the javascript can run. It builds, lets my React run just fine. in v6, I get the white screen of death as soon as pouchdb gets run.
