### ISSUE TITLE
Memory Leak on iOS

### ISSUE THREAD

**Issue by CatchSandeepVaid** [pouchdb/pouchdb#5646]
### Issue

We have few docs containing images and videos (around 300MB data) in our couchdb which we want to sync with pouchdb. When we try to sync these docs, memory keeps on increasing. iOS does GC but doesnt comes back to same level and creates higher memory tops. After some time, we see memory warning on xcode and our app crashes. 

NOTE: On android, when we start the app, the memory consumption is around 120MB, when we sync it goes to 600MB and after sync complete, it comes down to around 180 Mb and app doesnt crash.
### Info
- Environment: hybrid app (ionic)
- Platform: ios 9.3.5
- Adapter: We tried with all adapters
- Server: CouchDB
- Device : iPad Air/ iPad2
- PouchDB version - 5.4.4/5.4.5

**Comment by seigel** [comment]
Do you have a step by step to get it into this state?  Is it just videos or any large documents?  Do you have the videos as attachments or encoded in the document?

**Comment by nolanlawson** [comment]
I would not recommend syncing 300mb attachments with PouchDB. It's not optimized for this because it does not do streaming/chunked delivery. You can try adjusting batch_size or batches_limit to fix, but I doubt it will help much.

In your case I would not store attachments in Couch/Pouch but would rather store md5sums or URLs and then fetch the blobs independently through some other mechanism.

Ah, I see you also reported this in https://github.com/pouchdb/pouchdb/issues/4632. Thanks for creating a new issue.

**Comment by nolanlawson** [comment]
Seems a dup of #4632
