### ISSUE TITLE
ETIMEOUT waiting for socket in Chrome when using live sync

### ISSUE THREAD

**Issue by aexmachina** [pouchdb/pouchdb#5675]
### Issue
We use `sync(remote, {live: true})` and have been trying to track down a problem where the remote database become unreachable on an (apparently) intermittent basis. When this happens there are ETIMEOUT errors in the Chrome console output.

We've finally worked out that it's because of Chrome's limit on the number of open connections to a given host. 

### Info
- Environment: browser
- Platform: Chrome
- Adapter: IndexedDB
- Server: CouchDB, Cloudant

### Reproduce
I've put together a demo page here:

1. Open https://ns-zpbmphjjqu.now.sh/ in Chrome
2. You will see that _connecting_ changes to _synced_
3. Keep opening the same address in new tabs
4. After you have opened enough tabs (13 for me) you'll see that it never changes to _synced_
5. Now you can no longer access the database at https://jtribe.cloudant.com/test

Even if you close all of the tabs it still doesn't fix the problem. The only way to get it to work again is to restart the browser.

13 tabs seems a lot, but we hit this problem much sooner in our app because we're syncing with several databases so we hit this limit much sooner.

We have also found that the same problem happens with our own CouchDB server, as well as Cloudant.

**Comment by nolanlawson** [comment]
The http connection limitation is a longstanding and known problem in web applications. Unfortunately the only way to fix this in the case of PouchDB is to limit the number of open connections, for which there are a few solutions you can try:

1. use a proxy on your server to mux connections into separate HTTP calls to CouchDB
2. use domain sharding to allow more connections
3. use a SharedWorker to funnel all your requests (note: only works in Chrome and Firefox)
4. instead of `live` sync, do a periodic one-shot sync on a timer.

Sorry I don't have a better answer for you. There isn't really any way for PouchDB to solve this unless CouchDB implements a totally different replication protocol.

**Comment by gmurrayhays** [comment]
Nolan, I have implemented your 4th solution suggestion and find that it works great. However, I am concerned about the network traffic that will occur with the couchdb server if I have, say 10,000 client machines, each replicating 10 databases from the couchdb server to each client machine.

So, I implemented your 3rd solution suggestion. However, I found that the 'HTTP connection limitation' was still causing ETIMEOUT errors in the Chrome console output. Any ideas as to why using a SharedWorker didn't eliminate the ETIMEOUT problem?

**Comment by paolosanchi** [comment]
I'm trying this approach this issue making use use of the retry mechanism of live replication.
The docs says: "In live changes, only cancelling the changes should trigger this event."
So I've implemented this:

```
continuousSync(remoteDatabase: PouchDB.Database<{}>, options: PouchDB.Replication.SyncOptions) {
	var sync = this.doSync(remoteDatabase, options);

	sync.on('complete', () => {
	  window.setTimeout(() => this.continuousSync(remoteDatabase), environment.syncPolling);
	});
}

doSync(remoteDatabase: PouchDB.Database<{}>)(
    remoteDatabase: PouchDB.Database<{}>,
	var sync = this.localDb.sync(remoteDatabase, { live: true, retry: true });
	sync.on('paused', (error) => {
                // if there is an error the sync will retry later so I don't have to cancel()
		if (!error) {
		  sync.cancel();  

                  // works only with this:
                  // window.setTimout(() => sync.cancel(), 1);
		}
	});
});
```

The issue is that sync.cancel() doesn't trigger 'complete' if called immediately. I can make it work adding a timeout of 1ms before doing .cancel(). A timeout of 0ms don't work, and this make me untrust this solution.
I suppose there is a bug in the implementation of cancel in this particular case.
Is this implementation a good idea?
