### ISSUE TITLE
Safari drops attachment type

### ISSUE THREAD

**Issue by DreamingMatt** [pouchdb/pouchdb#5726]
### Issue
Storing attachments in Safari seems to drop the type attribute/property of said attachment. I've only tested it with Files/Blobs.

### Info
- Environment: browser
- Platform: Safari 9.1.1
- Adapter: WebSQL
- Server: Custom

### Reproduce
You can reproduce running [this JSbin](https://jsbin.com/milanatigo/edit?html,output) and by following these steps:

1. select a file
2. click the newly appeared button
3. check the logs;  especially `object -> _attachments -> files -> data`

You'll see that type is `undefined` in Safari. This is not the case in Chrome or Firefox.

**Comment by nolanlawson** [comment]
I feel like I may have already seen this bug filed this bug on Safari, but I don't have time to look for it now. If you're able to find a small reproducible test case, please file the issue on WebKit while you're at it (they do fix bugs!): https://bugs.webkit.org/

As for this particular bug, do you have a feeling if PouchDB would be able to work around this issue? Or does WebKit themselves need to fix it?

**Comment by nolanlawson** [comment]
Nevermind, I understand what's going on here. Here's your code:

```js
db.post({
  _attachments: {
    file: {
      type: file.type,
      data: file
    }
  }
})
```

This should be:

```js
db.post({
  _attachments: {
    file: {
      content_type: file.type,
      data: file
    }
  }
})
```

PouchDB uses **content_type** rather than **type** for attachments. You are essentially omitting the type, which means that IndexedDB browsers (non-Safari) stores the raw Blob whereas Safari stores the base64 encoding without the type. Hence this bug.

In the corrected version, Safari should work. Please reopen if I've mis-diagnosed.
