### ISSUE TITLE
Safari does not request more space after exceeding the 5MB quota.

### ISSUE THREAD

**Issue by hpop** [pouchdb/pouchdb#5761]
### Issue

Safari does not request more space after exceeding the 5MB quota. Instead it will ask for 5MB again and the write will fail. I my understanding of the docs, it should ask for 10MB instead.
### Info
- Environment: browser
- Platform: Safari 10.0 (12602.1.50.0.10)
- Adapter: WebSQL
- Server: none
### Reproduce

Fill a database up with 5MB of data.  Safari will ask the user to allow 5MB for this site.
Either click allow or 'not allow'. The code will throw 
`there was not enough remaining storage space, or the storage quota was reached and the user declined to allow more space`
and on the next request, it will happen again.

**Comment by dharders** [comment]
Have you tried this ?

[https://pouchdb.com/errors.html#not_enough_space](https://pouchdb.com/errors.html#not_enough_space)

I'm pretty sure you have to ask for the larger storage upfront in iOS, maybe the same for Desktop Safari ?. i.e. `{size: 50} // 50MB storage` .

In my testing I haven't found that it automatically increases in iOS. Maybe because my individual dbs are not greater than 5MB, but combined are greater than 5MB. 

Eg. I have a local db1 around 3MB in size and another local db2 also 3MB in size. When I sync the second db2 from the server (same domain & port) I get the popup asking to increase to 5MB. This is where the bug lies in my opinion. It should request 10MB here. As combined dbs add up to 6MB we are already over the limit and we get stuck in a loop of "Increase to 5MB ?" -> Yes! -> "Increase to 5MB?" (and repeat)

Not sure if this is a Pouch issue or Safari issue.

**Comment by hpop** [comment]
Requesting more space upfront works as expected. 

The documentation says, that desktop Safari should ask for more space if you reach the limit (https://pouchdb.com/faq.html#data_limits). That why I was assuming that this is a bug. But I'm not sure if its in Pouch or Safari either.

**Comment by nolanlawson** [comment]
The documentation should be updated in that case. I thought this bug was fixed in Safari 8 but I guess I was wrong.

This is definitely a bug in Safari because the popup is a nonstandard Safari-specific thing.

**Comment by nolanlawson** [comment]
Whoops so the bug is that we need to update the docs.

**Comment by andig89** [comment]
I see another problem - how can I recognize whether the user allowed or not? Is there any discussion about this whole issue on the Apple support page?

**Comment by dynamind** [comment]
I experimented with various settings and we're currently using { size: 1 }. 
This results in the desired behaviour: 

- No approval dialog when DB stays small
- Asks approval at 5, 10, 25 and 50MB (max on Mobile Safari), 100MB, 500MB, etc.

I suppose any non-zero value below the first limit (5) will work.

**Comment by andig89** [comment]
Safari asks but when we confirm fail. Try in https://demo.agektmr.com/storage/.
