### ISSUE TITLE
Add batch=ok support to put()/bulkDocs() for the HTTP adapter

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb#5782]
Is it possible to perform bulkDocs in batch mode similar to `PUT?batch=ok`? http://guide.couchdb.org/draft/performance.html

**Comment by daleharvey** [comment]
Are you looking to do these writes to indexeddb or using pouchdb as a http adapter and want to pass `batch=ok` to couchdb? If you want to pass the option to CouchDB would happily accept a patch for that, otherwise batch=ok is an implementation detail of CouchDB that doesnt apply to any PouchDB adapters

**Comment by ronag** [comment]
@daleharvey: I'm using the http adapter.

**Comment by ronag** [comment]
So something like: `db.bulkDocs(docs, { batch: true })` could work?

**Comment by daleharvey** [comment]
Yeh I think a patch adding that would be fine, would need to add the param handling @ https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-http/src/index.js#L611 and a test could look something like https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.http.js#L101
