### ISSUE TITLE
Intermittent test failure - local -> http sync (5782)

### ISSUE THREAD

**Issue by willholley** [pouchdb/pouchdb#5799]
### Issue

In the fix for #5767 I added a test which checks synchronisation of rev-1 conflicts. Whilst investigating #5793, I noticed this intermittently failing when the source database was local and the remote was http. Even with the workaround added in #5793, this error is only fixed by commenting out the use of `getRevisionOneDocs` in the sync codes, making me suspect a more fundamental problem in PouchDB somewhere (e.g. `conflicts=true` is returning empty when it should not).
### Info
- Environment: reproduced in Node.js and browser
- Platform: Chrome/FF
- Adapter: Defaults
- Server: CouchDB 2.0
### Reproduce

I can reliably reproduce this error with a fixed SEED as below.

```
$ export SEED=1477254495092
$ export GREP=5782
$ npm run test
```

Again, this suggests to me that something about the specific rev values that PouchDB generates with this seed lead to the error.

I attempted to reproduce in a new test which simply creates the rev-1 conflicts locally, deletes the winning revision, and checks that the active leaf is now the winner. However, that seems to work.

Any ideas/thoughts as to where the error might be would be very welcome!

**Comment by willholley** [comment]
A log of the failing test run is available [here](https://gist.github.com/willholley/03e245ddcaf7efac23824ebffa3eb22c)

**Comment by nolanlawson** [comment]
The fact that the `allDocs()` optimization does not work for rev-1 conflicts is a known issue (#4651). Unfortunately we've been reluctant to remove it because it is a _huge_ performance boost, and is only fixed by the addition of the `_bulk_get` API added in CouchDB 2.0 and PouchDB Server. (Does Cloudant have it yet BTW?)

I would be okay with just removing the `allDocs()` API altogether, since folks now have the option to upgrade to Couch 2.0, but we should make a separate plugin for the old style of replication (`pouchdb-replication-legacy-rev1-conflicts`?) and heavily document what's going on here.

I also kinda wish CouchDB had released a 1.7 with just the `_bulk_get` addition, but I understand it's difficult to backport. This would make it easier for folks on 1.x to upgrade. @janl @rnewson any hope of that?

**Comment by willholley** [comment]
@nolanlawson I thought I had fixed the sync of rev-1 conflicts in https://github.com/pouchdb/pouchdb/commit/8f0d7d2248ed46bffb9350ce50a033113241ae8f. I think the problem I'm seeing in this ticket is something else - a bug around the internals of conflict deletion or determining the winning rev.

**Comment by willholley** [comment]
just to elaborate, this problem doesn't occur when using PouchDB to replicate http <-> http, so it's a PouchDB issue which is not the replicator itself.

**Comment by willholley** [comment]
some progress. The issue only occurs when using `local.sync(remote)`. If I replace that with 
```
local.replicate.to(remote).then(function () { return local.replicate.from(remote); })
```
it works! Clearly something's funky...

**Comment by willholley** [comment]
ok - I think I've found the issue. CouchDB 2.0 doesn't return `_conflicts` when a `POST` is make to `_all_docs?conflicts=true` with a keys array in the body. The reason the test passes in http <-> http mode is a failing of the test logic - both instances will generate the same rev for the document so no conflict is generated anyway.

**Comment by willholley** [comment]
filed COUCHDB-3264

**Comment by willholley** [comment]
In terms of short term impact for PouchDB, this only affects conflicted rev-1 documents which are rare. In all other cases, PouchDB will use `_bulk_get` (or the shim) rather than `_all_docs`.

**Comment by rnewson** [comment]
Good find.
