### ISSUE TITLE
Couchbase Sync Gateway is not supported at 100%

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#5820]
So opening one issue that we can dupe any CSG bugs to

The state of CSG support is, we have it in our test suite @ https://travis-ci.org/pouchdb/pouchdb/jobs/171449096, it has been green forever despite fairly severe problems we have found with csg previously so I am not certain I trust it. Over the years we have had the occasional patch to fix something in CSG, it certainly does not get the use or the testing that CouchDB / Cloudant does.

The current active maintainers have all shown a preference towards focusing on CouchDB compatibility so I do not see a need to track CSG issues, we may want to remove mention of its support from the website, if you are using CSG and are seeing a bug, please feel free to submit a fix, I think we will be happy merging stuff that doesnt interfere with the code base too much but providing tests will still be necessary. 

I do see this as being a bit of a last call though, unless someone wants to take up maintenance of the tests to ensure full compatibility, it seems likely that we may want to drop support for csg explicitly in the future

**Comment by nolanlawson** [comment]
We've always been open to Couchbase folks providing pull requests and have interacted with them frequently, but yeah, at the end of the day compatibility is impossible unless you consider _something_ a standard, and for us the de-facto standard has been CouchDB because there's never been a formal spec/standardization process (closest is http://replication.io).

A couple years ago we were in a similar position with Cloudant – most of the tests were failing, the API surface wasn't guaranteed to work 100%, and even replication was a little wonky. However @willholley came in and basically fixed all the Cloudant bugs as well as CouchDB 2.0 bugs and so that problem is largely fixed. We never saw the same from Couchbase (despite a few great PRs from @jchris), and so I think even mentioning CSG support on the website as "in progress" is just not an accurate depiction of reality at this point.

There are plenty of CouchDB-likes out there (rcouch, AvanceDB, pouchdb-server, pouchdb-express-router, Drupal Relaxed Web Services), but ultimately it's up to those maintainers to provide compatibility because we don't have time or resources to test them all, even if PouchDB has what amounts to the only "Couch compatibility test suite" in the Couch ecosystem. We've even been careful not to give pouchdb-server any special privileges (it's an allowed failure in CI), so we've been pretty even-handed about it.

Personally I would change the wording on our website to say that we don't guarantee 100% compatibility with Couchbase Sync Gateway, AvanceDB, rcouch, or any of the other CouchDB-likes. Unfortunately I think we have to underline it for CSG because it has the name "Couch" and so people assume compatibility. I'd also be fine with dropping CSG from the test suite and maybe even pouchdb-server/express-pouchdb/pouchdb-express-router as well because we can always run the test suite in those projects, and PouchDB itself is stable enough now that I think it's safe to do.

**Comment by davengeo** [comment]
Hi guys

I have made some experiments with pouchdb and sync-gateway and it seems there is a trivial mismatch between the content type accepted by the sync-gateway and the one required by pouchdb. 

I have shown this in a small project in angular2 here https://github.com/davengeo/pouch-experiment
which requires a man in the middle doing the correct translation of content types: https://github.com/davengeo/middle-patch

There are some screenshots I have made as outcome of the experiment.

with patching: https://github.com/davengeo/pouch-experiment/blob/master/screenshots/experiment-1.png
without patching: https://github.com/davengeo/pouch-experiment/blob/master/screenshots/experiment-3.png
The whole point of the content type: https://github.com/davengeo/pouch-experiment/blob/master/screenshots/experiment-2.png

The gain in performance seems remarkable IMO and I think it deserves a try. Besides this I am not aware if this trivial translation cover all the corner cases, but it seems working in the happy path.

Please let me know if I can help in any other way. I am posting a similar comment in the sync-gateway issues site.

**Comment by toddfreese** [comment]
Let me know if there is anything I can help with as well. We use PouchDB and SG a ton and love the combination. We could possibly fund a little work to make this better.

**Comment by Zerzio** [comment]
Hi @toddfreese,

I'm glad you're combining those with success. @davengeo and I had performance issues because of the mis-alignment of the two products about _bulk_get implementation. Without it, your app does too many calls to sync documents and history one by one. The performance on tablet was terrible. We then implemented this proxy in NodeJS to transform the SG response to a _bulk_get from multipart to json so that PouchDB understands it.
Reading the SG doc, it should be supported but it's not. The reading of the source code tells you it's not a bug, it's just not implemented.

Aren't you facing such issue?

**Comment by toddfreese** [comment]
We do notice that PouchDB is much slower than native CouchbaseLite, but it hasn't been a problem yet. We don't have a lot docs. But this concerns me for the future.

**Comment by jchris** [comment]
I haven't worked on CSG for over a year, but my guess is that they would be friendly to work with anyone who wanted to help maintain these things. It's been a while, but I also don't mind helping folks get oriented in the CSG codebase.

**Comment by toddfreese** [comment]
If there is a developer that would want to take this on, this is something that I could fund. PouchDB/CSG happiness is very important to our business.

**Comment by nolanlawson** [comment]
Thanks for the comment @jchris! And yes @davengeo: `_bulk_get` was inspired by Couchbase but CouchDB/PouchDB decided to use application/json instead of multipart/mixed (or maybe Couch supports both, I dunno). In Pouch we avoid using multipart/mixed for downloads because there is no way to unzip the data we receive (Couch sends it zipped, individually, inside the multipart response) because the browser does not provide an unzipping API and it would be prohibitively expensive to implement our own in JavaScript.

So this fix would have to be on CSG folks rather than Pouch folks, i.e. to support application/json as you say in your PR.
