### ISSUE TITLE
Storing small audio files as Attachments.... then extracting them and converting back

### ISSUE THREAD

**Issue by irvins** [pouchdb/pouchdb#5841]
### Issue
Hi,  Ive been making a phonegap app, that allows users to walk around and take photos and record small audio observations around their neighborhood.   I am storing the photos as base64 attachments.  When it comes to the audio, i think im doing it correctly , theres a choice of reading the file as an arrayBuffer or dataURL (base64)  so i chose the readAsDataURL.  It saves ok to my pouch and replicates to my remote couch.  and it looks the proper file size for an audio clip.  However ,  i'm having difficulty trying to figure out how to actually extract the audio file back out for playback.... if im even saving it correctly in the first place.   i can't seem to formulate the correct google words to find an answer,  was hoping you might be able to help here Nolan,  thanks.

### Info
- Environment: (phonegap)
- Platform: (iOS/Android)
- Adapter: (WebSQL)
- Server: (CouchDB)

### Reproduce

```js
var fileName  = "audio_test.wav";
myMediaObject.file(function(file) {
  var reader    = new FileReader();
  reader.onloadend = function(e) {
            var base64_convert  = this.result;
            var strip_typedata     = base64_convert.replace("data:audio/wav;base64,","");
            var blobit                   = new Blob([base64_convert], {type: 'audio/wav'});
            myUserObject._attachments[fileName] = { "content_type": "audio/wav" , "data" : blobit };
            datastore.writeDB(mylocalusersdb , myUserObject);  //my doc put function
      };
      reader.readAsDataURL(file);
 }
 ,function(err){
     console.log(err);     
    }
);
```

**Comment by nolanlawson** [comment]
>  I am storing the photos as base64 attachments. When it comes to the audio, i think im doing it correctly , theres a choice of reading the file as an arrayBuffer or dataURL (base64) so i chose the readAsDataURL

It is almost always better to use Blobs rather than base64/dataURLs because of memory implications. If you need help transforming Blobs to and from different types, check out https://github.com/nolanlawson/blob-util .

In your case, it's even simpler because it turns out a `File` _is_ a `Blob`. Therefore your code can be simplified:

```js
var fileName  = "audio_test.wav";
myMediaObject.file(function(file) {
  myUserObject._attachments[fileName] = {
    content_type: 'audio/wav',
    data: file
  };
})
```

Then when you need to play the file back, you can just use the `getAttachment()` API and use the `Blob` directly, since it is also a `File`. I admit I'm not too familiar with audio, but in [the attachments guide](http://pouchdb.com/guides/attachments.html) there are details on how to work with images at least. Please post to the PouchDB IRC/Slack channel if you need more help! Else StackOverflow is also good for these kinds of questions. :)

**Comment by irvins** [comment]
Hi Nolan, Thank you for this solution.  It is much simpler than what i was attempting.  Since you mentioned you weren't familiar with storing audio,   I wanted to post a followup to let you know that it worked perfectly.    Now the audio can be accessed directly with no intermediate decoding step , same as the photos.    Thanks again.

**Comment by nolanlawson** [comment]
No prob. :)
