### ISSUE TITLE
Leveldown-Adapter in Browser

### ISSUE THREAD

**Issue by danielsun174** [pouchdb/pouchdb#5844]
Hello,
I wanted to use a leveldown-adapter in the browser and nodejs with pouchdb.

### Issue

The problem is, that I cannot load my adapter without requirering 'pouchdb-adapter-leveldb'.
But also 'pouchdb-adapter-leveldb' wont work in the browser because it tries to call the exist()-function in the filesystem.

I tried to only use the 'pouchdb-adapter-leveldb-core'-Plugin but it says "Cannot read property 'name' of undefined"

Am I able to use my custom leveldown-adapters with pouchdb in the browser?

### Reproduce
To make it reproduceable I created some snippets with memdown:

```javascript

var PouchDB = require('pouchdb-core');

var PouchDBLevelCore = require('pouchdb-adapter-leveldb-core');
PouchDB.plugin(PouchDBLevelCore);

var memdown = require('memdown');

var db = new PouchDB('mydatabase', {
    db: memdown
});


// says  Cannot read property 'name' of undefined
```

```javascript

var PouchDB = require('pouchdb-core');
var PouchDBLevel = require('pouchdb-adapter-leveldb');
PouchDB.plugin(PouchDBLevel);

var memdown = require('memdown');

var db = new PouchDB('mydatabase', {
    db: memdown
});

// Wont work in the browser because fs.exists is not defined
```

**Comment by nolanlawson** [comment]
If you want to use memdown adapter, you can use `pouchdb-adapter-memory` which is already doing this. Otherwise for a custom `db` implementation, you would need to use `pouchdb-adapter-leveldb-core`, e.g. here's an example: https://github.com/pouchdb/pouchdb/tree/03b8b30c00dcb1369ec9b40dec2b65c631c89d0a/packages/node_modules/pouchdb-adapter-localstorage
