### ISSUE TITLE
Put items into PouchDB coming from a REST service on first page load

### ISSUE THREAD

**Issue by tabalinas** [pouchdb/pouchdb#5890]
I'm using PouchDB with a simple REST service (currently in dev I'm using json-server).
So I have to take care of data synchronization myself.
The app allows to work offline, so all offline ajax requests enqueued, and sent once user goes online.

The problem is how to load data coming from REST service in the DB on the first page load.

I've tried `bulkDocs`, but it doesn't work since all items already have `_id` and the PouchDB is empty, so I get `409 Conflict`.
Of course, I could fetch all data, remove ids, clean up the service data, do `bulkDocs` and then load all new data to the service. But this seems super inefficient.

Could you please advice on how to do it correctly?
Thank you in advance!

**Comment by nolanlawson** [comment]
You might want to look into http://github.com/nolanlawson/pouchdb-dump-cli and http://github.com/nolanlawson/pouchdb-load which should be able to help you out here. You can embed the dumped JSON into your index.html so that it's available on first load. Also the design of pouchdb-load ensures no conflicts because it's an idempotent operation.

**Comment by tabalinas** [comment]
@nolanlawson, thanks, I'll give it a try.
I guess it's something similar to what you described here http://stackoverflow.com/questions/33156523/pouchdb-preload-database

**Comment by nolanlawson** [comment]
Yes, also take a look at this post about prebuilt databases: https://pouchdb.com/2016/04/28/prebuilt-databases-with-pouchdb.html <https://pouchdb.com/2016/04/28/prebuilt-databases-with-pouchdb.html>
