### ISSUE TITLE
Reduce travis running time

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#5908]
@nolanlawson you mentioned this on IRC, I agree we should trim some of these down

`CLIENT=node LEVEL_PREFIX=foo_ COMMAND=test` - I feel like we could remove this, code that could break this rarely changes and can be verified manually

pouchdb-server / pouchdb-express-router - So pouchdb-server has been broken for a long time (I seen its getting worked on now) pouchdb-express-router I fix whenever I see a problem so having it in the test suite is useful for me however I could see these being delegated to having to test themselves as projects

Phantomjs I have long believed should go, we test in various websql platforms and I do not think testing phantom gives us any value, we could keep it for the map reduce smoke tests or we can switch them to safari / node-websql

`CLIENT="saucelabs:internet explorer:10:Windows 8" ADAPTERS=memory COMMAND=test` this was added for a very specific bug in a non core module and its an expensive test, I think we should remove

Couchbase, I would be fine removing the test, I dont believe its actually passing

Any others we can remove or any of these ones not agreed with? if not I will PR shortly

**Comment by nolanlawson** [comment]
> `CLIENT=node LEVEL_PREFIX=foo_ COMMAND=test` - I feel like we could remove this, code that could break this rarely changes and can be verified manually

Yup, I'd get rid of these. Also SERVER_ADAPTER. This hugely complicates the test code and has minimal value IMO. node-websql is worth testing, maybe pouchdb-adapter-memory but not `db: require('memdown')` which is deprecated anyway.

> Phantomjs I have long believed should go, we test in various websql platforms and I do not think testing phantom gives us any value, we could keep it for the map reduce smoke tests or we can switch them to safari / node-websql

Still gonna push back on this one, if only because it's one of the few tests that _rarely_ fails, and as soon as we replace it with Safari we're looking at longer build times and more flakiness. I vastly prefer testing inside of Travis-only where possible. If Travis ran Safari natively I'd want to use that instead though. :)

`CLIENT="saucelabs:internet explorer:10:Windows 8" ADAPTERS=memory COMMAND=test` this was added for a very specific bug in a non core module and its an expensive test, I think we should remove

We need at least one Trident-based test in there because there are _so_ many hacks in the code just for IE/Edge. Sadly Edge is failing in Sauce for some reason; I'm going to look into this and file bugs on my own team as necessary; we are in bug-fixing mode right now and can potentially fix IDB race conditions in time for Edge 15.

> Couchbase, I would be fine removing the test, I dont believe its actually passing

Yup, just remove it. Same for Cloudant I'd say; too much overhead and CouchDB 2 is basically the same.

> pouchdb-server / pouchdb-express-router - So pouchdb-server has been broken for a long time (I seen its getting worked on now) pouchdb-express-router I fix whenever I see a problem so having it in the test suite is useful for me however I could see these being delegated to having to test themselves as projects

I've got tests running in pouchdb-server and express-pouchdb. These are broken very infrequently by PouchDB itself these days and I'm happy to just test it in those projects.

**Comment by nolanlawson** [comment]
Another thing: we can probably run migration tests in fewer browsers.

**Comment by daleharvey** [comment]
> We need at least one Trident-based test in there because there are so many 
> hacks in the code just for IE/Edge. Sadly Edge is failing in Sauce for some reason; 
> I'm going to look into this and file bugs on my own team as necessary; we are 
> in bug-fixing mode right now and can potentially fix IDB race conditions in time for Edge 15.

We are testing ie10 in a seperate test as well `  - CLIENT="saucelabs:internet explorer:10:Windows 8" COMMAND=test`, I only meant removing the test that is specifically the memory adapter in ie10

**Comment by nolanlawson** [comment]
Oh yeah right, that test was added because of a bug that only occurred in the memory adapter and only in IE10.

I still think it’s important to test memory/fruitdown/localstoragedown/etc. but I would be happy to switch them to Travis-based Firefox so that they can run faster.

**Comment by nolanlawson** [comment]
I think we can safely close this. Lots of work recently to improve this.
