### ISSUE TITLE
PouchDB Attachement Storage Question

### ISSUE THREAD

**Issue by ddolheguy** [pouchdb/pouchdb#5917]
Hi Guys,

I'm working on a PR for the React Native PouchDB project (https://github.com/stockulus/pouchdb-react-native) to provide better attachment support as currently when you sync with CouchDB, any attachments come through as BLOB and are not dealt with correctly.

I would just like to understand in what format does PouchDB usually store/provide attachments?  I understand that the point of adapters is to extract this functionality away, but I just don't want to make an incorrect decision here.

My plan was to take the BLOB object, convert it to base64 and store this locally in AsyncStorage.  The advantage of this is when I perform a ```doc.get('myId', { attachments: true })``` the result under ```doc._attachments``` will be an object with each item containing a data property of type string (base64 data).

To me this mimics current functionality for example if you use SQLLite adapter and request an attachment you get the same result.

I'm also making the assumption that the MD5 digest of an attachment is just the MD5 of the base64 once converted and not the original digest of the BLOB object.

Any help on these questions would really help?

**Comment by nolanlawson** [comment]
So, this is a very complicated question unfortunately. Every storage engine stores data in a different format; there is a discussion here: https://pouchdb.com/faq.html#data_types

So some adapters store using native Blobs/Buffers, some use base64. PouchDB accepts either format as input.

Blobs are typically used in the browser, whereas Buffers are used in Node. They are mostly equivalent.

In the case of React Native, it is not quite a browser environment and not quite a Node environment, but my understanding (correct me if I'm wrong) is that most developers are using Buffers, not because they're natively supported, but because there is [a polyfill](https://github.com/feross/buffer) that when you use Browserify/Webpack will automatically convert `new Buffer()` into this polyfill, which is based on Uint8Arrays.

So the short story is that you'll probably want to use Buffers, and the pouchdb-react-native adapter should already support this because it's based on our LevelDB adapter which already uses Buffers.

I know this isn't super helpful information, but if I were you I would try to run the PouchDB test suite on React Native and see where it fails in the `test.attachment.js` file. Then I would look at the code to see what needs to be fixed to support attachments.

Also FWIW pouchdb-react-native is not the only solution; I also wrote http://github.com/nolanlawson/pouchdb-adapter-cordova-sqlite and if you can get a SQLite plugin working for React Native then it will work. This adapter has a test suite and I've verified that it passes 100% on both Android and iOS even for attachments.

**Comment by nolanlawson** [comment]
Closing as this question was answered, please reopen as necessary
