### ISSUE TITLE
Expose metadata from getAttachment()

### ISSUE THREAD

**Issue by kanongil** [pouchdb/pouchdb#5924]
### Issue
When I use `getAttachment()`, I need to know the `content_type` and `digest` from `_attachments` as well. Currently I need to do a separate `db.get()` on the document to retrieve this information. However, as `getAttachment()` internally needs this info, this `get()` call can be avoided if it could somehow be exposed it in the callback.

### Info
- Environment: Node.js

### Reproduce

Currently I need to do something like this (error handling omitted):
```js
function getAttachmentWithMeta(docId, attachmentId, callback) {
  db.get(docId, (err, doc) => {
    const meta = doc._attachments[attachmentId];
    db.getAttachment(docId, attachmentId, { rev:doc._rev }, (err, buf) => {
      return callback(err, buf, meta);
    });
  });
}
```

**Comment by nolanlawson** [comment]
There is currently no API to allow you to do this.

Also technically `getAttachment()` is just a sugar API that does a regular `get()` ([here's the code]). Technically you can write your desired code yourself, e.g.:

```js
db.get('docid').then(function (doc) {
  var contentType = doc._attachments['myatt'].content_type;
  var digest = doc._attachments['myatt'].digest;
  return db.getAttachment('docid', 'myatt', {rev: doc._rev}).then(function (blob) {
    return {
      contentType: contentType,
      digest: digest,
      blob: blob
    }
  })
})
```

In fact you could even write this as a plugin and then distribute it on npm so that others could use it. :)

Closing because this is something that can be done in userland rather than in PouchDB itself.

**Comment by nolanlawson** [comment]
Heh just realized that your code looks exactly like mine, but yeah, that is basically what you would do to implement `getAttachmentWithMetadata`.

**Comment by kanongil** [comment]
@nolanlawson I think you misunderstood. I don't want to add this because it simplifies the code, but to avoid a redundant `get(doc)` call. This is not possible using a plugin, as far as i know.

As it is, both you and my code will effectively call `get(doc)` twice in a row [with the current code here](https://github.com/pouchdb/pouchdb/blob/d3d602d9d5dd0003951968f3a97ea1d2394e5d5b/packages/node_modules/pouchdb-core/src/adapter.js#L670-L693). It seems simple to extend the callback with some metadata, though I guess this will cause problems for the promise version?

**Comment by nolanlawson** [comment]
@kanongil OK I see your point now. Yes, if you implemented this via a plugin, then effectively it would call `get()` twice. One way to work around this currently is to use the quasi-secret `_getAttachment` API which does not do an extra `get()`.

Looking at [the code](https://github.com/pouchdb/pouchdb/blob/62be5fed959bbdf91758f9b4a47eca77b2d69394/packages/node_modules/pouchdb-core/src/adapter.js#L682-L705) there is a TODO to remove the extra `get()` entirely. Perhaps this is something we should re-think entirely.

**Comment by nolanlawson** [comment]
One potential solution is to rewrite the existing `_getAttachment` so that it does not do an explicit `get()` under the hood, meaning that you could implement `getAttachmentWithMetadata` safe in the knowledge that it's only doing one extra get (which it would have to do anyway since that metadata is stored separately from the binary attachment data). TBH I'm not sure why the existing `getAttachment` even does an extra `get`, so maybe this is changeable.
