### ISSUE TITLE
db.get(undefined) should throw error

### ISSUE THREAD

**Issue by soitgoes** [pouchdb/pouchdb#6025]
### Issue
db.get(undefined) against CouchDB should return Promise(undefined).  Currently it returns the database information hash like so.

{
   "db_name": "somedb",
   "doc_count": 431,
   "doc_del_count": 660,
   "update_seq": 2246,
   "purge_seq": 0,
   "compact_running": false,
   "disk_size": 27349115,
   "data_size": 770558,
   "instance_start_time": "1481515237783887",
   "disk_format_version": 6,
   "committed_update_seq": 2246
}

### Info
- Environment: node.js
- Adapter: CouchDB
- Server: CouchDB

### Reproduce
let db = new PouchDb("http://localhost:5984/somedb");
db.get(undefined).then( (doc) => {
   //Should return undefined and not a database hash.
})

**Comment by soitgoes** [comment]
Empty string should return undefined as well.

**Comment by nolanlawson** [comment]
Hmmm I kinda feel like `db.get(undefined)` should really throw an error. It's an invalid argument.

**Comment by soitgoes** [comment]
I prefer return undefined.  It prevents having to do weird branching if
it's a valid condition.

Consider this awkwardness
let contactPromise = req.params.id ? db.get(req.params.id):
Promise.resolve(undefined)

contactPromise.then(...)

As opposed to just...
db.get(req.params.id)

**Comment by nolanlawson** [comment]
Hmmm have to say I still disagree; this seems it should be the responsibility of the app author rather than PouchDB. An `id` needs to be defined for the request to be valid; if it's undefined then we shouldn't resolve to undefined because then that potentially hides errors in user code that will then be hard to debug because you're trying to guess why PouchDB resolved to undefined.

**Comment by soitgoes** [comment]
Fine by me
