### ISSUE TITLE
feed: 'longpoll' and feed: 'normal' support

### ISSUE THREAD

**Issue by broerse** [pouchdb/pouchdb#6046]
### Issue
ember-pouch stops syncing when you open multiple tabs in the browser.
With `feed: 'normal'` support we can fix this in ember-pouch if needed.

Is it possible to add `feed: 'longpoll'` and `feed: 'normal'` support to PouchDB?

### Info
- https://github.com/nolanlawson/ember-pouch/pull/140

**Comment by nolanlawson** [comment]
I can't recall why we decided to use `longpoll` instead of `normal`. Also it wouldn't be as simple as passing the `normal` option to CouchDB; we would also need to rewrite our replication algorithm to use `normal`.

**Comment by nolanlawson** [comment]
Else we could make it a replication option that is then passed to the changes feed.

**Comment by broerse** [comment]
In CouchDB 2.0 we now also have [`feed: 'event-source'`](http://docs.couchdb.org/en/2.0.0/api/database/changes.html#event-source) . I am not suggesting adding that now but it would be nice if the `feed:` option is easily extendable in the future.

**Comment by broerse** [comment]
Ping for stale bot.

**Comment by broerse** [comment]
Ping for stale bot.

**Comment by daleharvey** [comment]
We use longpoll because it was the lowest common denominator for browser support at the time and probably still is since ie doesnt support eventsource. Not sure we want to support being able to define different feeds here as it means we need to maintain cross browser support for how to read them, pouchdb isnt a couchdb api client it has its own api and we use what is available from couchdb to fulfill that api.

I would suggest if you are having issues with multiple tabs being open that you set one coordinator tab that holds the replication instead of just letting all tabs interleave their own replication requests (its been talked about haivng that as a pouchdb feature)

Either way if you could only ping bugs if you are working on a PR for the issue it would be best, this has gone > a year without much activity so going to close out

**Comment by broerse** [comment]
@daleharvey Default ember-pouch Apps stop syncing if you open multiple tabs. I think this is not up to ember-pouch or the ember App itself to fix this. We are doing a lot of work on ember-pouch and hope someone with PouchDB knowledge will write a PR to fix this bug. It does not have to be `feed: 'normal'` if it can be done with interleaving tabs.

So I don't agree with the idea to close issues that need to be solved in the future because it is not happening fast enough.
