### ISSUE TITLE
Slow puts on database ( and really weird bug )

### ISSUE THREAD

**Issue by limoragni** [pouchdb/pouchdb#6093]
### Issue

I'm using PouchDb on Electron with IndexedDb as adapter.

 I have a couple hundred databases with more or less the same kind of data. One of the databases on one of the apps is really slow when I try to update a document (using bulkDocs or just put). 

After some debugging I couldn't determine what was happening so I decided to delete that database and run the script it was slowing down again only yo find another of the databases was really slow now. If I delete that database, another of the databases is going to be the slow one and so on. I can't understand whats the connection here. 

Any idea why a database can be so slow only for inserts (same size and everything than other working fine)? And how can a database being afected by another database being deleted?

Thanks!

### Info
- Environment: Hybrid app (Electron 1.3.4 with NodeJs 6.3.0)
- Platform: Chrome 52.0.2743.82
- Adapter: IndexedDB
- Server: Offline

### Reproduce
I don't really know how to reproduce this issue since I don't know how is that the database got slow on the first place. Sorry :(

**Comment by nolanlawson** [comment]
We've been constantly trying to improve the performance of PouchDB, but insertions are a difficult thing to optimize for IndexedDB because there is a `put()`/`add()` API but no `putAll()`/`addAll()`. From the user POV, the best way to optimize is usually to tweak your batch size to find the ideal size depending on the size of your documents. Usually this ideal size is somewhere between 100-500 documents in my experience.

Another thing: if you run indexedDB on the main thread, then it will interfere with anything else your app is doing, whereas if you run it inside of a web worker, then it essentially has its own thread and therefore doesn't compete with your other JS at all. Details here: http://nolanlawson.com/2015/09/29/indexeddb-websql-localstorage-what-blocks-the-dom/

For Electron you also have the option of using LevelDB or SQLite or WebSQL, so you could experiment and see which one of the four gives you the best performance; if I had a hunch, I would say LevelDB but it depends on your usage patterns.

**Comment by nolanlawson** [comment]
Also if you can provide a Chrome trace (timeline -> right click -> save Timeline data) and then upload it to a pastebin and give it to me, I can take a look. :)

**Comment by limoragni** [comment]
@nolanlawson Thanks for your quick reply. I'm planning on using leveldb from now on, maybe that'll fix the problem I'm having. I don't think this is a general performance problem. Under the exact same circumstances the inserts are working just fine. Only one of the databases has slow inserts (all the databases are more or less the same size and have the same type of data). But when I delete the slow database the problem starts happening with other of the databases that was working fine before deleting the first one. There's a strange pattern where always one database is slow and the rest is working fine. And this is happening only to one user. Maybe IndexedDb got corrupted, maybe there's a bug on IndexedDb. Other than that particular bug I have no problems with PouchDb performance. I'll get back with the Chrome trace when I can get to the machine that has this problem again.
