### ISSUE TITLE
Performance issue over 10k

### ISSUE THREAD

**Issue by gine** [pouchdb/pouchdb#6109]
### Issue

I'm developing an app where i need to work with all the data loaded because there are a lot of relations between type of different doc. 

For example i need to display on the select field info from other type, or i need to display inside a form a table with all the detail. (On a contract form, i need to display a select field where i can chose from client from a list, and choosing it auto-compile other field, i have a table to display what car are rented, another select field where i need to chose what quotation the client have accepted.. and a lot of other related data).

To do that i load at the app init all docs from all documents type on an array splitted for type whit:

```
API.pouchAdapter.dbs.local.allDocs({include_docs:true}).then(function (result) {
   //split
});
```
I some app i have 30k(1) docs and some other 80k(2). Pouch db let me work with the result data in: 
(1) 30sec
(2) 3 min

The split operation after allDocs is done in about 1sec.

There isn't any attachment inside documents. And Documents have slow size.

It's realy slow. I don't undestand if it's a normal time to wait or if there are some bug or if there is some other type of implementation. I don't understand how is possible that data from a local db getted without any filter cab be so slow.

I need pouch because who work with this app can work offline and i need to sync data.

### Info
- Environment: browser
- Platform: Chrome
- Adapter: IndexedDB
- Server: Couchbase

**Comment by willholley** [comment]
@gine it's hard to say exactly why this is slow but most likely it's due to HTTP traffic. Are you able to profile the sync and/or look a the network tab in Chrome to see what's consuming time? A common bottleneck is a large number of requests to individual documents (Couchbase isn't compatible with CouchDB's bulk_get so PouchDB can't take advantage of that optimisation with CSG is used on the server).

**Comment by gine** [comment]
@willholley i'm talking about local database.. so local.allDocs must get data from indexDB not from remote.

**Comment by t-knapp** [comment]
@gine Check [the closed issue #6087](https://github.com/pouchdb/pouchdb/issues/6087). 
Depending on the size of your documents, increasing the `batch_size` option may help.

This solved my performance problems with dealing with a lot of (1.5k) small documents.

**Comment by elliskot** [comment]
Hi all, I have the same problem as @gine.

When I call local.allDocs, with about 100k docs (1.5k doc size average), I have to wait about 5-10 min, before it completes. (No Attachments).
During this time the browser is locked!

Thank you

**Info**
Browser: Chrome
Adapter: IndexedDB
DB Server: Couchbase

**Comment by nolanlawson** [comment]
@elliskot The issue of the browser being locked can only be fixed by moving PouchDB to a web worker. Please see [this article](http://nolanlawson.com/2015/09/29/indexeddb-websql-localstorage-what-blocks-the-dom/).

As for `allDocs()` slowness in general, I've actually done a lot of work to optimize this in PouchDB 6.1.1. Currently you should be able to get good performance by using the `startkey`/`endkey` pattern as described in [pagination strategies with PouchDB](http://pouchdb.com/2014/04/14/pagination-strategies-with-pouchdb.html) and use a `limit` of 1000 or so (given that your number of documents is 100k.

An alternative is to use an in-memory database. If you have 100k documents and you want to display 100k DOM elements to represent them, then there probably isn't an IndexedDB/WebSQL database on the planet that will be fast enough for you; in-memory would probably be the way to go. You could try using PouchDB's in-memory adapter as a replicating cache in front of an IndexedDB/WebSQL version, or you could try an in-memory database like LokiJS or just a regular JavaScript array even.

**Comment by johannesjo** [comment]
I've encountered a similar issue using pouchdb (through RxDb). Starting with a couple 100 of entries loading and manipulating the data gets sluggish. Going beyond 200 starts to get painfully slow. I wonder if there is any smart solution out there dealing with larger sets of data being stored to the client (e.g. to make everything available offline).

**Comment by vikingbr** [comment]
@johannesjo happen the same thing with me
