### ISSUE TITLE
Search for postfix in _id

### ISSUE THREAD

**Issue by t-knapp** [pouchdb/pouchdb#6113]
### Question
I have some documents with their "Name" in the _id e.g. 
Pattern: [Type]-[Identifier]-[Name]
```
{ _id: TAG-1000-Firstname},
{ _id: TAG-1001-Language},
{ _id: HOS-10-Address },
{ _id: AAA-1091-Language}
```
And I like to fetch all Documents with a Name in their _id. For instance all Documents with "-Language" postfix in the _id.

I played around with startkey and endkey but was not capable of "searching" for postifxes, only for prefixes.

I was able to fetch these documents with a map function, but this is not recommended in the documentation and is slow with lot of documents.

### Info
PouchDB v6.1.0

**Comment by nolanlawson** [comment]
There is no simple or performant way to do this in PouchDB, due to an inherent limitation of how B-trees work. You can either 1) search prefixes, which [can be done performantly](https://github.com/nolanlawson/pouchdb-quick-search/#autosuggestions-and-prefix-search), or 2) read all keys into memory using `allDocs()` and then search in-memory yourself using JavaScript.
