### ISSUE TITLE
Add option to cancel bulkDocs if there is one error

### ISSUE THREAD

**Issue by natcohen** [pouchdb/pouchdb#6122]
It's a feature request... 

Could we add the option of cancelling the `bulkdocs` if there is at least one error? Sometimes, the `bulkdocs` is part of the same transaction and if there is at least one error, the whole transaction should not happen. I could manually do it each time I have such transaction but it would be handy if we would have this feature directly integrated into pouchdb

**Comment by nolanlawson** [comment]
There is no concept of a transaction in CouchDB; by design _bulk_docs is not supposed to be transactional and if there is an error it doesn't stop. There used to be an `all_or_nothing` parameter, but it was dropped in CouchDB 2 because it's incompatible with clustering (see https://stackoverflow.com/questions/29554887/why-there-is-no-all-or-nothing-support-in-cloudant/30047109)

Hope that helps, sorry about that!

**Comment by nolanlawson** [comment]
BTW the advice I usually give is "the smallest unit of atomicity in Couch/Pouch is a single document." so basically if you need changes to be made together, you can do it as a single document.
