### ISSUE TITLE
Can't delete a document having a conflict winning revision

### ISSUE THREAD

**Issue by kiyanovsky** [pouchdb/pouchdb#6153]
### Issue

Let's say we have two revisions "3-lost" and "3-win", where revision "3-win" is the winning (current) revision. When I delete this doc with .remove() or .put() with _deleted:true, instead of creating new revision "4-deleted", PouchDB deletes revision "3-win" and revision "3-lost" becomes a new revision.

Is it possible to delete a document in this situation without prior deleting conflict revisions?

### Info
- Environment: (browser)
- Platform: (Chrome)
- Adapter: (IndexedDB)
- Server: (CouchDB)

**Comment by willholley** [comment]
@kiyanovsky this sounds like expected behaviour. If there are 2 non-deleted leafs and you delete one, regardless of which is the current "winner", the non-deleted leaf will become the new "winner". If you want to fully delete a document, you must delete all non-deleted leaf revisions. I think [this blog post](https://dx13.co.uk/articles/2017/1/1/the-tree-behind-cloudants-documents-and-how-to-use-it.html) explains it well - the context there is Cloudant but the same applies to CouchDB and PouchDB.

**Comment by kiyanovsky** [comment]
Thank you, Will! Now I got it.
