### ISSUE TITLE
Maximum IPC message size exceeded error

### ISSUE THREAD

**Issue by xGETSx** [pouchdb/pouchdb#6227]
### Issue
I am trying to sync remote CouchDB with local PouchDB. After replicating 40-50 entries an error message arrives to console: `Database has a global failure DOMException: Maximum IPC message size exceeded.`

### Info
- Environment: Windows 10 64-bit
- Application: VueJS Webpack buid app
- Platform: Chrome 56.0.2924.87
- Adapter: IndexedDB
- Server: CouchDB

### Reproduce
```
import PouchDB from 'pouchdb'
import PouchAuth from 'pouchdb-authentication'
PouchDB.plugin(PouchAuth);

const sellers_db = new PouchDB('http://server_name/db_name', {
    skip_setup: true
});
sellers_db.login('login', 'password')
    .then(function (login) {
        console.info("Logged in as", login.name);
        console.info("Roles:", login.roles);
    })
    .catch(function(err){
        console.error(err.message);
    });

const local = new PouchDB('local_sellers');

export default local.sync(sellers_db, {
    live: true,
    retry: true
})
```

**Comment by ajayambre** [comment]
I am able to reproduce this issue consistently.

For testing, we created a database in Couch with ~20000 records. These are basically major Cities in the World and we need to load them in a dropdown that uses VirtualScroll in the Ionic app.
The initial size of this database in Couch was ~8 MB.

On syncing this to a local PouchDB, the all_docs query ran and fetched all the records as expected.

Each record was updated in PouchDB and then the db was synced to remote Couch.
On completion of the sync, the all_docs query was run again and then the documents were updated and synced.
This was done in a loop just to check the point where the all_docs query failed with `Database has a global failure DOMException: Maximum IPC message size exceeded.` error.

After about 94 revisions, the all_docs query started failing consistently.
The size of CouchDB  after running compaction is ~86 MB and it translates to ~120MB when I sync it to a new local PouchDB.

I am aware that the size increase is due to _revisions array.
Since the default _rev_limit is 1000, we were thinking of bringing it down to 100 but it failed at 94.
Not sure what _rev_limit should be used as the docs mention that using a low value increases chances of a conflict.

What is the Maximum IPC message size?
