### ISSUE TITLE
Rev not sync back to the pouchDB. 

### ISSUE THREAD

**Issue by tedwong** [pouchdb/pouchdb#6232]
### Issue
I do have a PouchDB to set the data, after that I sync to the CouchDB. 
The ver is correct in CouchDB, but when I query back the document from previous version, it returns me : "{"error":"not_found","reason":"missing"}" . 

### Info
- Environment: Node.js
- Platform: OS X 10.12.2 (16C67)
- Server: CouchDB

### Reproduce
Here is the code snippet:

>         var db = new PouchDB('POC_Test');
>         db
>             .put({_id: "testSyncId", myMsg: "version1"})
>             .then(function (response) {
>                 return db.get("testSyncId");
>             })
>             .then(function (doc : any) {
>                 return db.put({_id: "helloWorld", _rev: doc._rev, myMsg: "version2"});
>             })
>             .then(function (response) {
>                 console.log(response);
>                 done();
>             })
>             .catch(function (err) {
>                 console.log(err);
>             });
> 

The code that sync the DB:

>         PouchDB.sync('POC_Test', urlPath).on('complete', function (info) {
>             console.log(info);
>             done();
>         }).on('error', function(e){
>             console.error(e);
>             done();
>         });

**Comment by willholley** [comment]
@tedwong this is [expected behaviour](http://docs.couchdb.org/en/2.0.0/replication/conflicts.html). During sync, the revision history of each document is synchronised (so Pouch/Couch will know that a rev existed and what its lineage is) but only guarantees to have the "active" version of the document available for querying. 

If you need to store the full history of changes (e.g. for audit query), you'd need to store an immutable document per edit.
