### ISSUE TITLE
and/or with regex on same field

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6260]
_From @valepu on October 20, 2016 11:47_

Hello,
I have tried to use both an $and and an $or including a set of conditions ($regex) all on the same field, but it appears that only the last regex gets used (both using $and and $or)

Here's a plunker showing the issue: http://plnkr.co/edit/9N0xuC6k5iwPrY8QMca2?p=preview
This should show no results but it shows all of them instead, if you move the 2nd regex at the end it'll show only 1 result (the one starting with a b)

Checking a regex on different fields will work, but if the same field is checked multiple times then only the last regex will work

I'm not sure it's intended or not, i haven't found anything on the Cloudant API documentation but i admit i haven't read it thoroughly (although i've seen an example of an $or checking the same field multiple times, even though it was not a regex)

_Copied from original issue: nolanlawson/pouchdb-find#219_

**Comment by LivingOnAPear** [comment]
I patched this locally on my version.  My fix is not very good but hopefully it will point someone who knows enough of the internals to do it right in the right direction.

The issue is that the mergeAndedSelectors function creates an js object with keys of the field names e.g.

query
```
{
  "$and":[
    {"field1":{"$regex":"a"}},
    {"field2":{"$regex":"b"}},
    {"field3":{"$regex":"c"}},
  ]
}
```

requestDef.selector becomes
```
{
  "field1":{
     "$regex":"a"
  },
  "field2":{
     "$regex":"b"
  },
  "field3":{
     "$regex":"c"
  }
}
```

Hence, if you have the same field name with the same operator in an $and you will only ever get the last value.  The right solution I am sure is to make an array under the operator level in requestDef.selector, but I don't know enough about the code to do that safely.  This is what I did:

Changed:
`fieldMatchers[operator] = value;`

to:
```
if(!fieldMatchers.hasOwnProperty(operator)){
  fieldMatchers[operator] = value;
  }else{
    var w = 1;
    while(fieldMatchers.hasOwnProperty(operator+"_"+w)){
      w+=1;
    }
  fieldMatchers[operator+"_"+w] = value;
}
```

suffixing each repeat operator with _(int)

then in function match() i just added this to the top:
`userOperator = userOperator.replace(/(_[0-9]+$)/,"");`

It is very dirty, but it seems to work well.  I was mostly interested in $and but it seems to work for $or as well.

**Comment by mrzslr** [comment]
Hey! the Issue regarding using $and is fixed, but using $or with multiple $regex conditions is not working. I couldn't see any test cases for this case in [`test.or.js`](https://github.com/pouchdb/pouchdb/blob/master/tests/find/test-suite-1/test.or.js) file.
