### ISSUE TITLE
Application freezes when bulkDocs adds lots of data

### ISSUE THREAD

**Issue by maxharlow** [pouchdb/pouchdb#6290]
### Issue
I have a Node API using Express and PouchDB. Sometimes I need to add large numbers of documents to the database (roughly 75,000 when I ran into this problem). Whilst bulkDocs is running Express stops responding to HTTP requests.

### Info
- Environment: Node
- Adapter: LevelDB

### Reproduce
A simplified version of my API:

```javascript
const PouchDB = require('pouchdb')
const Express = require('express')

const db = new PouchDB('testdata')

function create() {
    const object = { foo: 'bar' }
    const objects = Array.from({ length: 75000 }, () => Object.assign({}, object))
    const documents = objects.map((data, i) => ({ _id: 'test' + i, data }))
    console.log('creating data')
    return db.bulkDocs(documents).then(result => {
        console.log('done')
    })
}

const app = Express()

app.get('/', (request, response) => {
    response.status(200).send('something else')
})

app.post('/', (request, response) => {
    create()
    response.status(200).send('started create')
})

app.listen(8585)
```

If you then:

    $ curl localhost:8585

all is fine. If you then start adding all these docs to the database:

    $ curl -X POST localhost:8585

and then try and call the first endpoint again:

    $ curl localhost:8585

it won't respond until bulkDocs has finished.

**Comment by nolanlawson** [comment]
There is an upper limit to how many bulk docs PouchDB can process at once just due to normal memory limitations. For instance it can probably not handle a million docs at once, and on your server it appears it can’t handle 75,000. :)

Usually you want to tweak this based on your app and your server conditions to find the right value. I would recommend breaking up your requests to <75000 docs per batch, and perhaps enforcing it with a proxy to ensure malicious users don’t try to break your server by inserting too much at once.

**Comment by maxharlow** [comment]
Thanks!
