### ISSUE TITLE
Conflict 409 on every document update attempt

### ISSUE THREAD

**Issue by zangarmarsh** [pouchdb/pouchdb#6292]
**Issue**
Conflict 409 on every document update attempt. I am using PouchDb as browser storage.
**Edit:** I don't really like the upsert solution, I'd like to solve the problem

**Info**
- Environment: browser
- Platform: Chrome
- Adapter: default

**Reproduce**
http://pastebin.com/zqUadjp5

**Comment by nolanlawson** [comment]
409s are normal and need to be handled by the application. It's possible for `get`s/`put`s to be interleaved incorrectly, leading to 409s.

In your code, you need to do `return db.get()` instead of just `db.get()`, otherwise the promise won't wait for the `db.get()` promise to resolve. Please read [We have a problem with promises](https://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html) if this is unclear.

We've also designed a plugin that avoids 409s by wrapping everything in an update function. If you use this plugin it is impossible to get 409s: http://npmjs.com/pouchdb-upsert

**Comment by nolanlawson** [comment]
More details can be found in the guide: https://pouchdb.com/guides/updating-deleting.html
