### ISSUE TITLE
Option to disable remote checkpoints

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6308]
I can't find where this was originally discussed, but in a discussion about the performance of the replication protocol I suggested we add an option to disable remote checkpointing. We already do this in cases where the remote DB refuses writes.

Off the top of my head, API could look like this:

```js
db.replicate.to('http://remote', {
  remote_checkpoints: false
})
```

Or maybe:

```js
var remoteDB = new PouchDB('http://remote', {
  checkpoints: false
})
db.replicate.to(remoteDB)
```

I'm leaning towards the second one, because it doesn't encode a concept of "remote" or "local," since PouchDB is potentially p2p and also allows replication between locals and between remotes. `checkpoints` would default to `true`, though, which is awkward. We could also make it `disable_checkpoints: true` instead.

**Comment by gr2m** [comment]
I’m looking into the code for this. I could use some help for documenting that feature and giving some insights on why we do the checkpointing in the first place, and why we do it by default

**Comment by gr2m** [comment]
@nolanlawson could you give me a few more pointers? 

I’m looking into https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-checkpointer/src/index.js. I’ve set `this.readOnlySource = true;` in the constructor just to see what happens when I run tests, but all tests pass?

My guess is that if we set the options to disable remote checkpoints, I’ll avoid running `this.writeCheckpoint()`, so we won’t write checkpoints in neither source nor target. We also want `getCheckpoint` to behave the same it does if `readOnlySource` is true.

And I assume that we can’t just set `readOnlySource` with the new option, it should be a separate state, as it would be confusing with my source is not read-only but I still don’t want checkpoints?

**Comment by daleharvey** [comment]
We checkpoint because we do not want to run entire replications from scratch every time you load your local application, a checkpoint says 'this is where we left off, start from here'. 

We write checkpoints to both the client and the server to handle the case where either gets deleted, if you know the server will never be deleted then its safe to skip writing the remote ones which is what we are talking about here, with the flag enabled we would still be writing local ones.

I dont think there is any need to distinguish this feature and `readOnlySource`, they do the same thing, I would say its best to rename it but reuse the same code letting it be set as an option.

I really think this needs to be an option on the replication as opposed to the PouchDB instance though, its changing the behaviour of the replicator works instead of how pouchdb functions

**Comment by gr2m** [comment]
agree with all, will do, thanks Dale!

**Comment by gr2m** [comment]
Say I want to run a single test in `tests/integration/test.replication.js`, is there a way to speed up building / rerun? When I run in latest Node, do I need to build at all?

**Comment by gr2m** [comment]
I think I would like to differentiate settings for local and remote checkpoints.

The case I’m caring about is this: I have a local db `localdb` and a remote db `http://example.com/remotedb`. When I sync localdb <-> remotedb, I want to write checkpoints in `localdb` so that the next time I sync it resumes where it stopped. But I do not want to write checkpoints to `remotedb` to limit the amount of requests to the remote server. Does that make sense?

My understanding is that if I’d add a `checkpoints: false` option and don’t write checkpoints at all, neither in source nor in target, then my replications could not pick up the local changes since the last replication and it would try to bulk docs all my locla data and it also could not request remote changes with the `seq` number since the last time I pulled.

Or am I missing something? Sorry if I miss something obvious.

**Comment by daleharvey** [comment]
So not sure if Nolan was talking about shortening the name or actually disabling local checkpoints, but I think we only have a real use case for disabling remote checkpoints to lower the traffic so for simplicity's sake I would only expect one option 

However I fully agree with Jan, as mentioned in https://github.com/pouchdb/pouchdb/issues/6316 I would much rather see us take care to ensure we checkpoint a sensible amount than to add features to let users configure them

**Comment by nolanlawson** [comment]
> I really think this needs to be an option on the replication as opposed to the PouchDB instance though, its changing the behaviour of the replicator works instead of how pouchdb functions

Agree, came in here to say that. :)

> is there a way to speed up building / rerun

No, my implementation of `npm run dev` is really crappy. It could be sped up a lot.

> My understanding is that if I’d add a `checkpoints: false` option and don’t write checkpoints at all, neither in source nor in target

As Dale said this should really be a "don't write _remote_ checkpoints" option. Since replication has no concept of "remote" vs "local" though, it would have to be encoded as "source" or "target" checkpoints. I'm also not sure what this option would look like on the `sync` API since both sides are a target and a source.

> However I fully agree with Jan, as mentioned in #6316 I would much rather see us take care to ensure we checkpoint a sensible amount than to add features to let users configure them

You can already reduce the number of checkpoints written by changing the `batch_size`. Although if we think it would make sense, we can make it so that, say, a checkpoint is written every `n` batches instead of every batch. E.g.:

```js
{
  batches_per_checkpoint: 10 // default would be 1
}
```

I would be fine with such an option, although it's debatable whether it should apply to both local and remote checkpoints or just one or the other. `batches_per_target_checkpoint`? `batches_per_source_checkpoint`?

**Comment by gr2m** [comment]
> replication has no concept of "remote" vs "local" though

I would suggest to use `source` & `target` instead of `remote` and `local`, and match it with the docs on PouchDB, where the first argument is always the source, the 2nd is always the target: e.g. https://pouchdb.com/api.html#sync

At least for Hoodie’s case where we have full control over the sync and we know that source is the local db and target is the remote db, I would like to be able to have different settings for the two. In the local PouchDB I can write all the checkpoints with very little costs, for the remote database I want to limit this to a minimum

Does that make sense?

**Comment by nolanlawson** [comment]
Yes, so what you're proposing is that for PouchDB we use `source`/`target` but Hoodie can translate this to `remote`/`local`? That sounds good to me.

**Comment by gr2m** [comment]
yes exactly

**Comment by gr2m** [comment]
How do you all feel about a new single option `batches_per_checkpoint`:

```js
db.replicate.to('http://remote', {
  batches_per_checkpoint: 10
})
```

Then to set different values for source or target

### Option 1

```js
db.replicate.to('http://remote', {
  batches_per_checkpoint: {
    source: 1,
    target: 100
  }
})
```

### Option 2


```js
db.replicate.to('http://remote', {
  batches_per_checkpoint_source: 1,
  batches_per_checkpoint_target: 100
})
```

I like `Option 1` better, but I’d suggest to do whatever fits better with options of the existing APIs

**Comment by nolanlawson** [comment]
I vote `Option 1` as well. Also this:

```js
db.replicate.to('http://remote', {
  batches_per_checkpoint: 100
})
```

could be shorthand for:

```js
db.replicate.to('http://remote', {
  batches_per_checkpoint: {
    source: 100,
    target: 100
  }
})
```

As for the `sync` API, I think logically it would just be part of either the `push` or `pull` options.

**Comment by gr2m** [comment]
> could be shorthand for

Yes that was my thinking, too.

> it would just be part of either the push or pull options

I would think that when passed into sync, it would be passed to both, push & pull. If people need to pass different `batches_per_checkpoint` values they can do do the replicate.from and replicate.to separately, it’s pretty straight forward?

**Comment by nolanlawson** [comment]
So far with `sync` we've avoided complicating things by just having separate `pull` and `push` options (except for listeners). I think this is the best approach since it keeps things simple.

**Comment by chadrien** [comment]
@gr2m Hi! My current work project could use the option to disable remote checkpoints. Are you still working on this? If so how far is your progress on this feature? Is there anything I could do to help shipping this? :)

**Comment by gr2m** [comment]
@chadrien I unfortunately got pulled away because of other work and didn’t get to work on it yet myself. Please feel free to give it a try. I’m still very limited in time in June, but happy to help with reviews and questions as good as I can

**Comment by chadrien** [comment]
@gr2m I can definitely understand that. We (the rest of the team and I) will start working on something then. It's time to give back to the community :D

**Comment by chadrien** [comment]
@gr2m @nolanlawson @daleharvey so before we dive too deep into this, any recommendations/preferred API/other?
Would the new option used e.g. like this
```
sourceDb.replicate.to(targetDb, {target_checkpoints: false});
PouchDB.replicate(sourceDb, targetDb, {target_checkpoints: false});
```

**Comment by jareware** [comment]
I've also been looking forward to this, yay! 🎉 

> any recommendations/preferred API/other?

Rather than disabling the checkpointing completely, it might make more sense to just *limit it* a bit. Perhaps with options like "checkpoint after X many batches", or "checkpoint every 5 minutes"? Or in a perfect world, a combination of both?

Anyway, just my 0.02 EUR!

**Comment by gr2m** [comment]
> We (the rest of the team and I) will start working on something then

🎉🙌👏🙇 

> Rather than disabling the checkpointing completely, it might make more sense to just limit it a bit

I’d prefer to support both. Disabling it entirely makes sense for read only source databases. Say I build an app with a catalogue database, users can download this database and subscribe to its changes to keep it up-to-date, but they cannot do any changes in it, it’s only public-read. In such a case, no checkpoints should be written to the remote catalogue database whatsoever. Requests to write checkpoints would probably fail anyway if access settings are set correctly

**Comment by chadrien** [comment]
Hey @gr2m @nolanlawson @daleharvey sorry to bother you all, but I've be wrapping my head around and can't get to think of how to write a test case for this. Everything regarding checkpoints is made in a black box with local variable/constructors that can't be mocked and the actual checkpoints are stored in local documents with non deterministic id (unless I have access to the `generateReplicationId` function somehow?)

Also I've tried to take a look at how other tests regarding checkpoints are written, but then for example for [this test](https://github.com/pouchdb/pouchdb/blob/843e1f0eb102537551b295c37f9f343b26fb4db4/tests/integration/test.replication.js#L482-L503), if I write `return Promise.resolve()` as the first line of [`updateCheckpoint`](https://github.com/pouchdb/pouchdb/blob/843e1f0eb102537551b295c37f9f343b26fb4db4/packages/node_modules/pouchdb-checkpointer/src/index.js#L16) (meaning the checkpoints won't get written right?) the test is still passing…

So I'm quite unsure if I'm doing wrong, if the current tests are actually wrong, or maybe both :D ? A bit of help would be much appreciated, a lead of where/how I could start would be enough :)

Thanks!

**Comment by gr2m** [comment]
Probably the best to help would be @nolanlawson or @daleharvey, I remember I had a hard time with it myself when I tried to look into it

**Comment by nolanlawson** [comment]
> unless I have access to the generateReplicationId function somehow?

You do! :smiley: You can use this package: https://www.npmjs.com/package/pouchdb-generate-replication-id

**Comment by chadrien** [comment]
But is it available in the tests?

**Comment by daleharvey** [comment]
This one is more complicated than you need, but I think this is most easily tested with a component test, https://github.com/pouchdb/pouchdb/blob/master/tests/component/test.read_only_replication.js is an example (you can see the other examples in the same folder)

Doing a replication with the option then confirming that no requests were made to `_local/XXX` would be the easiest

**Comment by chadrien** [comment]
What about this, would that work?

```js
    it('Test configure batches per checkpoint', function (done) {
      var generateReplicationId = require('../../packages/node_modules/pouchdb-generate-replication-id');

      var db = new PouchDB(dbs.name);
      var remote = new PouchDB(dbs.remote);

      db.bulkDocs({ docs: docs }).then(function () {
        PouchDB.replicate(db, remote, { batch_size: 1, batches_per_checkpoint: 2 })
          .on('error', done)
          .on('complete', function () {
            generateReplicationId(db, remote, {}).then(function (replicationId) {
              remote.get(replicationId).then(function (checkpointDoc) {
                checkpointDoc.last_seq.should.equal(2);
                done();
              }).catch(done);
            }).catch(done);
          });
      }).catch(done);
    });
```

Basically checking that that 3 documents, a replication with `batch_size` of 1 of `batches_per_checkpoint` of 2, the checkpoint should have `last_seq` at 2 instead of 3 currently.

**Comment by daleharvey** [comment]
So few issues with that, one the API I was just commenting on (apologies for the delay), I would prefer we avoid leaky abstractions like `batches_per_checkpoint`, its exposing the internal details of how we replicate, it means this feature would need to be removed if/when we refactor the replicator, requires more understanding of the replicator than most people have and doesnt really make sense to me (the batches are written to the target whereas we are generally looking to prevent checkpoints written to the source)

I would much prefer an API of `checkpoints: remote | local | false` (hopefully self explanatory)

**Comment by chadrien** [comment]
After discussing about all this on IRC with @daleharvey the goal is to have the above described API (only with `s/remote/target/` and `s/local/source/`) to allow the user to disable checkpoints if needed.

The performance of what `batches_per_checkpoint` would provide should be improved in other ways (for the aforementioned reasons), i.e. like what's pointed out in #6554

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/01922606d6e5356fb244b75337027df4d62c86e2

**Comment by hermitdemschoenenleben** [comment]
thank you for implementing this! I'm just wondering how to use it in combination with sync if I just want to write checkpoints to my local db. Is this the way to go? (the documentation unfortunately does not comment on this)
```

PouchDB.sync(localDB, remoteDB, {
    push: {
        checkpoint: 'source'
    },
    pull: {
        checkpoint: 'target'
    }
})
```

**Comment by clariontools** [comment]
This is really a wonderful addition and I was running into sync issues before first stumbling on the api docs that mention it, then a few github threads including this one.  Like "the hermit"above, I am also pondering various use cases.

Where this tripped me up initially (testing not production) is in both deleting the server db, where I wanted the remote pouch to sync back to the server, and the case where a new mobile client is installed.  Also, issues occurred with indexdb localstorage on a web browser.

I was testing the since: 'now' option because without it I seemed to be getting all docs back even with checkpoint active simple calling allDocs on the local db with sync remote active. That turned the tables and with since: 'now' and checkpoints enabled, I would no longer get all the docs on the server if I completely deleted the local mobile (or web) data store and reinstalled or refreshed the web page.  This sort of thing happens in the real world where a user gets a new device, or uninstalls, then reinstalls on an existing device.

As I am testing with very small datasets at the moment, I don't think I can fully appreciate the effect of the different settings.  Also, additional docs or a cool graphic would help to understand how checkpoints work in the various configurations.  Even just understanding how checkpoints work how they are constructed, stored would be helpful in the PouchDB official docs.

I was also curious what would happen if I have one mobile client where checkpoints are off on the server db on local, then another client where checkpoints are active on both local and remote (the default)?  Understanding how checkpoints work and how they are stored would help.  In the case I just described, I am guessing that on the client that specified no checkpoints on the server but has checkpoints local, then docs that are sync'ed to the server would not get checkpoints?  Maybe the server always gets checkpoints but in this case the client sync would just ignore them?  BTW, I am using couchbase sync gateway for testing and this may differ from sync directly to CouchDB?

Regardless of any responses here, thanks again for implementing the checkpoint options, any additional documentation is just icing on the cake.  I will continue to test various use cases to see how these settings and the various db lifecycle use cases affect the overall sync functionality on both the server and local stores.
