### ISSUE TITLE
How to using total_rows in pouchdb find ?

### ISSUE THREAD

**Issue by lakulax** [pouchdb/pouchdb#6342]
I want to know how to using total_rows in pouchdb find ?

Thank You.

**Comment by lakulax** [comment]
Nope, i am found it by my self, it can using `result.docs.length` thanks everyone. :)

**Comment by darshantejani007** [comment]
That will be highly inefficient in case the result is very large. Is there any solution to get the same result as efficient as `_count` from `pouchdb map/reduce`?

**Comment by nolanlawson** [comment]
Currently, no. Also _count is not terribly efficient; it just does an Array.prototype.length in-memory.

**Comment by bgold0** [comment]
@nolanlawson so I don't have to open another issue, is there a way to get `total_rows` in `.find()`? Because I am not seeing it.

**Comment by garrensmith** [comment]
Total rows isn’t supported in find

________________________________

**Comment by atraianovschi** [comment]
Is this going to be reopened ?

**Comment by garrensmith** [comment]
No. It won’t ever be supported


________________________________

**Comment by justinr1234** [comment]
@garrensmith Why? Is there an alternative approach?

**Comment by appinteractive** [comment]
Its funny how many databases and/or examples/documentations struggle with that simple `total` issue over and over again. 🤦‍♂️ Did anyone solve that issues in a more or less sane way until now?

**Comment by CajunDust** [comment]
How should it then be solved ? Because simply saying "it will never be supported" is really not a helpfull alternative... Surely there must be a way to do this ?  Or is PouchDB/Find never meant to support large(r) datasets ? Isn't that the whole purpose of object db ?

**Comment by garrensmith** [comment]
Sorry, I thought I had left a decent explanation of why we can't support total_rows in this thread. But I hadn't. So here goes:
The issue is what is the total_rows that we would return? We have no way of calculating that other than taking the full result for a query and running through it and adding it up. 

With a pouchdb/couchdb view, we know how many rows we are saving on disk. So we keep a counter for that and when a query for a view is received just return the value from the counter. But pouchdb-find doesn't work like that. When you query with pouchdb-find, we can choose to use all_docs or an index. If we use all_docs, then total_rows would be your whole database. Is that useful? If we use an index, then total_rows would be the rows in the index. But that still isn't very accurate. Because not all the rows in the index will be returned for the selector. Pouchdb-find will filter out rows from the index/_all_docs that don't match the selector. 

What we actually need is aggregation functions with pouchdb-find that you could use to count, sum, min, max etc for an index. Some ideas around this can be found here https://github.com/apache/couchdb/issues/1254

I hope that helps.
