### ISSUE TITLE
Problem when updating docs in change event on sync.

### ISSUE THREAD

**Issue by tiagowippel** [pouchdb/pouchdb#6412]
### Issue

Problem when updating docs in change event on sync.

It is safe to update docs when a change event (on a sync) occurs ?

my code is leading my to a conflict state after doing this...

What i want it is basically notify the user that the replication was concluded and notify the server that the user received an update...

### Info
- Environment: (Node.js/browser)
- Platform: (Chrome)
- Adapter: (WebSQL)
- Server: (Cloudant)

### Reproduce

```
e.change.docs.filter(doc=>!doc._deleted).map((doc)=>{
                    //console.log(doc);

                    if (e.direction === 'push') {
                        if (doc.status === 1) { //a fresh doc created by the client

                            doc.status = 2; //mark this doc as sended
                            this.localDB.put(doc)
                            .then((res) => {})
                            .catch((err) => {console.log(err);});

                        }
                    }

                    if (e.direction === 'pull') {
                        if (doc.status === 3) { // user on server mark as received, at any time

                            doc.status = 4; // mark as received
                            this.localDB.put(doc)
                            .then((res) => {})
                            .catch((err) => {console.log(err);});
                           // after that i have a conflicted state....

                        }
                    }

                });
```

**Comment by karlwestin** [comment]
Hi there!

This is a little bit complicated, so i'm gonna make some assumptions from your text:

First, in general, try to avoid this pattern if you can. I'm making a suggestion on what to do instead below. 

### Why this is tricky

I Assume from your text that you are doing a live bi-directional replication, calling `PouchDB.sync(source, target, { live: true })`

Further, i assume that on your server, you are also listening to the changes feed, to replicate a document to another user and then marking it as seen from them.

I have modeled a similar flow here http://jsbin.com/bayadukove/edit?js,output with two browser PouchDB:s, one being 'browser' and one being 'server'

This pattern would work if all the events would happen in order, unfortunately in systems talking over the network, they rarely do :(

So what could happen is that
1. browser pushed document (status = 1) to the server
2. server starts doing its thing, updates document sets status = 3
3. browser updates document to status = 2
4. browser pushes status = 2 to the server
5. the server now has a conflict
6. browser receives (if it was the winning revision) status = 3
7. browser writes status = 4, document still has a conflict

Depending on what happens on the server, those events could happen in any order, but unfortunately because how networking is, they would rarely go in the one we want.

### What can we do instead?

Instead of updating the document status, write a new document that has signifies the status of the document. Relate them via the document ids. Here's an example

`var messageDoc = {   _id: message0001, message: 'whatever' }`

the message doc itself is status = 1, so that's not needed

in the sync function, instead of updating the doc, write a new doc

`browser.put({ _id: message0001-status_2, type: 'status', value: 2 })`

this doc only fills the role of writing status = 2

the server then writes

`server.put({ _id: message0001-status_3, type: 'status', value: 3 })`

when you receive this document in your replication, you can do

```javascript
if (doc.type === 'status' && doc.value === 3) {
   var docId = doc._id.split('-')[0] // make use to use a good delimiter here
   // check if we written status 4 first
   browser.get(docId + '-status_4')
      .catch(function (err) {
         // if you're getting an error here, you havent written status 4 yet
         return browser.put({ _id: message0001-status_4, type: 'status', value: 4 })
      })
}
```

**prefix all the status docs with the main doc id** this way you can get all the main document, and all its associated status docs via allDocs. 
Because we're writing the status as new documents instead of revisions, you wont have to handle any conflicts.
