### ISSUE TITLE
Live replication of multiple databases (12)

### ISSUE THREAD

**Issue by callum-spartan** [pouchdb/pouchdb#6528]
### Issue
Hi,

I have 12 databases on a CouchDB server that I want to replicate down to PouchDB on multiple mobile devices, and then keep the pouch databases up to date with any changes from the server. 

I have been separating the documents into different databases because of the high number of documents. Four of the databases still have between 500,000 - 600,000 documents.

When using live replication for each database, I am experiencing lots of connection time outs when connecting to the server for other tasks.

Is there another way to keep the pouch databases up to date without the need for 12 long polling connections to the server per mobile device?

### Info
- Environment: Cordova app
- Platform: Android/iOS Cordova
- Adapter: Cordova-sqlite-storage
- Server: CouchDB

![image](https://cloud.githubusercontent.com/assets/12034732/26458712/f5690b5a-416b-11e7-82f8-e1fde82e923a.png)

**Comment by nolanlawson** [comment]
I would recommend [pouchdb-load](https://github.com/pouchdb-community/pouchdb-load) for this use case. It would be really hard to optimize otherwise.

**Comment by callum-spartan** [comment]
Thanks @nolanlawson 

I have created sqlite databases to load an initial state for each database. 

The problem comes after the initial load when each of the databases is doing a long poll for further changes. 
I can turn off live replication for four of the databases that currently have 0 documents until they are needed in the future, but that still leaves 8 databases polling for changes. This includes the four databases with ~500,000 docs that will have lots of updates every few minutes that will need to be replicated to each handheld device.

I came across this stack overflow post that mentions a global changes feed across all databases in CouchDB 2.0. 
https://stackoverflow.com/questions/35993369/sync-with-multiple-databases#comment59683377_35994508

Is there a way to use the global changes feed to poll for changes across all of my databases in PouchDB 6.2.0?

**Comment by nolanlawson** [comment]
Unfortunately somebody would need to write a PouchDB plugin to work with the CouchDB global changes feed; I'm not aware of one. But yes, that would probably help your perf problem as well, although pouchdb-load would be much much faster if you are able to get it working.

**Comment by kripper** [comment]
The best solution so far is to use this socket-pouch fork (which @nolanlawson should merge into his abandoned original socket-pouch repo):
https://github.com/CoMfUcIoS/socket.io-pouch

This repo works perfect, supports multiplexing (to bypass the browser concurrent connection limits), uses socket.io instead of engine.io and looks clean.

I believe the socket-pouch server in the middle still keeps multiple long polling connections to the couchdb server.

Maybe the performance could be improved if the socket-pouch server in the middle is rewriten to use the global changes feed instead of keeping multiple long polling connections for each "subscribed" database.

Of course, it would be ideal if a pouch client plugin does it all directly and transparently using a single long polling connections listening the changes feed + database pulls only when needed. The only problem I see with this approach is that the client would be listening to all database changes, while you probably only want each client to listen to changes of a small set of "subscribed" databases. That's why the socket-pouch server in the middle solution could be preferred.

I never understood why there seems to be no official solution from the pouchdb community for this common problem.
