### ISSUE TITLE
Anyway to send raw query or not have parameters urlencoded?

### ISSUE THREAD

**Issue by LarryEitel** [pouchdb/pouchdb#6563]
I need to GET: `http://@localhost:5984/layer-terrhelper-default/_design/bbox/_view/bbox?startkey=[-76.36849134948727, 39.937618573722354, {}, {}]&endkey=[-75.99701612976071, 40.05466035844455, 0, 0]&include_docs=true`

However, in Explorer and Firefox the network shows: `http://localhost:5984/layer-terrhelper-default/_design/bbox/_view/bbox?include_docs=true&startkey=%22%5B-76.36849134948727%2C39.937618573722354%2C%7B%7D%2C%7B%7D%5D%22&endkey=%22%5B-75.99701612976071%2C40.05466035844455%2C0%2C0%5D%22`

Strange thing is that in Chrome it WORKS!!! Here is what Chrome shows: `http://localhost:5984/layer-terrhelper-default/_design/bbox/_view/bbox?startkey=[-76.36849134948727,%2039.937618573722354,%20{},%20{}]&endkey=[-75.99701612976071,%2040.05466035844455,%200,%200]&include_docs=true`

Thank you for any thoughts/suggestions.

**Comment by willholley** [comment]
I don't think the issue is the URL encoding - it's that the encoded representations have quotes around them, i.e. `startkey="[-76.36849134948727,39.937618573722354,{},{}]"&endkey="[-75.99701612976071,40.05466035844455,0,0]"` instead of `startkey=[-76.36849134948727,39.937618573722354,{},{}]&endkey=[-75.99701612976071,40.05466035844455,0,0]`.

Can you show the code you are using to make the get request and confirm the PouchDB version?

**Comment by LarryEitel** [comment]
@willholley THANK YOU!!!! That was the issue! I was doing something like:
```
db.query('bbox', {
        startkey: viewPortBounds.startkey,
        endkey: viewPortBounds.endkey,
        include_docs: true
      })
```
The variables came in as strings rather than the needed arrays.

Thank You :)
