### ISSUE TITLE
TypeError: __WEBPACK_IMPORTED_MODULE_4_pouchdb__.plugin is not a function

### ISSUE THREAD

**Issue by petrot** [pouchdb/pouchdb#6615]
### Issue
Got the following error with 6.3.4:

Uncaught (in promise): TypeError: __WEBPACK_IMPORTED_MODULE_4_pouchdb__.plugin is not a function TypeError: __WEBPACK_IMPORTED_MODULE_4_pouchdb__.plugin is not a function at http://localhost:8100/build/main.js:6890:64 at t.invoke (http://localhost:8100/build/polyfills.js:3:8971) at Object.onInvoke (http://localhost:8100/build/vendor.js:4488:37) at t.invoke (http://localhost:8100/build/polyfills.js:3:8911) at r.run (http://localhost:8100/build/polyfills.js:3:4140) at http://localhost:8100/build/polyfills.js:3:13731 at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9655) at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4479:37) at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9576) at r.runTask (http://localhost:8100/build/polyfills.js:3:4831)

Is there any new type definition for this version?

### Info
- Environment: Ionic 3
- Platform: Chrome
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: PouchDB

### Reproduce
I can't reproduce, this error appears on app init.

**Comment by michael42** [comment]
I think I'm having the same issue. Did the export change with 6.3? I'm importing it with webpack 3 via `import * as PouchDB from "pouchdb"` and then try to call `new PouchDB()`. With PouchDB 6.3.4, I'm getting an `{ default:function PouchDB$5(name, opts), __esModule:true }` object instead of a usable constructor.

Changing the import accordingly to `import PouchDB from "pouchdb"` (and the type definition to `declare module 'pouchdb' { const plugin: PouchDB.Static; export default plugin; }`) seems to fix it.

**Comment by mlegenhausen** [comment]
Is this a bug or a feature? Will there be a bugfix for pouchdb or should the type definition be fixed?

**Comment by michael42** [comment]
I'd call it an undocumented breaking change, but the interactions between PouchDB, TypeScript/Babel, Webpack and Node.js are quite messy...

The details, as I understand it, are that PouchDB now sets `{"module": "./lib/index.es.js"}` (#6352) in the package.json, which causes Webpack (2+) to load a different file than current Node.js 8 or Webpack with an older PouchDB. As both files export different a different structure (the old CommonJS `pouchdb.js` directly exports the PouchDB constructor, but the `index.es.js` can't do that because ES2015 modules don't export objects, they have just have named and defaults exports. The result is that when using Webpack (or a future Node.js that also loads `index.es.js`), users have to use the default import, otherwise the default import mustn't be used.

As far as I see it, a cleaner upgrade path requires both module formats to be structurally equivalent. With the ES2015 modules not supporting direct exports of functions, that probably means deprecating and removing the `var PouchDB = require('pouchdb')` import. Taking the existing structure of the ES2015 module, it would be written as `var PouchDB = require('pouchdb').default`. But wasn't one of the main principles behind the ["module" in package.json Proposal](https://github.com/dherman/defense-of-dot-js/blob/master/proposal.md) that it shouldn't require such breaking changes? Would different type definitions (depending on if `require` or `import` was used) be a better solution?

**Comment by karlbateman** [comment]
Hi all,
I notice this issue occurs when upgrading `@ionic/cli-plugin-cordova` from `1.4.1 -> 1.6.1` and `@ionic/cli-plugin-angular` from `1.3.2 -> 1.4.1`. I also have the latest Ionic CLI installed locally and Node v6.10.3 with NPM v3.10.10.

I hope this helps :smile:

**Comment by michael42** [comment]
I'm afraid the [new type definition](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18519) fixes this, but breaks the PouchDB import on Node.js. As outlined in my last comment, it's quite a mess to fix the issue.

I'm currently compiling with typings that just add a default export and don't remove the function export. That way, both `import PouchDB from "pouchdb"` (webpack) and `import * as PouchDB from "pouchdb"` (Node.js require) do compile, but if the wrong import is used, the imported value is `undefined`. I can open a pull request if that's the preferred solution/workaround.

**Comment by luanmm** [comment]
It's really messy the PouchDB + TypeScript combo. Hope someday we could get this things working well, because PouchDB do it job really well and is a great library to use with Angular and other frameworks. A shame is that it's too dificult to make things work in this scenarios.

**Comment by shimaore** [comment]
FWIW in webpack 3 (3.5.5) I was able to work around this by adding
```javascript
  resolve: {
    mainFields: ['browser','main','module']
  },
```
to `webpack.conf.js`. (This changes the order of processing of fields in `package.json`, however [`mainFields`](https://webpack.js.org/configuration/resolve/#resolve-mainfields) affects all modules.)

**Comment by CarlosAyala** [comment]
I fix this issue with 

`npm install --save @types/pouchdb`

And changing all the code from 

`import * as PouchDB from 'pouchdb'; `

to

`import PouchDB from 'pouchdb';`
