### ISSUE TITLE
Invalid Adapter in iOS 10 WKWebView

### ISSUE THREAD

**Issue by alexmills** [pouchdb/pouchdb#6701]
### Issue
When using pouchdb-browser in an WKWebView, it fails with error

```
Error: Invalid Adapter: undefined
```

### Info
- Environment: React app in a WKWebView
- Platform: iOS

### Reproduce
Using either 

``` javascript
const db = new PouchDB('db_test_4')
```
or

``` javascript
const db = new PouchDB('db_test_4', { adapter: 'idb'})
```

will result in the same error (specifying adaptor will list it's name instead of 'undefined')

Calling `window.indexedDB` via console returns a `IDBFactory` object as normal.

If I go through the PouchDB code at `parseAdapter` 

``` javascript
PouchDB$3.adapters -> {http: function, https: function}
PouchDB$3.preferredAdapters -> []
```

**Comment by lostdev** [comment]
I also have this same issue. @alexmills do you have a workaround?

Thanks!

**Comment by alexmills** [comment]
Hi @lostdev, from what I can remember I had to do this little hack within the node_module itself

```
node_modules/pouchdb-browser/lib/index.es.js
```

![screen shot 2017-09-21 at 8 54 17 am](https://user-images.githubusercontent.com/661414/30674165-cf4b4d38-9eaa-11e7-8f38-20afc07ec7d6.png)
 
Which makes sure that IndexDB is used when Safari is detected. I've only tested this within my WKWebView app so your mileage may vary.

If that doesn't solve it, let me know and I'll look to see if I had to do anything else 👍

**Comment by humpedli** [comment]
That's a great issue management! Congratulation! The bot is closing the issues without any modifications. This issue is still exist and should be fixed!

**Comment by daleharvey** [comment]
Just a heads up we have zero tolerance for sarcastic / antagonistic posts here, if you would like to contribute / have any useful information or want to actually fix the issue at hand (its a cordova issue, not a core pouchdb one) then we would be happy to receive them, otherwise please keep it to yourself, cheers

**Comment by humpedli** [comment]
@daleharvey No, unfortunately this is not a cordova issue, since I am not using cordova at all. 

- [ ] Just create a single html file, load the latest PouchDB (6.4.3) JS
- [ ] Create a simple database in this file (with PouchDB)
- [ ] Then create a native iOS application in XCode (use Swift or Objective-C as language, it doesn't matter), it should contain only a simple WKWebview container. 
- [ ] Then load the previously created and hosted html file in it and you will see the error. 

This is a PouchDB error because I used only native code except PouchDB library and as @alexmills mentioned `window.indexedDB` returns the correct object. @alexmills also mentioned a possible solution for this bug and it's working but I don't see that you would have accepted it, the bot just closed this issue and nothing happened. I think this is not a correct workflow.

**Comment by daleharvey** [comment]
1. WKWebview errors are not necessarily PouchDB errors, given we are working on ios safari and every other browser indexeddb implementation its likely a wkwebview issue, we may or may not burden core pouchdb with a workaround for wkwebview bugs, depending on the bug / fix, neither of which are apparent

2. The fix alex mills suggested is already in PouchDB, we use indexeddb in safari @ https://github.com/pouchdb/pouchdb/commit/49bdffd1bc2a6ec41d7d7c8c90782bf22bc73adc (the hasFetch may need tweaking for wkwebview?)

3. I cant accept pull requests that do not exist, this project has 280 contributors, we accept pull requests when people make them

4. Nobody has asked for your opinion on correct issue management workflow
