### ISSUE TITLE
Sync changes from a specific remote sequence

### ISSUE THREAD

**Issue by parthgandhi7** [pouchdb/pouchdb#6751]
Here's what i want to do:
1. Bulk insert some(not all) of my documents(which are also present in the remote db)
2. Start my pouchdb sync from the **update sequence of the remote db**. i.e. start listening for changes on remote and local database from now (i tried since: 'now', but it does not seem useful in my case as it starts listening for changes from the update sequence of my local db and thus syncs all documents (the documents i bulk inserted also) again. and thus there are 2 pairs of those documents with conflicting revisions and thus they get processed twice (once while i inserted and once while the sync brings those documents)
I don't want to sync all my documents from the remote db to my local db. I just want the bulk inserted documents and the subsequent changes should be synced properly.

So, i want to tell the changesFeed to start syncing from the remote sequence.

If i start listening for changes from the remote sequence, none of my changes to local documents are processed as the local sequence is quite behind the remote sequence. Can you please help me with this ? Am i missing some thing or am i doing something conceptually wrong?

**Comment by willholley** [comment]
sequence numbers are specific to an individual database instance so it's never valid to take a sequence from e.g. a local database and use it as a `since` parameter on a remote database. That said, both local and remote databases should natively support `since=now`, so if PouchDB is translating that into some invalid valid then it's a bug.
