### ISSUE TITLE
Travis stability

### ISSUE THREAD

**Issue by marten-de-vries** [pouchdb/pouchdb#6802]
Travis makes it pretty much impossible to merge even trivial PRs currently. (See e.g.: @loic's https://travis-ci.org/pouchdb/pouchdb/builds/290187434 ; #6793) I've been restarting the tests, but they seem to keep failing due to timeouts and one-off unreproducable errors.

Unless someone wants to and has time to look into fixing the stability of the test suite, I think we're going to have to move some of the tests to the allowed failures list. It's quite indicative that not a single PR that's currently open manages to pass Travis, not even the simple greenkeeper PRs. It currently makes development impossible. Thoughts?

**Comment by gr2m** [comment]
That’s a tough one, the great code coverage and trust in tests was a strength of PouchDB. I’d be great if someone could take the time to investigate it proper, unfortunately I’m to caught up in other projects myself right now :/

**Comment by loic** [comment]
Maybe a middle ground would be to only test `master` against the more exotic browser/platforms and be more lenient with branches and PRs. As long as releases are only issued following a full green CI, that doesn't compromise the quality of the project.

Most of those failure are not related to broken tests, but to fragile infrastructure, fixing it is not trivial and may require ugly hardening all over the place.

**Comment by daleharvey** [comment]
After dealing with this problem hundreds of times with pouchdb, 99% of the time the test suite is not broken, it is doing its job and finding failures with pouchdb, sometimes the bug is an assertion in the test but either way the test suite is not a seperate thing to pouchdb, its what makes pouchdb work

In terms of relaxing the test suite, if there are specific environments that are buggy like websql or couchdb-master and we can temporarily put them in allowed_failures then we have been happy to do that, but otherwise I do not love the idea of testing less because it means in very real terms giving up the stability of pouchdb

Taking a very quick look over the failures in https://travis-ci.org/pouchdb/pouchdb/builds/290688191, I cant see a quick correlation between environments so it looks like a core problem with pouchdb or a test, 3 of the failures have stacks and they looks very similiar if someone could find whats up with that bug then it would likely have a large effect

Maintaining the test suite is kinda like gardening, we either have to keep it green and trim the weeds when we see them, or we give up and very quickly get overrun. If we cant get a green test suite on trivial PR's then just doing it for releases will take a monumental effort. I havent had any time recently to work on this but will in the new year by the latest

**Comment by gr2m** [comment]
@daleharvey maybe we can coordinate a few days with other folks who are interested to block some time for PouchDB, and we can work on it together? I’d be happy to block some time in the new year for that :) 

Also I agree to everything you said :100

**Comment by marten-de-vries** [comment]
I did not open this issue lightly. I agree, dropping tests will cause the configurations we drop to become less stable. Dropping them will mean having to do significant work to get them supported again later on. That said, I do think we have a problem when we cannot timely merge minor PRs of new contributors. It might turn them away. Stability is important, but so is keeping the project active in the long term.

It's clear that disabling tests now is probably a step too far based on your responses. All I ask then is that everyone keeps the option of reducing the test matrix in mind as an alternative to having to fix everything, going forward. The test suite is worth a lot, but in my opinion not project stagnation or increased pressure on the few contributors that know the whole code base well.

> I havent had any time recently to work on this but will in the new year by the latest

Please don't feel like you have to, that was not my intention when starting this discussion.

**Comment by marten-de-vries** [comment]
Closing this issue, as I don't think much more needs to be said on this. The points of view seem to be clear. Feel free to reopen if you have something to add, though.

I did open a more concrete follow-up issue on a specific problematic test that keeps failing: https://github.com/pouchdb/pouchdb/issues/6803
