### ISSUE TITLE
Feature: 'pending' number of docs to UPLOAD to CouchDB 2.0+ server

### ISSUE THREAD

**Issue by dharders** [pouchdb/pouchdb#6818]
### Issue
This is a follow on from PR #6812 , which added `pending` support to the replication changes event feed (i.e.  `rep.on('change', (info) => console.log(info.pending))`) when it is provided by the remote server (CouchDB 2.0+ feature).

However, the `pending` value only appears in the replication changes feed **FROM** the remote server. eg Pending docs to DOWNLOAD from remote db server to local db.

We now wish to provide the same feature in the opposite direction. i.e. `pending` documents/changes to **UPLOAD TO** remote db server from local db.

We will most likely have to emulate CouchDB 2.0+ pending algorithm on the frontend. Investigation still needs to be carried out.

### Motivation
Have `pending` values given in both directions of replication/sync `change` event so we can finally have easy replication progress reporting and percentages. Closes #5713 

### Info
- Environment: All
- Platform: All
- Adapter: All
- Server: CouchDB 2.0+

**Comment by MartinN3** [comment]
Something like background fetch to rescue? https://developers.google.com/web/updates/2018/12/background-fetch

**Comment by simpsojo** [comment]
Hi, is there a workaround for this?  Any way to inspect pouch or IndexedDB directly to know the upload queue size?

**Comment by plinss** [comment]
The workaround I use is to wrap PouchDB in my own DB class and after every put or remove I store the document's id and revision sequence in a map (overwriting existing ids only if the sequence is higher, the sequence being the part of the revision before the '-'). Then when syncing, watch for change events with a 'push' direction and remove the pushed document's id from the map if the revision sequence matches. The size of the map is the number of documents waiting to be pushed.

**Comment by jbotte** [comment]
@plinss i like this solution. is there ever an instance where a user could close the app after a successful change but before the item is removed from the map? I have some clients which experience frequent power outages and i'm trying to prevent orphaned data.

**Comment by plinss** [comment]
@jbotte unfortunately this approach is completely memory based, so yes, there's nothing preventing the app from quitting at any time, especially due to a power outage. Simply reloading the page would also lose the map as I'm not persisting it anywhere (currently, though nothing would prevent data loss between updating the map and persisting it). Ideally we really need a solution internal to PouchDB that can recover the upload state when reconnecting to a remote.

**Comment by kdoran** [comment]
we use a hack where you listen to the replication feed's `change` event and store the `last_seq` from it in a local doc. To get an estimate of pending changes you count the current changes since that stored replication last_seq. https://github.com/fielded/pouchdb-pending-upload/blob/master/index.js

It's flawed but works OK for when users go offline and the remote feed stops firing. And like mentioned here we use the real `pending` number from couch to show download:

> For now, I use the pending code for DOWNLOAD, and fallback to last_seq / update_seq for UPLOAD.

https://github.com/pouchdb/pouchdb/issues/5713#issuecomment-435631516
