### ISSUE TITLE
test pouchdb-server doesnt use updated pouchdb modules

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#6859]
As been finding in recent PR's

**Comment by nename0** [comment]
One question: Why is [the code](https://github.com/pouchdb/pouchdb/blob/master/bin/run-test.sh#L8) only executed on travis?? The way I reproduced / found this error was to actually remove this if and run it with the paramters from travis. If you just execute the parameters from travis and dont't remove the if, it will fail [here](https://github.com/pouchdb/pouchdb/blob/master/bin/run-test.sh#L33) because it does not find `pouchdb-server-install`. So the if seems a bit odd to me.

**Comment by daleharvey** [comment]
Locally users are expected to have set up their own server, the code that runs outside the if should really be inside it for the reason you said

**Comment by daleharvey** [comment]
Fixed, however would like to get rid of ispouchdbServer in the tests (and the recently added istanbul ignores) before closing
