### ISSUE TITLE
How can I get an array with all the values from my PouchDB database to use Datatable pagination?

### ISSUE THREAD

**Issue by chuntaro18** [pouchdb/pouchdb#6867]
Hi PouchDb team.

With the following code I am able to show a table with the data storage locally using PouchDB, but there is no pagination.

To make the pagination I want to use DataTables (jQuery plugin) through Javascript sourced data, because receives the values with an array.

The question is, how can I obtain the array with all the values from my pouchdb database to use DataTable pagination?

the array should have this structure

var myVariable = [ ["name value", "age value", "email value", "comment value"] ];

This is my code:

    <!DOCTYPE html>
    <html>
    <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, 
    minimum-scale=1, user-scalable=no, minimal-ui">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    

       <link rel="stylesheet" href="css/bootstrap.min.css">
       <link rel="stylesheet" href="css/jquery.dataTables.min.css">
    
        <script src="js/jquery-3.2.1.min.js"></script> 
	<script src="js/pouchdb-6.3.4.min.js"></script>
	<script src="js/bootstrap.min.js"></script>
	<script src="js/jquery.dataTables.min.js"></script>
    
        <title>Offline App</title>
    
       </head>
  
          <body>
   
            <h2 style="text-align: center">Add survey</h2>
            <br>
    
          <div style="text-align: center">    
	        <form id="formularioencuesta" name="formularioencuesta" method="post">         
	        <label>Name:</label>
	        <input id="name" name="name" placeholder="Type your name"/>	

	        <label>Age:</label>  
	        <input id="age" name="age" type="text" placeholder="Type your age"/>

		<label>Email:</label>               
		<input id="email" name="email" type="text" placeholder="Type your email"/>

		<label>Comment:</label>               
		<input id="comment" name="comment" type="text" placeholder="Type your comment"/>   

		<hr/>
		<input id="btn_save" name="btn_save" type="button" value="Save survey"/>
		 &nbsp;
		<input id="btn_sync" name="btn_sync" type="button" value="Sync data"/>  
		<hr/>      
	      </form>
         </div>

     <div class="row">         
        <div class="table-responsive col-sm-12">
           <table id="TableResults" class="table table-bordered table-striped display" cellspacing="0" 
              width="100%">
                 <thead>
                     <tr>
                        <th>Name</th>
                        <th>Age</th>
                        <th>Email</th>
                        <th>Comment</th>
                        <th></th>
                    </tr>
                   </thead>  
                   <tbody></tbody>   
                </table>   
         </div>
      </div>

    <script>	
        $(document).ready(function(){
        ShowResults();	
        $('#TableResults').DataTable();				
        $('#btn_save').click(function(){
		Add( 
		$('#name').val(), 
		$('#age').val(), 
		$('#email').val(), 
		$('#comment').val() 
		);
            });			
         $('#btn_sync').click(function(){
		sync();
         });
       });
	
	var LocalDB = new PouchDB('offlinebd');
	var RemoteDB = 'http://127.0.0.1:5984/offlinebd';	
	var documents=[];
			
	LocalDB.changes({
		since: 'now',
		live: true
	}).on('change', ShowResults);
		
    // ADD FUNCTION
		function Add(name, age, email, comment){
			var survey={
				_id: new Date().toISOString(),
				name: name,
				age: age,
				email: email,
				comment: comment
			};
			LocalDB.put(survey, function callback(error,result){
				if (!error){
					alert('¡Survey saved!');
					document.getElementById("name").value="";
					document.getElementById("age").value="";
					document.getElementById("email").value="";
					document.getElementById("comment").value="";
				}
				
			});
		};	
			
    // SHOW RESULTS FUNCTION
    function ShowResults() {
	
	  documents=null;
      
	  LocalDB.allDocs({include_docs: true, descending:true}).then(function(docs) {
	  
	  documents = docs.rows;	
            var tbody = '';
      
		$.each(documents, function (i, element) {
                  var row = '<tr> <td>' + element.doc.name + '</td> <td>' + element.doc.age + '</td> 
                  <td>' + element.doc.email + '</td> <td>' + element.doc.comment + '</td> <td><button 
                  onclick="remove('+i+')">[X]</button></td> </tr>';
                  tbody += row;
                  });

                $("#TableResults tbody").html('').html(tbody);
             });
           } 
	
      // REMOVE FUNCTION
		function remove(indice){
			if(confirm("Are you sure want to delete this?")==true){
				element = documents[indice].doc;
				LocalDB.remove(element).then(function(){
					alert('The data has been deleted');
				});
			}
		}	
			
       // SYNC FUNCTION	
		function sync(){
			LocalDB.sync(RemoteDB)
				.on('complete', function () {
				  alert('All data has been sync!');
				})		
				.on('error', function (err) {
				  alert('The sync has failed!');
				});
		        }
		
        </script>
     </body>
    </html>

**Comment by avickers** [comment]
This is really a question for StackOverflow.

You already know how to use AllDocs and a mapping function.  Instead of using the mapping function to create the HTML, you would create an array and push it to an array of arrays.  That's what you asked, but probably not what you want an answer to.

[See the documentation for DataTables](https://datatables.net/manual/data/).
Build an array of objects instead of an array of arrays, and map the data to your columns per the documentation.

Only call your ShowResults function, where you map all the documents, once after an initial load/sync of the data.  Do not call it from the on change event with a live replication.

Once you have populated your table with the initial data, setup a live replication and use the on change event in conjunction with row.add() and row().remove() to dynamically update your data.  Do not rebuild your entire model and rerender the entire UI for each change.

The reason for building an array of objects is so that you can retain the doc ids and use them to easily identify which row to remove.

Since this repo is about PouchDB and not DataTables, I would like to emphasize that, if you are calling AllDocs as a regular matter of course in order to rebuild your entire model in response to the changes feed, then you are probably using C/PouchDB in a very inefficient manner.

**Comment by daleharvey** [comment]
not a bug and answered, thanks
