### ISSUE TITLE
Remote couchdb updates only trigger sync.on('change') event on 1 of multiple application tabs

### ISSUE THREAD

**Issue by flamasa** [pouchdb/pouchdb#7004]
### Issue
When a document is changed remotely from couchdb and I have 2 application instances running (each on it's own chrome tab), only one instance's sync.on('change', myChangeFunction) is triggered.

### Info
- Environment: browser
- Platform: Chrome
- Adapter: IndexedDB
- Server: CouchDB

### Reproduce
1) Create an html with:

```
const myDb = new PouchDB('mydb');
const myRemoteDb = new PouchDB(remoteDbUrl);

const sync = myDb .sync(myRemoteDb , {
      live: true,
      retry: true
    }).on('change', function (change) {
      // handle change
      console.log("CouchDB data updated: loadFromStore().");
      if (change.direction === 'pull') console.log('Remote change event received..');
    });
```

2) Bring up CouchDb instance.

3) Open page in 2 chrome browser tabs.

4) Load "_utils" couchdb page, drill into , edit and save document.

Result:
You should see that only one tab prints "Remote change event received.." to console.

**Comment by fehrenbach** [comment]
I think this is expected. The updated document is only changed once, by one replication process, because then it is up to date, so there is no need to change it again by the second replication process.

You might want to use the [changes API](https://pouchdb.com/api.html#changes) to listen to database changes. These change events should fire in all tabs, no matter which tab actually did the replication.

**Comment by daleharvey** [comment]
Yup, definitely a little confusing but the change events are those of the replication, not of the database as @fehrenbach described

**Comment by flamasa** [comment]
I will try that.  Thank  you.
