### ISSUE TITLE
Get Edge tested in CI

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#7047]
Apparently @nolanlawson has seen this working, currently failing @ https://github.com/pouchdb/pouchdb/pull/7041

**Comment by daleharvey** [comment]
Working on this

**Comment by nolanlawson** [comment]
Unfortunately you may have trouble getting Edge to pass in Sauce Labs. Our IDB implementation still needs a fair bit of work; I even have an internal issue open where I point to the PouchDB test suite as an example of lack of stability in our IDB impl. Seems Travis CI is failing with either Sauce Labs giving no response (Web Driver issues?) or an IDB error saying "Are you in private browsing mode?" (IDB reliability issues)

In the past I used to only test IE 10 in Win 8.1 because it was literally the only one that seemed to work in Sauce, dunno if that's still an option.

**Comment by daleharvey** [comment]
So edge 17 is looking pretty reliable for me locally, theres 1 browser.worker failing but ran the test suite 3 times and only seen that failure, however only Edge 14 is running for me on saucelabs and I dont even know how to get that installed

IE11 is too much marketshare to be dropping support for, I am guessing our fetch / promise changes have broken that so I think we should be both getting edge 17 working in saucelabs, and fixing ie11, would be happy to do a release with either of those in place

**Comment by daleharvey** [comment]
quick update, locally the tests are passing in edge 17, in travis edge 17 wont run for some reason, edge 14 does and is reasonably stable but always fails an intermittent somewhere around 800-1000 passing tests. ie is definitely buggy but seems to mostly fail on the tests that do lots of writes quickly (some of those tests we already sniff safari in)

right now I am looking for the tests that regularly fail in ie (cause I can do that locally) and skip them, not that fussed about them being skipped since its obviously ie thats broken here

**Comment by daleharvey** [comment]
These are still a little less stable than I am happy with, but passing :) https://github.com/pouchdb/pouchdb/commit/903110d201fddef7e32dbf4d93179db912962f06
