### ISSUE TITLE
subdocument support

### ISSUE THREAD

**Issue by wreuven** [pouchdb/pouchdb#7063]
### Issue
Does pouchdb support couchdb subdocument access: i.e. mutate_in(...). If not, could it be added?

**Comment by daleharvey** [comment]
How does couchdb do sub document access? I remember it being mentioned on a roadmap a long time ago but have not seen it be implemented, we would be looking for parity across any API like this

**Comment by daleharvey** [comment]
Looking at `mutate_in` it looks like a couchbase thing and not couchdb, if we were going to do this it would be led by a couchdb implementation (sub document access is generally less important for pouchdb since access it local anyway) so closing out, if anyone makes any progress on the couch side then please reopen

alternatively if you really want this for just pouchdb, it would be a suitable as a plugin
