### ISSUE TITLE
Question: Sync throttling

### ISSUE THREAD

**Issue by mpicard** [pouchdb/pouchdb#7076]
# Question: Sync throttling / batching

Is there a way to throttle syncing while `live: true`? I have set a batch_size of 10 but each put makes a request. I would expect every 10 puts to make a request. Perhaps I misunderstood the options for replication/sync. Is there an elegant way to throttle http requests while using `live: true` or will I have to manually push-pull in intervals?

**Comment by daleharvey** [comment]
The batch size refers to how many document we will collect for a single push, this will usually only be effective when we start replicating an existing database, possible to hit if local documents are written faster than we can replicate them but otherwise it is unlikely to be used during live replication. live replication is supposed to be as fast as it possibly can and it will send changes as soon as it sees them, if you want to throttle it then you will need to do non live and stop / start it yourself

**Comment by mpicard** [comment]
Thanks for the explanation Dale! I'll do `live: false` and manage the sync
manually
