### ISSUE TITLE
Error indexed_db_went_bad on reading from a database

### ISSUE THREAD

**Issue by aneeshd16** [pouchdb/pouchdb#7098]
### Issue
Error on reading data from a pouch database:
```
{status: 500, name: "indexed_db_went_bad", message: "unknown", error: true, reason: "DataError"}
```

The database has auto compaction enabled, and is continuously replicated `from` a remote couch db database. Currently, this database has only 4 documents, but they are updated very frequently (every 10 seconds or so). This error cropped up after a few days of the application running on the target system. The application typically runs for around 12 hours everyday, and this replication is active during the entire time.

### Info
- Pouch Version - 6.3.4
- Environment: (browser)
- Platform: (Chrome)
- Adapter: (IndexedDB)
- Server: (CouchDB)

CC: @MohitKumar1991

**Comment by baversjo** [comment]
I'm experiencing exactly the same issue in production. My database is continuously replicated to/from a remote Cloudant database. PouchDB 6.4.3, Chrome 64.

**Comment by baversjo** [comment]
In my case however, i've been using worker-pouch to improve user performance. I'm disabling that in hopes it may resolve the issue.

**Comment by baversjo** [comment]
There's another report of indexed_db_went_bad, #6985 . I am not using attachments in my application at all, not sure if you are @aneeshd16 ?

**Comment by aneeshd16** [comment]
@baversjo Nope, not using attachments. I also get this error message logged to the console: `DOMException: Failed to read large IndexedDB value`

**Comment by 0000marcell** [comment]
This error occurs everytime i try to use the db so i'm unable to do anything, i'm just using local storage without any syncing

**Comment by group131** [comment]
Same problem here... (Followed by pouchdb-6.3.4.min.js:8 Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.)

**Comment by zeemi** [comment]
I've encountered the same problem on version "6.4.3".  I'm also not using attachment.

**Comment by baversjo** [comment]
For my specific application, I was able to resolve the issue by doing two things. As this only occurs in production, I've yet to determine what the actual cause was. But in case you're doing one of below things, they could be the cause:
- I used [worker-pouch](https://github.com/pouchdb-community/worker-pouch) to speed up my UI.
- I was causing excessive conflicts in my backend ( a single document could have ~50 conflicts) in my CouchDB (which synced to pouch).

Since I removed worker-pouch, and fixed the cause of the excessive conflicts, we haven't seen this issue at all. To check for conflicts, add a view like this in couch:
```
function(doc) {
  if(doc._conflicts) {
    emit(doc._conflicts, doc._conflicts.length);
  }
}
```

My guess is that the issue was the excessive conflicts, so I will soon enable `worker-pouch` again to be sure. Then I will let you know if worker-pouch or conflicts was the culprit in my case...

**Comment by aneeshd16** [comment]
Thanks @baversjo my CouchDB has a similar issue. A lot of documents (~2000) have conflicts, but a single document does not have more than 2 or 3 conflicts. However, I am still not sure whether this would could be the root cause. FYI, I am not using worker-pouch.

I am also using secondary indexes to query data, and query times are also a lot more than expected.

**Comment by platov** [comment]
I have the same issue.
Application creates about 6 000 documents per 2 hours
Randomly at some point of time IDB send error 'Failed to read large IndexedDB value'.

After investigations i realized that IDB contain 1 document that cannot be fetched.

Looks like this issue more related to IndexedDB itself.
I don't know how to reproduce this issue manually, had try to create very large document and do read/write with IDB - but it works well.
In source files of Chromium i found one mentioning about this error https://github.com/chromium/chromium/blob/94be0097939ef4938459e4ffa8dbc9a2ed45dda0/third_party/WebKit/Source/modules/indexeddb/IDBRequestLoader.cpp#L135

##Info
- Pouch Version - 6.4.1
- Auto compaction: true
- Replication: false
- worker-pouch: false
- Environment: Chrome v58 webview
- Platform: Android(Cordova)
- Adapter: IndexedDB

**Comment by aneeshd16** [comment]
Just wondering, are revisions/conflicts in a pouch document stored in the same IDB "field"?

**Comment by group131** [comment]
> After investigations i realized that IDB contain 1 document that cannot be fetched.
That broken document is often changing in application (may be changed 1000 times per 2 hours)

>Looks like this issue more related to IndexedDB itself.

Very similar with my experience. Problem arises with a single file that breaks the entire thing. You can fetch all other files one by one using their id (was actually thinking of creating an emergency export script for my app). It seems that something happens when a file is updated repeatedly and it most certainly is an IndexedDB issue.

**Comment by platov** [comment]
Today i've tried to fetch broken document directly using IDB API, result - the same error.

Interesting that about month ago i didn't experience this issue. Chromium version was not updated since.

Only one thing what was changed is - i enabled auto compaction and set `revs_limit: 1`.

So now i'm running test on 4 application instances (in parallel) with **disabled auto compaction**.
The error didn't appeared yet. When i complete the test i will share the end result.

Is it possible that auto compaction may do something wrong with document ?

**Comment by platov** [comment]
Made 8 times test where application create up to 1200 documents.
Error didn't appear.

### What was changed
disabled auto compaction
removed `revs_limit:1` option

Any thoughts how that options may lead to IDB exception `Failed to read large IndexedDB value` ?
```
{
    auto_compaction: true
    revs_limit: 1
}
```

**Comment by group131** [comment]
Hmmmm wouldn't this create huge indexedDBs? What about storage issues?

**Comment by platov** [comment]
@group131 , may you provide yours options for PouchDB instance ?

**Comment by group131** [comment]
I use auto compaction too... {auto_compaction: true}
You may have a good lead there, however I'm a bit worried about size with auto_compaction false.

**Comment by baversjo** [comment]
I just realized that one of the changes I did which may have resolved it for me, was to disable auto compaction. I sync weekly databases to the pouch client and delete old ones, so I don't need auto compaction. This could've been what solved it for me too.

**Comment by group131** [comment]
So @baversjo is this fixed for you?

**Comment by platov** [comment]
@group131 what Chrome version do you use ?

**Comment by group131** [comment]
@platov Build 65.0.3325.181 (Official) (64-bit)

**Comment by platov** [comment]
## Conclusion
Definitely the entire error appears if `auto_compaction` is enabled and DB contains documents are which often changing.

**Temporary solution is**
disable `auto_compaction` and do manual compaction by some rules or timer imperatively.

But entire problem is not resolved - i want to see thought from PouchDB developers about of how `auto_compaction` may perform this issue with IDB. We have to understand is it possible to fix from PouchDB side or this is only IDB issue and we have to move this discussion into the Chromium repo

**Comment by group131** [comment]
I disabled auto_compaction to check if this comes up again. Question: Can I change options for an existing pouchDB? Or users should create new pouchDBs with auto_compaction:false?

I also wrote a script that performs an emergency export of all files except the one with the problem. If I could find a way to also salvage this one last file, it would be awesome...

@platov is manual compaction safe? Have you tested it?

**Comment by tomaszn** [comment]
FYI: I'm getting the same `DOMException: Failed to read large IndexedDB value` using localforage (completely different db wrapper) on Chrome 65.0.3325.109 and 67.0.3381.0 (current unstable). I can't reproduce it on Firefox 52.5.3 and Chrome 48.0.2564.109.

**Comment by daleharvey** [comment]
Thanks a lot, this investigation is awesome. So from I can guess at from the comments, I am not convinced there is anything broken with `auto_compaction` itself, however it looks like some recent changes in chrome have caused it to not be able to handle a large volume of writes consistently, and `auto_compaction` will trigger a lot of writes. 

Will see about writing a script to reproduce and ask any chrome developers if they know of anything like this on their radar

**Comment by tomaszn** [comment]
Looks like https://bugs.chromium.org/p/chromium/issues/detail?id=756447.

All bugs in IndexedDB (including fixed etc.):
https://bugs.chromium.org/p/chromium/issues/list?can=1&q=component%3ABlink>Storage>IndexedDB

And this maybe useful, looks like a list of changes in `indexeddb`:
https://chromium.googlesource.com/chromium/src.git/+log/master/third_party/WebKit/Source/modules/indexeddb

**Comment by tomaszn** [comment]
For me these crashes start with [commit number 516126: IndexedDB: Re-enable special handling of large values.](https://chromium.googlesource.com/chromium/src/+/564f38984a515998699c7a522f9721a22933630c)

Please check your case on [last good for me](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/516121/) and [first bad](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/516127/).

**Comment by tomaszn** [comment]
They're asking for a reproducer: https://bugs.chromium.org/p/chromium/issues/detail?id=756447#c24

**Comment by rpiaggio** [comment]
We are having the same issue:

`{"status":500,"name":"indexed_db_went_bad","message":"unknown","reason":"UnknownError"}`

User-Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1`

The error happens on iPhone Safari 11.3 when we attempt to retrieve or save a document (via `db.get` or `db.put`).

**Comment by group131** [comment]
What I did was try to get all my files one by one, to isolate the one that caused the issue.

**Comment by daleharvey** [comment]
ok so the chrome fix for this has landed, I will call out the bug in the release notes since its pretty severe but otherwise very hard for us to do anything reliably to fix bugs in chrome migrations so closing this out, if your bug isnt the chrome issue and you can reproduce with latest pouch / latest browsers please file a new bug

**Comment by aneeshd16** [comment]
@daleharvey thanks, which version of Chrome has the fix for this?

**Comment by tomaszn** [comment]
Chrome 64 and 65 were broken. Chrome 66 is fine.

**Comment by vikaskumar2299** [comment]
@daleharvey I'm facing the same issue in Chrome 66 (Version 66.0.3359.170 (Official Build) (64-bit)). Is this a browser bug or is there a fix in PouchDB for this? I created DB like this: `var rcChatDb = new PouchDB("rc_chat_db", {revs_limit: 1});`

**Comment by alenl** [comment]
Is it possible this might in some cases also be caused by a PouchDb timeout when accessing IndexedDb?
 I've had this same error code ("IndexedDb went bad") happen a few times while debugging something else and was already worried that the db is actually damaged. It turns out it only happened when running with many breakpoints that would be triggered and I would be examining the call stacks - while some indexeddb reads/writes were pending - so I guess it looks to the code like those accesses are taking seconds or minutes even. If I removed the breakpoints, the problem would go away.
Would it be conceivable that this can be caused by reads/writes taking a long time in general?

**Comment by Avaq** [comment]
I'm facing the same issue on Chrome 68.0.3440.70 on iOS 11.2 with PouchDB 6.4.3: I get the error consistently on the very first attempt to pull changes from a remote. I can avoid the issue with a 100% success rate by opening an incognito window.

**Comment by georgemck** [comment]
With PouchDB 7.0.0:

Google Chrome Version 69.0.3497.100 (Official Build) (64-bit) (Windows)
- Does Not Work: (Chrome)
+Does Work: (Chrome in Incognito, Firefox 63.0b5 (64-bit), Microsoft Edge 42.17134.1.0)

**Comment by masiorama** [comment]
> Is it possible this might in some cases also be caused by a PouchDb timeout when accessing IndexedDb?
> I've had this same error code ("IndexedDb went bad") happen a few times while debugging something else and was already worried that the db is actually damaged. It turns out it only happened when running with many breakpoints that would be triggered and I would be examining the call stacks - while some indexeddb reads/writes were pending - so I guess it looks to the code like those accesses are taking seconds or minutes even. If I removed the breakpoints, the problem would go away.
> Would it be conceivable that this can be caused by reads/writes taking a long time in general?

@alenl I just experienced the same behavior: with client breakpoints on it gives the error you mentioned, while when disabled no errors at all.

**Comment by Jarzka** [comment]
I faced this bug with my Samsung Galaxy Tab S 10.5 LTE using Chrome 74 and PouchDB 7.0. Not only is the putAttachment operation very slow on my device (takes up to 40 seconds per image), but it also sometimes causes this problem when I try to put 4-8 10MB image files to my PouchDB database. Auto compact is turned on.

**Comment by daw415** [comment]
Soo from few days I have a similar problem.

In browser in chrome version 78.0.3904.108 I can see:

{status: 500, name: "indexed_db_went_bad", message: "unknown", error: true, reason: "DataError"}

And this problem is when I replicate from server document types attachement,example : 

{
  "_id": "attachemnt214",
  "_rev": "1-1b071ca0213bda5922ab8a8d34c02c94",
  "_attachments": {
    "att": {
      "content_type": "image/png",
      "revpos": 1,
      "digest": "md5-96ahm+XEqSo2PZ4r2XgnRA==",
      "length": 11114,
      "stub": true
    }
  }
}

The same problem is on android application but about one week ago this worked.

What's wrong,, it is a problem Chrome ?

**Comment by Jarzka** [comment]
Any news? This bug still happens occasionally.

**Comment by Jarzka** [comment]
Based on posts on Stack Overflow, the storage quota on Chrome has increased recently a lot: https://stackoverflow.com/questions/10988569/storage-limits-on-chrome-browser

In fact, after updating Chrome to the latest version, I haven't faced this issue since then. At least not yet.

**Comment by flashguru-git** [comment]
Why is this issue closed? This bug still happens.

**Comment by Jarzka** [comment]
I don't know. But since this has been unfixed for so long, we decided to give up with pouch and create our own solution. :/

**Comment by flashguru-git** [comment]
@Jarzka 
Would you please tell me about your own solution?

**Comment by Jarzka** [comment]
We are using pouchdb to temporarily save user's file attachments to the browsers permanent memory (indexeddb), so that if multiple big files are uploded to the server, the process can continue later even if the user closes the browser. This works most of the time, but the bug mentioned in this issue sometimes causes problems with the upload process.

Firstly, we considered removing pouchdb completely and using the indexeddb API directly instead. However, we decided that we don't actually need this permanent memory functionality anymore: the files can be uploaded to the server directly without saving them into indexeddb in between. So, technicially we are not replacing pouch, we are simply leaving it out.

However, some of my colleagues have used indexeddb directly by creating their own little high level helper functions on top of it to make it a bit easier to use. I believe it has not been too much hassle, so I would consider it.

**Comment by dheimoz** [comment]
Hello @Jarzka , thanks for sharing your thoughts and following up this issue. I have worked with attachments raging from 2 MB to 100 MB and honestly my experience hasn't been good. In case you are syncing with Couchdb or Cloudant, the whole attachment is sent to the server, and if you are updating the document fields and attachments the revisions will contain old data. For instance, if you attached two 3 MB files and then another 3 MB files, the final document will have 6 MB revisions included. 

The way I use Pouchdb regarding attachments is using Localforage for offline purposes and then upload the files to Cloudinary. In the document I only have the reference, never the document. This way I can sync without problems.

Also attaching or using large documents is discouraged by  Couchdb https://blog.couchdb.org/2020/02/26/the-road-to-couchdb-3-0-prepare-for-4-0/

Hope this helps.

**Comment by sureshvv** [comment]
This issue has started happening to me with Chrome 91. I am using pouchdb 7.0.0
