### ISSUE TITLE
Don't apply plugins to the global PouchDB reference

### ISSUE THREAD

**Issue by lukechilds** [pouchdb/pouchdb#7198]
Why are plugins applied to the global `PouchDB` reference? Shouldn't they be applied to individual instances.

With the current setup, it looks like if I'm using a third-party lib that also uses pouch and they use a plugin, my app is forced to also use that plugin.

Is that correct?

If so, is there any interest in changing this behaviour.

I think instead of:

```js
const PouchDB = require('pouchdb');
const pouchPlugin = require('pouchdb-plugin');

PouchDB.plugin(pouchPlugin);

// Uses pouchPlugin :)
const db = new PouchDB('plugin-db');

// Also uses pouchPlugin :(
const db = new PouchDB('no-plugin-db');
```

it should be:

```js
const PouchDB = require('pouchdb');
const pouchPlugin = require('pouchdb-plugin');

// Uses pouchPlugin :)
const db = new PouchDB('plugin-db');
db.plugin(pouchPlugin);

// Doesn't use pouchPlugin :)
const db = new PouchDB('no-plugin-db');
```

**Comment by daleharvey** [comment]
We apply plugins to the global because we want them to work on each database created without having to setup the plugin on every database, `db.query` is a plugin and we dont want users to have to setup map reduce on every database they create, similiarly on the server plugins are used to give behaviours to every database that users create

I dont think we want to break that, however can see the need for getting a clean pouchdb instance that isnt affected by plugins, it seems like we should use the `defaults` model for this where we return a constructor like

```
const PouchDB = require('pouchdb');
const pouchPlugin = require('pouchdb-plugin');

// Uses pouchPlugin :)
const MyPluginPouch = PouchDB.plugin(pouchPlugin);
const db = new MyPluginPouch('plugin-db');

// Doesn't use pouchPlugin :)
const db = new PouchDB('no-plugin-db');
```

**Comment by lukechilds** [comment]
>we dont want users to have to setup map reduce on every database they create

If users have a common set of plugins they use in multiple DBs throughout their app they could just wrap it in a function and export it as their own module:

```js
const createDB = name => {
  const db = new PouchDB(name);
  db.plugin(aPlugin);
  db.plugin(anotherPlugin);

  return db;
}

module.exports = createDB;
```

I personally like this approach, I think it's more explicit and clearer to see what's going on. But your solution of returning a new class reference with the plugin set also solves the problem just as well.

---

By the way, I don't have a specific use case where I need this, I just saw this in the docs and it struck me as odd. The main issue I see with the current behaviour is if you were depending on a third party lib that used pouch under the hood. It could potentially cause very nasty issues.

Imagine some logging lib is using pouch with their own custom plugin to intercept reads/writes and replicate everything to their remote logging system. Then I use my own pouch instance in my app code to store some sensitive data. All my sensitive data would be replicated to the logging platform in plain text.

That's not a particularly likely scenario, just an example. But the point is it probably shouldn't be possible for that to be possible.

---

Are you open to making this change then? Either per instance or like in your example above? It would obviously be a SemVer major breaking change. Although it should be fairly easy to update any existing apps.

**Comment by daleharvey** [comment]
> If users have a common set of plugins they use in multiple DBs throughout their app they could just wrap it in a function and export it as their own module

Again with map reduce or with server side usage, downstream libraries expect to be able to use the pouchdb constructor / standard api and not whatever convenience function we make up, we arent going to expose both `new PouchDB` and `createDBWithMapReduce` in core PouchDB, nor can we ever expect the api to be a security barrier. We also have consistency with `PouchDB.defaults` in my example.

I would be open to the change, it isnt hugely requested so I wouldnt want to have it complicated the code base too much, but if it turned out to be a relatively simple change would be happy to see it

**Comment by daleharvey** [comment]
Also would like to avoid major version changes, however we have a major release upcoming @ https://github.com/pouchdb/pouchdb/issues/6946, so if it was something you planned to work on give us a heads up and can make sure to try and get it within the same release

**Comment by lukechilds** [comment]
Unfortunately this isn't something I'm able to contribute at the moment, I'm in the middle of a very time sensitive project.

However when I've got more free time I'll happily check back here and see if you're still interested.

**Comment by jeffkhull** [comment]
Is anyone else still interested in this issue?

I would like to have multiple pouch databases, which will each represent a collection of objects validated via JSON schema.  To do this, I need to apply a different plugin to each database, like this:

```ts
dogDb.plugin(jsonSchemaValidator(DogSchema))
```

Instead of applying plugins at the global instance level.
