### ISSUE TITLE
A warning about PouchDB with IndexedDB in Cordova on devices with low disk space

### ISSUE THREAD

**Issue by cmaas** [pouchdb/pouchdb#7241]
This is not really an issue with PouchDB, but it affects people and I think it makes sense to write a small guide here:

I've been pretty happy with PouchDB so far. But for the last few days, I received significantly more complaints via email that data won't show up in my Cordova app. The problem seems to be that devices run out of disk space. I'm not sure what exactly triggered this wave of complaints, because it ran rather smoothly over the last 6 months. Maybe people took more photos (spring time, yay!) or some app or OS update took way more disk space than before.

Problems with IndexedDB on Android:

- Quite a few people still have devices with only 16GB
- **These devices are almost always full**
- Android / Chrome grant a quota for IndexedDB based on the *internal* free disk space (SD-cards apparently don't matter)
- The *granted quota* in Chrome can go down significantly, if there are only a few hundred MB of free space left on the device

Result:

- No data is loaded via PouchDB from IndexedDB, because of a `QuotaExceededError`.
- My app requires only 3-4MB, but even then it fails to load data, because the granted quote is merely a few KB (measured via `navigator.webkitTemporaryStorage.queryUsageAndQuota()`, see: https://developer.chrome.com/apps/offline_storage#query)

I suggest my users to free up some disk space. This helps, but unfortunately, disk space gets full rather quickly these days and the same problem comes back.

I'm considering moving the DB to SQLite. Performance seems to be okay in my case (few writes, only a big `allDocs` read when the app starts and then keeping everything in memory). The problem here is: If people don't have enough disk space, the original data can't be loaded from IndexedDB.

If you want to migrate users to SQLite, it might make sense to properly check if all data was loaded successfully before attempting a migration.

Edit: One more thing: The Pouch docs recommend to almost always use IndexedDB on Android, unless one wants to save large amounts of data and that there's no other downside. I feel like this recommendation is not entirely accurate, because the quota seems to be hard to predict and for whatever reasons can be only a few KB in scenarios with almost no free disk space.

**Comment by cmaas** [comment]
Sorry to hear that, but I'm glad I'm not the only one. So far, I haven't found anything *official* about a change to Chrome, but this is exactly what I suspect, too.

I noticed two more things:

* Most people must have more than 1 GB of free space on the internal storage to get a small share for IndexedDB. >1 GB of free storage almost always helps. Unfortunately, apps these days cache so much data that 1 GB becomes full rather quickly.
* Sometimes, it takes a few minutes after the storage was freed, until either the OS or Chrome grants more quota for IndexedDB after. So I receive emails like *doesn't work, even with 1 GB* but 3 minutes later *never mind, now it works*. I try to encourage people to open Android's Settings → Storage to "re-calculate" the free disk space. Not sure if this helps.

But for sure, the only real way forward for me is to push an update which uses SQLite, because the situation with IndexedDB seems to be quite unstable right now.

**Comment by riterrani** [comment]
@cmaas  Yeah our experience is exactly the same at the moment, and we are working in migrating to SQLite and alert the user that needs to free some space.

**Comment by pmenager** [comment]
I made a test of the same with the same dataset before and after updating Google Chrome.
After the update I get the `QuotaExceededError` error.

**Comment by cmaas** [comment]
Thanks for testing. Check this out: https://stackoverflow.com/questions/50019306/chrome-on-android-granted-quota-for-indexeddb-suddenly-almost-0

It's apparently a known bug in Chromium that was introduced recently.

But for PouchDB, the recommendation right now seems to be: don't use IndexedDB on Android. Too unreliable, because too many old devices with almost full internal storage

**Comment by masimplo** [comment]
The actual commit that made things worse in Chrome is this https://chromium.googlesource.com/chromium/src/+/1e5b5704d062321a0c6d000224573661029b4b19%5E%21/#F0 where they went for a hard limit instead of a percentage of total storage, which I guess made the rule quite a bit easier to hit on almost full devices. This was introduced in Chrome 66 but has been changed in Chrome 67 to use both strategies.
Here is the comment from the "reverted" code:
>  // The amount of the device's storage the browser attempts to
  // keep free. If there is less than this amount of storage free
  // on the device, Chrome will grant 0 quota to origins.
  //
  // Prior to M66, this was 10% of total storage instead of a fixed value on
  // all devices. Now the minimum of a fixed value (2GB) and 10% is used to
  // limit the reserve on devices with plenty of storage, but scale down for
  // devices with extremely limited storage.
  // *   1TB storage -- min(100GB,2GB) = 2GB
  // * 500GB storage -- min(50GB,2GB) = 2GB
  // *  64GB storage -- min(6GB,2GB) = 2GB
  // *  16GB storage -- min(1.6GB,2GB) = 1.6GB
  // *   8GB storage -- min(800MB,2GB) = 800MB

I too was about to migrate to SQLite in Android (we are already using it in iOS as we had prior issues with indexeddb there) but it feels like a step back and the migration of users with limited space would be a nightmare.

**Comment by cmaas** [comment]
> the migration of users with limited space would be a nightmare

It kind of is. Fortunately, I'm syncing PouchDB with a remote DB both ways. So swapping to SQLite merely required a relogin for people with low disk space (because the data from IndexedDB wasn't available in that case). For all others with enough space, I simply replicated from IndexedDB to SQLite as recommended in the PochDB docs.

**Comment by daleharvey** [comment]
Cheers for the guide, hopefully still helps people googling for the issue but not anything we can do about in pouchdb, hopefully the chrome 67 behaviour. is a bit more forgiving, closing out, cheers
