### ISSUE TITLE
regex with Insensitive

### ISSUE THREAD

**Issue by manikandan07081995** [pouchdb/pouchdb#7242]
Pouch DB find regex with insensitive not working.

**Comment by manikandan07081995** [comment]
"$regex": "(?i)eh.*" is working fine in CouchDB mango query. But not working in pouch DB selector.

**Comment by willholley** [comment]
PouchDB uses the RegExp object (see https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-selector-core/src/in-memory-filter.js#L163). Does the selector work if you use:

```
"$regex": /eh.*/i
```

instead?

**Comment by manikandan07081995** [comment]
@willholley  **"$regex": /eh.*/i**   not working for me

**Comment by manikandan07081995** [comment]
@nolanlawson  @willholley 
This is my requirement

 db.find({
 selector: {series: {$regex: RegExp('mario', "i")}}
});

 http://nolanlawson.github.io/pouchdb-find/  But Same think when to enter ionic project 
$regex:{} empty parsing happen. What can I do?

**Comment by daleharvey** [comment]
Hrm so this is a sucky situation, locally /mario/i works fine but CouchDB doesnt like that obviously since we just send a string, JavaScript doesnt support the case insensitive modifier `(?i)` so if you want a case insensitive search you need to give different values to a local / remote pouch.

I cant really think of any ways to fix this within pouch, it may be possible for couchdb to support some way to pass modifiers to the regex then we could support that in pouch but otherwise any ideas?

**Comment by dsebastien** [comment]
Hello.

If I understood correctly, when using $regex: new Regexp(...), it only works against Pouch locally and hen using $regex: '(?i)blabla' it only works against Couch; is that correct?

I'm kind of curious. Do you think it would make sense to improve PouchDB for it to know whether it is working locally or targeting a CouchDB instance so that it can handle the regexp correctly depending on the target?
