### ISSUE TITLE
since: 'now' makes async call, delaying 'now'

### ISSUE THREAD

**Issue by alex-r-bigelow** [pouchdb/pouchdb#7258]
### Issue
Running into an issue similar to #3283 (dupe issue was closed without a fix?).
`since: 'now'` doesn't fire `change` events for `.bulkDocs()`, but applying the workaround in #3283 does seem to work

It's possible this is a corner case, where `now` doesn't trigger events when documents haven't actually changed (see Reproduce below)... I'm still a PouchDB n00b, and maybe not firing for unchanged documents is desired behavior. However, in that case, I wouldn't expect the workaround to fire either (it does).

### Info
- Environment: browser
- Platform: Chrome
- Adapter: auto-selected... I think IndexedDB?
- Server: n/a

### Reproduce
This works in the console sandbox on PouchDB.com:
```
const db = new PouchDB('test');
db.bulkDocs([
  {_id: '1'},
  {_id: '2'}
]);
```
(refresh the page)
```
(async () => {
  const db = new PouchDB('test');
  db.changes({
    since: 'now',
    live: true
  }).on('change', () => {
    console.log('since:now fired');
  });
  db.changes({
    since: (await db.info()).update_seq - 1,
    live: true
  }).on('change', () => {
    console.log('since:workaround fired');
  });
  db.bulkDocs([
    {_id: '1'},
    {_id: '2'}
  ]);
})();
```
(you should only see a `since:workaround fired` on the console, without a `since:now fired`)

**Comment by daleharvey** [comment]
Few issues here:

```
  db.bulkDocs([
    {_id: '1'},
    {_id: '2'}
  ]);
```

If you run this twice the second time will fail, since you need to pass a revision to update existing documents, failed updates wont trigger change events

```since: (await db.info()).update_seq - 1,```

In CouchDB 1.X the seq numbers used to be integers, however 2.x onwards they are opaque pointers and while doing `-1` on them may work sometimes (in pouchdb) its warned against as it wont always do what you expect

The issue is that since: 'now' is doing an async call to `info()`, once it yields the event loop your `db.bulkDocs` happens, it manages to do its writes before `info()` returns, so when your changes listener starts it starts listening from after the `bulkDocs` (https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-core/src/changes.js#L163)

I think as mentioned in the bug, it should be a fairly simple fix, I believe the update_seq is cached in all the adapters so adapter.js should be able to access it synchronously and start the listener before letting any writes happen, happy to get a fix however not a particularly urgent bug since there is an easy workaround (also if you know you are going to write, do it before starting the changes listener)

Cheers

**Comment by daleharvey** [comment]
ok actually took a look at a patch for this and remembered / figured out its not something we can reasonably change. While we keep track of the `update_seq` for local adapters and could probably do this synchronously, we do not keep track of remote databases update_seq and so it requires an async call to the server to find the current update_seq, so have to close out, cheers
