### ISSUE TITLE
pouchdb not fetch views from remoteServer

### ISSUE THREAD

**Issue by nicobytes** [pouchdb/pouchdb#7264]
### Issue
I try pouchdb but I have problem with remote views:
https://imgur.com/7RDDzhh

No fetch remote views

### Info
- Environment: browser
- Platform: Chrome
- Adapter: IndexedDB
- Server: CouchDB

### Reproduce
Hello, I try pouchdb but I have problem with remote views, in my remote server there are views like this:

https://imgur.com/4ST9RK7

And my conexion is 

```
const remotePath = `url/remote`;
    const remoteDatabase = new PouchDB(remotePath);
    const syncHandler = localDB.sync(remoteDatabase, {
      live: true,
      retry: true
    });
syncHandler.on('active', () => {
      console.log('replication was resumed');
    });
```
Fetch all documents but the `_desing` documents there isn't.

**Comment by willholley** [comment]
@nicobytes can you see whether Pouch is fetching the _design documents by looking at the network activity in Chrome dev tools? I can't see why this wouldn't work, though I would generally recommend managing local indexes independently rather than syncing them; usually the query/index requirements for local clients are somewhat different to server-side applications, not to mention the constraints of the device.

**Comment by daleharvey** [comment]
Without any more information nothing to debug here
