### ISSUE TITLE
Replication: 1 request by deleted document

### ISSUE THREAD

**Issue by nicolas-albert** [pouchdb/pouchdb#7276]
### Issue
Is this normal that a replication of existing documents is done with few huge requests and of deleted documents with a request per document ?

If a database contains thousands of deleted documents, the replication is very long a use a lot of bandwidth.

Do I miss something ? Is there a tips or a setting to just apply deleted documents from **_changes** instead of request for them ?

Thx.

### Info
- Environment: browser/hybrid app
- Platform: Chrome/iOS/Android
- Adapter: default
- Server: CouchDB

### Reproduce
Here a simple sample with a CouchDB database : starts with 2000 deleted documents and ends with 100 documents. Use the Chrome network tools to see the flow of requests : http://jsbin.com/xekowenoti/edit?html,output

**Comment by willholley** [comment]
@nicolas-albert it depends what version of CouchDB you're syncing against. For CouchDB <=1.6, PouchDB can sometimes optimise fetches using `_all_docs` to retrieve multiple documents at once. That optimisation is only available for non-deleted documents with a single revision (since `_all_docs` does not contain deleted docs and cannot return multiple revisions per document in the case that there are conflicts). That is, for any document that is either deleted or has a `_rev` higher than `1-`, Pouch will fetch it with an individual request.

For CouchDB 1.7 and later, there is a new endpoint `_bulk_get` that PouchDB should be using to retrieve multiple documents during sync, so avoiding a request per document in all cases.

**Comment by nicolas-albert** [comment]
@willholley Thank you for your reply.
Indeed, with CouchDB 1.7.1 and 2.1.1, `_bulk_get` is well used!
We also use couchbase-lite 1.4.0 but it does not use `_bulk_get` and generates thousands of queries, however you can not do anything about it.
I close this ticket, PouchDB is really a great CouchDB client :)
