### ISSUE TITLE
replicating .from() working but .to() isn't

### ISSUE THREAD

**Issue by bgold0** [pouchdb/pouchdb#7280]
### Issue
I have a [stackoverflow post](https://stackoverflow.com/questions/50395179/pouchdb-and-react-native-not-replicating-to-but-from-is-working) but basically I am looking for guidance on what steps I can do to help figure out why my issue is occurring.

- I am able to do a `device_db.replicate.from(remote_db)` (using a filter) and it grabs all the changes from the remote database (cloudant) and edits documents that are on pouchdb on my device (iOS).
- If I create **new** documents on the device and then do a `device_db.replicate.to(remote_db)` (with **no** filter), the documents do not get replicated to the remote database. 

So my issue is: Why can't I get my documents out of the device to the cloudant database. I haven't seen anything out of the ordinary in the debug console but none of the created document ID's are showing up ANYWHERE in the console when doing these commands. 

Is there some sort of *cache* I can reset. I really want to solve this issue without having to press the reset button as deleting documents is a no-go for the application I am building.

Any help would be greatly appreciated.

### Info
- Environment: [pouchdb-react-native](https://github.com/stockulus/pouchdb-react-native)
- Platform: React-Native iOS
- Adapter: Not sure
- Server: Cloudant

**Comment by daleharvey** [comment]
So in stackoverflow Glynn had the right idea, if you post the full debug log it should be easier to figure out, and knowing the contents of `_local/checkpoint` would be very useful

**Comment by bgold0** [comment]
@daleharvey do you need to be able to see the entire objects? I'm not quite sure how to save the entire debug log as when I save it using chrome you get something like so (notice the `{...}`:

     browser.js:133 pouchdb:api c5768a5186d0fccc07cfb9a9867deadec +133ms revsDiff {radial_testing: Array(1), work_template: Array(1), t366e1638-09b4-431f-8a20-1884f240ef34: Array(1), t76989d31-e3eb-4c64-9adc-572683019650: Array(1), 556017ef687011a33ed01a3fb54f0ea1: Array(1), …}

Also, if you could provide details on getting the contents of `_local/checkpoint`, I'd be more then happy to provide it however I don't see any of that in the debug log.

**Comment by bgold0** [comment]
Any guidance @daleharvey from my previous comment that would help narrow down the issue? I really need to get this figured out

**Comment by bgold0** [comment]
So I'm really not sure why but the moment I changed 

    let device_db = new PouchDB(company_id, {auto_compaction: true});

to:

    let device_db = new PouchDB(company_id, {});

Things seem to be syncing. Does anyone know why this would be the case? @daleharvey

**Comment by daleharvey** [comment]
Honestly no idea at all, auto_compaction wont affect checkpointing, I dont know how to copy chromes consoles properly, as for the checkpoint, during replication we write checkpoints which tells the replicator where to pick up from you will see these in the log as references to `PUT _local/aslkdja;lfjs;dlfkjs`, the contents of that document will tell you where the replicator things its last succesful write went.

However this is fairly certainly a bug in pouchdb-react-native and this repo is only for core pouchdb bugs, so best to file over there, please reopen if you find that there is anything needing fixed in core pouchdb

**Comment by martinhbramwell** [comment]
I spent  a half a day yesterday, and an entire day today trying to understand what I was doing wrong with `sync`.

I have a toy database that I was dropping and rebuilding repeatedly with commands like

    curl -X DELETE ${COUCH_URL}/${COUCH_DATABASE};
    curl -X PUT ${COUCH_URL}/${COUCH_DATABASE};

Nothing I did would get client to server replication to work, until @bgold0 's hint `{auto_compaction: true}`.

I built a new database with a new name, instead of replacing the old one, and everything began working just fine.
