### ISSUE TITLE
Change direction always "push"

### ISSUE THREAD

**Issue by amazingmarvin** [pouchdb/pouchdb#7296]
### Issue

I am debugging sync issues that my customers are experiencing.  I am using the following code to sync with cloudant and feed the changes to my application state:

```
currentDB.sync(currentRemoteDB, {
  live: true,
  retry: true,
  batch_size: batchSize,
  filter: makeFilter(),
}).on("change", ({ direction, change }) => {
  if (direction === "pull") {
    processChanges(change);
  }
});
```

I have noticed that syncing seems to work (i.e. I get a "change" event) but the changes are not fed to my application because the direction is "push" both when I make a change locally (expected) and when I make a change in another tab (unexpected)!

### Info
- Version: pouchdb 6.2.0
- Environment: browser (also sync problems on react-native)
- Platform: Opera Developer 55.0 macOS (also sync problems with electron and various platforms)
- Adapter: IndexedDB
- Server: Cloudant

### Reproduce
Issue can often be reproduced by starting a trial at app.amazingmarvin.com, opening in two tabs, adding a task in one tab, and watching in the other.  But unfortunately (fortunately?) the problem only happens sporadically.

**Comment by amazingmarvin** [comment]
My conclusion is that pouchdb probably just shouldn't be run from two browser tabs of the same browser and that this is likely unrelated to my customers' sync issues.

**Comment by daleharvey** [comment]
Sorry for the delay replying, was about to sign up for your app (looks nice) but stuff got in the way. So if you have 2 tabs running replication when you do a local write both of them will do a push write to the server. PouchDB should handle being in 2 tabs fine however you may want to see if you can only run the repication in one, nothing should break but you may start hitting connection limits if you have > 2 tab running replication

**Comment by amazingmarvin** [comment]
Hey @daleharvey, thanks for your reply and no worries.  My issue with two tabs is that I am using pouchdb as a store but keeping a copy of documents in my redux store.  Once a replication is complete I forward the documents to the redux store if it's a "pull" replication.  Since both of the tabs see it as a "push", documents aren't forwarded to the redux store (in the tab that didn't initiate the replication), so they don't show up in the app.

> (looks nice)

Thanks! If you end up trying it and liking it, let me know. Happy to give a free account to any pouchdb developers.

**Comment by garrensmith** [comment]
@amazingmarvin nice app. I signed up. It looks really useful 👍 

For your replication issue. You going to have to add some logic into your sync. I think the first idea to try is that instead of only updating redux based on a push, you need to keep track of the seq number passed in the changes feed, and if it is great than a previously processed seq value it means you have not processed that change and now you can process it.

Otherwise, you need to use localstorage or a session cookie to track replications and if there is already a replication happening then you don't need to do the remote replication but just listen to the local db's changes feed. Using localstorage could be quite tricky because if the browser crashes or for some reason you don't reset localstorage you might not start a new replication sync even if there is no current sync.

**Comment by amazingmarvin** [comment]
Thanks @garrensmith!  Yes, I think that would probably be the proper solution to this issue.  But I don't think that a lot of users are using Marvin from two tabs of the same browser, so I'm not too worried about it for now :).
