### ISSUE TITLE
Optimizing network traffic on Sync using batch_size / batch_limit doesn't seem to be working

### ISSUE THREAD

**Issue by tudordumitriu** [pouchdb/pouchdb#7329]
### Issue
We have a PouchDB synced with a CouchDB (both latest stable versions), on web and mobile (cordova wrapped) by doing a
`db.sync(remoteDbUrl, {
                live: true,
                retry: true,
                batch_size: 200,
                batches_limit: 1,
            })`
On a specific action we are updating / creating 3 docs, and for EACH of them we see being performed on the network layer a:
 _revs_diff, _bulk_docs, 4 x _local (2 are CORS but sill), an one _changes call,
So for a simple operation there are **7 server calls** (so 21 for this action) which seems like a LOT since the docs are quite small.
What worries me even more is that at some point we need to update a list of documents which if it's going to be multiplied by 7 and I don't even want to imagine the performance impact especially on mobile devices.
I really hope that we're doing something wrong here, but I've read everything I could find.
Also we're awaiting these calls but I really don't understand how should that affect since sync is done independently (I would believe).

### Info
- Environment: Web and Cordova hybrid app
- Platform: Chrome
- Adapter: IndexedDB
- Server: CouchDB

**Comment by daleharvey** [comment]
So most of these requests are amortized across the amount of documents that are changed, 7 calls per change doesnt always means 21 requests for 3 changes (depending on the timing of those changes)

I remember there was some server problem that prevented us from writing local docs along with a batch, not sure if thats something we could reintroduce as it would remove a lot of our replication traffic

**Comment by daleharvey** [comment]
How are you going these changes? are they individual writes or a single bulkdocs update?

**Comment by tudordumitriu** [comment]
Thanks @daleharvey 
So in any of the tests I haven't seen less the 21 for these 3 docs but what you're saying it makes sense, just don't know how to trigger that optimiziation.
We are doing individual writes to answer your last question.

Now, any suggestions that will reduce the network traffic are more then welcomed.

**Comment by tudordumitriu** [comment]
To simplify the question, if let's say the _local call cannot be optimized, maybe we can force saving all docs at once by doing a _bulk_docs which should automatically force only one _local call?

**Comment by daleharvey** [comment]
So instead of doing individual writes, if you do a bulk_docs then we are more likely to do the write in a batch (in reality we always do the first write immediately then the subsequent writes in a batch if they are written in time). If you turn off live replication and start the replication once the writes are finished we are also more likely to batch

and lastly its possible to reduce the amount of checkpointing, if you dont need to handle the situation where you delete your server database and try to resync from it, you can use `checkpoint: source` in your replications that will stop writing checkpoints to the server (https://pouchdb.com/api.html#replication). Sadly thats not currently a supported option with `sync` so you can either use 2 `replicate`'s manually, or write a patch to support it with `sync`

**Comment by daleharvey** [comment]
> or write a patch to support it with sync

And just to mentioned, we would very much welcome that, also pointed out that https://github.com/pouchdb/pouchdb/issues/7094 you should be able to pass through the opts

**Comment by daleharvey** [comment]
And closing out, as more a question than a specific bug to track
