### ISSUE TITLE
Recovering data from Pouchdb

### ISSUE THREAD

**Issue by gillestasse** [pouchdb/pouchdb#7415]
### Issue

I have created an application using Ionic and Pouchdb. So far it has worked very well with hundred of thousands of records synchronized. The application is used by farmers to register birth of animals. Now, one user, on an older device had a crash while offline. The application can not be started and I cannot get my hand on the device. The user managed to send me the application folder, so I have the .ldb files for the application.

What I am trying to achieve is to recover his data from those binary files.

I have tried with node / level in order to read the files and it does not work.

`
OpenError: Invalid argument: idb_cmp1 does not match existing comparator : leveldb.BytewiseComparator
`

I have also tried with clients (FastNoSql) with no success (database corrupted)

I am a little bit out of ideas. Garren Smith suggested me in irc to file a issue to get help (tried on StackOverflow with sucess)

### Info
- Environment: hybrid app
- Platform: Chrome/Android
- Adapter: IndexedDB
- Server: CouchDB
- PouchDB : 6.4.3

I hope i am precise enough.

**Comment by daleharvey** [comment]
This is lower level than I have been, ping @ralphtheninja in case you have any ideas, otherwise taking a guess that ionic uses chromium under the hood? so if privacy isnt an issue I would file a bug on chromium with the files attached as I am sure they would want to prevent any files from being corrupted and may be able to help you recover them, closing since not a pouch issue, but feel free to carry on discussing in here
