### ISSUE TITLE
Electron renderer process use leveldb for adapter

### ISSUE THREAD

**Issue by worudso** [pouchdb/pouchdb#7449]
### Issue
Is this the intended behaviour? I expected main process to use leveldb and renderer process to use indexeddb. And I don't understand even how it its possible. Because, renderer process is just a chrome. Is there something I don't know that makes it work?

### Info
- Environment: (Node.js/browser/hybrid app/etc.)
Electron
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
Electron
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
LevelDB
- Server: (CouchDB/Cloudant/Couchbase/PouchDB Server/etc.)
CouchDB

### Reproduce
```typescript
const db = new PouchDB("test");
console.log(db.adapter);
```
both in main process and renderer process, it prints `leveldb`.

**Comment by karlwestin** [comment]
This is tricky, and it would be really helpful with more info.

It seems to me there's a high change this is related to your build setup, depending on whether your your build picks up the 'browser' or the 'main' field from the package.json file (https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb/package.json)

Could you provide a small repository with your build setup and the code above so some of our contributors with electron experience can weigh in?

**Comment by worudso** [comment]
https://github.com/ownerclan/electron-pouch
Here it is. I suspect `install-app-deps` has something to do with it.

And which one is better in performance, leveldb or indexeddb?

**Comment by W1M0R** [comment]
@karlwestin It looks like Electron's `process` object does not have a `process.browser` property, but `process.type` instead. The problem manifests itself in other areas, such as when retrieving attachments from `express-pouchdb` using `pouchdb-browser`. 

For example, the following error occurs in `pouchdb-browser` index.js: `TypeError: response.buffer is not a function`. Upon further inspection, the `index.js` does a check for the value of `process.browser`, which in Electron's case is `undefined`, and thus the result of `response.buffer()` (a NodeJS concept) is returned, instead of the expected `response.blob()` (a browser concept). If I use `pouchdb-browser`'s `putAttachment` with `Blob` types, then I expect its `getAttachment` to resolve `response.blob()`. Hope all this makes sense. Looking at the source code will help.

**Comment by tom-james-watson** [comment]
I managed to solve this by using `pouchdb-browser` in the renderer instead of `pouchdb`
