### ISSUE TITLE
pouchDb + MongoDB

### ISSUE THREAD

**Issue by GlauberF** [pouchdb/pouchdb#7466]
Hello,
Today I have in the backend an application with mongoDB and I'm building my frontend in PWA, how can I use the frontend in the pouchDb with synchronization, for my MongoDb backend database?

ps: MongoDb works with collection, as I would have to handle this in frontend

**Comment by garrensmith** [comment]
PouchDB won’t sync with Mongodb. You need to run CouchDB on the backend.

________________________________

**Comment by GlauberF** [comment]
@garrensmith perfect, and how would I do it through the couchDB to synchronize with my database?

Any article for reading?

**Comment by karlwestin** [comment]
Ok this is tricky and exactly how the final solution looks is extremely tied to the rest of your app, but in general:

- you wanna listen to the [changes feed](http://docs.couchdb.org/en/stable/api/database/changes.html) on the couchdb
- there are 2 ways to do this: 
1. read at a for example 5 minute interval, and store the last_seq that you read somewhere. Then on next read you need to start from the last checkpoint you read.
2. read via a live changes feed. if you do this, you need to prepare for what happens if you need to read changes from the start. That means, you have to have a way to make sure you don't write everything to your MongoDB once again (so you dont get duplicate data)

- On every change you need to decide what to do with it. Can you look up if something is already written? do you need to update it or do you need to write something new?

- From experience, it's helpful to design this in a way that you can re-run the import and get the same results from the same data. If you have a production system with MongoDB data and you run the import from sequence number 0 again, what happens then?

I'm gonna mark this as a question and close it. I'm sorry it's hard to provide more info, but this is very very application specific and not really something for this issue tracker.

Good luck, and prepare to be patient with this :)
