### ISSUE TITLE
Mixed sorting does not work

### ISSUE THREAD

**Issue by madeken** [pouchdb/pouchdb#7549]
Using pouchdb `7.0.0`, sorting with:

`sort: [ {'colA': 'asc'} , { 'colB': 'desc' } ]`
or
`sort: [ {'colA': 'desc'} , { 'colB': 'asc' } ]`

will have the sort order of `colB` ignored in favor of the sort order of `colA`, which leads to incorrect results.

**Comment by duytq94** [comment]
@madeken 
First, did you make sure that you indexed both `colA` and `colB`?
Second, you have to indexed your db follow your order sort, eg: you sort is check `colA` then `colB`, so you have to index `colA` before `colB`.
![image](https://user-images.githubusercontent.com/24253421/58303646-40ecfa80-7e1b-11e9-892f-9970adf33063.png)

And if your `colA` is diffrent in every item, then colB won't useful because sort at colB just happen when more than 2 items have `colA` the same values. Eg: your `colA` is `created_at` and you sort your items by colA, at that time colB won't be cared.

**Comment by duytq94** [comment]
Also recheck your `selector`, maybe you stuck in this case https://pouchdb.com/guides/mango-queries.html#more-than-one-field
