### ISSUE TITLE
Implement partitions

### ISSUE THREAD

**Issue by garrensmith** [pouchdb/pouchdb#7566]
### Issue
We currently working on new functionality in CouchDB called partitions (https://github.com/apache/couchdb/pull/1789)

We would need to implement some basic support for this in PouchDB. Initially just supporting it for HTTP calls will be fine. There won't be huge benefit for implementing it locally, but I think if we want to stay consistent with CouchDB we will have to look at doing this for local storage as well. We might be able to get some nice performance benefits so its definitely worth thinking about.

### Info
- Environment: (Node.js/browser/hybrid app/etc.)
- Platform: (Chrome/FF/Safari/Edge/iOS/Android/etc.)
- Adapter: (IndexedDB/WebSQL/LevelDB/etc.)
- Server: (CouchDB/Cloudant/PouchDB Server/etc.)

**Comment by garrensmith** [comment]
I would like to take a stab at this in the new year.

**Comment by daleharvey** [comment]
So similiar to https://github.com/pouchdb/pouchdb/pull/7472. I have reservations about implementing these features in pouchdb core given that they are little to no use in pouchdb itself, every feature has maintenance, code size, complexity costs in the code base and keeping those to a minimum is always best.

We split off the core couchdb api that didnt make since in pouchdb as a set of plugins (rewrite, list, views etc) and I think doing the same with the cluster specific features may be the way to go

**Comment by garrensmith** [comment]
Yes that makes sense. I'm happy to do that.
