### ISSUE TITLE
fetch-cookie 0.7.2 needed

### ISSUE THREAD

**Issue by jlami** [pouchdb/pouchdb#7725]
https://github.com/pouchdb/pouchdb/pull/7397

This version is needed to fix a cookie problem when using pouchdb on node. 
https://github.com/valeriangalliat/fetch-cookie/issues/17

There is a test in `tests/component/test-ajax.js` that tries to catch this, but those fetch calls do not include a custom header, so it will not trigger this scenario. I could alter test-ajax to include the custom header that is needed to trip this bug if you like?

**Comment by daleharvey** [comment]
@jlami That would be great, if there is value in testing both code path can copy and paste, otherwise adding the header and getting it to trigger the failure would be great, then we can verify the fix

**Comment by leonid-shevtsov** [comment]
FWIW I'm testing [my PR to make pouchdb-authentication compatible with PouchDB 7](https://github.com/pouchdb-community/pouchdb-authentication/pull/254), and I'm hitting a different [issue](https://github.com/valeriangalliat/fetch-cookie/issues/23) with fetch-cookie: an `Error: Cookie failed to parse` - it should also be resolved with the update to version 0.7.2.

**Comment by cochlear-atlas** [comment]
This is a blocker for us, and anybody else trying to use `pouchdb-http` to hit an endpoint that returns cookies containing commas (due to https://github.com/valeriangalliat/fetch-cookie/issues/22).

Note that this impacts, for example, anybody hitting an endpoint behind an AWS ALB (so not a rare edge case!)

It seems that the issue could be resolved by simply relaxing the `pouchdb-fetch` dependency from `"fetch-cookie": "0.7.0"` to "fetch-cookie": "^0.7.0" (is there any reason why the explicit version `0.7.0` is declared?

Any thoughts on when this could be rolled into a PouchDB release, or suggestions on a work around?

Cheers.

**Comment by stemail23** [comment]
This is a blocker for us, and anybody else trying to use `pouchdb-http` to hit an endpoint that returns cookies containing commas (due to valeriangalliat/fetch-cookie#22).

Note that this impacts, for example, anybody hitting an endpoint behind an AWS ALB (so not a rare edge case!)

It seems that the issue could be resolved by simply relaxing the `pouchdb-fetch` dependency from `"fetch-cookie": "0.7.0"` to `"fetch-cookie": "^0.7.0"` (is there any reason why the explicit version 0.7.0 is declared?

Any thoughts on when this could be rolled into a PouchDB release, or suggestions on a work around?

Cheers.

**Comment by jlami** [comment]
Sorry I haven't found the time to add the test, but is a new release with #7827 on the horizon to fix this?
