### ISSUE TITLE
Creating secondary index taking too long on hybrid application

### ISSUE THREAD

**Issue by Romyeo** [pouchdb/pouchdb#7783]
### Issue
Currently we have ~150k (could be more) documents we are syncing in client pouchdb. Then we create a secondary index so we could easily get a specific document with "type" as a key. It works great on desktop browsers and android, but it seems to be hanging on iOS (taking too long, took around 24 hrs and still loading). First we loaded it into web worker thinking there might be some performance boost. Well it didn't turned out that way. 

Is there a way to make this faster? I'm not actually asking for a fix, more of a guide or better way to do this? Or a better route in searching and creating indexes of large amount of documents

### Info
- Environment: hybrid app/ios-webview
- Platform: iOS/webview
- Adapter: PouchDB
- Server: CouchDB

**Comment by garrensmith** [comment]
Ideally you don't want to have over 150k docs in PouchDB. Are you using indexeddb?
Also it should be better to use _all_docs rather than creating secondary indexes. Try using pouchdb-find without indexes versus indexes. Finally when we eventually get the newer indexeddb adapter out it should help a little
