### ISSUE TITLE
TS2305: Module '"url"' has no exported member 'URLSearchParams'

### ISSUE THREAD

**Issue by keophilavanh** [pouchdb/pouchdb#7814]
### Issue
I am using angular-cli 6.9.0, with node 10.16.0, and I am using a template https://github.com/akveo/nebular
every thing seems working fine, then after I install pouch db , it fires many errors and trying to fix it , and this error , I am not sure if it's bug or something else , how to fix and use this pouchdb in my project thank you 
ERROR in node_modules/@types/node-fetch/index.d.ts(16,10): error TS2305: Module '"url"' has no exported member 'URLSearchParams'

### Info
ERROR in node_modules/@types/node-fetch/index.d.ts(16,10): error TS2305: Module '"url"' has no exported member 'URLSearchParams'

**Comment by karlwestin** [comment]
Hi!
Sorry you're having this issue, it must be really annoying!

That being said, when you file an issue like this
- please don't assume we know angular cli/your specific template. We get a lot of angular/ionic/cordova issues, and it's really hard to work with when we're not getting more than a link to a repo that has huge amounts of dependencies and things on your own
- rather, set up a repo that can be cloned, npm install and shows the error. I know this is more work for you but it's even more work for us to try and guess your setup.

Unfortunately, there's a small chance anyone here can help you, because it sounds like this issue is in the build system, and also, when you read carefully, you see that the referenced module is `node-fetch`  

Here's some ideas to help you move on
- try to include node-fetch separately in your project => is it still causing problems?
- try to use [PouchDB-Browser](https://www.npmjs.com/package/pouchdb-browser) instead of pouchdb, which skips the node dependencies

**Comment by keophilavanh** [comment]
we have comment this 
//import { URLSearchParams, URL } from "url";
in index.d.ts

we use this 
import pouchdb from 'pouchdb';

in component

and 
this.db = new pouchdb('user');

then 

this.db.put({ test: 'ok', _id: id+'' },{force:true}, (err, res) => {
      if (err) {
        console.log('err after put'
        );
        
        console.log(err);

      } else {
        console.log('after put');
        
        console.log(res);
        

        this.db.allDocs({ include_docs: true, descending: true }).then(res => {
          console.log("show all docs");
          
          console.log(res);

        }).catch(err => {
          console.log("error show all docs");
          console.log(err);

        });
      }
    });

seems it's working 

any way, seems most of tutorials guideline they were unclear, and many bugs , let see how far can I go with pouchdb

**Comment by keophilavanh** [comment]
note: 
when I use
import pouchdb from 'pouchdb';

in visual code would show error 
This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

so I just build it and ignore this problem , and It could work normally
