### ISSUE TITLE
Content Security Policy fails without unsafe-eval

### ISSUE THREAD

**Issue by jamesmfriedman** [pouchdb/pouchdb#7853]
This is from the most recent version of Pouch 7.1.1

The short of it
- One of the best things you can do for your web apps security is turn off unsafe-eval using the Content-Security-Policy header
- index-browser.es.js has a scopeEval function that violates this policy
- Looked through the code, not 100% sure what its doing but it definitely seems required.
- Is there a different approach that could be taken which would make access to this more secure? Otherwise I'm required to open a large security vector in order to use pouchdb in my app :/

![image](https://user-images.githubusercontent.com/975256/61957944-64086780-af8e-11e9-91d3-7b2818c275d2.png)

**Comment by jamesmfriedman** [comment]
Any thoughts on this from one of the maintainers / creators?

**Comment by SCdF** [comment]
So PouchDB requires the ability to execute arbitrary, user-created JavaScript, because that's how various features of CouchDB (which PouchDB emulates) works, such as [mapreduce](https://docs.couchdb.org/en/stable/ddocs/views/intro.html).

I haven't looked into it, but you may be able to use the use the more specific npm packages to pull in just the bits of PouchDB that you want, that _might_ avoid these. It's likely that PouchDB hasn't been optimised for this and they could get pulled in anyway, but if that's the case and they aren't really needed it would be a bug to be fixed!

**Comment by SCdF** [comment]
To expand on my comment above, I mean instead of doing:

```
const PouchDB = require('pouchdb');
```

You would be more selective, and do something like:

```
const PouchDB = require('pouchdb-core')
  .plugin(require('pouchdb-adapter-idb')) // for local browser storage
  .plugin(require('pouchdb-adapter-http')) // for interacting with remote CouchDB
//.plugin(require('pouchdb-mapreduce')) // not this one, it definitely needs eval!
  .plugin(require('pouchdb-replication')); // to allow for replicating between them, though this may need eval

```

**Comment by jamesmfriedman** [comment]
Oh don't get me wrong, I know eval has to be done for this to work, just wondering if theres a way to do it so it doesn't trigger the unsafe-eval CSP policy.

**Comment by SCdF** [comment]
Ah. I am not massively familiar with how the CSP works unfortunately, so I can't help you there :-(

**Comment by githorse** [comment]
I'm running into this same CSP problem with [Alasql](https://github.com/AlaSQL/alasql/issues/1482). My security team, understandably, will not let me deploy to production with `unsafe-eval` in the CSP. 

Question for the community: are you using PouchDB in a production app? Are there ways of passing security audits (e.g. SOC) with `unsafe-eval` in the CSP? How do you manage this problem?
