### ISSUE TITLE
pouchdb tries to sync indefinitely when there is no internet connectivity

### ISSUE THREAD

**Issue by iconicsammy** [pouchdb/pouchdb#7931]
### Issue
My setup is simple where data is downloaded/synced down from couchbase down to pouchdb (there is no upload sync from pouchdb to the server). As data is downloaded, I have a spinning icon that disappears when there is no more data sync.

But now, if there is no internet, it spins forever. I want it to try for say 2 minute and stop.
### Info
- Environment: Browser
- Platform: Chrome
- Adapter: IndexDB
- Server: CouchDB

### Reproduce
```
pdf.replicate
      .from(remoteURL, { live: true, retry: true })
```

then disconnect from the internet.

**Comment by knubie** [comment]
@iconicsammy You may need to write your own `back_off_function`.
See: https://pouchdb.com/api.html#customizing-retry-replication

**Comment by daleharvey** [comment]
Yup, we provide some fairly high level customisation to how back off works, but if you have specific requirements then you can manage the starting and stopping of replication yourself.

**Comment by boaz-lachman** [comment]
Hi,
for me this issue appears when there is a very slow network. not offline, but a very slow network so the request doesn't fail. Can a backoff function also address this issue. This issue appeared ever since 7.0.0 , when there was a transition to "fetch" and now there is no ETIMEOUT to indicate that there was a slow network
