### ISSUE TITLE
PouchDB in node.js 10x slower than in browser - is this expected?

### ISSUE THREAD

**Issue by lacker** [pouchdb/pouchdb#7951]
It seems like a section on Node db adapters has been removed from the documentation - the https://pouchdb.com/adapters.html#pouchdb_in_node_js link is broken on that page.

I'm trying to get a JS library running in both the browser and in node. I have a small database of about 100 items, and a simple `db.find({selector: {})` takes about 0.13 seconds in the browser, but 1.5 seconds in Node. I'm just using all the default configuration, so the leveldb adapter in node.

I'm not sure how to debug this further - it's definitely slower than I would expect such a query to be, compared to other databases. But I also just don't know if pouchdb's node support is just expected to be this slow. Is it?

If there are practical tips for speeding up pouchdb in node, like using a different adapter, I would love to hear them.

**Comment by detroitenglish** [comment]
The best way to use PouchDB server side is to... not, because that's CouchDB's job 😅 

But I doubt that's helpful... so I'd start by asking whether you really need `pouchdb-find` at all for 100 documents. If you can use a structured `_id` format (e.g. `type:category:subcategory:title:id`) for docsuments, then bulk fetching with specific 'startkey' and `endkey` is the way to go. Lot of good tips on that  here: https://pouchdb.com/2014/05/01/secondary-indexes-have-landed-in-pouchdb.html

If you do need `find`, know that poor index definitions are the usual source of query performance issues: https://developer.ibm.com/articles/ba-optimize-queries-cloudant/

Avoid querying for data within arrays. Avoid `$regex` like the plague. And if you're not querying `_id`, always add `{ "_id": { "$gt": null } }` to the selector. Details on why here: https://developer.ibm.com/dwblog/2015/mango-json-vs-text-indexes/ 

A final nuclear option for only 100 docs could be two PouchDB instances in continuous 2-way replication, one using leveldb and the other using `pouchdb-adapter-memory`. Read/Write from the in-memory pouch and let the other async write to disk via `sync`. Wise? No. Fast? You betcha.

It's possible to squeeze performance out of PouchDB on Node, but never more than you'll gain in the 30 seconds it takes to fire up a CouchDB container.

**Comment by lacker** [comment]
Maybe I'm missing something. I thought it couldn't be a problem with poor indexing or complex queries because it's just doing a simple linear scan over 100 documents, and the whole database is 100 documents. Why would 'find' be that slow, is it doing a disk access for every document?

My use case here is a library that is intended to work both in the browser and in a CLI, so requiring CouchDB isn't a great solution. In the past I have used SQLite for similar applications, but that doesn't seem applicable in a browser environment.

**Comment by detroitenglish** [comment]
Can you show a few example documents and the query selector you're using?

**Comment by lacker** [comment]
The selector is just `{}`. A single document looks like:

```
{
  "author": "lacker",
  "board": "0x1ef2419473010e607f9b53edabda7452b240aca5ccb4f20573c7d0ccd26db90f6c62:censorship",
  "summary": "Hard to believe. The laws for Chinese companies are much stricter at requiring them to obey government mandates.",
  "title": "TikTok CEO claims he would defy Xi Jinping",
  "url": "https://www.scmp.com/tech/start-ups/article/3038343/tiktok-distances-itself-china-amid-pressure-us-while-branching-out"
}
```

**Comment by detroitenglish** [comment]
> The selector is just {}.

So you're using `find` just to batch fetch all documents? If so, it's the wrong tool for the job.

That's a job for [`allDocs`](https://pouchdb.com/api.html#batch_fetch):
```javascript
const { rows } = await db.allDocs({ include_docs: true })
const docs = rows.map(({ doc }) => doc)
```

**Comment by lacker** [comment]
Well, I was just trying to find a minimal reproducible example of unacceptable performance. I get that if this were the only query I were running, it would be better to use `allDocs`. Shouldn't this be faster than 1.5 seconds for 100 documents?

**Comment by detroitenglish** [comment]
If benchmarking software built for handling 10K docs with 100, which is intended for the browser but running on a server, by wildcard-querying a plugin designed to scan predefined indexes with structured selectors —  _unacceptable performance_ seems a rather bald assertion.

**Comment by lacker** [comment]
Okay, I don't really want to have a stance on whether it is acceptable performance or not, I just want to know if I am doing something wrong in my test setup. The core question here is, is this the speed you would expect from PouchDB's leveldb+node implementation?

**Comment by lacker** [comment]
I found the problem here, the problem was specific to this disk. In case anyone runs into this thread in the future, this is indeed unacceptable performance, and a correctly configured PouchDB in Node with the leveldb adapter should perform a lot better than 100 docs in 1.5 seconds. More like 0.13s

**Comment by yoonghm** [comment]
I guess browser cached the data inside the memory but node needed to read from disk for every iteration. Leveldb cached key-value pairs in the memory.
