### ISSUE TITLE
Ionic 3 LocalHost and local IPs work but not remote IPs

### ISSUE THREAD

**Issue by blakefox** [pouchdb/pouchdb#7965]
Hello all and thank you for you your time. I am sure this is a simple error on my part so I apologize in advance. In my case, I have a CouchDB server on a machine on my network with CORS enabled, chttpd set to 0.0.0.0 and port 5984 opened on the firewall. On the same machine, I can run an ionic web app on localhost with PouchDB and syncing works as expected. On a different machine but on the same network, the same application syncs as expected. When I move to a machine off-network and try to sync via the web IP, syncing fails. 

### Info

- Environment: CouchDB - NodeJS
- Platform: Ionic 3 - PouchDB
- Adapter: None
- Server: Windows Server 2016

### Reproduce

1) Installed CouchDB onto Server 2016 Machine
2) Added DB with sample Data
3) Set chttpd ip to 0.0.0.0
4) Exposed port 5984 in windows firewall
5) Created Ionic 3 template app
6) Added PouchDB and sample sync logic to the ionic application
7) Tested webapp on same machine as couch with local host ( Works as expected )
8) Tested webapp on differnet machine ( name network ) with network up ( Works as expected )
9) Tested webapp on different maching ( off network ) with internet ip ( Failed to sync ) ( net::ERR_CONNECTION_REFUSED ) 
10) Tested as android app off network ( Failed to Sync ) ( Failed to sync, ( net::ERR_CONNECTION_REFUSED ) 

Expected Result: Able to sync PouchDB and CouchDB via the internet ( off the isolated network ) securely.

Thanks in advance for your help. If any other information is needed, let me know.

**Comment by jffernandez** [comment]
Make sure you can access the http endpoint of your CouchDB from internet. Test it with your browser, you should have same result that if you open http://localhost:5984 from the same machine where you installed CouchDB (point 7 of your scenario), you should get a response like:

`{"couchdb":"Welcome","version":"2.1.0","features":["scheduler"],"vendor":{"name":"The Apache Software Foundation"}}`

If you don't get that, you need to correctly route the internet petitions to your CouchDB machine. (You don't described that on your setup, so, maybe the problem is there)

**Comment by blakefox** [comment]
Hello jffernandez,

Thank you for the quick reply. We had the routes set up but thanks to you comment, when double checking, we realized that our hardware firewall was configured incorrectly. We are now able to sync via a remote IP, thank you for that.

Closing as all is working as expected not. Thank you again for your time!
