### ISSUE TITLE
Can pouch db sync with Couchdb 2.3 ? if yes, how do pouch db calculate the update_seq ?

### ISSUE THREAD

**Issue by anuragvohraec** [pouchdb/pouchdb#7977]
### Issue
Can Pouch db sync with couchdb 2.3 ? 
if yes, how do pouch db calculate the update_seq ?

I have been writing a couchdb implementation in dart language, in my pursuit I am able to replicate from my local database [implemented in dart] to remote [couchdb 2.3], but the replication from remote [source] to local [target] is not working as it gives me this error :
`{"error":"bad_request","reason":"Malformed sequence supplied in 'since' parameter."}`

In my implementation I have used simple increment integer for update_seq.
I have read  few related links here on it:
https://github.com/pouchdb/pouchdb/issues/2089#issuecomment-46127917
https://github.com/pouchdb/npm-browser/issues/15

but I am not able to deduce if pouch db supports couchdb 2.3 and if yes how it creates the update sequence of this format :

`{"seq":"2-g1AAAAEheJzLYWBgYMlgTmGQT0lKzi9KdUhJMtXLSs1LLUst0kvOyS9NScwr0ctLLckBKmRKZEiy____f1YGUyJjLlCA3dwiNSnF3JRoA5IcgGRSPdgMZqgZpsamKWlJqYRNINqWPBYgydAApIAW7c9KZCBR5wGIzv9AnVkA4xxeAA","id":"3","changes":[{"rev":"1-40a32f4093d73c66bb6d6c147b31d136"}]},
`

**Comment by karlwestin** [comment]
Hi!
Yes PouchDB can sync with CouchDB 2.X. 
The anwswer to the question 'how is the update sequence calculated' is that PouchDB has its own system with simple integers, it does not try to do the integer + hash update sequence that couchdb does. 

Why does this work anyway?
Because when replicating, it's only the update sequence of the *source* that matters.
When i replicate A->B i tell A "give me all changes since update 2, limit 100". A will then tell me, 'here's 100 changes, next sequence number is 105' (there can be more jumps)". You write this as a checkpoint (maybe on B only, maybe on both instances), then you say again, "give me all changes since 105, limit 100". A says "here's 100 changes, next sequence is 240"

So the 2 instances can have different update sequences, it's the *source* sequence number that matters and as long as that one is being internally consistent, you can have a system based on letters or something else

Hope this helps!

**Comment by anuragvohraec** [comment]
> During replication, we compare source update_seq to checkpoint, and what's written in the checkpoint comes from the source, we _do not compare_ source update_seq to target update_seq.
> 
> So the 2 instances can have different update_seq systems, it's the _source_ sequence number that matters and as long as that one is being internally consistent, you can have a system based on letters or something else
> 
> Hope this helps!

Sounds reasonable. Thank you ! it does helps.

**Comment by bilalswiftsolutions** [comment]
Hi, I am also confused about the sequence number, for example, I want to give a sequence number in `since` which was 1 month ago, how i can find that sequence number ? 
for example, if I have a current sequence number 1000 and in `since` I give 800 it gives an error that it is Malformed

can please explain a bit on this?

**Comment by garethbowen** [comment]
@bilalswiftsolutions The sequence number isn't simple or predictable like that because it contains other information about the replication, ie: you need to include the entire string including the long string after the hyphen. This needs to match exactly a seq in the db so you can't just make it up. The only exception is the special values `now` and `0`.

To find a sequence from a month ago you will have to go through the changes feed and ignore all older docs until you find the first one you want to sync and then use that seq as the `since` value.

Alternatively you could do a reverse sync request with a limit so you sync the most recent docs, but there's no way to check the date with this approach.

**Comment by bilalswiftsolutions** [comment]
Thank you for replying.

In docs i never see sequence number. There is rev and id . Is rev is
sequence number?

In docs reverse sync is not mentioned . If you can give coding demo it will
be great help or if i have miss in the docs. This is also good solution i
think of but didn't find it

**Comment by garethbowen** [comment]
> Is rev is sequence number?

No, but it looks similar. PouchDB implements the CouchDB replication protocol so have a look at the CouchDB docs for examples, eg: https://docs.couchdb.org/en/stable/api/database/changes.html#changes

> In docs reverse sync is not mentioned

For reverse sync, use the [changes api](https://pouchdb.com/api.html#changes) and specify the `descending` option. That will give you the most recent IDs which you can then [batch fetch](https://pouchdb.com/api.html#batch_fetch).
