### ISSUE TITLE
Cookie parse error in Node for remote database only

### ISSUE THREAD

**Issue by natcohen** [pouchdb/pouchdb#7980]
### Issue
Setting up a remote database and adding a document in Node returns a cookie parse error

### Info
- Environment: Node 10.13.0
- Platform: PouchDB 7.1.1 running on Node
- Adapter: Default
- Server: CouchDB 2.3.1

### Reproduce

I use express but I guess any Node server can do the job. Simply create a remote DB and link it directly with PouchDB

    const db = new PouchDB(https://couchdbAddress.io/myDB, {auth: {username:'user', password:'pass'}});

    db.put({
        _id: 'myID',
        name: 'myName'
    }, (err, response) => {
        if (err) { return console.log(err); }
        console.log(response);
    });

I get the following error:

```
{ Error: Cookie failed to parse
    at CookieJar.setCookie (/Users/user/test/node_modules/tough-cookie/lib/cookie.js:1014:11)
    at /Users/user/test/node_modules/es6-denodeify/index.js:16:18
    at new Promise (<anonymous>)
    at /Users/user/test/node_modules/es6-denodeify/index.js:15:14
    at /Users/user/test/node_modules/fetch-cookie/index.js:37:18
    at Array.map (<anonymous>)
    at /Users/user/test/node_modules/fetch-cookie/index.js:36:36
    at process._tickCallback (internal/process/next_tick.js:68:7) docId: 'myID' }
```
PS I downgraded to PouchDB 6.4.3 and it works...

**Comment by AdrianoFerrari** [comment]
Similar issues here : PouchDB and auth cookies don't seem to work on Node (Electron).

If I use a **browser**, I can use axios\* to POST to `_session` and I can see that the cookie is set properly. From then on I can access the remote db as expected.

If I try the exact same code in an **electron app** (Node), I receive a "Set-Cookie" header in the response, but it isn't saved in the cookies.

I've tried all kinds of code mentioned in other issues, but after two days of non-stop searching, I'm not sure what to do!

This happens on PouchDB 7.1.1, and 6.4.3 for me.

\* I am using axios for sessions instead of `pouchdb-authenticate` because the latter doesn't seem to work with latest pouch :confused: .

**Comment by AdrianoFerrari** [comment]
Yes!

Fixed this issue by using fetch directly:

```
  var remoteOpts =
    { skip_setup: true
    , fetch(url, opts){
        return fetch(url, opts);
      }
    };
  var remoteDB = new PouchDB(dbUrl, remoteOpts);
```

**Comment by natcohen** [comment]
I tried your solution but I get this:

`TypeError: Cannot read property 'bind' of undefined`

**Comment by AdrianoFerrari** [comment]
I don't know for sure, but from what I remember of the code, `ourFetch` shouldn't be called, if the `fetch` option is passed properly. Can you make sure that you're passing it in correctly, and that your version of PouchDB supports it, maybe?

**Comment by natcohen** [comment]
Doesn't work for me... any help would be very helpful!

**Comment by natcohen** [comment]
Ok, I got it working by calling `fetch-cookie` like this:

```
const nodeFetch = require('node-fetch');
const fetch = require('fetch-cookie')(nodeFetch);
```

I will keep this issue open since it should work without this hacky fetch...

Thanks @AdrianoFerrari !

**Comment by natcohen** [comment]
Not yet...
