### ISSUE TITLE
Pre-7.0 comment in docs

### ISSUE THREAD

**Issue by tomsun** [pouchdb/pouchdb#8002]
https://github.com/pouchdb/pouchdb/blob/5bb2edebb47034cc74939882cb690070456e6f2e/docs/_includes/api/debug_mode.html#L9

Found this one while skimming the docs: currently at 7.1.1: what would be the up-to-date version of this warning?

**Comment by karlwestin** [comment]
Great question, thanks for bringing this up!
debug used to be a part of pouchdb-core but it was removed here https://github.com/pouchdb/pouchdb/commit/014a34dd7c40379987bd88a30c9533ec932ec8db

In order to use PouchDB debug you have to add it like a plugin like here https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-debug/README.md#usage

So actually that comment could be removed and replaced with something like

> In versions before 7.0.0, this was available as a part of pouchdb-core. If you're using a version lower than that you can start using the API without installing the plugin.
