### ISSUE TITLE
Discussion: Attempting to use PouchDB with Deno

### ISSUE THREAD

**Issue by coldino** [pouchdb/pouchdb#8158]
I've begun to look at what it might take to get PouchDB working within Deno, using a service that attempts to make npm modules available via transpiling (skypack.dev, taking over from pika.dev) These issues are most likely not issues with Pouch, but I hope that discussion will enable progress and eventually support for Deno to some degree.

Starting simple is encouraging:
```ts
import PouchDB from 'https://cdn.skypack.dev/pouchdb-core@^7.2.2';
console.log(PouchDB, PouchDB.plugin);
// outputs: [Function: PouchDB] [Function]
```

Moving on:
```ts
import PouchDB from 'https://cdn.skypack.dev/pouchdb-core@^7.2.2';
import PouchHttp from 'https://cdn.skypack.dev/pouchdb-adapter-http@^7.2.2';
PouchDB.plugin(PouchHttp);
const db = new PouchDB('http://localhost:5984/test');
```
...fails on the `new` line with:
```log
error: Uncaught TypeError: nextTick is not a function
  nextTick(function () {
  ^
    at PouchDB.HttpPouch (https://cdn.skypack.dev/-/pouchdb-adapter-http@v7.2.2-CqNakEqoOd09meIqLnca/dist=es2020/pouchdb-adapter-http.js:315:3)
    at new PouchDB (https://cdn.skypack.dev/-/pouchdb-core@v7.2.2-1LKmsnWVbUdDy5Lhbnas/dist=es2020/pouchdb-core.js:1761:34)
    at file:///ws/ctrl/testpouch.ts:32:12
```

Looking into this, I can see the transpiled attempt at importing `immediate` as `nextTick`, which clearly isn't working. `nextTick` is `undefined` in `pouch-adapter-http`.  However, this must mean that the transpilation system is using the _browser_ version of `pouch-utils`.

To verify the library itself works:
```ts
import immediate from 'https://cdn.skypack.dev/immediate'
immediate(() => console.log('ding!'))
// outputs: ding!
```

After hacking Deno's cache file for `pouchdb-adapter-http` to correctly use `immediate`...
```ts
import PouchDB from 'https://cdn.skypack.dev/pouchdb-core@^7.2.2';
import PouchHttp from 'https://cdn.skypack.dev/pouchdb-adapter-http@^7.2.2';
PouchDB.plugin(PouchHttp);
const db = new PouchDB('http://db:5984/test');
const result = await db.put({ _id:''+Date.now() });
console.log(await db.get(result.id));
// outputs: { _id: "1596815936763", _rev: "1-aa5a23a1050148ae909d4a2d1c002a46" }
```
That's some great news!

For my intended uses in a server process I'd like to work towards a local in-memory Pouch with full sync to an http Pouch. This `nextTick` is just one of many issues once I started exploring other adapters. The in-memory adapter sadly isn't as dependency free as I was hoping.

Now before I try to work out how I can debug these issue, is anyone looking into this or have any ideas with how to reproduce and debug issues like this on a fork, considering the transpiling?

**Comment by coldino** [comment]
Bit of a positive update:

* Reported the odd transpilation error to skypack-cdn.
* Testing with https://jspm.io/ gets much further, allowing both memory and http adapters plus briefly-tested replication!
* TypeScript types are an issue with both service. I have overcome this with a local modified copy of the various @types files (to include the hardcoded service URL), but it might make sense to start including types actually in the packages as part of #8097.

Very happy to get enough of Pouch running to test this in anger and build on top of it.

**Comment by jbriales** [comment]
Hi! A question on this:
What's the current official status of PouchDB @ Deno then? Does it work? Is it stable enough? If not, is there any WIP on this to make support more official?

**Comment by Type1J** [comment]
I'm also interested in PouchDB (and PouchDB Server) on Deno.

**Comment by lgourain** [comment]
Hello,
I am also very interested for having a clean way to use PouchDB with Deno.
Our team is developing a Node project with PouchDB that consists in a REACT API that can be plugged to any CouchDB database with a url provided by a CLI. But we are willing to switch to Deno for many reasons because we think that it's an easier way to achieve this goal. And the fact that it supports TypeScript, ES Modules, Async / Await, is shipped with lots of tools (compiler, formatter, dependency manager, etc.) and a standard library with many other cool features natively, is for us a good reason to use Deno instead of Node for our small project.
Hope you can give us information if it's something you are thinking about to support !
Thank in advance,

**Comment by dheimoz** [comment]
Hello everyone:

Far as I understand, only a major release is planned with some PR ready to be merged. In order, Deno is uncharted territory.

Maybe we can try checking the test related to the communication layer.

It is just an idea.

Do you believe Deno is stable enough to give it a try?

Thanks.

**Comment by lgourain** [comment]
Hello,

In my opinion, Deno is growing really fast and it's something to consider supporting. But because a new release is published really often it can lack stability.

I don't know how PouchDB is working beneath the surface but it could be interesting but challenging to support Deno. I think the best way is to have the point of view from a contributor to understand if we could ecounter limits.

Or, does anyone feel confident enough to give it a try ?

Thanks,

**Comment by dheimoz** [comment]
Not confident, but we may add it to the backlog

**Comment by wesleycoder** [comment]
@dheimoz
I'm just giving a ping on this issue since I'm interested on this.
Deno has become much more stable since the last update on this issue...
Is this on the roadmap or is it being scrapped?

**Comment by dheimoz** [comment]
hello  @wesleycoder. It has not been discussed. The priority thanks to the neighbourhoodie team's assistance is to have the suite test working. However, the idea has not been scrapped. Thanks for the interest.

**Comment by aaronhuggins** [comment]
@wesleycoder @lgourain @Type1J @jbriales I'm working on getting PouchDB up and running, with types.

Currently pinned to version 7.2.2 if you want to check it out.

I have a vested interest in getting this working in Deno because I love Couch/PouchDB and have used it in a number of private projects. I'm currently undertaking a migration of almost all my code to work on Deno.

My plan to get this up-and-running with in-memory and persist-to-disk dbs is in the readme.

https://github.com/aaronhuggins/pouchdb_deno

**Comment by aaronhuggins** [comment]
It lives! Got it working and properly typed in Deno v1.18.1. See main branch at https://github.com/aaronhuggins/pouchdb_deno

```shell
deno run --allow-read --allow-write examples/indexeddb.ts
```

Now... I need to write tests for code.

Yay. Any help would be appreciated discussing versioning and trying it out before a release is cut.

**Comment by aaronhuggins** [comment]
First release is live on Deno.land/x. Please feel free to give it a try. It's maybe production ready?

https://github.com/aaronhuggins/pouchdb_deno/tree/v1.0.0-PouchDB+7.2.2

https://deno.land/x/pouchdb_deno@v1.0.0-PouchDB+7.2.2
