### ISSUE TITLE
Event listeners are leaked after sync error

### ISSUE THREAD

**Issue by Fedjmike** [pouchdb/pouchdb#8161]
### Issue

After a sync which throws an error, PouchDB leaves listeners for the `'destroyed'` event on both the local and remote databases without cleaning them up. [This was supposed to be happen when the sync was cancelled](https://pouchdb.com/errors.html#event_emitter_limit), which it already has been, and subsequent calls to `cancel` have no effect.

### Info
- Environment: Chrome 84.0.4147.105
- Platform: Mac OS 10.15.5
- Adapter: test on both IDB and IndexedDB
- Server: CouchDB

### Reproduce

https://spotless-ionian-skirt.glitch.me/

**Comment by pkcinna01** [comment]
This is important issue for our rxdb application because we cannot access the non live sync Replication instance in PouchDb. Without a fix to this our app is not stable for production because we cannot assume there will never be an error.

This is a temp hack that seems to get around issue for our scenario ( added   self.once('error', cleanup); )

pouchdb-replication index.js:

```
Replication.prototype.ready = function (src, target) {
  var self = this;
  if (self._readyCalled) {
    return;
  }
  self._readyCalled = true;

  function onDestroy() {
    self.cancel();
  }
  src.once('destroyed', onDestroy);
  target.once('destroyed', onDestroy);
  function cleanup() {
    src.removeListener('destroyed', onDestroy);
    target.removeListener('destroyed', onDestroy);
  }
  self.once('complete', cleanup);
  self.once('error', cleanup);
};
```

**Comment by geoidesic** [comment]
This issue should be re-opened. It went stale because no-one replied to the issue, not because the answer / solution isn't required.

**Comment by erezsh** [comment]
This issue is relevant to me too. It's the only memory leak in my app.
