### ISSUE TITLE
PouchDB <--> CouchDB sync works but new changes are replicated after a long delay (about 10 minutes)

### ISSUE THREAD

**Issue by daweedm** [pouchdb/pouchdb#8170]
### Issue
PouchDB <--> CouchDB sync works but new changes are replicated after a long delay (about 10 minutes).

It seems similar to the following issue : https://stackoverflow.com/questions/33757419/couchdb-pouchdb-sync-works-but-first-change-is-very-slow.

We are able to start the app normally, we can successfully retrieve the local version of the documents but when we make changes, theses changes takes about 10 minutes to be replicated to the CouchDB server. 

### Info
- Environment: Browser
- Platform: Electron
- Adapter: IndexedDB
- Server: CouchDB

### Reproduce
Just start the app using PouchDB with a database where there is a lot of documents (total of about 300 documents created per day during 4 years an each doc was updated 2 times on average).

**Comment by wgrhstf** [comment]
I have very similar Problems in Electron starting from Version 9.0.0 onward. There seems to be no sync between PouchDB and CouchDb, or it takes extremely long. Sometimes it works, flawless, then syncing seems to stop. 
I was not able to find any pattern to reproduce the Problem. 

I also tried to switch to websql adapter - one app takes it, the other (with identical setup) gives me an error (`...\node_modules\pouchdb-browser\lib\index.js:2843 Uncaught Error: Invalid Adapter: websql`). I already mentioned that in #8082

**Comment by endyjasmi** [comment]
I believe this is part of the backoff function in play? This thing usually happens when there is no new changes inside the database for some time, and the next replication will only start after 10 or so minute.

You can usually change this behaviour by changing the `back_off_function`. For more information, you can take a look at this;
[https://pouchdb.com/api.html#customizing-retry-replication](https://pouchdb.com/api.html#customizing-retry-replication)

**Comment by wgrhstf** [comment]
@endyjasmi I do not think is hat to do with the back_off_function since this behaviour starts directly after the app is launched.  so there is no time for back up to add up to 10 minutes waiting time. 
Furthermore it seems to be something between PouchDB and Electron. Reverting back Electron to Version 8.3.0 leads to normal sync again.

**Comment by wgrhstf** [comment]
I found something. If I open my application and make any changes inside my CouchDB it get's synced as expected. 
The moment I reload my App via `Ctrl+R` syncing stops. It will fetch all docs from CouchDB, but any changes after this initial fetch are not synced to my application.
