### ISSUE TITLE
Sync, Privacy, and traditional RDBMS transitioning apps.

### ISSUE THREAD

**Issue by amanpatel** [pouchdb/pouchdb#8252]
I am reading a lot of the tutorials, guides and the API on the pouchDB website. It’s all nicely written and easy to follow. However I feel there is some lack of information surrounding how traditional problems are solved using PouchDB. The TODO app is ok, but what about the following:

- How does authentication work (forgot password, registration).
- How is privacy maintained for a synced `users` table. In traditional web app, the database is not directly accessible by the client - so the middleware can enforce security. How is this protected in CouchDB/PounchDB solutions?
- Multi tenancy support and privacy concerns there in. What if the web app was a multi-tenant system and users that are part of a region should not be able to view data from other regions. But they can optionally view *some* data based on ACLs or permissions.

This is probably asked before, but I couldn’t find any direct questions addressing this with some simple searching in github issues. Hope my questions make sense!

**Comment by dheimoz** [comment]
Hello @amanpatel , thanks for giving it a try to PouchDB. I strongly believe that this projects is the best piece of software ever written, because it solves offline needs graciously. Regarding your questions I will only state my personal opinions, take them with a grain of salt.

Before trying to address them, I see pouchdb as a No SQL DB that lives in your browser. As with anything that is client side, it is out of your control. For instance, you need to validate the Fields in a Web Form in the client, and then validate the very same information when it is received in the server, you cannot trust 100% end user.

With that being said:
1) There are some plugins that enable authentication to Pouchdb (https://www.npmjs.com/package/superlogin) . But you must be aware that Access Control and Authorization can be handled by Couchdb. Pouchdb by itself its a great tool to store offline information. It shines when there is replication between a Couchdb node and your web App powered by Pouchdb.
2)  When you mention "users Table" you mean the "_users DataBase" in Couchdb? If not, I must admit that I did not know that Pouchdb has this "users" table.  On the other, if you mean the internal Database, I would never replicate the information, the same for the "_replicator". Those are very sensitive information, despite some fields are encrypted.
3) In the No SQL World the concept of Database is cheap. What I mean by that is that you can create any number of databases you see fit. WIth traditional SQL Databases, for instance Sql Server or Oracle, you need to take into account several variables before setting up your schemas, users and High Availability options. There is even a concept of database per user that you can turn it on. Finally, you can take a look into Cloudant, an IBM product based on Couchdb that is very roboust and integrates seamslessly with Pouchdb. https://www.ibm.com/cloud/cloudant

 To follow up, I recommend you the following links:

https://guide.couchdb.org/draft/recipes.html
http://guide.couchdb.org/draft/security.html

**Comment by amanpatel** [comment]
Very thoughtful and informative reply. I'll add a few things I've found so far regarding offline architecture and design

ServiceWorkers: https://developers.google.com/web/fundamentals/primers/service-workers

SuperHuman (offline email client silicon valley startup): https://blog.superhuman.com/architecting-a-web-app-to-just-work-offline-part-1-8697f316c0eb

I'll definitely check out your links! Really appreciate it.

**Comment by dheimoz** [comment]
on the contrary @amanpatel thank you very much for your links as well. Welcome to offline first!! and PocuchDB.
