### ISSUE TITLE
Provide filter key to generateReplicationId

### ISSUE THREAD

**Issue by pgmahoney** [pouchdb/pouchdb#8270]
Currently generateReplicationId uses the filter name and query params, or the filter function's toString to build a checkpoint document id. This means that any change to these properties will invalidate existing checkpoints.

I have a scenario where on initial one-way replication to a new Pouchdb database I want to exclude deleted documents, but after that replication I want to include them in the live sync. I was using the queryParams for this (includeDeleted=true/false), but found this was creating 2 checkpoints and a lot of unnecessary requests. I solved this issue by rewriting the url in the fetch().

I also would like to be able to optimise the push filter function, but again any change at all will result in checkpoint invalidation.

It would therefore be really useful to be able to specify a filterKey as an option to be passed to generateReplicationId. If a filterKey is specified then it would override the use of the filter name/params/toString and make it the developer's responsibility to decide when the checkpoints should invalidate.

**Comment by janl** [comment]
Heya, this is a clever idea. My gut feeling is that giving end-users access to this detailed checkpoint behaviour will cause more harm then help. However, your use-case is super valid. Would this work:

- replicate with filter
- record highest server seq
- start non-filtered replication with `options.since` https://pouchdb.com/api.html#replication
