### ISSUE TITLE
revs_limit: 1 not handling deleting of documents correctly

### ISSUE THREAD

**Issue by sureshvv** [pouchdb/pouchdb#8311]
### Issue
revs_limit: 1 not handling deleting of documents correctly

### Reproduce
https://volcano-dramatic-raft.glitch.me

You may have to run this more than once to reproduce.

**Comment by dheimoz** [comment]
Hello @sureshvv 

I do not understand, what should happen? An error at the console?

**Comment by sureshvv** [comment]
1. Document was deleted
2. Sync was done
3. Document shows up again (It should be gone)

**Comment by dheimoz** [comment]
Hey @sureshvv 
The test creates 2 different documents. Check
![image](https://user-images.githubusercontent.com/382153/122622235-a98c1d00-d05d-11eb-9bad-9abb4bde65ed.png)

I am not positive should this is by design. I have never worked with rev_limits= 1

Maybe there are more versed people that can help at the Slack channel
https://couchdb.slack.com/archives/C016TJAE7A4

Should you have the chance to jump in, we can work there.

**Comment by sureshvv** [comment]
When I run it from glitch.me, this is what I get:

![Screenshot from 2021-06-19 10-17-26](https://user-images.githubusercontent.com/506019/122631271-44313e00-d0e8-11eb-95a8-0c410f08d125.png)

Are you seeing anuthing different?

**Comment by sureshvv** [comment]
Seems this issue has been fixes in 7.2.2. I was using 7,0.0.

**Comment by dheimoz** [comment]
@sureshvv great to know. Sorry that I did not ask for the version you were using.

**Comment by sureshvv** [comment]
Was thrown off the trail because the default pouchdb version in glitch,me is still 6.x.x and my local version was 7.0.0 and the bug was present in both these versions. 7.2.2 works as expected.
