### ISSUE TITLE
calculate Balance for every day and date range

### ISSUE THREAD

**Issue by Dinesh101041** [pouchdb/pouchdb#8352]
### Issue
Not a issue small doubt 

i am working on small billing application,i want to calculate the opening balance and closing balance for every day and also for date range 

 i have following fields in docs of pouch db data base
```
 {
  date:2021-08-01 
  sale:800
  invest:500
  expense: 100
}
```

 i want to calculate the opening balance and closing balance

  **opening balance will be previous date closing balance**

 calculation will be -> **closing = ( opening+investment+sale ) - exp**

This table is example to calculate the balance for each day 
```
date        opening     sale        invest     exp    closing
2020-03-01  0           100.00      10.00      0      90.00
2020-03-02  90.00       50.00       20.00      0      120.00     
2020-03-02  120.0       100.00       0.00      0      220.00
2020-03-03  220.00      0.00        0.00        0     220.00  
2020-03-04  220.00      110.00      10.00      10     330.00
```
i am stuck with this problem for one week
can any one tell  or help me with the code to achieve this using pouch db

**Comment by dheimoz** [comment]
hey @Dinesh101041 
Have you tried calculating this at front end?
I assume you save every document whenever there is a sale, invest or expense, am I right?
Or is it any other event to "close" the day?
I would love to see the design of your documents. Maybe the result you want to achieve can be done with a view or, again at front end.

Could you share some documents?

**Comment by Dinesh101041** [comment]
in my application there is two form one for sale record and another for investment expense  in different db, both are saved on daily basis,  i dumped two db into single db to calculate the balance

the data of dumped db look as
```
 {
  date:2021-08-01 
  sale:800
  invest:500
  expense: 100
}
```
below i attached the ui for calculating balance <br>
![image](https://user-images.githubusercontent.com/59551894/131207491-7694596a-22b3-4ea2-9c2e-e1e58417af21.png)


when changing the date i want to calculate the balance 

if you need more information please feel free to ask

**Comment by dheimoz** [comment]
hey @Dinesh101041, first of all, we both agree this not a Pouchdb issue, I mean, the product is not failing. This is more related to NoSQL DB Design, correct?
Having said that, I believe the best way to sort the problem is separating concerns. 

- I would create indivual documents for sale, invest and expense. something like this:

`js
{
 _id: "SAL:21321321",
 type: "sale",
 date: "2021-08-28",
 amount: 700,
 account: "SOME ACCOUNT",
},
{
 _id: "INV:3432532",
 type: "invest",
 date: "2021-08-28",
 amount: 100,
 account: "SOME ACCOUNT",
},
{
 _id: "EXP:543232",
 type: "expense",
 date: "2021-08-28",
 amount: 600,
 account: "SOME ACCOUNT",
}
`

What is dynamic and needs calculation is opening and closing, I would map the array "allDocs" at Frond End wtih a FLUX State Management (Redux, Vuex, any other).

Then create a View or Getter just to calculate the openings without considering the day before. You only want the amounts or transactions per day. You would need to create something like this

``js
 const totalPerDay = [
 { date:'2021-08-28', grandTotalperDay: 200 }, // 700 + 100 - 600 | sale + invest - expense
 { date:'2021-08-29', grandTotalperDay: 0 },
....
]

``
And then you can now Calculate the final Openings and Closings based on a date.

Further reading:
https://jrsinclair.com/articles/2019/functional-js-do-more-with-reduce/
https://blog.cloudant.com/2019/08/16/Design-Docs-For-Life.html
https://medium.com/codait/cloudant-fundamentals-the-document-855c5ab92051
https://medium.com/codait/cloudant-fundamentals-the-id-f6c7c88fbc75
https://medium.com/@glynn_bird/time-sortable-document-ids-in-cloudant-c3af5b23d8bf
https://medium.com/@glynn_bird/generating-sample-data-for-a-json-data-store-1eb45604691e

I will close this Issue. Hope the information is useful for you.
Cheers.

**Comment by Dinesh101041** [comment]
is there any way to calculate the opening balance without redux   i tried with pouch db find to get data by date and calculate the balance but it did not work <br> below i add a link to the one stack overflow question to calculate balance using sql  and  one sql query fiddle  the query is calculating the balance without any state  management  , is there any way or equivalent code like sql query  in pouch-db  to calcuate balance 

[Calculate balance](https://stackoverflow.com/questions/61452118/mysql-opening-closing-balance-with-date-range)

[sql queryfiddle](https://www.db-fiddle.com/f/xx2cjamKE1SpKAXyMrDXAY/0)

hope for your reply Thank you

**Comment by dheimoz** [comment]
Hello @Dinesh101041 

Pouchdb does not have an equivalent to what you are sharing, at least that I am aware of. Maybe you should start considering to change the scope of the technology you are using for your app. Maybe a Traditional SQL Database would be better.

CouchDB, Cloudant and Pouchdb are NOSql Databases. The links shared are applicable to SQL Tables.

Cheers.
