### ISSUE TITLE
Adding a sort option to a query includes deleted documents in the indexeddb adapter

### ISSUE THREAD

**Issue by nirvdrum** [pouchdb/pouchdb#8438]
### Issue

When sending a query to PouchDB using this adapter, deleted documents show up in the results if any sort option is added to the query. E.g, using the following query:

```json
{
  "selector": {
    "rank": {
      "$gt": ""
    }
  },
  "sort": [
    {
      "rank": "asc"
    }
  ]
}
```
If I remove the `sort` property, deleted documents will not be included in the results. With the `sort` present, deleted documents appear. This is a change in behavior from _pouchdb-adapter-idb_. For the time being, I need to add my own selector to exclude deleted documents any time I want to sort values.

### Info
- Environment: Browser
- Platform: Firefox
- Adapter: indexeddb
- Server: None
- Version: 7.2.2

**Comment by nirvdrum** [comment]
I'm sorry. I can't keep up with all the stalebot notifications. For anyone coming across this issue, it's still present despite the issue being closed (I can't re-open it).

**Comment by nirvdrum** [comment]
Not fixed yet, I don't think.

**Comment by nirvdrum** [comment]
Is the bot broken? I commented on the issue and it closed the issue anyway.

**Comment by Terreii** [comment]
I could recreate the bug!

**Comment by Terreii** [comment]
Found it!
The new `indexeddb` adapter uses the native IndexedDB indexes. Problem with them is, that they go over all entries.
Therefore PouchDB adds a field to the beginning of all indexes where deleted = 1 and not deleted = 0.
If you use sort, it can happen that PouchDB will use [`IDBKeyRange.lowerBound()`](https://developer.mozilla.org/en-US/docs/Web/API/IDBKeyRange/lowerBound). Which will include deleted docs (because they are indexed later).
So I replaced the `IDBKeyRange.lowerBound()` with a [`IDBKeyRange.bound()`](https://developer.mozilla.org/en-US/docs/Web/API/IDBKeyRange/bound).
