### ISSUE TITLE
db.compact() runs much slower than auto_compaction

### ISSUE THREAD

**Issue by DarrenCook** [pouchdb/pouchdb#8525]
In a large web app we switched on `auto_compaction`. It seemed to work (e.g. chrome disk usage went from 102M to 89M on my test setup, and from 2.3GB to 1.6GB for the guinea pig production user) with no reports of long delays. But we did start seeing 409s on about 10-20% of the DB puts.

So, instead of auto_compaction, I set it up to do a `db.compact()` just when the app first connects to the DB. I expected it to have negligible run-time, especially for an already compacted DB, but for the test setup this adds takes 20 seconds to start-up time; for the same production user it takes at least 3hrs 50 (it eventually had to be killed).

### More Info

Initially, assuming it would add negligible run-time, I did `await db.compact()` immediately after the `new PouchDB()` call, and then again once the `db.replicate.from(remoteDB)` had completed. This added a 40 second delay to startup for my test setup. I commented out one of those calls, and it "only" added 20 seconds.

So I tried removing the `await`, letting it run in the background. But now the app hangs for 20 seconds if we try to immediately do anything with those databases. (If we wait 20 seconds, before doing anything, everything is fine.)

So I moved it to a button, for more controlled testing, and to do one DB at a time. Same behaviour.

We have 5 databases. In my test setup, 4 of them were basically finishing immediately, and the 5th (with 174 documents and possibly some high revision counts) was taking about 20 seconds.

In the production system mentioned above two of the five databases are large: 34205 documents in one, 25544 in another. And some of those documents will have over 100 revisions.  (Assuming it was proportional to document count I'd estimated it might take 2-3hrs, but looks like it is even more...)

Possibly Related: we use worker-pouch as the adapter for those databases, so all the couchDB actions are kept in their own thread. I'm not able to easily test without that, though.

Other information: main testing done in Chromium 101, on Linux and Mac; also on Electron (so basically Chromium again). Reasonably fast machines. The remote server is CouchDB (3.1.x); I checked logs during the app startup, and could see the sync requests come through, nothing else, nothing unusual.

### The Question/Bug/Feature Request

Is `auto_compaction` using the same code as `db.compact()`? If so, what could explain the hugely different run times?

If not, what are they doing differently, and why?

Can I create PouchDB with `auto_compaction:true` (as that seems to do what we wanted), but then switch it off again? I.e. just before heavy use of the DB starts, so I can avoid those 409s?

**Comment by DarrenCook** [comment]
The apparent broken-ness of `db.compact()` is still very much an issue, though I have a feeling I might be back here every 60 days arguing with the mindless bot. :-(

**Comment by ramblin-rose** [comment]
The documentation for `auto_compaction` states

> auto_compaction: This turns on auto compaction, which means compact() is called after every change to the database. Defaults to false.

That's some deliberate language and answers your questions.  `auto_compaction` is a run-time property (it is not persistent) thus it is enabled or disabled when creating a pouchDB instance.

**Comment by DarrenCook** [comment]
Thanks for giving this some attention (everything is a local DB, by the way).

Creating a database with `auto_compaction:true` gives very different behaviour to calling `db.compact()` just after creating the database. I.e. the first has no hangs, but gives lots of 409s, vs. huge hangs, proportional to database size.

So either a different `compact()` is being called when `auto_compaction` is on, or the same internal function is being called but with different args? I was hoping someone might be able to track down and give a link to the code. I spent over an hour on it at the time, but couldn't track down exactly what code gets run in each case.

It'd be great if someone could reproduce this, or give feedback that they could not reproduce it. But note that you will need a fairly large database to see the hangs; it is negligible on the kinds of databases we normally create for unit tests.

**Comment by ramblin-rose** [comment]
`compact()` is not literally called when `auto_compaction` is enabled, however virtually the same code is invoked on a per-document basis. Of course the behavior is going to be different because these are disparate things - one a function, the other a run-time option.

`compact()` is a request that **every** document tree in the database be compacted (using a queue) so depending on database size the cost could be trivial or significant with respect to time.  Regardless, at completion there is a compacted database. For example see `AbstractPouchDB.prototype.compact` in packages/node_modules/pouchdb/lib/index-browser.js

With `auto_compaction` compaction occurs _only_ when a document is modified as post-processing step, where its tree (and _only_ its tree) is compacted.  To exhaust the point, `auto_compaction` causes compaction on a per-document-changed basis.  Thus it is quite possible to have a wholly, partially, or not at all compacted database with `auto_compaction` enabled.  For more, see `function finishDoc` and `function compactTree` in packages/node_modules/pouchdb-adapter-idb/lib/index.js

The difference between the option and the function call is apparent, and explains why `compact()` causes an obvious penalty and `auto_compaction` does not.  In your circumstance I can only guess `compact()` is being called on the main thread which would could hamper an app.

As far as 409's go, it can happen a lot (e.g. replication) and does not necessarily suggest an error.  I invite you to track them down and will be surprised if they are the result of an error rather than simply from a harmless status check.

**Comment by DarrenCook** [comment]
@ramblin-rose Thanks for the pointers.

From looking at `compact()`, I can see it then calls `doNextCompaction()` which comes back to `_compact()` which does:

```
  var changesOpts = {
    return_docs: false,
    last_seq: opts.last_seq || 0
  };
  ...  
  self.changes(changesOpts)
    .on('change', onChange)
    .on('complete', onComplete)
    .on('error', callback);
```

Is this an exotic way of calling `onChange(row)` for every document in the database? Any insight into why it was done this way? I'm wondering if I can take control of `changesOpts` to limit how much work any one call to `db.compact()` would do?

And/or, is it reasonable to directly call `compactDocument(row)` in a loop of my own? I could then tell it to just go and compact one document at a time, as a background process, with e.g. a 1000ms sleep between each call. (As mentioned earlier, 174 documents took 20 seconds, even when there was no compacting to do.)

This would allow me to get clever: e.g. choosing to do just those documents with a high _rev number, to get most benefit from the effort. Or choosing those documents I think are very unlikely to get any more user updates.

What happens if an update for a document comes in while `compactDocument()` is running? Is that what `openTransactionSafely()` does (inside `api._doCompaction()`) ? Does the guarantee it will finish the compaction before allowing a new revision to be applied?

**Comment by ramblin-rose** [comment]
@DarrenCook your questions are beyond my expertise.  pouchDB is a mature, successful OSS project.  `openTransactionSafely` is  adapter specific (indexedDB), one of many adapters supported by pouchDB.  

All I can offer at this point is experience, which says not to monkey with internals and work with what is available via the public API.  If I for some reason needed a replacement for `compact()` then I would would ply the `auto_compaction` feature.

**Comment by H--o-l** [comment]
I have the same issue, the compaction re-run every time it's called on all the documents of the database, not just the updated document.

I think the commit https://github.com/pouchdb/pouchdb/pull/2623 fixed that in 2014, but it looks like the `opts.since` parameter was remove here in 2015:
https://github.com/pouchdb/pouchdb/commit/b4f79e215e9f96f0685a4612f62a613d9b609ea6#diff-77fcec9d7bb0046cd062c60635550ae5ae61118b539f7653168e3251a6c9f85fL447

If I put back the `opts.since` it fixes the issue for me.
I will try to make a pull request in the next days.

**Comment by H--o-l** [comment]
(For reference the pull request is here: https://github.com/pouchdb/pouchdb/pull/8834)

**Comment by garethbowen** [comment]
Clearly still an issue...

**Comment by garethbowen** [comment]
Merged.
