### ISSUE TITLE
Find alternative to using eval

### ISSUE THREAD

**Issue by trisapeace** [pouchdb/pouchdb#96]
New content security policy for Chrome extensions disallow the use to eval() and other inline Javascript (http://code.google.com/chrome/extensions/contentSecurityPolicy.html).

Is there any way to avoid using it in Pouch?

**Comment by Gozala** [comment]
Maybe `new Pouch` could be passed set of views as an option as a way to avoid eval and there for a CSP limitation. In fact pouch could even compare view function source with actual passed functions and complain if function view function is no longer passed or source is different.

**Comment by Gozala** [comment]
@daleharvey in fact thinking about it little further, what if `new Pouch({asyncEval: myEval})` was a thing ? That way one could workaround lack of eval in an environment specific way. For example we could generate it somewhat like `Eval(fn1, fn2, fn3)` and allow it to only return either of passed `fn`s while @anowak could pass something that captures idea behind `noeval`. In some environments like certified fxos apps we could do a round trip to a server to fetch a script with a function and return that back.

**Comment by nolanlawson** [comment]
@Gozala I think our new approach to solving this problem is [pouchdb-find](http://nolanlawson.github.io/pouchdb-find/), which doesn't require `eval()` at all. For filter functions, though, we still don't have a good solution, so yours might be a step in the right direction.

**Comment by abuisman** [comment]
Hi, I am not completely familiar with CSP as I just discovered that it exists due to pouchdb not working for me, but I found this:

http://www.html5rocks.com/en/tutorials/security/content-security-policy/#if-you-absolutely-must-use-it

It seems like you can use eval inside a script tag that is given a `nonce` attribute. 
Alternatively you can create a hash of the code that you want to eval and append that to the security policy. Maybe there is a way to hash the contents of the `views` beforehand and still be able to use them with pouchdb?
